export const assignmentOutputSchema = {
  type: "object" as const,
  properties: {
    AssignmentId: { type: "integer" },
    AssignmentName: { type: ["string", "null"] },
    AssignmentNumber: { type: ["string", "null"] },
    DepartmentName: { type: "string" },
    GradeCode: { type: "string" },
    GradeName: { type: "string" },
    JobCode: { type: ["string", "null"] },
    JobName: { type: ["string", "null"] },
    LegalEmployerName: { type: "string" },
    LocationCode: { type: "string" },
    LocationName: { type: "string" },
    ManagerName: { type: ["string", "null"] },
    PositionCode: { type: "string" },
    PositionName: { type: "string" },
    PrimaryAssignmentFlag: { type: "boolean" },
    StartDate: { type: "string" },
    WorkerType: { type: ["string", "null"], enum: ["E", "C", "P", "N", null] },
    FullPartTime: { type: ["string", "null"] },
  },
  required: [
    "AssignmentId",
    "DepartmentName",
    "GradeCode",
    "GradeName",
    "LegalEmployerName",
    "LocationCode",
    "LocationName",
    "PositionCode",
    "PositionName",
    "PrimaryAssignmentFlag",
    "StartDate",
  ],
};
export const listAssignmentsOutputSchema = {
  type: "object" as const,
  properties: {
    items: { type: "array", items: assignmentOutputSchema },
    count: { type: "integer" },
    hasMore: { type: "boolean" },
    limit: { type: "integer" },
    offset: { type: "integer" },
  },
  required: ["items", "count", "hasMore", "limit", "offset"],
};
