export const listAttachmentsResponse = {
  result: [
    {
      table_sys_id: "5054b6f8c0a800060056addcf551ecf8",
      size_bytes: "462",
      download_link:
        "https://instance.service-now.com/api/now/attachment/615ea769c0a80166001cf5f2367302f5/file",
      sys_updated_on: "2009-05-21 04:12:21",
      sys_id: "615ea769c0a80166001cf5f2367302f5",
      image_height: "",
      sys_created_on: "2009-05-21 04:12:21",
      file_name: "blocks.swf",
      sys_created_by: "glide.maint",
      compressed: "true",
      average_image_color: "",
      sys_updated_by: "glide.maint",
      sys_tags: "",
      table_name: "content_block_programmatic",
      image_width: "",
      sys_mod_count: "0",
      content_type: "application/x-shockwave-flash",
      size_compressed: "485",
    },
  ],
};

export const getAttachmentResponse = {
  result: {
    table_sys_id: "5054b6f8c0a800060056addcf551ecf8",
    size_bytes: "462",
    download_link:
      "https://instance.service-now.com/api/now/attachment/615ea769c0a80166001cf5f2367302f5/file",
    sys_updated_on: "2009-05-21 04:12:21",
    sys_id: "615ea769c0a80166001cf5f2367302f5",
    image_height: "",
    sys_created_on: "2009-05-21 04:12:21",
    file_name: "blocks.swf",
    sys_created_by: "glide.maint",
    compressed: "true",
    average_image_color: "",
    sys_updated_by: "glide.maint",
    sys_tags: "",
    table_name: "content_block_programmatic",
    image_width: "",
    sys_mod_count: "0",
    content_type: "application/x-shockwave-flash",
    size_compressed: "485",
  },
};

export const getAttachmentFileResponse = Buffer.from("file contents");

export const deleteAttachmentResponse = "";

export const uploadAttachmentResponse = {
  result: {
    average_image_color: "String",
    compressed: "String",
    content_type: "String",
    created_by_name: "String",
    download_link: "String",
    file_name: "String",
    image_height: "String",
    image_width: "String",
    size_bytes: "String",
    size_compressed: "String",
    sys_created_by: "String",
    sys_created_on: "String",
    sys_id: "String",
    sys_mod_count: "String",
    sys_tags: "String",
    sys_updated_by: "String",
    sys_updated_on: "String",
    table_name: "String",
    table_sys_id: "String",
    updated_by_name: "String",
  },
};

export const multipartUploadAttachmentResponse = {
  result: {
    table_sys_id: "d71f7935c0a8016700802b64c67c11c6",
    size_bytes: "36597",
    download_link:
      "https://instance.service-now.com/api/now/attachment/994adbc64f511200adf9f8e18110c796/file",
    sys_updated_on: "2016-02-02 14:00:21",
    sys_id: "994adbc64f511200adf9f8e18110c796",
    image_height: "",
    sys_created_on: "2016-02-02 14:00:21",
    file_name: "banner-CS0001345_v1_1.jpeg",
    sys_created_by: "admin",
    compressed: "true",
    average_image_color: "",
    sys_updated_by: "admin",
    sys_tags: "",
    table_name: "incident",
    image_width: "",
    sys_mod_count: "0",
    content_type: "image/jpeg",
    size_compressed: "25130",
  },
};

export const listConfigurationItemsResponse = {
  data: {
    result: [
      {
        sys_id: "3a290cc60a0a0bb400000bdb386af1cf",
        name: "PS LinuxApp01",
      },
    ],
  },
};

export const getConfigurationItemAttributesResponse = {
  data: {
    result: {
      outbound_relations: [
        {
          sys_id: "3a62e64ac0a8ce0100aead1e3fd5439f",
          type: {
            display_value: "Depends on::Used by",
            link: "https://instance.servicenow.com/api/now/table/cmdb_rel_type/1a9cb166f1571100a92eb60da2bce5c5",
            value: "1a9cb166f1571100a92eb60da2bce5c5",
          },
          target: {
            display_value: "PS ORA01",
            link: "https://instance.servicenow.com/api/now/cmdb/instance/cmdb_ci/3a307c930a0a0bb400353965d0b8861f",
            value: "3a307c930a0a0bb400353965d0b8861f",
          },
        },
        {
          sys_id: "3a67513fc0a8ce0100914a76cea11b02",
          type: {
            display_value: "Exchanges data with::Exchanges data with",
            link: "https://instance.servicenow.com/api/now/table/cmdb_rel_type/607ad1b2c0a8010e01941856b365af90",
            value: "607ad1b2c0a8010e01941856b365af90",
          },
          target: {
            display_value: "PS ORA01",
            link: "https://instance.servicenow.com/api/now/cmdb/instance/cmdb_ci/3a307c930a0a0bb400353965d0b8861f",
            value: "3a307c930a0a0bb400353965d0b8861f",
          },
        },
      ],
      attributes: {
        firewall_status: "Intranet",
        os_address_width: "",
        attested_date: "",
        operational_status: "1",
        os_service_pack: "",
        cpu_core_thread: "",
        cpu_manufacturer: "",
        sys_updated_on: "2020-07-08 11:16:51",
        discovery_source: "",
        first_discovered: "",
        due_in: "",
        used_for: "Production",
        invoice_number: "",
        gl_account: "",
        sys_created_by: "glide.maint",
        warranty_expiration: "",
        ram: "2048",
        cpu_name: "",
        cpu_speed: "2800",
        owned_by: "",
        checked_out: "",
        kernel_release: "",
        sys_domain_path: "/",
        classification: "Production",
        disk_space: "40",
        object_id: "",
        maintenance_schedule: "",
        cost_center: "",
        attested_by: "",
        dns_domain: "",
        assigned: "2020-01-04 07:00:00",
        purchase_date: "",
        life_cycle_stage: "",
        short_description: "",
        cd_speed: "",
        floppy: "",
        managed_by: {
          display_value: "Lynda Caraway",
          link: "https://instance.service-now.com/api/now/table/sys_user/8a826bf03710200044e0bfc8bcbe5d72",
          value: "8a826bf03710200044e0bfc8bcbe5d72",
        },
        os_domain: "",
        last_discovered: "",
        can_print: "false",
        sys_class_name: "cmdb_ci_linux_server",
        manufacturer: {
          display_value: "Iris",
          link: "https://instance.servicenow.com/api/now/table/core_company/c115c2f737e3100044e0bfc8bcbe5d46",
          value: "c115c2f737e3100044e0bfc8bcbe5d46",
        },
        cpu_count: "1",
        vendor: {
          display_value: "Cloudward Inc",
          link: "https://instance.servicenow.com/api/now/table/core_company/3efe8c4c37423000158bbfc8bcbe5d7d",
          value: "3efe8c4c37423000158bbfc8bcbe5d7d",
        },
        life_cycle_stage_status: "",
        model_number: "",
        assigned_to: "",
        start_date: "",
        os_version: "2.6.9-22.0.1.ELsmp",
        serial_number: "",
        cd_rom: "false",
        support_group: "",
        unverified: "false",
        correlation_id: "",
        attributes: "",
        asset: {
          display_value: "P1000091 - Iris 5875",
          link: "https://instance.servicenow.com/api/now/table/alm_asset/0bc1ba8837f3100044e0bfc8bcbe5dbb",
          value: "0bc1ba8837f3100044e0bfc8bcbe5dbb",
        },
        form_factor: "",
        cpu_core_count: "",
        skip_sync: "false",
        attestation_score: "",
        sys_updated_by: "system",
        sys_created_on: "2008-10-26 17:17:28",
        sys_domain: {
          display_value: "global",
          link: "https://instance.servicenow.com/api/now/table/sys_user_group/global",
          value: "global",
        },
        cpu_type: "Intel",
        install_date: "2019-08-18 08:00:00",
        asset_tag: "P1000091",
        dr_backup: "",
        hardware_substatus: "",
        fqdn: "",
        change_control: "",
        internet_facing: "false",
        delivery_date: "",
        hardware_status: "",
        install_status: "1",
        supported_by: "",
        name: "PS LinuxApp01",
        subcategory: "",
        default_gateway: "",
        chassis_type: "",
        virtual: "false",
        assignment_group: "",
        managed_by_group: "",
        sys_id: "3a290cc60a0a0bb400000bdb386af1cf",
        po_number: "",
        checked_in: "",
        sys_class_path: "/!!/!2/!(/!!/!0",
        mac_address: "",
        company: {
          display_value: "ACME Corporation",
          link: "https://instance.servicenow.com/api/now/table/core_company/e7c1f3d53790200044e0bfc8bcbe5deb",
          value: "e7c1f3d53790200044e0bfc8bcbe5deb",
        },
        justification: "",
        department: "",
        cost: "45557.5",
        comments: "",
        os: "Linux Red Hat",
        sys_mod_count: "24",
        monitor: "false",
        model_id: {
          display_value: "Iris 5875",
          link: "https://instance.servicenow.com/api/now/table/cmdb_model/5f5fbcc3c0a8010e00f3b27814f3b96b",
          value: "5f5fbcc3c0a8010e00f3b27814f3b96b",
        },
        ip_address: "",
        duplicate_of: "",
        sys_tags: "",
        cost_cc: "USD",
        order_date: "",
        schedule: "",
        environment: "",
        due: "",
        attested: "false",
        location: {
          display_value: "322 West 52nd Street, New York,NY",
          link: "https://instance.servicenow.com/api/now/table/cmn_location/25ab9f690a0a0bb3001c5fec1d0d7bcb",
          value: "25ab9f690a0a0bb3001c5fec1d0d7bcb",
        },
        category: "Do not migrate to asset",
        fault_count: "0",
        host_name: "",
        lease_id: "",
      },
      inbound_relations: [
        {
          sys_id: "3a5e4d8ac0a8ce010005145afb730818",
          type: {
            display_value: "Depends on::Used by",
            link: "https://instance.servicenow.com/api/now/table/cmdb_rel_type/1a9cb166f1571100a92eb60da2bce5c5",
            value: "1a9cb166f1571100a92eb60da2bce5c5",
          },
          target: {
            display_value: "PS Apache01",
            link: "https://instance.servicenow.com/api/now/cmdb/instance/cmdb_ci/3a27d4370a0a0bb4006316812bf45439",
            value: "3a27d4370a0a0bb4006316812bf45439",
          },
        },
        {
          sys_id: "3a5e4d9cc0a8ce010097f2f5c2f65fd8",
          type: {
            display_value: "Depends on::Used by",
            link: "https://instance.servicenow.com/api/now/table/cmdb_rel_type/1a9cb166f1571100a92eb60da2bce5c5",
            value: "1a9cb166f1571100a92eb60da2bce5c5",
          },
          target: {
            display_value: "PS Apache02",
            link: "https://instance.servicenow.com/api/now/cmdb/instance/cmdb_ci/3a27f1520a0a0bb400ecd6ff7afcf036",
            value: "3a27f1520a0a0bb400ecd6ff7afcf036",
          },
        },
        {
          sys_id: "3a5e4d9fc0a8ce0100a3754fac26fe56",
          type: {
            display_value: "Depends on::Used by",
            link: "https://instance.servicenow.com/api/now/table/cmdb_rel_type/1a9cb166f1571100a92eb60da2bce5c5",
            value: "1a9cb166f1571100a92eb60da2bce5c5",
          },
          target: {
            display_value: "PS Apache03",
            link: "https://instance.servicenow.com/api/now/cmdb/instance/cmdb_ci/3a2810c20a0a0bb400268337d6e942ca",
            value: "3a2810c20a0a0bb400268337d6e942ca",
          },
        },
      ],
    },
  },
};

export const deleteConfigurationItemRelationResponse = {
  data: null,
};

export const getCMDBClassMetaDataResponse = {
  data: {
    result: {
      icon_url: "images/app.ngbsm/computer.svg",
      is_extendable: true,
      parent: "cmdb_ci_hardware",
      children: [
        "cmdb_ci_ucs_blade",
        "cmdb_ci_pc_hardware",
        "cmdb_ci_ucs_rack_unit",
        "cmdb_ci_mainframe_hardware",
        "cmdb_ci_server",
        "cmdb_ci_storage_switch",
      ],
      name: "cmdb_ci_computer",
      icon: "c6442dd69fb00200eb3919eb552e7012",
      attributes: [
        {
          is_inherited: "false",
          is_mandatory: "false",
          is_read_only: "false",
          default_value: null,
          label: "OS Address Width (bits)",
          type: "integer",
          element: "os_address_width",
          max_length: "40",
          is_display: "false",
        },
        {
          is_inherited: "true",
          is_mandatory: "false",
          is_read_only: "true",
          default_value: "false",
          label: "Skip sync",
          type: "boolean",
          element: "skip_sync",
          max_length: "40",
          is_display: "false",
        },
        {
          is_inherited: "true",
          is_mandatory: "false",
          is_read_only: "false",
          default_value: null,
          label: "DNS Domain",
          type: "string",
          element: "dns_domain",
          max_length: "255",
          is_display: "false",
        },
        {
          is_inherited: "true",
          is_mandatory: "false",
          is_read_only: "false",
          default_value: null,
          label: "Purchased",
          type: "glide_date",
          element: "purchase_date",
          max_length: "40",
          is_display: "false",
        },
        {
          is_inherited: "true",
          is_mandatory: "false",
          is_read_only: "false",
          default_value: null,
          label: "Lease contract",
          type: "string",
          element: "lease_id",
          max_length: "40",
          is_display: "false",
        },
      ],
      relationship_rules: [
        {
          parent: "cmdb_ci_computer",
          relation_type: "cb5592603751200032ff8c00dfbe5d17",
          child: "dscy_route_next_hop",
        },
        {
          parent: "cmdb_ci_computer",
          relation_type: "cb5592603751200032ff8c00dfbe5d17",
          child: "dscy_router_interface",
        },
        {
          parent: "cmdb_ci_computer",
          relation_type: "cb5592603751200032ff8c00dfbe5d17",
          child: "dscy_route_interface",
        },
        {
          parent: "cmdb_ci_computer",
          relation_type: "55c95bf6c0a8010e0118ec7056ebc54d",
          child: "cmdb_ci_storage_pool",
        },
        {
          parent: "cmdb_ci_computer",
          relation_type: "55c95bf6c0a8010e0118ec7056ebc54d",
          child: "cmdb_ci_disk_partition",
        },
        {
          parent: "cmdb_ci_computer",
          relation_type: "55c95bf6c0a8010e0118ec7056ebc54d",
          child: "cmdb_ci_storage_volume",
        },
        {
          parent: "cmdb_ci_computer",
          relation_type: "55c95bf6c0a8010e0118ec7056ebc54d",
          child: "cmdb_ci_storage_device",
        },
      ],
      label: "Computer",
      identification_rules: {
        related_rules: [
          {
            condition: "",
            exact_count_match: false,
            referenced_field: "installed_on",
            active: true,
            attributes: "name",
            allow_fallback: false,
            table: "cmdb_print_queue_instance",
            order: 100,
            allow_null_attribute: false,
          },
        ],
        applies_to: "cmdb_ci_hardware",
        identifiers: [
          {
            condition: "valid=true^absent=false^EQ",
            exact_count_match: true,
            referenced_field: "cmdb_ci",
            active: true,
            attributes: "serial_number,serial_number_type",
            allow_fallback: false,
            table: "cmdb_serial_number",
            order: 100,
            allow_null_attribute: false,
          },
          {
            condition: null,
            exact_count_match: false,
            referenced_field: null,
            active: true,
            attributes: "serial_number",
            allow_fallback: false,
            table: null,
            order: 200,
            allow_null_attribute: false,
          },
          {
            condition: null,
            exact_count_match: false,
            referenced_field: null,
            active: true,
            attributes: "name",
            allow_fallback: false,
            table: null,
            order: 300,
            allow_null_attribute: false,
          },
          {
            condition: "install_status!=100^EQ",
            exact_count_match: true,
            referenced_field: "cmdb_ci",
            active: true,
            attributes: "ip_address,mac_address",
            allow_fallback: false,
            table: "cmdb_ci_network_adapter",
            order: 400,
            allow_null_attribute: false,
          },
        ],
        name: "Hardware Rule",
        description: "Identifier for hardware.",
        active: true,
        is_independent: true,
      },
    },
  },
};

export const createConfigurationItemResponse = {
  data: {
    result: {
      outbound_relations: [
        {
          sys_id: "403ff2641b425010593876a61a4bcb4b",
          type: {
            display_value: "Depends on::Used by",
            link: "https://instance.servicenow.com/api/now/table/cmdb_rel_type/1a9cb166f1571100a92eb60da2bce5c5",
            value: "1a9cb166f1571100a92eb60da2bce5c5",
          },
          target: {
            display_value: "PS ORA01",
            link: "https://instance.servicenow.com/api/now/cmdb/instance/cmdb_ci/3a307c930a0a0bb400353965d0b8861f",
            value: "3a307c930a0a0bb400353965d0b8861f",
          },
        },
        {
          sys_id: "443ff2641b425010593876a61a4bcb4c",
          type: {
            display_value: "Exchanges data with::Exchanges data with",
            link: "https://instance.servicenow.com/api/now/table/cmdb_rel_type/607ad1b2c0a8010e01941856b365af90",
            value: "607ad1b2c0a8010e01941856b365af90",
          },
          target: {
            display_value: "PS ORA01",
            link: "https://instance.servicenow.com/api/now/cmdb/instance/cmdb_ci/3a307c930a0a0bb400353965d0b8861f",
            value: "3a307c930a0a0bb400353965d0b8861f",
          },
        },
      ],
      attributes: {
        firewall_status: "Intranet",
        os_address_width: "",
        attested_date: "",
        operational_status: "1",
        os_service_pack: "",
        cpu_core_thread: "",
        cpu_manufacturer: "",
        sys_updated_on: "2020-07-13 20:27:28",
        discovery_source: "ServiceNow",
        first_discovered: "2020-07-13 20:27:28",
        due_in: "",
        used_for: "Production",
        invoice_number: "",
        gl_account: "",
        sys_created_by: "dora.gray",
        warranty_expiration: "",
        ram: "",
        cpu_name: "",
        cpu_speed: "",
        owned_by: "",
        checked_out: "",
        kernel_release: "",
        sys_domain_path: "/",
        classification: "Production",
        disk_space: "",
        object_id: "",
        maintenance_schedule: "",
        cost_center: "",
        attested_by: "",
        dns_domain: "",
        assigned: "",
        purchase_date: "",
        life_cycle_stage: "",
        short_description: "",
        cd_speed: "",
        floppy: "",
        managed_by: "",
        os_domain: "",
        last_discovered: "2020-07-13 20:27:28",
        can_print: "false",
        sys_class_name: "cmdb_ci_linux_server",
        manufacturer: "",
        cpu_count: "",
        vendor: "",
        life_cycle_stage_status: "",
        model_number: "",
        assigned_to: "",
        start_date: "",
        os_version: "",
        serial_number: "",
        cd_rom: "false",
        support_group: "",
        unverified: "false",
        correlation_id: "",
        attributes: "",
        asset: "",
        form_factor: "",
        cpu_core_count: "",
        skip_sync: "false",
        attestation_score: "",
        sys_updated_by: "dora.gray",
        sys_created_on: "2020-07-13 20:27:28",
        sys_domain: {
          display_value: "global",
          link: "https://instance.servicenow.com/api/now/table/sys_user_group/global",
          value: "global",
        },
        cpu_type: "",
        install_date: "",
        asset_tag: "",
        dr_backup: "",
        hardware_substatus: "",
        fqdn: "",
        change_control: "",
        internet_facing: "true",
        delivery_date: "",
        hardware_status: "installed",
        install_status: "1",
        supported_by: "",
        name: "lnux299",
        subcategory: "Computer",
        default_gateway: "",
        chassis_type: "",
        virtual: "false",
        assignment_group: "",
        managed_by_group: "",
        sys_id: "0c3ff2641b425010593876a61a4bcb39",
        po_number: "",
        checked_in: "",
        sys_class_path: "/!!/!2/!(/!!/!0",
        mac_address: "",
        company: "",
        justification: "",
        department: "",
        cost: "",
        comments: "",
        os: "",
        sys_mod_count: "0",
        monitor: "false",
        model_id: "",
        ip_address: "",
        duplicate_of: "",
        sys_tags: "",
        cost_cc: "USD",
        order_date: "",
        schedule: "",
        environment: "",
        due: "",
        attested: "false",
        location: "",
        category: "Hardware",
        fault_count: "0",
        host_name: "",
        lease_id: "",
      },
      inbound_relations: [
        {
          sys_id: "c03ff2641b425010593876a61a4bcb49",
          type: {
            display_value: "Depends on::Used by",
            link: "https://instance.servicenow.com/api/now/table/cmdb_rel_type/1a9cb166f1571100a92eb60da2bce5c5",
            value: "1a9cb166f1571100a92eb60da2bce5c5",
          },
          target: {
            display_value: "PS Apache01",
            link: "https://instance.servicenow.com/api/now/cmdb/instance/cmdb_ci/3a27d4370a0a0bb4006316812bf45439",
            value: "3a27d4370a0a0bb4006316812bf45439",
          },
        },
      ],
    },
  },
};
