import { action } from "@prismatic-io/spectral";
import { createZoomClient } from "../../client";
import {
  connection,
  firstName,
  lastName,
  userType,
  cmsUserId,
  company,
  department,
  hostKey,
  jobTitle,
  location,
  personalMeetingId,
  timezone,
  userId,
  vanityName,
  customAttributes,
  groupId,
  userLanguage,
  manager,
  phoneNumbers,
  usePMI,
  displayName,
  zoomOneTypeUpdate,
  planUnitedTypeUpdate,
  zoomPhone,
  linkedinUrl,
  pronouns,
  pronounsOption,
  aboutMe,
  loginType,
  removeTspCredentials,
} from "../../inputs";

export const updateUser = action({
  display: {
    label: "Update User",
    description: "Update the information or metadata of a user by Id",
  },
  perform: async (
    { debug: { enabled: debug } },
    {
      connection,
      userId,
      loginType,
      removeTspCredentials,
      cmsUserId,
      company,
      customAttributes,
      dept,
      firstName,
      groupId,
      hostKey,
      jobTitle,
      language,
      lastName,
      location,
      manager,
      phoneNumbers,
      pmi,
      pronouns,
      pronounsOption,
      timezone,
      userType,
      usePMI,
      vanityName,
      displayName,
      zoomOneTypeUpdate,
      planUnitedTypeUpdate,
      zoomPhone,
      aboutMe,
      linkedinUrl,
    },
  ) => {
    const client = createZoomClient({ connection, debug });

    const { data } = await client.patch(
      `/users/${userId}`,
      {
        cms_user_id: cmsUserId,
        company,
        custom_attributes: customAttributes,
        dept,
        first_name: firstName,
        group_id: groupId,
        host_key: hostKey,
        job_title: jobTitle,
        language,
        last_name: lastName,
        location,
        manager,
        phone_numbers: phoneNumbers,
        pmi,
        pronouns,
        pronouns_option: pronounsOption,
        timezone,
        type: userType,
        use_pmi: usePMI,
        vanity_name: vanityName,
        display_name: displayName,
        zoom_one_type: zoomOneTypeUpdate,
        plan_united_type: planUnitedTypeUpdate,
        feature: {
          zoom_phone: zoomPhone,
        },
        about_me: aboutMe,
        linkedin_url: linkedinUrl,
      },
      {
        params: {
          login_type: loginType,
          remove_tsp_credentials: removeTspCredentials,
        },
      },
    );

    return {
      data,
    };
  },
  inputs: {
    connection,
    loginType,
    removeTspCredentials,
    userId,
    cmsUserId,
    company,
    customAttributes,
    dept: department,
    firstName: { ...firstName, required: false },
    groupId,
    hostKey,
    jobTitle,
    language: userLanguage,
    lastName: { ...lastName, required: false },
    location,
    manager,
    phoneNumbers,
    pmi: personalMeetingId,
    pronouns,
    pronounsOption,
    timezone,
    userType: { ...userType, comments: "The type of user.", required: false },
    usePMI,
    vanityName,
    displayName,
    zoomOneTypeUpdate,
    planUnitedTypeUpdate,
    zoomPhone,
    aboutMe,
    linkedinUrl,
  },
  examplePayload: { data: {} },
});
