import { action, outputSchema } from "@prismatic-io/spectral";
import { createArenaClient } from "../../client";
import { listExtractRunFilesExamplePayload } from "../../examplePayloads";
import { listExtractRunFilesInputs } from "../../inputs";
import { listExtractRunFilesOutputSchema } from "../../outputSchemas";
import { handleArenaError } from "../../util";
export const listExtractRunFiles = action({
  display: {
    label: "List Extract Run Files",
    description: "Get metadata for files generated by an extract run.",
  },
  inputs: listExtractRunFilesInputs,
  outputSchema: outputSchema({
    type: "actionOutput",
    schema: listExtractRunFilesOutputSchema,
  }),
  examplePayload: listExtractRunFilesExamplePayload,
  perform: async (context, params) => {
    try {
      const client = await createArenaClient(context, params.connection);
      const { data } = await client.get(
        `/extracts/${params.extractGuid}/runs/${params.extractRunGuid}/files`,
      );
      return { data };
    } catch (error: unknown) {
      handleArenaError(error, context.logger, "List Extract Run Files");
    }
  },
});
