export const accountSignatureJson = {
  accountSignatures: [
    {
      adoptedDateTime: "2023-12-31T20:28:11Z",
      createdDateTime: "2023-12-31T20:28:11Z",
      customField: "field",
      dateStampProperties: {
        dateAreaHeight: "256",
        dateAreaWidth: "256",
        dateAreaX: "256",
        dateAreaY: "256",
      },
      disallowUserResizeStamp: "true",
      externalID: "12345",
      imageType: "stamp_image",
      initials150ImageId: "123",
      initialsImageUri: "https://example.com/images/initials.jpg",
      isDefault: "true",
      phoneticName: "name",
      signature150ImageId: "1234",
      signatureFont: "1_DocuSign",
      signatureId: "12345",
      signatureImageUri: "https://example.com/images/signature.jpg",
      signatureInitials: "JD",
      signatureName: "John",
      signatureRights: "read",
      signatureType: "type",
      signatureUsers: [
        {
          isDefault: "true",
          rights: "editable",
          userId: "1234",
          userName: "User",
        },
      ],
      stampFormat: "NameHanko",
      stampImageUri: "https://example.com/images/stamp.jpg",
      stampSizeMM: "50",
      stampType: "signature",
      status: "sent",
      imageBase64: "base64string",
    },
  ],
};
