const itamAssetBaseProperties = {
  asset_id: { type: "number" },
  id: { type: "number" },
  device_id: { type: ["number", "null"] },
  name: { type: "string" },
  serial_no: { type: ["string", "null"] },
  asset_no: { type: ["string", "null"] },
  uuid: { type: ["string", "null"] },
  notes: { type: ["string", "null"] },
  tags: { type: "array", items: { type: "string" } },
  aliases: { type: "array", items: { type: "string" } },
  preferred_alias: { type: ["string", "null"] },
  custom_fields: { type: ["array", "object"] },
  device_external_links: { type: "array" },
  in_service: { type: ["string", "boolean", "null"] },
  service_level: { type: ["string", "null"] },
  type: { type: ["string", "null"] },
  type_id: { type: ["number", "null"] },
  device_sub_type: { type: ["string", "null"] },
  impact: { type: ["string", "null"] },
  usage_type: { type: ["string", "null"] },
  state: { type: ["string", "null"] },
  category: { type: ["string", "null"] },
  last_updated: { type: ["string", "null"] },
  hw_model: { type: ["string", "null"] },
  hw_size: { type: ["number", "string", "null"] },
  hw_depth: { type: ["string", "null"] },
  manufacturer: { type: ["string", "null"] },
  cpucount: { type: ["number", "null"] },
  cpucore: { type: ["number", "null"] },
  cpuspeed: { type: ["number", "string", "null"] },
  ram: { type: ["number", "string", "null"] },
  hddcount: { type: ["number", "null"] },
  hddsize: { type: ["number", "string", "null"] },
  hddraid: { type: ["string", "null"] },
  hddraid_type: { type: ["string", "null"] },
  hdd_details: { type: ["string", "null"] },
  building: { type: ["string", "null"] },
  room: { type: ["string", "null"] },
  row: { type: ["string", "null"] },
  location: { type: ["string", "null"] },
  location_id: { type: ["number", "null"] },
  rack: { type: ["string", "null"] },
  rack_id: { type: ["number", "null"] },
  width_ratio_raw: { type: ["number", "null"] },
  width_ratio: { type: ["string", "null"] },
  start_at: { type: ["number", "string", "null"] },
  orientation: { type: ["string", "null"] },
  reversed: { type: ["string", "boolean", "null"] },
  slot_number: { type: ["number", "null"] },
  xpos: { type: ["number", "null"] },
  ip_addresses: { type: "array" },
  mac_addresses: { type: "array" },
  pdu_mapping_url: { type: ["string", "null"] },
  ucs_manager: { type: ["string", "null"] },
  blade_host_name: { type: ["string", "null"] },
  blade_host_id: { type: ["number", "null"] },
  virtual_host_name: { type: ["string", "null"] },
  modules: { type: "array" },
  vms: { type: "array" },
  devices: { type: "array" },
  device_purchase_line_items: { type: "array" },
  customer_id: { type: ["number", "null"] },
  customer: { type: ["string", "null"] },
  workspace_id: { type: ["number", "null"] },
  workspace: { type: ["string", "null"] },
  department_id: { type: ["number", "null"] },
  department: { type: ["string", "null"] },
  group_id: { type: ["number", "null"] },
  agent_id: { type: ["number", "null"] },
  user_id: { type: ["number", "null"] },
  technical_owner_user_id: { type: ["number", "null"] },
  functional_owner_user_id: { type: ["number", "null"] },
  vendor_id: { type: ["number", "null"] },
  vendor: { type: ["string", "null"] },
  asset_purchases: { type: ["array", "string"] },
  discovery_sources: {
    type: ["array", "object"],
    items: {
      type: "object",
      properties: {
        value: { type: ["string", "null"] },
        timestamp: { type: ["string", "null"], format: "date-time" },
      },
    },
  },
};
export const itamAssetOutputSchema = {
  type: "object" as const,
  properties: { ...itamAssetBaseProperties },
  required: [],
};
export const itamAssetsListOutputSchema = {
  type: "object" as const,
  properties: {
    meta: {
      type: "object",
      properties: {
        page: { type: "number" },
        per_page: { type: "number" },
        total_count: { type: "number" },
      },
      required: ["page", "per_page", "total_count"],
    },
    assets: {
      type: "array",
      items: {
        type: "object",
        properties: { ...itamAssetBaseProperties },
        required: [],
      },
    },
  },
  required: ["meta", "assets"],
};
export const itamAssetWriteOutputSchema = {
  type: "object" as const,
  properties: {
    action: {
      type: "string",
      description: "The write Freshservice reports having performed.",
    },
    id: {
      type: ["number", "null"],
      description: "The asset_id of the affected record.",
    },
    name: { type: "string" },
    didSomethingChange: {
      type: "boolean",
      description:
        "False when the request matched a record but changed nothing.",
    },
    isNew: {
      type: "boolean",
      description:
        "True when the request created the record rather than updating one.",
    },
    code: {
      type: ["number", "null"],
      description:
        "The vendor status code sent alongside msg. Zero on success.",
    },
    raw: {
      type: "array",
      description:
        "The original positional tuple, in case a position is unmapped.",
    },
  },
  required: ["action", "isNew"],
};
