import { attachmentSchema, customFieldsSchema } from "./common";
export const createServiceRequestOutputSchema = {
  type: "object" as const,
  properties: {
    service_request: {
      type: "object",
      properties: {
        id: { type: "number" },
        workspace_id: { type: "number" },
        subject: { type: "string" },
        description: { type: "string" },
        description_text: { type: "string" },
        type: { type: "string" },
        status: { type: "number" },
        priority: { type: "number" },
        urgency: { type: "number" },
        impact: { type: "number" },
        source: { type: "number" },
        requester_id: { type: "number" },
        responder_id: { type: ["number", "null"] },
        group_id: { type: ["number", "null"] },
        department_id: { type: ["number", "null"] },
        email_config_id: { type: ["number", "null"] },
        category: { type: ["string", "null"] },
        sub_category: { type: ["string", "null"] },
        item_category: { type: ["string", "null"] },
        due_by: { type: "string", format: "date-time" },
        fr_due_by: { type: "string", format: "date-time" },
        created_at: { type: "string", format: "date-time" },
        updated_at: { type: "string", format: "date-time" },
        custom_fields: customFieldsSchema,
        attachments: { type: "array", items: attachmentSchema },
        cc_emails: { type: ["array", "null"], items: { type: "string" } },
        fwd_emails: { type: ["array", "null"], items: { type: "string" } },
        reply_cc_emails: { type: ["array", "null"], items: { type: "string" } },
        to_emails: { type: ["array", "null"], items: { type: "string" } },
        resolution_notes: { type: ["string", "null"] },
        resolution_notes_html: { type: ["string", "null"] },
        fr_escalated: { type: "boolean" },
        is_escalated: { type: "boolean" },
        spam: { type: "boolean" },
        deleted: { type: "boolean" },
        sla_policy_id: { type: "number" },
        approval_status: { type: ["number", "string", "null"] },
        approval_status_name: { type: ["string", "null"] },
      },
      required: ["id"],
      additionalProperties: false,
    },
  },
  required: ["service_request"],
  additionalProperties: false,
};
