export const emptyPayload = { data: {} };
export const createCustomerPayload = {
  data: {
    reference: "ABCDE",
    name: "John",
    short_name: "John",
    balance: 0,
    on_hold: false,
    account_status_type: "AccountStatusActive",
    status_reason: "",
    currency_id: 2103,
    exchange_rate_type: "ExchangeRateSingle",
    telephone_country_code: "",
    telephone_area_code: "",
    telephone_subscriber_number: "",
    fax_country_code: "",
    fax_area_code: "",
    fax_subscriber_number: "",
    website: "",
    credit_limit: 0,
    country_code_id: 13,
    default_tax_code_id: 1729,
    vat_number: "",
    account_type: "TradingAccountTypeOpenItem",
    early_settlement_discount_percent: 0,
    early_settlement_discount_days: 0,
    payment_terms_days: 0,
    payment_terms_basis: "PaymentDueFromCalendarMonth",
    credit_bureau_id: 2135,
    credit_position_id: 1,
    trading_terms: "",
    credit_reference: "",
    account_opened: "2024-05-23T00:00:00Z",
    terms_agreed: false,
    order_priority: "",
    months_to_keep_transactions: 36,
    default_nominal_code_reference: "4000",
    default_nominal_code_cost_centre: "",
    default_nominal_code_department: "",
    analysis_code_1: "",
    analysis_code_2: "",
    analysis_code_3: "",
    analysis_code_4: "",
    analysis_code_5: "",
    analysis_code_6: "",
    analysis_code_7: "",
    analysis_code_8: "",
    analysis_code_9: "",
    analysis_code_10: "",
    analysis_code_11: "",
    analysis_code_12: "",
    analysis_code_13: "",
    analysis_code_14: "",
    analysis_code_15: "",
    analysis_code_16: "",
    analysis_code_17: "",
    analysis_code_18: "",
    analysis_code_19: "",
    analysis_code_20: "",
    spare_text_1: "",
    spare_text_2: "",
    spare_text_3: "",
    spare_text_4: "",
    spare_text_5: "",
    spare_text_6: "",
    spare_text_7: "",
    spare_text_8: "",
    spare_text_9: "",
    spare_text_10: "",
    spare_number_1: 0,
    spare_number_2: 0,
    spare_number_3: 0,
    spare_number_4: 0,
    spare_number_5: 0,
    spare_number_6: 0,
    spare_number_7: 0,
    spare_number_8: 0,
    spare_number_9: 0,
    spare_number_10: 0,
    spare_bool_1: false,
    spare_bool_2: false,
    spare_bool_3: false,
    spare_bool_4: false,
    spare_bool_5: false,
    value_of_current_orders_in_sop: 0,
    duns_code: "",
    average_time_to_pay: 0,
    finance_charge_id: 0,
    office_type: "Independent",
    associated_head_office_id: 0,
    produce_statements_for_customer: false,
    use_consolidated_billing: false,
    use_tax_code_as_default: false,
    invoice_discount_percent: 0,
    invoice_line_discount_percent: 0,
    customer_discount_group_id: 0,
    order_value_discount_id: 0,
    price_band_id: 0,
    id: 82660,
  },
};

export const getCustomerPayload = {
  data: {
    reference: "ABCDE",
    name: "John",
    short_name: "John",
    balance: 0,
    on_hold: false,
    account_status_type: "AccountStatusActive",
    status_reason: "",
    currency_id: 2103,
    exchange_rate_type: "ExchangeRateSingle",
    telephone_country_code: "",
    telephone_area_code: "",
    telephone_subscriber_number: "",
    fax_country_code: "",
    fax_area_code: "",
    fax_subscriber_number: "",
    website: "",
    credit_limit: 0,
    country_code_id: 13,
    default_tax_code_id: 1729,
    vat_number: "",
    account_type: "TradingAccountTypeOpenItem",
    early_settlement_discount_percent: 0,
    early_settlement_discount_days: 0,
    payment_terms_days: 0,
    payment_terms_basis: "PaymentDueFromCalendarMonth",
    credit_bureau_id: 2135,
    credit_position_id: 1,
    trading_terms: "",
    credit_reference: "",
    account_opened: "2024-05-23T00:00:00Z",
    terms_agreed: false,
    order_priority: "",
    months_to_keep_transactions: 36,
    default_nominal_code_reference: "4000",
    default_nominal_code_cost_centre: "",
    default_nominal_code_department: "",
    analysis_code_1: "",
    analysis_code_2: "",
    analysis_code_3: "",
    analysis_code_4: "",
    analysis_code_5: "",
    analysis_code_6: "",
    analysis_code_7: "",
    analysis_code_8: "",
    analysis_code_9: "",
    analysis_code_10: "",
    analysis_code_11: "",
    analysis_code_12: "",
    analysis_code_13: "",
    analysis_code_14: "",
    analysis_code_15: "",
    analysis_code_16: "",
    analysis_code_17: "",
    analysis_code_18: "",
    analysis_code_19: "",
    analysis_code_20: "",
    spare_text_1: "",
    spare_text_2: "",
    spare_text_3: "",
    spare_text_4: "",
    spare_text_5: "",
    spare_text_6: "",
    spare_text_7: "",
    spare_text_8: "",
    spare_text_9: "",
    spare_text_10: "",
    spare_number_1: 0,
    spare_number_2: 0,
    spare_number_3: 0,
    spare_number_4: 0,
    spare_number_5: 0,
    spare_number_6: 0,
    spare_number_7: 0,
    spare_number_8: 0,
    spare_number_9: 0,
    spare_number_10: 0,
    spare_bool_1: false,
    spare_bool_2: false,
    spare_bool_3: false,
    spare_bool_4: false,
    spare_bool_5: false,
    value_of_current_orders_in_sop: 0,
    duns_code: "",
    average_time_to_pay: 0,
    finance_charge_id: 0,
    office_type: "Independent",
    associated_head_office_id: 0,
    produce_statements_for_customer: false,
    use_consolidated_billing: false,
    use_tax_code_as_default: false,
    invoice_discount_percent: 0,
    invoice_line_discount_percent: 0,
    customer_discount_group_id: 0,
    order_value_discount_id: 0,
    price_band_id: 1064,
    id: 82660,
    date_time_created: "2024-05-23T22:04:20.567Z",
    date_time_updated: "2024-05-23T22:04:22.863Z",
  },
};

export const listCustomersPayload = {
  data: [
    {
      reference: "A1D001",
      name: "A1 Design Services",
      short_name: "A1 Desig",
      balance: 1120.92,
      on_hold: false,
      account_status_type: "AccountStatusActive",
      status_reason: "",
      currency_id: 2103,
      exchange_rate_type: "ExchangeRateSingle",
      telephone_country_code: "44",
      telephone_area_code: "01742",
      telephone_subscriber_number: "876234",
      fax_country_code: "44",
      fax_area_code: "01742",
      fax_subscriber_number: "876236",
      website: "www.sage.co.uk",
      credit_limit: 0,
      country_code_id: 13,
      default_tax_code_id: 1729,
      vat_number: "GB238 3839 38",
      account_type: "TradingAccountTypeOpenItem",
      early_settlement_discount_percent: 2.5,
      early_settlement_discount_days: 15,
      payment_terms_days: 30,
      payment_terms_basis: "PaymentDueFromDocumentDate",
      credit_bureau_id: 2136,
      credit_position_id: 1,
      trading_terms: "30 days nett",
      credit_reference: "TS3811",
      account_opened: "2024-01-02T00:00:00Z",
      last_credit_review: "2024-12-04T00:00:00Z",
      next_credit_review: "2025-02-01T00:00:00Z",
      application_date: "2024-01-02T00:00:00Z",
      date_received: "2024-01-02T00:00:00Z",
      terms_agreed: true,
      order_priority: "",
      months_to_keep_transactions: 36,
      default_nominal_code_reference: "4000",
      default_nominal_code_cost_centre: "",
      default_nominal_code_department: "",
      analysis_code_1: "Trade",
      analysis_code_2: "George",
      analysis_code_3: "Lancashire",
      analysis_code_4: "",
      analysis_code_5: "",
      analysis_code_6: "",
      analysis_code_7: "",
      analysis_code_8: "",
      analysis_code_9: "",
      analysis_code_10: "",
      analysis_code_11: "",
      analysis_code_12: "",
      analysis_code_13: "",
      analysis_code_14: "",
      analysis_code_15: "",
      analysis_code_16: "",
      analysis_code_17: "",
      analysis_code_18: "",
      analysis_code_19: "",
      analysis_code_20: "",
      spare_text_1: "",
      spare_text_2: "",
      spare_text_3: "",
      spare_text_4: "",
      spare_text_5: "",
      spare_text_6: "",
      spare_text_7: "",
      spare_text_8: "",
      spare_text_9: "",
      spare_text_10: "",
      spare_number_1: 0,
      spare_number_2: 0,
      spare_number_3: 0,
      spare_number_4: 0,
      spare_number_5: 0,
      spare_number_6: 0,
      spare_number_7: 0,
      spare_number_8: 0,
      spare_number_9: 0,
      spare_number_10: 0,
      spare_bool_1: false,
      spare_bool_2: false,
      spare_bool_3: false,
      spare_bool_4: false,
      spare_bool_5: false,
      value_of_current_orders_in_sop: 340.38,
      duns_code: "",
      average_time_to_pay: 0,
      finance_charge_id: 0,
      office_type: "Independent",
      associated_head_office_id: 0,
      produce_statements_for_customer: false,
      use_consolidated_billing: false,
      use_tax_code_as_default: false,
      invoice_discount_percent: 0,
      invoice_line_discount_percent: 0,
      customer_discount_group_id: 37745,
      order_value_discount_id: 0,
      price_band_id: 37418,
      id: 27825,
      date_time_created: "2024-02-28T14:06:36.61Z",
      date_time_updated: "2024-05-23T09:46:30.65Z",
    },
  ],
};

export const selectCustomerPayload = {
  result: [{ label: "A1 Design Services", key: "27825" }],
};

export const selectProductGroupPayload = {
  result: [{ label: "Paper Products", key: "34634" }],
};

export const selectTaxCodePayload = {
  result: [{ label: "Purchase Services ROW (Reverse Charge)", key: "16" }],
};

export const searchCustomersPayload = {
  data: [
    {
      id: 27825,
      reference: "A1D001",
      name: "A1 Design Services",
      short_name: "A1 Desig",
      account_status_type_id: 0,
      post_code: "BP12 7HT",
      office_type_id: 0,
    },
    {
      id: 49621,
      reference: "A1D002",
      name: "A2 Design Services",
      short_name: "A2 Desig",
      account_status_type_id: 0,
      post_code: "BP12 7HT",
      office_type_id: 0,
    },
  ],
};

export const updateCustomerPayload = {
  data: {
    reference: "ABCDE",
    name: "John",
    short_name: "John",
    balance: 0,
    on_hold: false,
    account_status_type: "AccountStatusActive",
    status_reason: "",
    currency_id: 2103,
    exchange_rate_type: "ExchangeRateSingle",
    telephone_country_code: "",
    telephone_area_code: "",
    telephone_subscriber_number: "",
    fax_country_code: "",
    fax_area_code: "",
    fax_subscriber_number: "",
    website: "",
    credit_limit: 0,
    country_code_id: 13,
    default_tax_code_id: 1729,
    vat_number: "",
    account_type: "TradingAccountTypeOpenItem",
    early_settlement_discount_percent: 0,
    early_settlement_discount_days: 0,
    payment_terms_days: 0,
    payment_terms_basis: "PaymentDueFromCalendarMonth",
    credit_bureau_id: 2135,
    credit_position_id: 1,
    trading_terms: "",
    credit_reference: "",
    account_opened: "2024-05-23T00:00:00Z",
    terms_agreed: false,
    order_priority: "",
    months_to_keep_transactions: 36,
    default_nominal_code_reference: "4000",
    default_nominal_code_cost_centre: "",
    default_nominal_code_department: "",
    analysis_code_1: "",
    analysis_code_2: "",
    analysis_code_3: "",
    analysis_code_4: "",
    analysis_code_5: "",
    analysis_code_6: "",
    analysis_code_7: "",
    analysis_code_8: "",
    analysis_code_9: "",
    analysis_code_10: "",
    analysis_code_11: "",
    analysis_code_12: "",
    analysis_code_13: "",
    analysis_code_14: "",
    analysis_code_15: "",
    analysis_code_16: "",
    analysis_code_17: "",
    analysis_code_18: "",
    analysis_code_19: "",
    analysis_code_20: "",
    spare_text_1: "",
    spare_text_2: "",
    spare_text_3: "",
    spare_text_4: "",
    spare_text_5: "",
    spare_text_6: "",
    spare_text_7: "",
    spare_text_8: "",
    spare_text_9: "",
    spare_text_10: "",
    spare_number_1: 0,
    spare_number_2: 0,
    spare_number_3: 0,
    spare_number_4: 0,
    spare_number_5: 0,
    spare_number_6: 0,
    spare_number_7: 0,
    spare_number_8: 0,
    spare_number_9: 0,
    spare_number_10: 0,
    spare_bool_1: false,
    spare_bool_2: false,
    spare_bool_3: false,
    spare_bool_4: false,
    spare_bool_5: false,
    value_of_current_orders_in_sop: 0,
    duns_code: "",
    average_time_to_pay: 0,
    finance_charge_id: 0,
    office_type: "Independent",
    associated_head_office_id: 0,
    produce_statements_for_customer: false,
    use_consolidated_billing: false,
    use_tax_code_as_default: false,
    invoice_discount_percent: 0,
    invoice_line_discount_percent: 0,
    customer_discount_group_id: 0,
    order_value_discount_id: 0,
    price_band_id: 1064,
    id: 82660,
    date_time_created: "2024-05-23T22:04:20.567Z",
    date_time_updated: "2024-05-23T22:04:20.567Z",
  },
};

export const getCustomerContactPayload = {
  data: {
    customer_id: 27825,
    salutation_id: 0,
    name: "Art Vandelay Dalkin",
    first_name: "Art",
    middle_name: "Vandelay",
    last_name: "Dalkin",
    is_default: true,
    default_telephone: "01742 876 234",
    default_email: "newbusinessadvice@sage.com",
    id: 27914,
    date_time_created: "2024-02-28T14:06:36.887Z",
    date_time_updated: "2024-05-23T09:25:16.827Z",
  },
};

export const listCustomerContactsPayload = {
  data: [
    {
      customer_id: 27825,
      salutation_id: 0,
      name: "Art Vandelay Dalkin",
      first_name: "Art",
      middle_name: "Vandelay",
      last_name: "Dalkin",
      is_default: true,
      default_telephone: "01742 876 234",
      default_email: "newbusinessadvice@sage.com",
      id: 27914,
      date_time_created: "2024-02-28T14:06:36.887Z",
      date_time_updated: "2024-05-23T09:25:16.827Z",
    },
  ],
};

export const updateCustomerContactPayload = {
  data: {
    customer_id: 27825,
    salutation_id: 0,
    name: "Art Vandelay Dalkin",
    first_name: "Art",
    middle_name: "Vandelay",
    last_name: "Dalkin",
    is_default: true,
    default_telephone: "01742 876 234",
    default_email: "newbusinessadvice@sage.com",
    id: 27914,
    date_time_created: "2024-02-28T14:06:36.887Z",
    date_time_updated: "2024-05-23T09:25:16.827Z",
  },
};

export const createCustomerDeliveryAddressPayload = {
  data: {
    contact: "",
    country: "",
    customer_id: 27825,
    description: "Home Address 4",
    email: "",
    fax: "",
    is_default: false,
    postal_name: "Peter Young",
    tax_code_id: 1729,
    tax_number: "GB238 3839 38",
    telephone: "",
    country_code_id: 13,
    address_1: "1 High Street",
    address_2: "",
    address_3: "",
    address_4: "",
    city: "",
    county: "",
    postcode: "",
    address_country_code_id: 0,
    id: 82790,
  },
};

export const getCustomerDeliveryAddressPayload = {
  data: {
    contact: "Lee Dalkin",
    country: "",
    customer_id: 27825,
    description: "Registered address",
    email: "newbusinessadvice@sage.com",
    fax: "01742 876 236",
    is_default: false,
    postal_name: "A1 Design Services",
    tax_code_id: 1729,
    tax_number: "GB238 3839 38",
    telephone: "01742 876 234",
    country_code_id: 13,
    address_1: "67a Station Road",
    address_2: "",
    address_3: "Blackpool",
    address_4: "Lancashire",
    city: "",
    county: "",
    postcode: "BP12 7HT",
    address_country_code_id: 0,
    id: 27927,
    date_time_created: "2024-02-28T14:06:36.983Z",
    date_time_updated: "2024-02-28T14:23:46.867Z",
  },
};

export const listCustomerDeliveryAddressesPayload = {
  data: [
    {
      contact: "Lee Dalkin",
      country: "",
      customer_id: 27825,
      description: "Registered address",
      email: "newbusinessadvice@sage.com",
      fax: "01742 876 236",
      is_default: false,
      postal_name: "A1 Design Services",
      tax_code_id: 1729,
      tax_number: "GB238 3839 38",
      telephone: "01742 876 234",
      country_code_id: 13,
      address_1: "67a Station Road",
      address_2: "",
      address_3: "Blackpool",
      address_4: "Lancashire",
      city: "",
      county: "",
      postcode: "BP12 7HT",
      address_country_code_id: 0,
      id: 27927,
      date_time_created: "2024-02-28T14:06:36.983Z",
      date_time_updated: "2024-02-28T14:23:46.867Z",
    },
  ],
};

export const updateCustomerDeliveryAddressPayload = {
  data: {
    contact: "",
    country: "",
    customer_id: 27825,
    description: "Home Address 4",
    email: "",
    fax: "",
    is_default: false,
    postal_name: "Company",
    tax_code_id: 1729,
    tax_number: "GB238 3839 38",
    telephone: "",
    country_code_id: 13,
    address_1: "1 High Street",
    address_2: "",
    address_3: "",
    address_4: "",
    city: "",
    county: "",
    postcode: "",
    address_country_code_id: 0,
    id: 82790,
    date_time_created: "2024-05-23T23:33:04.58Z",
    date_time_updated: "2024-05-23T23:33:04.58Z",
  },
};

export const getCustomerPriceBandPayload = {
  data: {
    customer_id: 27828,
    price_band_id: 37419,
    id: 44501,
    date_time_created: "2024-07-22T09:31:04.257Z",
    date_time_updated: "2024-02-28T14:23:46.01Z",
  },
};

export const listCustomerPriceBandsPayload = {
  data: [
    {
      customer_id: 27828,
      price_band_id: 37419,
      id: 44501,
      date_time_created: "2024-07-22T09:31:04.257Z",
      date_time_updated: "2024-02-28T14:23:46.01Z",
    },
  ],
};

export const getPriceBandPayload = {
  data: {
    name: "Standard",
    description: "Standard",
    is_standard_band: true,
    currency_id: 2103,
    price_band_type_id: 0,
    price_band_type: "Universal",
    is_active: true,
    is_time_based: false,
    id: 1064,
    date_time_created: "2024-02-28T14:03:39.973Z",
    date_time_updated: "2024-02-28T14:23:46.183Z",
  },
};

export const listPriceBandsPayload = {
  data: [
    {
      name: "Standard",
      description: "Standard",
      is_standard_band: true,
      currency_id: 2103,
      price_band_type_id: 0,
      price_band_type: "Universal",
      is_active: true,
      is_time_based: false,
      id: 1064,
      date_time_created: "2024-02-28T14:03:39.973Z",
      date_time_updated: "2024-02-28T14:23:46.183Z",
    },
  ],
};

export const listPricingSourceTypesPayload = {
  data: [
    {
      id: 0,
      value: "LastBuyingPrice",
      description: "Last Buying Price",
    },
  ],
};

export const listPricingTypesPayload = {
  data: [
    {
      id: 0,
      value: "EnumTradePricingTypeUnitPrice",
      description: "Unit Price",
    },
  ],
};

export const getProductPayload = {
  data: {
    code: "BOARD001",
    name: "Whiteboard - Drywipe (900 x 1200)",
    description: "Whiteboard - Drywipe (900 x 1200) Updated",
    use_description_on_documents: false,
    barcode: "",
    allow_sales_order: true,
    free_stock_quantity: 107,
    product_group_id: 34640,
    tax_code_id: 1729,
    product_status_type: "EnumStockItemStatusTypeActive",
    fulfilment_method_type: "EnumFulfilmentFromStock",
    fulfilment_sequence_type: "EnumBinPriority",
    manufacturer: "",
    part_number: "WB/U143-78243/2437032ALX4/24369/DW1200X900",
    label_printing_option_type: "EnumNotRequired",
    traceable_type: "EnumTraceableTypeNone",
    sale_from_single_batch: false,
    allow_duplicate_numbers: false,
    uses_alternative_ref: false,
    uses_sell_by_date: false,
    uses_use_by_date: false,
    shelf_life: 0,
    shelf_life_type: "EnumTimeUnitDay",
    record_nos_on_goods_received: false,
    include_nos_on_count_sheets: true,
    auto_generate_option_type: "EnumDoNotGenerate",
    auto_generate_separator_id: 1,
    auto_generate_prefix: "",
    auto_generate_next_number: 1,
    auto_generate_padding: 0,
    stocktake_cycle_period: 0,
    standard_cost: 15,
    average_buying_price: 13.2,
    default_picking_list_comment: "",
    default_despatch_note_comment: "",
    commodity_code: "",
    country_of_origin_id: 0,
    weight: 0,
    suppress_mass_on_declaration: false,
    is_weee_item: false,
    use_supplementary_units: false,
    supplementary_unit_conversion_ratio: 1,
    use_reverse_charge_vat_rules: false,
    analysis_code_1: "",
    analysis_code_2: "",
    analysis_code_3: "",
    analysis_code_4: "",
    analysis_code_5: "",
    analysis_code_6: "",
    analysis_code_7: "",
    analysis_code_8: "",
    analysis_code_9: "",
    analysis_code_10: "",
    analysis_code_11: "",
    analysis_code_12: "",
    analysis_code_13: "",
    analysis_code_14: "",
    analysis_code_15: "",
    analysis_code_16: "",
    analysis_code_17: "",
    analysis_code_18: "",
    analysis_code_19: "",
    analysis_code_20: "",
    spare_text_1: "",
    spare_text_2: "",
    spare_text_3: "",
    spare_text_4: "",
    spare_text_5: "",
    spare_text_6: "",
    spare_text_7: "",
    spare_text_8: "",
    spare_text_9: "",
    spare_text_10: "",
    spare_number_1: 0,
    spare_number_2: 0,
    spare_number_3: 0,
    spare_number_4: 0,
    spare_number_5: 0,
    spare_number_6: 0,
    spare_number_7: 0,
    spare_number_8: 0,
    spare_number_9: 0,
    spare_number_10: 0,
    spare_bool_1: false,
    spare_bool_2: false,
    spare_bool_3: false,
    spare_bool_4: false,
    spare_bool_5: false,
    landed_costs_type: "EnumNotApplicable",
    landed_costs_percentage: 0,
    landed_costs_per_item: 0,
    bom_item_type: "EnumBOMItemTypeComponent",
    id: 34751,
    date_time_created: "2024-02-28T14:06:51.043Z",
    date_time_updated: "2024-05-24T00:27:17.897Z",
  },
};

export const listProductsPayload = {
  data: [
    {
      code: "BOARD001",
      name: "Whiteboard - Drywipe (900 x 1200)",
      description: "Whiteboard - Drywipe (900 x 1200) Updated",
      use_description_on_documents: false,
      barcode: "",
      allow_sales_order: true,
      free_stock_quantity: 107,
      product_group_id: 34640,
      tax_code_id: 1729,
      product_status_type: "EnumStockItemStatusTypeActive",
      fulfilment_method_type: "EnumFulfilmentFromStock",
      fulfilment_sequence_type: "EnumBinPriority",
      manufacturer: "",
      part_number: "WB/U143-78243/2437032ALX4/24369/DW1200X900",
      label_printing_option_type: "EnumNotRequired",
      traceable_type: "EnumTraceableTypeNone",
      sale_from_single_batch: false,
      allow_duplicate_numbers: false,
      uses_alternative_ref: false,
      uses_sell_by_date: false,
      uses_use_by_date: false,
      shelf_life: 0,
      shelf_life_type: "EnumTimeUnitDay",
      record_nos_on_goods_received: false,
      include_nos_on_count_sheets: true,
      auto_generate_option_type: "EnumDoNotGenerate",
      auto_generate_separator_id: 1,
      auto_generate_prefix: "",
      auto_generate_next_number: 1,
      auto_generate_padding: 0,
      stocktake_cycle_period: 0,
      standard_cost: 15,
      average_buying_price: 13.2,
      default_picking_list_comment: "",
      default_despatch_note_comment: "",
      commodity_code: "",
      country_of_origin_id: 0,
      weight: 0,
      suppress_mass_on_declaration: false,
      is_weee_item: false,
      use_supplementary_units: false,
      supplementary_unit_conversion_ratio: 1,
      use_reverse_charge_vat_rules: false,
      analysis_code_1: "",
      analysis_code_2: "",
      analysis_code_3: "",
      analysis_code_4: "",
      analysis_code_5: "",
      analysis_code_6: "",
      analysis_code_7: "",
      analysis_code_8: "",
      analysis_code_9: "",
      analysis_code_10: "",
      analysis_code_11: "",
      analysis_code_12: "",
      analysis_code_13: "",
      analysis_code_14: "",
      analysis_code_15: "",
      analysis_code_16: "",
      analysis_code_17: "",
      analysis_code_18: "",
      analysis_code_19: "",
      analysis_code_20: "",
      spare_text_1: "",
      spare_text_2: "",
      spare_text_3: "",
      spare_text_4: "",
      spare_text_5: "",
      spare_text_6: "",
      spare_text_7: "",
      spare_text_8: "",
      spare_text_9: "",
      spare_text_10: "",
      spare_number_1: 0,
      spare_number_2: 0,
      spare_number_3: 0,
      spare_number_4: 0,
      spare_number_5: 0,
      spare_number_6: 0,
      spare_number_7: 0,
      spare_number_8: 0,
      spare_number_9: 0,
      spare_number_10: 0,
      spare_bool_1: false,
      spare_bool_2: false,
      spare_bool_3: false,
      spare_bool_4: false,
      spare_bool_5: false,
      landed_costs_type: "EnumNotApplicable",
      landed_costs_percentage: 0,
      landed_costs_per_item: 0,
      bom_item_type: "EnumBOMItemTypeComponent",
      id: 34751,
      date_time_created: "2024-02-28T14:06:51.043Z",
      date_time_updated: "2024-05-24T00:27:17.897Z",
    },
  ],
};

export const searchProductsPayload = {
  data: [
    {
      id: 34751,
      code: "BOARD001",
      name: "Whiteboard - Drywipe (900 x 1200)",
      free_stock_quantity: 107,
      record_nos_on_goods_received: false,
      product_status_id: 0,
      bom_item_type_id: 0,
      traceable_type_id: 0,
      this_is_the_sop_product_group: false,
      product_type_id: 0,
      allow_sales_order: true,
    },
  ],
};

export const updateProductPayload = {
  data: {
    code: "BOARD001",
    name: "Whiteboard - Drywipe (900 x 1200)",
    description: "Whiteboard - Drywipe (900 x 1200) Updated",
    use_description_on_documents: false,
    barcode: "",
    allow_sales_order: true,
    free_stock_quantity: 107,
    product_group_id: 34640,
    tax_code_id: 1729,
    product_status_type: "EnumStockItemStatusTypeActive",
    fulfilment_method_type: "EnumFulfilmentFromStock",
    fulfilment_sequence_type: "EnumBinPriority",
    manufacturer: "",
    part_number: "WB/U143-78243/2437032ALX4/24369/DW1200X900",
    label_printing_option_type: "EnumNotRequired",
    traceable_type: "EnumTraceableTypeNone",
    sale_from_single_batch: false,
    allow_duplicate_numbers: false,
    uses_alternative_ref: false,
    uses_sell_by_date: false,
    uses_use_by_date: false,
    shelf_life: 0,
    shelf_life_type: "EnumTimeUnitDay",
    record_nos_on_goods_received: false,
    include_nos_on_count_sheets: true,
    auto_generate_option_type: "EnumDoNotGenerate",
    auto_generate_separator_id: 1,
    auto_generate_prefix: "",
    auto_generate_next_number: 1,
    auto_generate_padding: 0,
    stocktake_cycle_period: 0,
    standard_cost: 15,
    average_buying_price: 13.2,
    default_picking_list_comment: "",
    default_despatch_note_comment: "",
    commodity_code: "",
    country_of_origin_id: 0,
    weight: 0,
    suppress_mass_on_declaration: false,
    is_weee_item: false,
    use_supplementary_units: false,
    supplementary_unit_conversion_ratio: 1,
    use_reverse_charge_vat_rules: false,
    analysis_code_1: "",
    analysis_code_2: "",
    analysis_code_3: "",
    analysis_code_4: "",
    analysis_code_5: "",
    analysis_code_6: "",
    analysis_code_7: "",
    analysis_code_8: "",
    analysis_code_9: "",
    analysis_code_10: "",
    analysis_code_11: "",
    analysis_code_12: "",
    analysis_code_13: "",
    analysis_code_14: "",
    analysis_code_15: "",
    analysis_code_16: "",
    analysis_code_17: "",
    analysis_code_18: "",
    analysis_code_19: "",
    analysis_code_20: "",
    spare_text_1: "",
    spare_text_2: "",
    spare_text_3: "",
    spare_text_4: "",
    spare_text_5: "",
    spare_text_6: "",
    spare_text_7: "",
    spare_text_8: "",
    spare_text_9: "",
    spare_text_10: "",
    spare_number_1: 0,
    spare_number_2: 0,
    spare_number_3: 0,
    spare_number_4: 0,
    spare_number_5: 0,
    spare_number_6: 0,
    spare_number_7: 0,
    spare_number_8: 0,
    spare_number_9: 0,
    spare_number_10: 0,
    spare_bool_1: false,
    spare_bool_2: false,
    spare_bool_3: false,
    spare_bool_4: false,
    spare_bool_5: false,
    landed_costs_type: "EnumNotApplicable",
    landed_costs_percentage: 0,
    landed_costs_per_item: 0,
    bom_item_type: "EnumBOMItemTypeComponent",
    id: 34751,
    date_time_created: "2024-02-28T14:06:51.043Z",
    date_time_updated: "2024-05-24T00:27:17.897Z",
  },
};

export const getProductGroupPayload = {
  data: {
    code: "0001",
    description: "Paper Products",
    product_type: "EnumStockItemTypeStock",
    costing_method: "EnumCostingMethodTypeFIFO",
    stocktake_cycle_period: 0,
    label_printing_option_type: "EnumNotRequired",
    keep_movement_history: true,
    can_levels_go_negative: true,
    can_over_allocate_negative_stock: false,
    use_description_on_documents: false,
    use_reverse_charge_vat_rules: false,
    do_items_use_units: false,
    selling_quantities_use_multiple_units: false,
    selling_prices_use_multiple_units: false,
    buying_quantities_use_multiple_units: false,
    buying_prices_use_multiple_units: false,
    do_items_use_markup: false,
    use_landed_costs: false,
    landed_costs_type: "EnumNotApplicable",
    landed_costs_percentage: 0,
    landed_costs_per_item: 0,
    this_is_the_sop_product_group: false,
    traceable_type: "EnumTraceableTypeNone",
    sale_from_single_batch: false,
    allow_duplicate_numbers: false,
    uses_alternative_ref: false,
    uses_sell_by_date: false,
    uses_use_by_date: false,
    id: 34634,
    date_time_created: "2024-02-28T14:06:50.347Z",
    date_time_updated: "2024-02-28T14:23:46.31Z",
  },
};

export const listProductGroupsPayload = {
  data: [
    {
      code: "0001",
      description: "Paper Products",
      product_type: "EnumStockItemTypeStock",
      costing_method: "EnumCostingMethodTypeFIFO",
      stocktake_cycle_period: 0,
      label_printing_option_type: "EnumNotRequired",
      keep_movement_history: true,
      can_levels_go_negative: true,
      can_over_allocate_negative_stock: false,
      use_description_on_documents: false,
      use_reverse_charge_vat_rules: false,
      do_items_use_units: false,
      selling_quantities_use_multiple_units: false,
      selling_prices_use_multiple_units: false,
      buying_quantities_use_multiple_units: false,
      buying_prices_use_multiple_units: false,
      do_items_use_markup: false,
      use_landed_costs: false,
      landed_costs_type: "EnumNotApplicable",
      landed_costs_percentage: 0,
      landed_costs_per_item: 0,
      this_is_the_sop_product_group: false,
      traceable_type: "EnumTraceableTypeNone",
      sale_from_single_batch: false,
      allow_duplicate_numbers: false,
      uses_alternative_ref: false,
      uses_sell_by_date: false,
      uses_use_by_date: false,
      id: 34634,
      date_time_created: "2024-02-28T14:06:50.347Z",
      date_time_updated: "2024-02-28T14:23:46.31Z",
    },
  ],
};

export const searchProductGroupsPayload = {
  data: [
    {
      id: 34634,
      code: "0001",
      description: "Paper Products",
      product_type_id: 0,
    },
  ],
};

export const getProductPriceViewsPayload = {
  data: [
    {
      product_price_id: 34760,
      product_id: 34751,
      product_code: "BOARD001",
      product_name: "Whiteboard - Drywipe (900 x 1200)",
      product_stock_unit_name: "Each",
      price_band_id: 1064,
      price_band_name: "Standard",
      product_price_use_standard: true,
      product_price_price: 20,
      currency_id: 2103,
      currency_name: "Pound Sterling",
      currency_symbol: "£",
      date_time_updated: "2024-02-28T14:23:46.787Z",
    },
  ],
};

export const createSalesInvoicePayload = {
  data: {
    urn: 1327,
  },
};

export const getSalesInvoiceReturnCreditViewsPayload = {
  data: [
    {
      customer_id: 27906,
      customer_reference: "SWA001",
      customer_name: "Swan Leisure Centre",
      sop_invoice_credit_id: 80700,
      sop_invoice_credit_type: "EnumInvoiceCreditTypeCredit",
      sop_invoice_credit_document_no: "0000000102",
      sop_invoice_credit_document_date: "2024-03-05T00:00:00Z",
      sop_invoice_credit_document_status: "EnumDocumentStatusDraft",
      sop_invoice_credit_exchange_rate: 1,
      sop_invoice_credit_date_time_updated: "2024-03-05T10:27:25.87Z",
      sop_invoice_credit_line_id: 80701,
      sop_invoice_credit_line_invoice_credit_date: "2024-03-05T00:00:00Z",
      sop_invoice_credit_line_total_value: 75,
      sop_invoice_credit_line_tax_value: 15,
      sop_invoice_credit_line_date_time_updated: "2024-03-05T10:27:25.863Z",
      product_id: 35092,
      product_code: "LAM001",
      product_name: "Laminator - A4",
      product_description: "Laminator - A4",
      product_date_time_updated: "2025-08-01T16:00:33.14Z",
      product_group_id: 34641,
      product_group_code: "0007_MISC",
      product_group_description: "Business Machines_MISC",
      product_group_date_time_updated: "2024-02-28T14:23:46.31Z",
    },
  ],
};

export const createSalesOrderPayload = {
  data: {
    is_credit_limit_exceeded: true,
    payment_with_order: false,
    invoice_payment_with_order_immediately: false,
    payment_value: 0,
    payment_reference: "",
    payment_method_id: 0,
    payment_method: {
      name: "",
      description: "",
      bank_account_id: 0,
      currency_id: 0,
      card_processing_method: false,
      id: 0,
    },
    payment_declared: 0,
    payment_undeclared: 0,
    declared_payment_remaining: 0,
    payment_status: {
      is_partially_invoiced: false,
      is_amendable: true,
      is_reference_amendable: true,
      is_payment_method_amendable: true,
    },
    document_no: "TBA",
    document_date: "2024-05-24T00:00:00Z",
    document_status: "EnumDocumentStatusLive",
    despatch_receipt_status: "EnumDocumentProcessStatusNone",
    invoice_credit_status: "EnumDocumentProcessStatusNone",
    cancelled_status: "EnumDocumentProcessStatusNone",
    customer_type: "EnumCustomerTypeCredit",
    customer_id: 27867,
    currency_id: 2103,
    is_draft: true,
    exchange_rate: 1,
    subtotal_goods_value: 0,
    subtotal_charge_net_value: 0,
    subtotal_charge_tax_value: 0,
    subtotal_discount_value: 0,
    total_net_value: 0,
    total_tax_value: 0,
    total_gross_value: 0,
    customer_document_no: "",
    use_invoice_address: true,
    is_triangulated: false,
    settlement_discount_days: 30,
    settlement_discount_percent: 2.5,
    document_discount_percent: 0,
    available_document_discount_percent: 0,
    document_created_by: "",
    requested_delivery_date: "2024-05-24T00:00:00Z",
    promised_delivery_date: "2024-05-24T00:00:00Z",
    order_priority: "",
    analysis_code_1: "",
    analysis_code_2: "",
    analysis_code_3: "",
    analysis_code_4: "",
    analysis_code_5: "",
    analysis_code_6: "",
    analysis_code_7: "",
    analysis_code_8: "",
    analysis_code_9: "",
    analysis_code_10: "",
    analysis_code_11: "",
    analysis_code_12: "",
    analysis_code_13: "",
    analysis_code_14: "",
    analysis_code_15: "",
    analysis_code_16: "",
    analysis_code_17: "",
    analysis_code_18: "",
    analysis_code_19: "",
    analysis_code_20: "",
    spare_text_1: "",
    spare_text_2: "",
    spare_text_3: "",
    spare_text_4: "",
    spare_text_5: "",
    spare_text_6: "",
    spare_text_7: "",
    spare_text_8: "",
    spare_text_9: "",
    spare_text_10: "",
    spare_number_1: 0,
    spare_number_2: 0,
    spare_number_3: 0,
    spare_number_4: 0,
    spare_number_5: 0,
    spare_number_6: 0,
    spare_number_7: 0,
    spare_number_8: 0,
    spare_number_9: 0,
    spare_number_10: 0,
    spare_bool_1: false,
    spare_bool_2: false,
    spare_bool_3: false,
    spare_bool_4: false,
    spare_bool_5: false,
    external_reference: "",
    customer: {
      reference: "KIN001",
      name: "Kinghorn & French",
      short_name: "Kinghorn",
      balance: 7398.35,
      on_hold: false,
      account_status_type: "AccountStatusActive",
      status_reason: "",
      currency_id: 2103,
      exchange_rate_type: "ExchangeRateSingle",
      telephone_country_code: "44",
      telephone_area_code: "0191",
      telephone_subscriber_number: "676 5656",
      fax_country_code: "44",
      fax_area_code: "0191",
      fax_subscriber_number: "676 5657",
      website: "www.sage.co.uk",
      credit_limit: 6000,
      country_code_id: 13,
      default_tax_code_id: 1729,
      vat_number: "GB958 5455 12",
      account_type: "TradingAccountTypeOpenItem",
      early_settlement_discount_percent: 2.5,
      early_settlement_discount_days: 30,
      payment_terms_days: 30,
      payment_terms_basis: "PaymentDueFromDocumentDate",
      credit_bureau_id: 2135,
      credit_position_id: 1,
      trading_terms: "30 Days",
      credit_reference: "BCS34367",
      account_opened: "2018-10-12T00:00:00Z",
      last_credit_review: "2024-03-03T00:00:00Z",
      next_credit_review: "2025-03-03T00:00:00Z",
      application_date: "2018-10-10T00:00:00Z",
      date_received: "2018-10-12T00:00:00Z",
      terms_agreed: true,
      order_priority: "",
      months_to_keep_transactions: 36,
      default_nominal_code_reference: "4002",
      default_nominal_code_cost_centre: "",
      default_nominal_code_department: "",
      analysis_code_1: "Trade",
      analysis_code_2: "George",
      analysis_code_3: "Tyne & Wear",
      analysis_code_4: "",
      analysis_code_5: "",
      analysis_code_6: "",
      analysis_code_7: "",
      analysis_code_8: "",
      analysis_code_9: "",
      analysis_code_10: "",
      analysis_code_11: "",
      analysis_code_12: "",
      analysis_code_13: "",
      analysis_code_14: "",
      analysis_code_15: "",
      analysis_code_16: "",
      analysis_code_17: "",
      analysis_code_18: "",
      analysis_code_19: "",
      analysis_code_20: "",
      spare_text_1: "",
      spare_text_2: "",
      spare_text_3: "",
      spare_text_4: "",
      spare_text_5: "",
      spare_text_6: "",
      spare_text_7: "",
      spare_text_8: "",
      spare_text_9: "",
      spare_text_10: "",
      spare_number_1: 0,
      spare_number_2: 0,
      spare_number_3: 0,
      spare_number_4: 0,
      spare_number_5: 0,
      spare_number_6: 0,
      spare_number_7: 0,
      spare_number_8: 0,
      spare_number_9: 0,
      spare_number_10: 0,
      spare_bool_1: false,
      spare_bool_2: false,
      spare_bool_3: false,
      spare_bool_4: false,
      spare_bool_5: false,
      value_of_current_orders_in_sop: 0,
      duns_code: "",
      average_time_to_pay: 0,
      finance_charge_id: 0,
      office_type: "Independent",
      associated_head_office_id: 0,
      produce_statements_for_customer: false,
      use_consolidated_billing: false,
      use_tax_code_as_default: false,
      invoice_discount_percent: 0,
      invoice_line_discount_percent: 0,
      customer_discount_group_id: 0,
      order_value_discount_id: 0,
      price_band_id: 37419,
      main_address: {
        customer_id: 27867,
        country: "Great Britain",
        contact_name: "John Bell",
        address_1: "98 Cathedral Gardens",
        address_2: "Benfield Rd",
        address_3: "Newcastle upon Tyne",
        address_4: "Tyne & Wear",
        city: "",
        county: "",
        postcode: "NE19 1GH",
        address_country_code_id: 13,
        id: 27868,
        date_time_created: "2024-02-28T14:06:36.62Z",
        date_time_updated: "2024-02-28T14:23:45.963Z",
      },
      default_tax_code: {
        code: 1,
        name: "Standard rate",
        tax_rate: 20,
        terms: "EcTermsNotApplicable",
        terms_description: "Not Applicable",
        is_notional_acquisition_tax: false,
        id: 1729,
        date_time_created: "2024-02-28T14:03:24.59Z",
        date_time_updated: "2024-02-28T14:23:46.133Z",
      },
      country_code: {
        code: "GB",
        name: "Great Britain",
        eu_member: false,
        id: 13,
        date_time_created: "2024-02-28T13:38:48.637Z",
        date_time_updated: "2024-02-28T14:23:46.173Z",
      },
      currency: {
        symbol: "£",
        name: "Pound Sterling",
        core_currency_rate: 1,
        euro_currency_rate: 0.714285,
        currency_iso_code_id: 49,
        is_base_currency: true,
        is_euro_currency: false,
        use_for_new_accounts: true,
        exchange_rate_type: "ExchangeRateSingle",
        exchange_rate_amendability_type: "ExchangeAmendabilityAllTransactions",
        id: 2103,
        date_time_created: "2024-02-28T14:03:36.533Z",
        date_time_updated: "2024-02-28T14:23:46.243Z",
      },
      alerts: [],
      id: 27867,
      date_time_created: "2024-02-28T14:06:36.61Z",
      date_time_updated: "2024-02-28T14:23:45.697Z",
    },
    currency: {
      symbol: "£",
      name: "Pound Sterling",
      core_currency_rate: 1,
      euro_currency_rate: 0.714285,
      currency_iso_code_id: 49,
      is_base_currency: true,
      is_euro_currency: false,
      use_for_new_accounts: true,
      exchange_rate_type: "ExchangeRateSingle",
      exchange_rate_amendability_type: "ExchangeAmendabilityAllTransactions",
      id: 2103,
      date_time_created: "2024-02-28T14:03:36.533Z",
      date_time_updated: "2024-02-28T14:23:46.243Z",
    },
    lines: [],
    memos: [],
    profitability: {
      sop_order_return_id: 82900,
      estimated_cost_value: 0,
      estimated_profit_percent_on_revenue: 0,
      estimated_profit_percent_on_cost: 0,
      estimated_profit_value: 0,
      issue_value: 0,
      realised_cost_value: 0,
      realised_issue_value: 0,
      realised_profit_percent_on_revenue: 0,
      realised_profit_percent_on_cost: 0,
      realised_profit_value: 0,
      simple_profit_calculation_only: false,
      id: 82901,
    },
    id: 82900,
  },
};

export const getSalesOrderPayload = {
  data: {
    is_credit_limit_exceeded: true,
    payment_with_order: false,
    invoice_payment_with_order_immediately: false,
    payment_value: 0,
    payment_reference: "",
    payment_method_id: 0,
    payment_declared: 0,
    payment_undeclared: 0,
    declared_payment_remaining: 0,
    document_no: "0000000001",
    document_date: "2023-01-02T00:00:00Z",
    document_status: "EnumDocumentStatusComplete",
    despatch_receipt_status: "EnumDocumentProcessStatusFull",
    invoice_credit_status: "EnumDocumentProcessStatusFull",
    cancelled_status: "EnumDocumentProcessStatusNone",
    customer_type: "EnumCustomerTypeCredit",
    customer_id: 27867,
    currency_id: 2103,
    is_draft: false,
    exchange_rate: 1,
    subtotal_goods_value: 9583.2,
    subtotal_charge_net_value: 0,
    subtotal_charge_tax_value: 0,
    subtotal_discount_value: 0,
    total_net_value: 9583.2,
    total_tax_value: 1635.13,
    total_gross_value: 11218.33,
    customer_document_no: "",
    use_invoice_address: false,
    is_triangulated: false,
    settlement_discount_days: 30,
    settlement_discount_percent: 2.5,
    document_discount_percent: 0,
    document_created_by: "",
    order_priority: "",
    analysis_code_1: "",
    analysis_code_2: "",
    analysis_code_3: "",
    analysis_code_4: "",
    analysis_code_5: "",
    analysis_code_6: "",
    analysis_code_7: "",
    analysis_code_8: "",
    analysis_code_9: "",
    analysis_code_10: "",
    analysis_code_11: "",
    analysis_code_12: "",
    analysis_code_13: "",
    analysis_code_14: "",
    analysis_code_15: "",
    analysis_code_16: "",
    analysis_code_17: "",
    analysis_code_18: "",
    analysis_code_19: "",
    analysis_code_20: "",
    spare_text_1: "",
    spare_text_2: "",
    spare_text_3: "",
    spare_text_4: "",
    spare_text_5: "",
    spare_text_6: "",
    spare_text_7: "",
    spare_text_8: "",
    spare_text_9: "",
    spare_text_10: "",
    spare_number_1: 0,
    spare_number_2: 0,
    spare_number_3: 0,
    spare_number_4: 0,
    spare_number_5: 0,
    spare_number_6: 0,
    spare_number_7: 0,
    spare_number_8: 0,
    spare_number_9: 0,
    spare_number_10: 0,
    spare_bool_1: false,
    spare_bool_2: false,
    spare_bool_3: false,
    spare_bool_4: false,
    spare_bool_5: false,
    external_reference: "",
    id: 38294,
    date_time_created: "2024-02-28T14:06:55.723Z",
    date_time_updated: "2024-02-28T14:23:45.69Z",
  },
};

export const listSalesOrderPayload = {
  data: [
    {
      is_credit_limit_exceeded: true,
      payment_with_order: false,
      invoice_payment_with_order_immediately: false,
      payment_value: 0,
      payment_reference: "",
      payment_method_id: 0,
      payment_declared: 0,
      payment_undeclared: 0,
      declared_payment_remaining: 0,
      document_no: "0000000001",
      document_date: "2023-01-02T00:00:00Z",
      document_status: "EnumDocumentStatusComplete",
      despatch_receipt_status: "EnumDocumentProcessStatusFull",
      invoice_credit_status: "EnumDocumentProcessStatusFull",
      cancelled_status: "EnumDocumentProcessStatusNone",
      customer_type: "EnumCustomerTypeCredit",
      customer_id: 27867,
      currency_id: 2103,
      is_draft: false,
      exchange_rate: 1,
      subtotal_goods_value: 9583.2,
      subtotal_charge_net_value: 0,
      subtotal_charge_tax_value: 0,
      subtotal_discount_value: 0,
      total_net_value: 9583.2,
      total_tax_value: 1635.13,
      total_gross_value: 11218.33,
      customer_document_no: "",
      use_invoice_address: false,
      is_triangulated: false,
      settlement_discount_days: 30,
      settlement_discount_percent: 2.5,
      document_discount_percent: 0,
      document_created_by: "",
      order_priority: "",
      analysis_code_1: "",
      analysis_code_2: "",
      analysis_code_3: "",
      analysis_code_4: "",
      analysis_code_5: "",
      analysis_code_6: "",
      analysis_code_7: "",
      analysis_code_8: "",
      analysis_code_9: "",
      analysis_code_10: "",
      analysis_code_11: "",
      analysis_code_12: "",
      analysis_code_13: "",
      analysis_code_14: "",
      analysis_code_15: "",
      analysis_code_16: "",
      analysis_code_17: "",
      analysis_code_18: "",
      analysis_code_19: "",
      analysis_code_20: "",
      spare_text_1: "",
      spare_text_2: "",
      spare_text_3: "",
      spare_text_4: "",
      spare_text_5: "",
      spare_text_6: "",
      spare_text_7: "",
      spare_text_8: "",
      spare_text_9: "",
      spare_text_10: "",
      spare_number_1: 0,
      spare_number_2: 0,
      spare_number_3: 0,
      spare_number_4: 0,
      spare_number_5: 0,
      spare_number_6: 0,
      spare_number_7: 0,
      spare_number_8: 0,
      spare_number_9: 0,
      spare_number_10: 0,
      spare_bool_1: false,
      spare_bool_2: false,
      spare_bool_3: false,
      spare_bool_4: false,
      spare_bool_5: false,
      external_reference: "",
      id: 38294,
      date_time_created: "2024-02-28T14:06:55.723Z",
      date_time_updated: "2024-02-28T14:23:45.69Z",
    },
  ],
};

export const updateSalesOrderPayload = {
  data: {
    is_credit_limit_exceeded: true,
    payment_with_order: false,
    invoice_payment_with_order_immediately: false,
    payment_value: 0,
    payment_reference: "",
    payment_method_id: 0,
    payment_method: {
      name: "",
      description: "",
      bank_account_id: 0,
      currency_id: 0,
      card_processing_method: false,
      id: 0,
    },
    payment_declared: 0,
    payment_undeclared: 0,
    declared_payment_remaining: 0,
    payment_status: {
      is_partially_invoiced: false,
      is_amendable: true,
      is_reference_amendable: true,
      is_payment_method_amendable: true,
    },
    document_no: "TBA",
    document_date: "2024-05-24T00:00:00Z",
    document_status: "EnumDocumentStatusLive",
    despatch_receipt_status: "EnumDocumentProcessStatusNone",
    invoice_credit_status: "EnumDocumentProcessStatusNone",
    cancelled_status: "EnumDocumentProcessStatusNone",
    customer_type: "EnumCustomerTypeCredit",
    customer_id: 27867,
    currency_id: 2103,
    is_draft: true,
    exchange_rate: 1,
    subtotal_goods_value: 0,
    subtotal_charge_net_value: 0,
    subtotal_charge_tax_value: 0,
    subtotal_discount_value: 0,
    total_net_value: 0,
    total_tax_value: 0,
    total_gross_value: 0,
    customer_document_no: "",
    use_invoice_address: false,
    is_triangulated: false,
    settlement_discount_days: 30,
    settlement_discount_percent: 2.5,
    document_discount_percent: 0,
    available_document_discount_percent: 0,
    document_created_by: "",
    requested_delivery_date: "2024-05-24T00:00:00Z",
    promised_delivery_date: "2024-05-24T00:00:00Z",
    order_priority: "",
    analysis_code_1: "",
    analysis_code_2: "",
    analysis_code_3: "",
    analysis_code_4: "",
    analysis_code_5: "",
    analysis_code_6: "",
    analysis_code_7: "",
    analysis_code_8: "",
    analysis_code_9: "",
    analysis_code_10: "",
    analysis_code_11: "",
    analysis_code_12: "",
    analysis_code_13: "",
    analysis_code_14: "",
    analysis_code_15: "",
    analysis_code_16: "",
    analysis_code_17: "",
    analysis_code_18: "",
    analysis_code_19: "",
    analysis_code_20: "",
    spare_text_1: "",
    spare_text_2: "",
    spare_text_3: "",
    spare_text_4: "",
    spare_text_5: "",
    spare_text_6: "",
    spare_text_7: "",
    spare_text_8: "",
    spare_text_9: "",
    spare_text_10: "",
    spare_number_1: 0,
    spare_number_2: 0,
    spare_number_3: 0,
    spare_number_4: 0,
    spare_number_5: 0,
    spare_number_6: 0,
    spare_number_7: 0,
    spare_number_8: 0,
    spare_number_9: 0,
    spare_number_10: 0,
    spare_bool_1: false,
    spare_bool_2: false,
    spare_bool_3: false,
    spare_bool_4: false,
    spare_bool_5: false,
    external_reference: "",
    customer: {
      reference: "KIN001",
      name: "Kinghorn & French",
      short_name: "Kinghorn",
      balance: 7398.35,
      on_hold: false,
      account_status_type: "AccountStatusActive",
      status_reason: "",
      currency_id: 2103,
      exchange_rate_type: "ExchangeRateSingle",
      telephone_country_code: "44",
      telephone_area_code: "0191",
      telephone_subscriber_number: "676 5656",
      fax_country_code: "44",
      fax_area_code: "0191",
      fax_subscriber_number: "676 5657",
      website: "www.sage.co.uk",
      credit_limit: 6000,
      country_code_id: 13,
      default_tax_code_id: 1729,
      vat_number: "GB958 5455 12",
      account_type: "TradingAccountTypeOpenItem",
      early_settlement_discount_percent: 2.5,
      early_settlement_discount_days: 30,
      payment_terms_days: 30,
      payment_terms_basis: "PaymentDueFromDocumentDate",
      credit_bureau_id: 2135,
      credit_position_id: 1,
      trading_terms: "30 Days",
      credit_reference: "BCS34367",
      account_opened: "2018-10-12T00:00:00Z",
      last_credit_review: "2024-03-03T00:00:00Z",
      next_credit_review: "2025-03-03T00:00:00Z",
      application_date: "2018-10-10T00:00:00Z",
      date_received: "2018-10-12T00:00:00Z",
      terms_agreed: true,
      order_priority: "",
      months_to_keep_transactions: 36,
      default_nominal_code_reference: "4002",
      default_nominal_code_cost_centre: "",
      default_nominal_code_department: "",
      analysis_code_1: "Trade",
      analysis_code_2: "George",
      analysis_code_3: "Tyne & Wear",
      analysis_code_4: "",
      analysis_code_5: "",
      analysis_code_6: "",
      analysis_code_7: "",
      analysis_code_8: "",
      analysis_code_9: "",
      analysis_code_10: "",
      analysis_code_11: "",
      analysis_code_12: "",
      analysis_code_13: "",
      analysis_code_14: "",
      analysis_code_15: "",
      analysis_code_16: "",
      analysis_code_17: "",
      analysis_code_18: "",
      analysis_code_19: "",
      analysis_code_20: "",
      spare_text_1: "",
      spare_text_2: "",
      spare_text_3: "",
      spare_text_4: "",
      spare_text_5: "",
      spare_text_6: "",
      spare_text_7: "",
      spare_text_8: "",
      spare_text_9: "",
      spare_text_10: "",
      spare_number_1: 0,
      spare_number_2: 0,
      spare_number_3: 0,
      spare_number_4: 0,
      spare_number_5: 0,
      spare_number_6: 0,
      spare_number_7: 0,
      spare_number_8: 0,
      spare_number_9: 0,
      spare_number_10: 0,
      spare_bool_1: false,
      spare_bool_2: false,
      spare_bool_3: false,
      spare_bool_4: false,
      spare_bool_5: false,
      value_of_current_orders_in_sop: 0,
      duns_code: "",
      average_time_to_pay: 0,
      finance_charge_id: 0,
      office_type: "Independent",
      associated_head_office_id: 0,
      produce_statements_for_customer: false,
      use_consolidated_billing: false,
      use_tax_code_as_default: false,
      invoice_discount_percent: 0,
      invoice_line_discount_percent: 0,
      customer_discount_group_id: 0,
      order_value_discount_id: 0,
      price_band_id: 37419,
      main_address: {
        customer_id: 27867,
        country: "Great Britain",
        contact_name: "John Bell",
        address_1: "98 Cathedral Gardens",
        address_2: "Benfield Rd",
        address_3: "Newcastle upon Tyne",
        address_4: "Tyne & Wear",
        city: "",
        county: "",
        postcode: "NE19 1GH",
        address_country_code_id: 13,
        id: 27868,
        date_time_created: "2024-02-28T14:06:36.62Z",
        date_time_updated: "2024-02-28T14:23:45.963Z",
      },
      default_tax_code: {
        code: 1,
        name: "Standard rate",
        tax_rate: 20,
        terms: "EcTermsNotApplicable",
        terms_description: "Not Applicable",
        is_notional_acquisition_tax: false,
        id: 1729,
        date_time_created: "2024-02-28T14:03:24.59Z",
        date_time_updated: "2024-02-28T14:23:46.133Z",
      },
      country_code: {
        code: "GB",
        name: "Great Britain",
        eu_member: false,
        id: 13,
        date_time_created: "2024-02-28T13:38:48.637Z",
        date_time_updated: "2024-02-28T14:23:46.173Z",
      },
      currency: {
        symbol: "£",
        name: "Pound Sterling",
        core_currency_rate: 1,
        euro_currency_rate: 0.714285,
        currency_iso_code_id: 49,
        is_base_currency: true,
        is_euro_currency: false,
        use_for_new_accounts: true,
        exchange_rate_type: "ExchangeRateSingle",
        exchange_rate_amendability_type: "ExchangeAmendabilityAllTransactions",
        id: 2103,
        date_time_created: "2024-02-28T14:03:36.533Z",
        date_time_updated: "2024-02-28T14:23:46.243Z",
      },
      alerts: [],
      id: 27867,
      date_time_created: "2024-02-28T14:06:36.61Z",
      date_time_updated: "2024-02-28T14:23:45.697Z",
    },
    currency: {
      symbol: "£",
      name: "Pound Sterling",
      core_currency_rate: 1,
      euro_currency_rate: 0.714285,
      currency_iso_code_id: 49,
      is_base_currency: true,
      is_euro_currency: false,
      use_for_new_accounts: true,
      exchange_rate_type: "ExchangeRateSingle",
      exchange_rate_amendability_type: "ExchangeAmendabilityAllTransactions",
      id: 2103,
      date_time_created: "2024-02-28T14:03:36.533Z",
      date_time_updated: "2024-02-28T14:23:46.243Z",
    },
    delivery_address: {
      contact: "John Bell",
      postal_name: "Kinghorn & French",
      country: "",
      telephone_number: "0191 676 5656",
      fax_number: "0191 676 5657",
      email_address: "johnbell@kinghornfrench.co.uk",
      tax_number: "",
      tax_code_id: 1729,
      tax_code: {
        code: 1,
        name: "Standard rate",
        tax_rate: 20,
        terms: "EcTermsNotApplicable",
        terms_description: "Not Applicable",
        is_notional_acquisition_tax: false,
        id: 1729,
        date_time_created: "2024-02-28T14:03:24.59Z",
        date_time_updated: "2024-02-28T14:23:46.133Z",
      },
      country_code_id: 13,
      country_code: {
        code: "GB",
        name: "Great Britain",
        eu_member: false,
        tax_mask: {
          name: "^[0-9]{3}[\\s]*[0-9]{4}[\\s]*[0-9]{2}$",
          id: 10,
          date_time_created: "2024-02-28T13:38:48.74Z",
          date_time_updated: "2024-02-28T14:23:46.19Z",
        },
        id: 13,
        date_time_created: "2024-02-28T13:38:48.637Z",
        date_time_updated: "2024-02-28T14:23:46.173Z",
      },
      address_1: "98 Cathedral Gardens",
      address_2: "Benfied Rd",
      address_3: "Newcastle upon Tyne",
      address_4: "Tyne & Wear",
      city: "",
      county: "",
      postcode: "NE19 1GH",
      id: 82910,
    },
    lines: [],
    memos: [],
    profitability: {
      sop_order_return_id: 82900,
      estimated_cost_value: 0,
      estimated_profit_percent_on_revenue: 0,
      estimated_profit_percent_on_cost: 0,
      estimated_profit_value: 0,
      issue_value: 0,
      realised_cost_value: 0,
      realised_issue_value: 0,
      realised_profit_percent_on_revenue: 0,
      realised_profit_percent_on_cost: 0,
      realised_profit_value: 0,
      simple_profit_calculation_only: false,
      id: 82901,
      date_time_created: "2024-05-24T00:53:12.14Z",
      date_time_updated: "2024-05-24T00:53:12.14Z",
    },
    id: 82900,
    date_time_created: "2024-05-24T00:53:12.093Z",
    date_time_updated: "2024-05-24T00:53:12.093Z",
  },
};

export const getTaxCodePayload = {
  data: {
    code: 16,
    name: "Purchase Services ROW (Reverse Charge)",
    tax_rate: 20,
    terms: "EcTermsPurchaseNonRelatedServices",
    terms_description: "Purchase Non-Related Services",
    is_notional_acquisition_tax: true,
    id: 16,
    date_time_created: "2024-11-06T11:41:16.86Z",
    date_time_updated: "2024-11-06T11:41:16.86Z",
  },
};

export const listTaxCodesPayload = {
  data: [
    {
      code: 16,
      name: "Purchase Services ROW (Reverse Charge)",
      tax_rate: 20,
      terms: "EcTermsPurchaseNonRelatedServices",
      terms_description: "Purchase Non-Related Services",
      is_notional_acquisition_tax: true,
      id: 16,
      date_time_created: "2024-11-06T11:41:16.86Z",
      date_time_updated: "2024-11-06T11:41:16.86Z",
    },
  ],
};

export const getItemsOnSalesOrderPayload = {
  data: {
    sop_order_id: 84180,
    line_number: 1,
    line_type: "EnumLineTypeStandard",
    code: "BOARD001",
    description: "Whiteboard - Drywipe (900 x 1200)",
    use_description: false,
    tax_code_id: 1729,
    nominal_reference: "4000",
    nominal_cost_centre: "",
    nominal_department: "",
    line_quantity: 1,
    to_allocate_quantity: 1,
    allocated_quantity: 1,
    despatch_receipt_quantity: 0,
    invoice_credit_quantity: 0,
    posted_invoice_credit_quantity: 0,
    available_for_despatch: 1,
    stock_unit_line_quantity: 1,
    stock_unit_to_allocate_quantity: 1,
    stock_unit_allocated_quantity: 1,
    stock_unit_despatch_receipt_quantity: 0,
    stock_unit_invoice_credit_quantity: 0,
    stock_unit_posted_invoice_credit_quantity: 0,
    stock_unit_available_for_despatch: 1,
    stock_unit_available_quantity: 106,
    allocation_status: "EnumLineStatusFully",
    despatch_receipt_status: "EnumLineStatusNone",
    invoice_credit_status: "EnumLineStatusNone",
    selling_unit_description: "Each",
    pricing_unit_description: "Each",
    line_unit_precision: 0.00001,
    stock_unit_precision: 0.00001,
    selling_unit_multiple: 1,
    stock_unit_multiple: 1,
    selling_unit_price: 20,
    unit_discount_percent: 0,
    unit_discount_value: 0,
    discounted_unit_price: 20,
    cost_price: 13.2,
    discount_percent_specified: false,
    selling_unit_price_overridden: false,
    unit_discount_overridden: false,
    retain_manual_prices: false,
    fulfilment_method: "EnumFulfilmentFromStock",
    picking_list_comment: "",
    despatch_note_comment: "",
    show_on_customer_docs: true,
    show_on_picking_list_type: "Show",
    confirmation_intent_type: "ConfirmOnDespatch",
    has_pop_order: false,
    back_to_back_status: "EnumBackToBackStatusPONotReq",
    is_complete: false,
    is_line_deletable: true,
    line_total_value: 20,
    line_tax_value: 4,
    requested_delivery_date: "2024-05-24T00:00:00Z",
    promised_delivery_date: "2024-05-24T00:00:00Z",
    analysis_code_1: "",
    analysis_code_2: "",
    analysis_code_3: "",
    analysis_code_4: "",
    analysis_code_5: "",
    analysis_code_6: "",
    analysis_code_7: "",
    analysis_code_8: "",
    analysis_code_9: "",
    analysis_code_10: "",
    analysis_code_11: "",
    analysis_code_12: "",
    analysis_code_13: "",
    analysis_code_14: "",
    analysis_code_15: "",
    analysis_code_16: "",
    analysis_code_17: "",
    analysis_code_18: "",
    analysis_code_19: "",
    analysis_code_20: "",
    spare_text_1: "",
    spare_text_2: "",
    spare_text_3: "",
    spare_text_4: "",
    spare_text_5: "",
    spare_text_6: "",
    spare_text_7: "",
    spare_text_8: "",
    spare_text_9: "",
    spare_text_10: "",
    spare_number_1: 0,
    spare_number_2: 0,
    spare_number_3: 0,
    spare_number_4: 0,
    spare_number_5: 0,
    spare_number_6: 0,
    spare_number_7: 0,
    spare_number_8: 0,
    spare_number_9: 0,
    spare_number_10: 0,
    spare_bool_1: false,
    spare_bool_2: false,
    spare_bool_3: false,
    spare_bool_4: false,
    spare_bool_5: false,
    product_id: 34751,
    warehouse_id: 34627,
    id: 84181,
    date_time_created: "2024-05-24T08:51:22.257Z",
    date_time_updated: "2024-05-24T08:51:22.883Z",
  },
};

export const createProductPayload = {
  data: {
    code: "PAPERA4",
    name: "Paper - A4 (500 sheets)",
    description: "",
    use_description_on_documents: false,
    barcode: "",
    allow_sales_order: true,
    free_stock_quantity: 0,
    product_group_id: 34634,
    tax_code_id: 16,
    product_status_type: "EnumStockItemStatusTypeActive",
    fulfilment_method_type: "EnumFulfilmentFromStock",
    fulfilment_sequence_type: "EnumBinPriority",
    manufacturer: "",
    part_number: "",
    label_printing_option_type: "EnumNotRequired",
    traceable_type: "EnumTraceableTypeNone",
    sale_from_single_batch: false,
    allow_duplicate_numbers: false,
    uses_alternative_ref: false,
    uses_sell_by_date: false,
    uses_use_by_date: false,
    shelf_life: 0,
    shelf_life_type: "EnumTimeUnitDay",
    record_nos_on_goods_received: false,
    include_nos_on_count_sheets: false,
    auto_generate_option_type: "EnumDoNotGenerate",
    auto_generate_separator_id: 1,
    auto_generate_prefix: "",
    auto_generate_next_number: 0,
    auto_generate_padding: 0,
    stocktake_cycle_period: 0,
    standard_cost: 0,
    average_buying_price: 0,
    default_picking_list_comment: "",
    default_despatch_note_comment: "",
    commodity_code: "",
    country_of_origin_id: 0,
    weight: 0,
    suppress_mass_on_declaration: false,
    is_weee_item: false,
    use_supplementary_units: false,
    supplementary_unit_conversion_ratio: 1,
    use_reverse_charge_vat_rules: false,
    analysis_code_1: "",
    analysis_code_2: "",
    analysis_code_3: "",
    analysis_code_4: "",
    analysis_code_5: "",
    analysis_code_6: "",
    analysis_code_7: "",
    analysis_code_8: "",
    analysis_code_9: "",
    analysis_code_10: "",
    analysis_code_11: "",
    analysis_code_12: "",
    analysis_code_13: "",
    analysis_code_14: "",
    analysis_code_15: "",
    analysis_code_16: "",
    analysis_code_17: "",
    analysis_code_18: "",
    analysis_code_19: "",
    analysis_code_20: "",
    spare_text_1: "",
    spare_text_2: "",
    spare_text_3: "",
    spare_text_4: "",
    spare_text_5: "",
    spare_text_6: "",
    spare_text_7: "",
    spare_text_8: "",
    spare_text_9: "",
    spare_text_10: "",
    spare_number_1: 0,
    spare_number_2: 0,
    spare_number_3: 0,
    spare_number_4: 0,
    spare_number_5: 0,
    spare_number_6: 0,
    spare_number_7: 0,
    spare_number_8: 0,
    spare_number_9: 0,
    spare_number_10: 0,
    spare_bool_1: false,
    spare_bool_2: false,
    spare_bool_3: false,
    spare_bool_4: false,
    spare_bool_5: false,
    landed_costs_type: "EnumNotApplicable",
    landed_costs_percentage: 0,
    landed_costs_per_item: 0,
    bom_item_type: "EnumBOMItemTypeComponent",
    warehouse_holdings: [
      {
        warehouse_id: 34627,
        product_id: 84250,
        reorder_level: 1,
        minimum_level: 1,
        maximum_level: 1,
        quantity_reserved: 0,
        confirmed_qty_in_stock: 0,
        unconfirmed_qty_in_stock: 0,
        quantity_in_stock: 0,
        quantity_in_stock_less_reserved: 0,
        quantity_on_order: 0,
        quantity_allocated_stock: 0,
        quantity_allocated_sop: 0,
        quantity_allocated_bom: 0,
        quantity_allocated: 0,
        free_stock_available: 0,
        free_stock_available_less_reserved: 0,
        warehouse_name: "Warehouse",
        is_default_manufacturing_warehouse: true,
        bin_holdings: [
          {
            warehouse_holding_id: 84263,
            product_id: 84250,
            name: "Unspecified",
            allocation_priority: 9,
            quantity_reserved: 0,
            unconfirmed_qty_in_stock: 0,
            confirmed_qty_in_stock: 0,
            quantity_allocated_sop: 0,
            quantity_allocated_stock: 0,
            quantity_allocated_bom: 0,
            quantity_in_stock: 0,
            quantity_in_stock_less_reserved: 0,
            quantity_allocated: 0,
            free_stock_available: 0,
            free_stock_available_less_reserved: 0,
            spare_text_1: "",
            spare_text_2: "",
            spare_text_3: "",
            spare_text_4: "",
            spare_text_5: "",
            spare_text_6: "",
            spare_text_7: "",
            spare_text_8: "",
            spare_text_9: "",
            spare_text_10: "",
            spare_number_1: 0,
            spare_number_2: 0,
            spare_number_3: 0,
            spare_number_4: 0,
            spare_number_5: 0,
            spare_number_6: 0,
            spare_number_7: 0,
            spare_number_8: 0,
            spare_number_9: 0,
            spare_number_10: 0,
            spare_bool_1: false,
            spare_bool_2: false,
            spare_bool_3: false,
            spare_bool_4: false,
            spare_bool_5: false,
            id: 84264,
          },
        ],
        id: 84263,
      },
    ],
    id: 84250,
  },
};

export const getSiteAndCompanyInformationPayload = {
  data: [
    {
      company_id: 123,
      company_name: "APITestCompany",
      tenant_id: 1234,
      site_id: "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
      site_name: "Demodata",
      site_short_name: "xxxxxxxxxx",
    },
  ],
};
