import { action } from "@prismatic-io/spectral";
import { createClient } from "../../../client";
import { updateProductExamplePayload } from "../../../examplePayloads/v2_1";
import { updateProductInputs } from "../../../inputs/v2_1";
export const updateProduct = action({
  display: {
    description:
      "Updates an existing product in the Merchant Center account, only updating attributes provided in the request.",
    label: "Update Product (Legacy v2.1)",
  },
  inputs: updateProductInputs,
  perform: async (
    _context,
    {
      connectionInput,
      merchantId,
      externalSellerId,
      productId,
      offerId,
      contentLanguage,
      targetCountry,
      feedLabel,
      title,
      description,
      link,
      imageLink,
      additionalImageLinks,
      lifestyleImageLinks,
      channel,
      expirationDate,
      adult,
      kind,
      brand,
      color,
      googleProductCategory,
      gtin,
      itemGroupId,
      material,
      mpn,
      pattern,
      price,
      salePrice,
      salePriceEffectiveDate,
      dimensions,
      shipping,
      shippingDimensions,
      sizes,
      taxes,
      customAttributes,
      identifierExists,
      installment,
      multipack,
      customLabel0,
      customLabel1,
      customLabel2,
      customLabel3,
      customLabel4,
      isBundle,
      mobileLink,
      availabilityDate,
      shippingLabel,
      unitPricingMeasure,
      unitPricingBaseMeasure,
      displayAdsId,
      displayAdsSimilarIds,
      displayAdsTitle,
      displayAdsLink,
      displayAdsValue,
      sellOnGoogleQuantity,
      promotionIds,
      maxHandlingTime,
      minHandlingTime,
      costOfGoodsSold,
      source,
      includedDestinations,
      excludedDestinations,
      adsGrouping,
      adsLabels,
      adsRedirect,
      productTypes,
      ageGroup,
      availability,
      condition,
      gender,
      sizeSystem,
      sizeType,
      additionalSizeType,
      energyEfficiencyClass,
      minEnergyEfficiencyClass,
      maxEnergyEfficiencyClass,
      taxCategory,
      transitTimeLabel,
      shoppingAdsExcludedCountries,
      pickupMethod,
      pickupSla,
      linkTemplate,
      mobileLinkTemplate,
      productDetails,
      productHighlights,
      subscriptionCost,
      canonicalLink,
      pause,
      updateMask,
    },
  ) => {
    const client = createClient(connectionInput);
    const { data } = await client.products.update({
      merchantId,
      productId,
      updateMask,
      requestBody: {
        id: null,
        offerId,
        contentLanguage,
        targetCountry,
        feedLabel,
        title,
        description,
        link,
        imageLink,
        additionalImageLinks,
        lifestyleImageLinks,
        channel,
        expirationDate,
        adult: adult || undefined,
        kind,
        brand,
        color,
        googleProductCategory,
        gtin,
        itemGroupId,
        material,
        mpn,
        pattern,
        price,
        salePrice,
        salePriceEffectiveDate,
        productHeight: dimensions.productHeight,
        productLength: dimensions.productLength,
        productWidth: dimensions.productWidth,
        productWeight: dimensions.productWeight,
        shipping,
        shippingWeight: shippingDimensions.shippingWeight,
        sizes,
        taxes,
        customAttributes,
        identifierExists: identifierExists || undefined,
        installment,
        multipack,
        customLabel0,
        customLabel1,
        customLabel2,
        customLabel3,
        customLabel4,
        isBundle: isBundle || undefined,
        mobileLink,
        availabilityDate,
        shippingLabel,
        unitPricingMeasure,
        unitPricingBaseMeasure,
        shippingLength: shippingDimensions.shippingLength,
        shippingWidth: shippingDimensions.shippingWidth,
        shippingHeight: shippingDimensions.shippingHeight,
        displayAdsId,
        displayAdsSimilarIds,
        displayAdsTitle,
        displayAdsLink,
        displayAdsValue,
        sellOnGoogleQuantity,
        promotionIds,
        maxHandlingTime,
        minHandlingTime,
        costOfGoodsSold,
        source,
        includedDestinations,
        excludedDestinations,
        adsGrouping,
        adsLabels,
        adsRedirect,
        productTypes,
        ageGroup,
        availability,
        condition,
        gender,
        sizeSystem,
        sizeType,
        additionalSizeType,
        energyEfficiencyClass,
        minEnergyEfficiencyClass,
        maxEnergyEfficiencyClass,
        taxCategory,
        transitTimeLabel,
        shoppingAdsExcludedCountries,
        pickupMethod,
        pickupSla,
        linkTemplate,
        mobileLinkTemplate,
        productDetails,
        productHighlights,
        subscriptionCost,
        canonicalLink,
        externalSellerId,
        pause,
      },
    });
    return {
      data,
    };
  },
  examplePayload: updateProductExamplePayload,
});
