import { action } from "@prismatic-io/spectral";
import { createClient } from "../../client";
import { ENDPOINTS, ODATA_TYPES } from "../../constants";
import { createManagedDeviceExamplePayload } from "../../examplePayloads";
import { createManagedDeviceInputs } from "../../inputs";
export const createManagedDevice = action({
  display: {
    label: "Create Managed Device",
    description: "Create a new Managed Device object.",
  },
  perform: async (
    context,
    {
      connection,
      userId,
      deviceName,
      managedDeviceOwnerType,
      deviceActionResults,
      enrolledDateTime,
      lastSyncDateTime,
      operatingSystem,
      complianceState,
      jailBroken,
      managementAgent,
      osVersion,
      easActivated,
      easDeviceId,
      easActivationDateTime,
      azureADRegistered,
      deviceEnrollmentType,
      activationLockBypassCode,
      emailAddress,
      azureADDeviceId,
      deviceRegistrationState,
      deviceCategoryDisplayName,
      isSupervised,
      exchangeLastSuccessfulSyncDateTime,
      exchangeAccessState,
      exchangeAccessStateReason,
      remoteAssistanceSessionUrl,
      remoteAssistanceSessionErrorDetails,
      isEncrypted,
      userPrincipalName,
      model,
      manufacturer,
      imei,
      complianceGracePeriodExpirationDateTime,
      serialNumber,
      phoneNumber,
      androidSecurityPatchLevel,
      userDisplayName,
      configurationManagerClientEnabledFeatures,
      wiFiMacAddress,
      deviceHealthAttestationState,
      subscriberCarrier,
      meid,
      totalStorageSpaceInBytes,
      freeStorageSpaceInBytes,
      managedDeviceName,
      partnerReportedThreatState,
      requireUserEnrollmentApproval,
      managementCertificateExpirationDate,
      iccid,
      udid,
      notes,
      ethernetMacAddress,
      physicalMemoryInBytes,
      enrollmentProfileName,
    },
  ) => {
    const client = createClient(connection, context.debug.enabled);
    const payload = {
      "@odata.type": ODATA_TYPES.MANAGED_DEVICE,
      userId,
      deviceName,
      managedDeviceOwnerType,
      deviceActionResults,
      enrolledDateTime,
      lastSyncDateTime,
      operatingSystem,
      complianceState,
      jailBroken,
      managementAgent,
      osVersion,
      easActivated,
      easDeviceId,
      easActivationDateTime,
      azureADRegistered,
      deviceEnrollmentType,
      activationLockBypassCode,
      emailAddress,
      azureADDeviceId,
      deviceRegistrationState,
      deviceCategoryDisplayName,
      isSupervised,
      exchangeLastSuccessfulSyncDateTime,
      exchangeAccessState,
      exchangeAccessStateReason,
      remoteAssistanceSessionUrl,
      remoteAssistanceSessionErrorDetails,
      isEncrypted,
      userPrincipalName,
      model,
      manufacturer,
      imei,
      complianceGracePeriodExpirationDateTime,
      serialNumber,
      phoneNumber,
      androidSecurityPatchLevel,
      userDisplayName,
      configurationManagerClientEnabledFeatures,
      wiFiMacAddress,
      deviceHealthAttestationState,
      subscriberCarrier,
      meid,
      totalStorageSpaceInBytes,
      freeStorageSpaceInBytes,
      managedDeviceName,
      partnerReportedThreatState,
      requireUserEnrollmentApproval,
      managementCertificateExpirationDate,
      iccid,
      udid,
      notes,
      ethernetMacAddress,
      physicalMemoryInBytes,
      enrollmentProfileName,
    };
    const { data } = await client.post(ENDPOINTS.MANAGED_DEVICES, payload);
    return {
      data,
    };
  },
  inputs: createManagedDeviceInputs,
  examplePayload: createManagedDeviceExamplePayload,
});
