import { simpleUserSchema } from "./common";
const pullRefSchema = {
  type: "object" as const,
  properties: {
    label: { type: "string" },
    ref: { type: "string" },
    sha: { type: "string" },
    user: simpleUserSchema,
    repo: { type: ["object", "null"] },
  },
  required: ["label", "ref", "sha"],
};
export const pullsCreateOutputSchema = {
  type: "object" as const,
  properties: {
    id: { type: "integer" },
    node_id: { type: "string" },
    number: { type: "integer" },
    state: { type: "string", enum: ["open", "closed"] },
    title: { type: "string" },
    url: { type: "string", format: "uri" },
    html_url: { type: "string", format: "uri" },
    diff_url: { type: "string", format: "uri" },
    patch_url: { type: "string", format: "uri" },
    issue_url: { type: "string", format: "uri" },
    body: { type: ["string", "null"] },
    created_at: { type: "string", format: "date-time" },
    updated_at: { type: "string", format: "date-time" },
    closed_at: { type: ["string", "null"], format: "date-time" },
    merged_at: { type: ["string", "null"], format: "date-time" },
    merged: { type: "boolean" },
    mergeable: { type: ["boolean", "null"] },
    mergeable_state: { type: "string" },
    draft: { type: "boolean" },
    user: simpleUserSchema,
    head: pullRefSchema,
    base: pullRefSchema,
  },
  required: [
    "id",
    "node_id",
    "number",
    "state",
    "title",
    "url",
    "html_url",
    "created_at",
    "updated_at",
    "head",
    "base",
  ],
};
export const pullsListOutputSchema = {
  type: "array" as const,
  items: {
    type: "object" as const,
    properties: {
      id: { type: "integer" },
      node_id: { type: "string" },
      number: { type: "integer" },
      state: { type: "string", enum: ["open", "closed"] },
      title: { type: "string" },
      url: { type: "string", format: "uri" },
      html_url: { type: "string", format: "uri" },
      diff_url: { type: "string", format: "uri" },
      patch_url: { type: "string", format: "uri" },
      issue_url: { type: "string", format: "uri" },
      body: { type: ["string", "null"] },
      created_at: { type: "string", format: "date-time" },
      updated_at: { type: "string", format: "date-time" },
      closed_at: { type: ["string", "null"], format: "date-time" },
      merged_at: { type: ["string", "null"], format: "date-time" },
      draft: { type: "boolean" },
      user: simpleUserSchema,
      head: pullRefSchema,
      base: pullRefSchema,
    },
    required: [
      "id",
      "node_id",
      "number",
      "state",
      "title",
      "url",
      "html_url",
      "created_at",
      "updated_at",
      "head",
      "base",
    ],
  },
};
