const publicUserProperties = {
  login: { type: "string" },
  id: { type: "integer" },
  node_id: { type: "string" },
  avatar_url: { type: "string", format: "uri" },
  gravatar_id: { type: ["string", "null"] },
  url: { type: "string", format: "uri" },
  html_url: { type: "string", format: "uri" },
  followers_url: { type: "string", format: "uri" },
  following_url: { type: "string" },
  gists_url: { type: "string" },
  starred_url: { type: "string" },
  subscriptions_url: { type: "string", format: "uri" },
  organizations_url: { type: "string", format: "uri" },
  repos_url: { type: "string", format: "uri" },
  events_url: { type: "string" },
  received_events_url: { type: "string", format: "uri" },
  type: { type: "string" },
  site_admin: { type: "boolean" },
  name: { type: ["string", "null"] },
  company: { type: ["string", "null"] },
  blog: { type: ["string", "null"] },
  location: { type: ["string", "null"] },
  email: { type: ["string", "null"] },
  notification_email: { type: ["string", "null"] },
  hireable: { type: ["boolean", "null"] },
  bio: { type: ["string", "null"] },
  twitter_username: { type: ["string", "null"] },
  public_repos: { type: "integer" },
  public_gists: { type: "integer" },
  followers: { type: "integer" },
  following: { type: "integer" },
  created_at: { type: "string", format: "date-time" },
  updated_at: { type: "string", format: "date-time" },
};
const publicUserRequired = [
  "login",
  "id",
  "node_id",
  "avatar_url",
  "url",
  "html_url",
  "type",
  "site_admin",
  "public_repos",
  "public_gists",
  "followers",
  "following",
  "created_at",
  "updated_at",
];
export const usersGetByUsernameOutputSchema = {
  type: "object" as const,
  properties: publicUserProperties,
  required: publicUserRequired,
};
export const usersGetAuthenticatedOutputSchema = {
  type: "object" as const,
  properties: {
    ...publicUserProperties,
    private_gists: { type: "integer" },
    total_private_repos: { type: "integer" },
    owned_private_repos: { type: "integer" },
    disk_usage: { type: "integer" },
    collaborators: { type: "integer" },
    two_factor_authentication: { type: "boolean" },
    plan: {
      type: "object" as const,
      properties: {
        collaborators: { type: "integer" },
        name: { type: "string" },
        space: { type: "integer" },
        private_repos: { type: "integer" },
      },
    },
  },
  required: publicUserRequired,
};
