import { action } from "@prismatic-io/spectral";
import { createClient } from "../../client";
import { createEmployeeExamplePayload } from "../../examplePayloads";
import {
  city,
  connectionInput,
  country,
  date_of_birth,
  email,
  first_name,
  gender,
  home_phone,
  last_name,
  marital_status,
  mobile_phone,
  nationality,
  personal_identification_number,
  position_title,
  post_code,
  send_email,
  state,
  street_first,
  street_second,
  tax_number,
  work_phone,
  work_start_date,
} from "../../inputs";

export const createEmployee = action({
  display: {
    label: "Create Employee",
    description: "Create new employee",
  },
  inputs: {
    connectionInput,
    email,
    first_name,
    last_name,
    work_start_date,
    send_email,
    date_of_birth,
    gender,
    marital_status,
    nationality,
    country,
    state,
    post_code,
    street_first,
    street_second,
    city,
    position_title,
    home_phone,
    work_phone,
    mobile_phone,
    personal_identification_number,
    tax_number,
  },
  perform: async (
    context,
    {
      connectionInput,
      email,
      first_name,
      last_name,
      work_start_date,
      send_email,
      date_of_birth,
      gender,
      marital_status,
      nationality,
      country,
      state,
      post_code,
      street_first,
      street_second,
      city,
      position_title,
      home_phone,
      work_phone,
      mobile_phone,
      personal_identification_number,
      tax_number,
    },
  ) => {
    const client = createClient(connectionInput, context.debug.enabled);
    const { data } = await client.post(`/employees`, {
      email: email || undefined,
      first_name: first_name || undefined,
      last_name: last_name || undefined,
      work_start_date: work_start_date || undefined,
      send_email: send_email || undefined,
      date_of_birth: date_of_birth || undefined,
      gender: gender || undefined,
      marital_status: marital_status || undefined,
      nationality: nationality || undefined,
      country: country || undefined,
      state: state || undefined,
      post_code: post_code || undefined,
      street_first: street_first || undefined,
      street_second: street_second || undefined,
      city: city || undefined,
      position_title: position_title || undefined,
      home_phone: home_phone || undefined,
      work_phone: work_phone || undefined,
      mobile_phone: mobile_phone || undefined,
      personal_identification_number:
        personal_identification_number || undefined,
      tax_number: tax_number || undefined,
    });
    return {
      data,
    };
  },
  examplePayload: createEmployeeExamplePayload,
});
