import { action } from "@prismatic-io/spectral";
import { createClient } from "../../client";
import { updateEmployeeExamplePayload } from "../../examplePayloads";
import {
  approver_ids,
  city,
  connectionInput,
  country,
  date_of_birth,
  employee_id,
  employee_number,
  first_name,
  gender,
  home_phone,
  last_name,
  leader_id,
  location_id,
  marital_status,
  mobile_phone,
  nationality,
  personal_identification_number,
  position_id,
  post_code,
  selected_leave_types,
  state,
  street_first,
  street_second,
  tax_number,
  team_id,
  work_phone,
  work_start_date,
} from "../../inputs";

export const updateEmployee = action({
  display: {
    label: "Update Employee",
    description: "Update employee",
  },
  inputs: {
    connectionInput,
    employee_id,
    first_name: { ...first_name, required: false },
    last_name: { ...last_name, required: false },
    work_start_date,
    location_id,
    team_id,
    leader_id,
    date_of_birth,
    gender,
    marital_status,
    nationality,
    country,
    state,
    post_code,
    street_first,
    street_second,
    city,
    position_id,
    employee_number,
    home_phone,
    work_phone,
    mobile_phone,
    personal_identification_number,
    tax_number,
    approver_ids,
    selected_leave_types,
  },
  perform: async (
    context,
    {
      connectionInput,
      employee_id,
      first_name,
      last_name,
      work_start_date,
      location_id,
      team_id,
      leader_id,
      date_of_birth,
      gender,
      marital_status,
      nationality,
      country,
      state,
      post_code,
      street_first,
      street_second,
      city,
      position_id,
      employee_number,
      home_phone,
      work_phone,
      mobile_phone,
      personal_identification_number,
      tax_number,
      approver_ids,
      selected_leave_types,
    },
  ) => {
    const client = createClient(connectionInput, context.debug.enabled);
    const { data } = await client.put(`/employees/${employee_id}`, {
      first_name: first_name || undefined,
      last_name: last_name || undefined,
      work_start_date: work_start_date || undefined,
      location_id: location_id || undefined,
      team_id: team_id || undefined,
      leader_id: leader_id || undefined,
      date_of_birth: date_of_birth || undefined,
      gender: gender || undefined,
      marital_status: marital_status || undefined,
      nationality: nationality || undefined,
      country: country || undefined,
      state: state || undefined,
      post_code: post_code || undefined,
      street_first: street_first || undefined,
      street_second: street_second || undefined,
      city: city || undefined,
      position_id: position_id || undefined,
      employee_number: employee_number || undefined,
      home_phone: home_phone || undefined,
      work_phone: work_phone || undefined,
      mobile_phone: mobile_phone || undefined,
      personal_identification_number:
        personal_identification_number || undefined,
      tax_number: tax_number || undefined,
      approver_ids: approver_ids || undefined,
      selected_leave_types: selected_leave_types || undefined,
    });
    return {
      data,
    };
  },
  examplePayload: updateEmployeeExamplePayload,
});
