import { pageSchema } from "./shared";
const billSchema = {
  type: "object" as const,
  properties: {
    accounting_date: {
      type: "string",
      format: "date-time",
    },
    accounting_field_selections: {
      type: "array",
      items: {
        type: "object",
        properties: {
          category_info: {
            type: "object",
            properties: {
              external_id: {
                type: "string",
              },
              id: {
                type: "string",
              },
              name: {
                type: "string",
              },
              type: {
                type: "string",
                enum: [
                  "AMORTIZATION_TEMPLATE",
                  "BILLABLE",
                  "COST_CENTER",
                  "CUSTOMERS_JOBS",
                  "DEFERRAL_CODE",
                  "EXPENSE_ENTITY",
                  "GL_ACCOUNT",
                  "INVENTORY_ITEM",
                  "JOURNAL",
                  "MERCHANT",
                  "NON_ERP",
                  "OTHER",
                  "PROJECT",
                  "REPORTING_TAG",
                  "SUBSIDIARY",
                  "TAX_CODE",
                  "UNIT_OF_MEASURE",
                ],
              },
            },
            required: ["external_id", "id", "name", "type"],
          },
          display_name: {
            type: ["string", "null"],
          },
          external_code: {
            type: ["string", "null"],
          },
          external_id: {
            type: "string",
          },
          id: {
            type: "string",
          },
          name: {
            type: "string",
          },
          provider_name: {
            type: ["string", "null"],
          },
        },
        required: [
          "category_info",
          "display_name",
          "external_id",
          "id",
          "name",
          "provider_name",
        ],
      },
    },
    amount: {
      type: "object",
      properties: {
        amount: {
          type: "integer",
        },
        currency_code: {
          type: "string",
        },
        minor_unit_conversion_rate: {
          type: ["integer", "null"],
        },
      },
      required: ["amount", "currency_code", "minor_unit_conversion_rate"],
    },
    applied_vendor_credits: {
      type: "array",
      items: {
        type: "object",
        properties: {
          amount: {
            type: "object",
            properties: {
              amount: {
                type: "integer",
              },
              currency_code: {
                type: "string",
              },
              minor_unit_conversion_rate: {
                type: ["integer", "null"],
              },
            },
            required: ["amount", "currency_code", "minor_unit_conversion_rate"],
          },
          id: {
            type: "string",
          },
        },
        required: ["amount", "id"],
      },
    },
    approval_status: {
      type: ["string", "null"],
      enum: ["APPROVED", "INITIALIZED", "PENDING", "REJECTED", "TERMINATED"],
    },
    archived_at: {
      type: ["string", "null"],
      format: "date-time",
    },
    bill_owner: {
      type: "object",
      properties: {
        first_name: {
          type: "string",
        },
        id: {
          type: "string",
          format: "uuid",
        },
        last_name: {
          type: "string",
        },
      },
      required: ["id"],
    },
    created_at: {
      type: "string",
      format: "date-time",
    },
    deep_link_url: {
      type: "string",
    },
    draft_bill_created_at: {
      type: ["string", "null"],
      format: "date-time",
    },
    draft_bill_id: {
      type: ["string", "null"],
      format: "uuid",
    },
    due_at: {
      type: "string",
      format: "date-time",
    },
    enable_accounting_sync: {
      type: "boolean",
    },
    entity_id: {
      type: "string",
      format: "uuid",
    },
    fx_conversion_rate: {
      type: "string",
      format: "decimal",
    },
    id: {
      type: "string",
      format: "uuid",
    },
    inventory_line_items: {
      type: "array",
      items: {
        type: "object",
        properties: {
          accounting_field_selections: {
            type: "array",
            items: {
              type: "object",
              properties: {
                category_info: {
                  type: "object",
                  properties: {
                    external_id: {
                      type: "string",
                    },
                    id: {
                      type: "string",
                    },
                    name: {
                      type: "string",
                    },
                    type: {
                      type: "string",
                      enum: [
                        "AMORTIZATION_TEMPLATE",
                        "BILLABLE",
                        "COST_CENTER",
                        "CUSTOMERS_JOBS",
                        "DEFERRAL_CODE",
                        "EXPENSE_ENTITY",
                        "GL_ACCOUNT",
                        "INVENTORY_ITEM",
                        "JOURNAL",
                        "MERCHANT",
                        "NON_ERP",
                        "OTHER",
                        "PROJECT",
                        "REPORTING_TAG",
                        "SUBSIDIARY",
                        "TAX_CODE",
                        "UNIT_OF_MEASURE",
                      ],
                    },
                  },
                  required: ["external_id", "id", "name", "type"],
                },
                display_name: {
                  type: ["string", "null"],
                },
                external_code: {
                  type: ["string", "null"],
                },
                external_id: {
                  type: "string",
                },
                id: {
                  type: "string",
                },
                name: {
                  type: "string",
                },
                provider_name: {
                  type: ["string", "null"],
                },
              },
              required: [
                "category_info",
                "display_name",
                "external_id",
                "id",
                "name",
                "provider_name",
              ],
            },
          },
          amount: {
            type: "object",
            properties: {
              amount: {
                type: "integer",
              },
              currency_code: {
                type: "string",
              },
              minor_unit_conversion_rate: {
                type: ["integer", "null"],
              },
            },
            required: ["amount", "currency_code", "minor_unit_conversion_rate"],
          },
          item_receipt_line_item_ids: {
            type: "array",
            items: {
              type: "string",
              format: "uuid",
            },
          },
          memo: {
            type: "string",
          },
          purchase_order_line_item_id: {
            type: ["string", "null"],
            format: "uuid",
          },
          quantity: {
            type: "number",
          },
          unit_price: {
            type: "object",
            properties: {
              amount: {
                type: "integer",
              },
              currency_code: {
                type: "string",
              },
              minor_unit_conversion_rate: {
                type: ["integer", "null"],
              },
            },
            required: ["amount", "currency_code", "minor_unit_conversion_rate"],
          },
          withholding_line_item: {
            type: ["object", "null"],
            properties: {
              gross_amount: {
                type: "object",
                properties: {
                  currency: {
                    type: "string",
                    enum: [
                      "AED",
                      "AFN",
                      "ALL",
                      "AMD",
                      "ANG",
                      "AOA",
                      "ARS",
                      "AUD",
                      "AWG",
                      "AZN",
                      "BAM",
                      "BBD",
                      "BDT",
                      "BGN",
                      "BHD",
                      "BIF",
                      "BMD",
                      "BND",
                      "BOB",
                      "BOV",
                      "BRL",
                      "BSD",
                      "BTN",
                      "BWP",
                      "BYN",
                      "BZD",
                      "CAD",
                      "CDF",
                      "CHE",
                      "CHF",
                      "CHW",
                      "CLF",
                      "CLP",
                      "CNH",
                      "CNY",
                      "COP",
                      "COU",
                      "CRC",
                      "CUC",
                      "CUP",
                      "CVE",
                      "CZK",
                      "DJF",
                      "DKK",
                      "DOP",
                      "DZD",
                      "EGP",
                      "ERN",
                      "ETB",
                      "EUR",
                      "EURC",
                      "FJD",
                      "FKP",
                      "GBP",
                      "GEL",
                      "GHS",
                      "GIP",
                      "GMD",
                      "GNF",
                      "GTQ",
                      "GYD",
                      "HKD",
                      "HNL",
                      "HRK",
                      "HTG",
                      "HUF",
                      "IDR",
                      "ILS",
                      "INR",
                      "IQD",
                      "IRR",
                      "ISK",
                      "JMD",
                      "JOD",
                      "JPY",
                      "KES",
                      "KGS",
                      "KHR",
                      "KMF",
                      "KPW",
                      "KRW",
                      "KWD",
                      "KYD",
                      "KZT",
                      "LAK",
                      "LBP",
                      "LKR",
                      "LRD",
                      "LSL",
                      "LYD",
                      "MAD",
                      "MDL",
                      "MGA",
                      "MKD",
                      "MMK",
                      "MNT",
                      "MOP",
                      "MRU",
                      "MUR",
                      "MVR",
                      "MWK",
                      "MXN",
                      "MXV",
                      "MYR",
                      "MZN",
                      "NAD",
                      "NGN",
                      "NIO",
                      "NOK",
                      "NPR",
                      "NZD",
                      "OMR",
                      "OPEN_USD",
                      "PAB",
                      "PEN",
                      "PGK",
                      "PHP",
                      "PKR",
                      "PLN",
                      "PYG",
                      "QAR",
                      "RON",
                      "RSD",
                      "RUB",
                      "RWF",
                      "SAR",
                      "SBD",
                      "SCR",
                      "SDG",
                      "SEK",
                      "SGD",
                      "SHP",
                      "SLE",
                      "SLL",
                      "SOS",
                      "SRD",
                      "SSP",
                      "STN",
                      "SVC",
                      "SYP",
                      "SZL",
                      "THB",
                      "TJS",
                      "TMT",
                      "TND",
                      "TOP",
                      "TRY",
                      "TTD",
                      "TWD",
                      "TZS",
                      "UAH",
                      "UGX",
                      "USD",
                      "USDB",
                      "USDC",
                      "USDSUI",
                      "USDT",
                      "USN",
                      "UYI",
                      "UYU",
                      "UYW",
                      "UZS",
                      "VED",
                      "VES",
                      "VND",
                      "VUV",
                      "WST",
                      "XAD",
                      "XAF",
                      "XAG",
                      "XAU",
                      "XBA",
                      "XBB",
                      "XBC",
                      "XBD",
                      "XCD",
                      "XCG",
                      "XDR",
                      "XOF",
                      "XPD",
                      "XPF",
                      "XPT",
                      "XSU",
                      "XTS",
                      "XUA",
                      "XXX",
                      "YER",
                      "ZAR",
                      "ZMW",
                      "ZWG",
                      "ZWL",
                    ],
                  },
                  value: {
                    type: "integer",
                  },
                },
                required: ["currency", "value"],
              },
              withholding_amount: {
                type: "object",
                properties: {
                  currency: {
                    type: "string",
                    enum: [
                      "AED",
                      "AFN",
                      "ALL",
                      "AMD",
                      "ANG",
                      "AOA",
                      "ARS",
                      "AUD",
                      "AWG",
                      "AZN",
                      "BAM",
                      "BBD",
                      "BDT",
                      "BGN",
                      "BHD",
                      "BIF",
                      "BMD",
                      "BND",
                      "BOB",
                      "BOV",
                      "BRL",
                      "BSD",
                      "BTN",
                      "BWP",
                      "BYN",
                      "BZD",
                      "CAD",
                      "CDF",
                      "CHE",
                      "CHF",
                      "CHW",
                      "CLF",
                      "CLP",
                      "CNH",
                      "CNY",
                      "COP",
                      "COU",
                      "CRC",
                      "CUC",
                      "CUP",
                      "CVE",
                      "CZK",
                      "DJF",
                      "DKK",
                      "DOP",
                      "DZD",
                      "EGP",
                      "ERN",
                      "ETB",
                      "EUR",
                      "EURC",
                      "FJD",
                      "FKP",
                      "GBP",
                      "GEL",
                      "GHS",
                      "GIP",
                      "GMD",
                      "GNF",
                      "GTQ",
                      "GYD",
                      "HKD",
                      "HNL",
                      "HRK",
                      "HTG",
                      "HUF",
                      "IDR",
                      "ILS",
                      "INR",
                      "IQD",
                      "IRR",
                      "ISK",
                      "JMD",
                      "JOD",
                      "JPY",
                      "KES",
                      "KGS",
                      "KHR",
                      "KMF",
                      "KPW",
                      "KRW",
                      "KWD",
                      "KYD",
                      "KZT",
                      "LAK",
                      "LBP",
                      "LKR",
                      "LRD",
                      "LSL",
                      "LYD",
                      "MAD",
                      "MDL",
                      "MGA",
                      "MKD",
                      "MMK",
                      "MNT",
                      "MOP",
                      "MRU",
                      "MUR",
                      "MVR",
                      "MWK",
                      "MXN",
                      "MXV",
                      "MYR",
                      "MZN",
                      "NAD",
                      "NGN",
                      "NIO",
                      "NOK",
                      "NPR",
                      "NZD",
                      "OMR",
                      "OPEN_USD",
                      "PAB",
                      "PEN",
                      "PGK",
                      "PHP",
                      "PKR",
                      "PLN",
                      "PYG",
                      "QAR",
                      "RON",
                      "RSD",
                      "RUB",
                      "RWF",
                      "SAR",
                      "SBD",
                      "SCR",
                      "SDG",
                      "SEK",
                      "SGD",
                      "SHP",
                      "SLE",
                      "SLL",
                      "SOS",
                      "SRD",
                      "SSP",
                      "STN",
                      "SVC",
                      "SYP",
                      "SZL",
                      "THB",
                      "TJS",
                      "TMT",
                      "TND",
                      "TOP",
                      "TRY",
                      "TTD",
                      "TWD",
                      "TZS",
                      "UAH",
                      "UGX",
                      "USD",
                      "USDB",
                      "USDC",
                      "USDSUI",
                      "USDT",
                      "USN",
                      "UYI",
                      "UYU",
                      "UYW",
                      "UZS",
                      "VED",
                      "VES",
                      "VND",
                      "VUV",
                      "WST",
                      "XAD",
                      "XAF",
                      "XAG",
                      "XAU",
                      "XBA",
                      "XBB",
                      "XBC",
                      "XBD",
                      "XCD",
                      "XCG",
                      "XDR",
                      "XOF",
                      "XPD",
                      "XPF",
                      "XPT",
                      "XSU",
                      "XTS",
                      "XUA",
                      "XXX",
                      "YER",
                      "ZAR",
                      "ZMW",
                      "ZWG",
                      "ZWL",
                    ],
                  },
                  value: {
                    type: "integer",
                  },
                },
                required: ["currency", "value"],
              },
              withholding_percentage: {
                type: ["string", "null"],
                format: "decimal",
              },
            },
            required: [
              "gross_amount",
              "withholding_amount",
              "withholding_percentage",
            ],
          },
        },
        required: [
          "accounting_field_selections",
          "amount",
          "item_receipt_line_item_ids",
          "purchase_order_line_item_id",
          "quantity",
          "unit_price",
        ],
      },
    },
    invoice_number: {
      type: "string",
    },
    invoice_urls: {
      type: "array",
      items: {
        type: "string",
      },
    },
    is_withholding_release: {
      type: ["boolean", "null"],
    },
    issued_at: {
      type: "string",
      format: "date-time",
    },
    item_receipt_ids: {
      type: "array",
      items: {
        type: "string",
        format: "uuid",
      },
    },
    line_items: {
      type: "array",
      items: {
        type: "object",
        properties: {
          accounting_field_selections: {
            type: "array",
            items: {
              type: "object",
              properties: {
                category_info: {
                  type: "object",
                  properties: {
                    external_id: {
                      type: "string",
                    },
                    id: {
                      type: "string",
                    },
                    name: {
                      type: "string",
                    },
                    type: {
                      type: "string",
                      enum: [
                        "AMORTIZATION_TEMPLATE",
                        "BILLABLE",
                        "COST_CENTER",
                        "CUSTOMERS_JOBS",
                        "DEFERRAL_CODE",
                        "EXPENSE_ENTITY",
                        "GL_ACCOUNT",
                        "INVENTORY_ITEM",
                        "JOURNAL",
                        "MERCHANT",
                        "NON_ERP",
                        "OTHER",
                        "PROJECT",
                        "REPORTING_TAG",
                        "SUBSIDIARY",
                        "TAX_CODE",
                        "UNIT_OF_MEASURE",
                      ],
                    },
                  },
                  required: ["external_id", "id", "name", "type"],
                },
                display_name: {
                  type: ["string", "null"],
                },
                external_code: {
                  type: ["string", "null"],
                },
                external_id: {
                  type: "string",
                },
                id: {
                  type: "string",
                },
                name: {
                  type: "string",
                },
                provider_name: {
                  type: ["string", "null"],
                },
              },
              required: [
                "category_info",
                "display_name",
                "external_id",
                "id",
                "name",
                "provider_name",
              ],
            },
          },
          amount: {
            type: "object",
            properties: {
              amount: {
                type: "integer",
              },
              currency_code: {
                type: "string",
              },
              minor_unit_conversion_rate: {
                type: ["integer", "null"],
              },
            },
            required: ["amount", "currency_code", "minor_unit_conversion_rate"],
          },
          item_receipt_line_item_ids: {
            type: "array",
            items: {
              type: "string",
              format: "uuid",
            },
          },
          memo: {
            type: "string",
          },
          purchase_order_line_item_id: {
            type: ["string", "null"],
            format: "uuid",
          },
          withholding_line_item: {
            type: ["object", "null"],
            properties: {
              gross_amount: {
                type: "object",
                properties: {
                  currency: {
                    type: "string",
                    enum: [
                      "AED",
                      "AFN",
                      "ALL",
                      "AMD",
                      "ANG",
                      "AOA",
                      "ARS",
                      "AUD",
                      "AWG",
                      "AZN",
                      "BAM",
                      "BBD",
                      "BDT",
                      "BGN",
                      "BHD",
                      "BIF",
                      "BMD",
                      "BND",
                      "BOB",
                      "BOV",
                      "BRL",
                      "BSD",
                      "BTN",
                      "BWP",
                      "BYN",
                      "BZD",
                      "CAD",
                      "CDF",
                      "CHE",
                      "CHF",
                      "CHW",
                      "CLF",
                      "CLP",
                      "CNH",
                      "CNY",
                      "COP",
                      "COU",
                      "CRC",
                      "CUC",
                      "CUP",
                      "CVE",
                      "CZK",
                      "DJF",
                      "DKK",
                      "DOP",
                      "DZD",
                      "EGP",
                      "ERN",
                      "ETB",
                      "EUR",
                      "EURC",
                      "FJD",
                      "FKP",
                      "GBP",
                      "GEL",
                      "GHS",
                      "GIP",
                      "GMD",
                      "GNF",
                      "GTQ",
                      "GYD",
                      "HKD",
                      "HNL",
                      "HRK",
                      "HTG",
                      "HUF",
                      "IDR",
                      "ILS",
                      "INR",
                      "IQD",
                      "IRR",
                      "ISK",
                      "JMD",
                      "JOD",
                      "JPY",
                      "KES",
                      "KGS",
                      "KHR",
                      "KMF",
                      "KPW",
                      "KRW",
                      "KWD",
                      "KYD",
                      "KZT",
                      "LAK",
                      "LBP",
                      "LKR",
                      "LRD",
                      "LSL",
                      "LYD",
                      "MAD",
                      "MDL",
                      "MGA",
                      "MKD",
                      "MMK",
                      "MNT",
                      "MOP",
                      "MRU",
                      "MUR",
                      "MVR",
                      "MWK",
                      "MXN",
                      "MXV",
                      "MYR",
                      "MZN",
                      "NAD",
                      "NGN",
                      "NIO",
                      "NOK",
                      "NPR",
                      "NZD",
                      "OMR",
                      "OPEN_USD",
                      "PAB",
                      "PEN",
                      "PGK",
                      "PHP",
                      "PKR",
                      "PLN",
                      "PYG",
                      "QAR",
                      "RON",
                      "RSD",
                      "RUB",
                      "RWF",
                      "SAR",
                      "SBD",
                      "SCR",
                      "SDG",
                      "SEK",
                      "SGD",
                      "SHP",
                      "SLE",
                      "SLL",
                      "SOS",
                      "SRD",
                      "SSP",
                      "STN",
                      "SVC",
                      "SYP",
                      "SZL",
                      "THB",
                      "TJS",
                      "TMT",
                      "TND",
                      "TOP",
                      "TRY",
                      "TTD",
                      "TWD",
                      "TZS",
                      "UAH",
                      "UGX",
                      "USD",
                      "USDB",
                      "USDC",
                      "USDSUI",
                      "USDT",
                      "USN",
                      "UYI",
                      "UYU",
                      "UYW",
                      "UZS",
                      "VED",
                      "VES",
                      "VND",
                      "VUV",
                      "WST",
                      "XAD",
                      "XAF",
                      "XAG",
                      "XAU",
                      "XBA",
                      "XBB",
                      "XBC",
                      "XBD",
                      "XCD",
                      "XCG",
                      "XDR",
                      "XOF",
                      "XPD",
                      "XPF",
                      "XPT",
                      "XSU",
                      "XTS",
                      "XUA",
                      "XXX",
                      "YER",
                      "ZAR",
                      "ZMW",
                      "ZWG",
                      "ZWL",
                    ],
                  },
                  value: {
                    type: "integer",
                  },
                },
                required: ["currency", "value"],
              },
              withholding_amount: {
                type: "object",
                properties: {
                  currency: {
                    type: "string",
                    enum: [
                      "AED",
                      "AFN",
                      "ALL",
                      "AMD",
                      "ANG",
                      "AOA",
                      "ARS",
                      "AUD",
                      "AWG",
                      "AZN",
                      "BAM",
                      "BBD",
                      "BDT",
                      "BGN",
                      "BHD",
                      "BIF",
                      "BMD",
                      "BND",
                      "BOB",
                      "BOV",
                      "BRL",
                      "BSD",
                      "BTN",
                      "BWP",
                      "BYN",
                      "BZD",
                      "CAD",
                      "CDF",
                      "CHE",
                      "CHF",
                      "CHW",
                      "CLF",
                      "CLP",
                      "CNH",
                      "CNY",
                      "COP",
                      "COU",
                      "CRC",
                      "CUC",
                      "CUP",
                      "CVE",
                      "CZK",
                      "DJF",
                      "DKK",
                      "DOP",
                      "DZD",
                      "EGP",
                      "ERN",
                      "ETB",
                      "EUR",
                      "EURC",
                      "FJD",
                      "FKP",
                      "GBP",
                      "GEL",
                      "GHS",
                      "GIP",
                      "GMD",
                      "GNF",
                      "GTQ",
                      "GYD",
                      "HKD",
                      "HNL",
                      "HRK",
                      "HTG",
                      "HUF",
                      "IDR",
                      "ILS",
                      "INR",
                      "IQD",
                      "IRR",
                      "ISK",
                      "JMD",
                      "JOD",
                      "JPY",
                      "KES",
                      "KGS",
                      "KHR",
                      "KMF",
                      "KPW",
                      "KRW",
                      "KWD",
                      "KYD",
                      "KZT",
                      "LAK",
                      "LBP",
                      "LKR",
                      "LRD",
                      "LSL",
                      "LYD",
                      "MAD",
                      "MDL",
                      "MGA",
                      "MKD",
                      "MMK",
                      "MNT",
                      "MOP",
                      "MRU",
                      "MUR",
                      "MVR",
                      "MWK",
                      "MXN",
                      "MXV",
                      "MYR",
                      "MZN",
                      "NAD",
                      "NGN",
                      "NIO",
                      "NOK",
                      "NPR",
                      "NZD",
                      "OMR",
                      "OPEN_USD",
                      "PAB",
                      "PEN",
                      "PGK",
                      "PHP",
                      "PKR",
                      "PLN",
                      "PYG",
                      "QAR",
                      "RON",
                      "RSD",
                      "RUB",
                      "RWF",
                      "SAR",
                      "SBD",
                      "SCR",
                      "SDG",
                      "SEK",
                      "SGD",
                      "SHP",
                      "SLE",
                      "SLL",
                      "SOS",
                      "SRD",
                      "SSP",
                      "STN",
                      "SVC",
                      "SYP",
                      "SZL",
                      "THB",
                      "TJS",
                      "TMT",
                      "TND",
                      "TOP",
                      "TRY",
                      "TTD",
                      "TWD",
                      "TZS",
                      "UAH",
                      "UGX",
                      "USD",
                      "USDB",
                      "USDC",
                      "USDSUI",
                      "USDT",
                      "USN",
                      "UYI",
                      "UYU",
                      "UYW",
                      "UZS",
                      "VED",
                      "VES",
                      "VND",
                      "VUV",
                      "WST",
                      "XAD",
                      "XAF",
                      "XAG",
                      "XAU",
                      "XBA",
                      "XBB",
                      "XBC",
                      "XBD",
                      "XCD",
                      "XCG",
                      "XDR",
                      "XOF",
                      "XPD",
                      "XPF",
                      "XPT",
                      "XSU",
                      "XTS",
                      "XUA",
                      "XXX",
                      "YER",
                      "ZAR",
                      "ZMW",
                      "ZWG",
                      "ZWL",
                    ],
                  },
                  value: {
                    type: "integer",
                  },
                },
                required: ["currency", "value"],
              },
              withholding_percentage: {
                type: ["string", "null"],
                format: "decimal",
              },
            },
            required: [
              "gross_amount",
              "withholding_amount",
              "withholding_percentage",
            ],
          },
        },
        required: [
          "accounting_field_selections",
          "amount",
          "item_receipt_line_item_ids",
          "purchase_order_line_item_id",
        ],
      },
    },
    memo: {
      type: "string",
    },
    paid_at: {
      type: "string",
      format: "date-time",
    },
    payment: {
      type: ["object", "null"],
      properties: {
        amount: {
          type: "object",
          properties: {
            amount: {
              type: "integer",
            },
            currency_code: {
              type: "string",
            },
            minor_unit_conversion_rate: {
              type: ["integer", "null"],
            },
          },
          required: ["amount", "currency_code", "minor_unit_conversion_rate"],
        },
        customer_friendly_payment_id: {
          type: ["string", "null"],
        },
        details: {
          type: "object",
          properties: {
            approval_status: {
              type: ["string", "null"],
              enum: [
                "APPROVED",
                "INITIALIZED",
                "PENDING",
                "REJECTED",
                "TERMINATED",
              ],
            },
            fund_id: {
              type: "string",
              format: "uuid",
            },
            is_same_day: {
              type: "boolean",
            },
            manual_payment_method: {
              type: ["string", "null"],
              enum: [
                "CASH",
                "CHECK",
                "CROSS_BORDER_PAYMENT",
                "CRYPTO_WALLET_TRANSFER",
                "DIRECT_DEBIT",
                "DOMESTIC_WIRE_TRANSFER",
                "NON_RAMP_CREDIT_CARD",
                "OTHER",
                "PAID_IN_ERP",
              ],
            },
            source_bank_account_id: {
              type: ["string", "null"],
              format: "uuid",
            },
            spend_limit_id: {
              type: "string",
              format: "uuid",
            },
            transaction_ids: {
              type: "array",
              items: {
                type: "string",
                format: "uuid",
              },
            },
            vendor_account_id: {
              type: ["string", "null"],
              format: "uuid",
            },
          },
        },
        effective_date: {
          type: ["string", "null"],
          format: "date-time",
        },
        id: {
          type: ["string", "null"],
        },
        payment_date: {
          type: ["string", "null"],
          format: "date-time",
        },
        payment_method: {
          type: ["string", "null"],
          enum: [
            "ACH",
            "AUTOMATIC_CARD_PAYMENT",
            "CARD",
            "CHECK",
            "CRYPTO_WALLET_TRANSFER",
            "DOMESTIC_WIRE",
            "FED_NOW",
            "INTERNATIONAL",
            "LOCAL_BANK_TRANSFER",
            "ONE_TIME_CARD",
            "ONE_TIME_CARD_DELIVERY",
            "PAID_MANUALLY",
            "RTP",
            "SWIFT",
            "UNSPECIFIED",
            "VENDOR_CREDIT",
          ],
        },
        trace_id: {
          type: ["object", "null"],
          properties: {
            descriptor: {
              type: "string",
            },
            trace_id: {
              type: "string",
            },
          },
        },
      },
      required: [
        "amount",
        "customer_friendly_payment_id",
        "details",
        "effective_date",
        "id",
        "payment_date",
        "payment_method",
        "trace_id",
      ],
    },
    posting_date: {
      type: "string",
      format: "date-time",
    },
    purchase_order_id: {
      type: "string",
      format: "uuid",
    },
    remote_id: {
      type: "string",
    },
    status: {
      type: "string",
      enum: ["OPEN", "PAID"],
    },
    status_summary: {
      type: "string",
      enum: [
        "APPROVAL_PENDING",
        "APPROVAL_REJECTED",
        "ARCHIVED",
        "AWAITING_RELEASE",
        "BLOCKED",
        "HELD_BY_PROVIDER",
        "ON_HOLD",
        "PAYMENT_COMPLETED",
        "PAYMENT_DETAILS_MISSING",
        "PAYMENT_ERROR",
        "PAYMENT_NOT_INSTRUCTED",
        "PAYMENT_PROCESSING",
        "PAYMENT_READY",
        "PAYMENT_SCHEDULED",
        "PENDING_VENDOR_APPROVAL",
        "WAITING_FOR_TRANSACTION_MATCH",
        "WAITING_FOR_VENDOR",
      ],
    },
    sync_status: {
      type: "string",
      enum: ["BILL_AND_PAYMENT_SYNCED", "BILL_SYNCED", "NOT_SYNCED"],
    },
    vendor: {
      type: "object",
      properties: {
        id: {
          type: "string",
          format: "uuid",
        },
        name: {
          type: "string",
        },
        remote_code: {
          type: "string",
        },
        remote_id: {
          type: "string",
        },
        remote_name: {
          type: "string",
        },
        type: {
          type: "string",
          enum: ["BUSINESS", "INDIVIDUAL"],
        },
      },
      required: ["id", "name"],
    },
    vendor_contact_id: {
      type: ["string", "null"],
      format: "uuid",
    },
    vendor_memo: {
      type: "string",
    },
  },
  required: [
    "accounting_date",
    "accounting_field_selections",
    "amount",
    "applied_vendor_credits",
    "approval_status",
    "archived_at",
    "bill_owner",
    "created_at",
    "draft_bill_created_at",
    "draft_bill_id",
    "due_at",
    "entity_id",
    "fx_conversion_rate",
    "id",
    "inventory_line_items",
    "invoice_urls",
    "issued_at",
    "item_receipt_ids",
    "line_items",
    "payment",
    "status",
    "status_summary",
    "sync_status",
    "vendor",
    "vendor_contact_id",
  ],
};
export const getBillOutputSchema = billSchema;
export const listBillsOutputSchema = {
  type: "object" as const,
  properties: {
    data: {
      type: "array",
      items: billSchema,
    },
    page: pageSchema,
  },
  required: ["data", "page"],
};
