import { pageSchema } from "./shared";
const businessEntitySchema = {
  type: "object" as const,
  properties: {
    accounts: {
      type: "array",
      items: {
        type: "object",
        properties: {
          bank_account_id: {
            type: ["string", "null"],
            format: "uuid",
          },
          classification: {
            type: "string",
            enum: [
              "ANY",
              "ASSET",
              "CREDCARD",
              "EQUITY",
              "EXPENSE",
              "LIABILITY",
              "REVENUE",
              "UNKNOWN",
            ],
          },
          created_at: {
            type: "string",
            format: "date-time",
          },
          external_id: {
            type: "string",
          },
          external_name: {
            type: "string",
          },
          internal_id: {
            type: "string",
          },
          usage_type: {
            type: ["string", "null"],
            enum: [
              "ACCRUAL_AP_ACCOUNT",
              "ACCRUAL_LIABILITY_ACCOUNT",
              "AR_ACCOUNTS_RECEIVABLE_ACCOUNT",
              "AR_BAD_DEBT_ACCOUNT",
              "AR_CARD_FEES_ACCOUNT",
              "AR_CASH_ACCOUNT_DEFAULT",
              "AR_CHARGEBACK_CLEARING_ACCOUNT",
              "AR_INCOME_ACCOUNT_DEFAULT",
              "AR_REFUNDS_CLEARING_ACCOUNT",
              "AR_SALES_TAX_PAYABLE_ACCOUNT",
              "AR_UNBILLED_ACCOUNTS_RECEIVABLE_ACCOUNT",
              "AR_UNDEPOSITED_FUNDS_ACCOUNT",
              "BILL_PAY_ACCOUNTS_PAYABLE_ACCOUNT",
              "BILL_PAY_BANK_ACCOUNT",
              "BILL_PAY_FX_GAIN_LOSS_ACCOUNT",
              "BILL_PAY_RETAINAGE_PAYABLE_ACCOUNT",
              "BOOKKEEPING_AUTOMATION_BANK_ACCOUNT",
              "BOOKKEEPING_AUTOMATION_CLEARING_ACCOUNT",
              "BROKERAGE_ACCOUNT",
              "BROKERAGE_DIVIDEND_ACCOUNT",
              "CARD_LIABILITY_ACCOUNT",
              "CARD_TRANSACTION_BILLS_ACCOUNTS_PAYABLE_ACCOUNT",
              "CASHBACK_ACCOUNT",
              "CASH_ACCOUNT",
              "FIXED_ASSET_ACCUMULATED_IMPAIRMENT_ACCOUNT",
              "FIXED_ASSET_GAIN_ACCOUNT",
              "FIXED_ASSET_IMPAIRMENT_LOSS_ACCOUNT",
              "FIXED_ASSET_LOSS_ACCOUNT",
              "FIXED_ASSET_PROCEEDS_ON_DISPOSAL_ACCOUNT",
              "INTERCOMPANY_ACCOUNTS_PAYABLE_ACCOUNT",
              "INTERCOMPANY_ACCOUNTS_RECEIVABLE_ACCOUNT",
              "INTERCOMPANY_TRANSFER_CLEARING_ACCOUNT",
              "MANAGED_PORTFOLIO_CASH_ACCOUNT",
              "MANAGED_PORTFOLIO_INTEREST_INCOME_ACCOUNT",
              "MANAGED_PORTFOLIO_POSITION_ASSET_ACCOUNT",
              "MANAGED_PORTFOLIO_REALIZED_GAIN_LOSS_ACCOUNT",
              "MANAGED_PORTFOLIO_UNREALIZED_GAIN_LOSS_ACCOUNT",
              "REIMBURSEMENT_ACCOUNTS_PAYABLE_ACCOUNT",
              "REIMBURSEMENT_BANK_ACCOUNT",
              "TRANSFER_BANK_ACCOUNT",
              "UNDEPOSITED_FUNDS",
              "WALLET_ACCOUNT",
              "WALLET_BANK_ACCOUNT",
              "WALLET_YIELD_ACCOUNT",
            ],
          },
        },
        required: [
          "bank_account_id",
          "classification",
          "created_at",
          "external_id",
          "external_name",
          "internal_id",
          "usage_type",
        ],
      },
    },
    connected_subsidiary: {
      type: ["object", "null"],
      properties: {
        external_id: {
          type: "string",
        },
        id: {
          type: "string",
        },
        name: {
          type: "string",
        },
      },
      required: ["external_id", "id", "name"],
    },
    currency: {
      type: ["string", "null"],
      enum: [
        "AED",
        "AFN",
        "ALL",
        "AMD",
        "ANG",
        "AOA",
        "ARS",
        "AUD",
        "AWG",
        "AZN",
        "BAM",
        "BBD",
        "BDT",
        "BGN",
        "BHD",
        "BIF",
        "BMD",
        "BND",
        "BOB",
        "BOV",
        "BRL",
        "BSD",
        "BTN",
        "BWP",
        "BYN",
        "BZD",
        "CAD",
        "CDF",
        "CHE",
        "CHF",
        "CHW",
        "CLF",
        "CLP",
        "CNH",
        "CNY",
        "COP",
        "COU",
        "CRC",
        "CUC",
        "CUP",
        "CVE",
        "CZK",
        "DJF",
        "DKK",
        "DOP",
        "DZD",
        "EGP",
        "ERN",
        "ETB",
        "EUR",
        "EURC",
        "FJD",
        "FKP",
        "GBP",
        "GEL",
        "GHS",
        "GIP",
        "GMD",
        "GNF",
        "GTQ",
        "GYD",
        "HKD",
        "HNL",
        "HRK",
        "HTG",
        "HUF",
        "IDR",
        "ILS",
        "INR",
        "IQD",
        "IRR",
        "ISK",
        "JMD",
        "JOD",
        "JPY",
        "KES",
        "KGS",
        "KHR",
        "KMF",
        "KPW",
        "KRW",
        "KWD",
        "KYD",
        "KZT",
        "LAK",
        "LBP",
        "LKR",
        "LRD",
        "LSL",
        "LYD",
        "MAD",
        "MDL",
        "MGA",
        "MKD",
        "MMK",
        "MNT",
        "MOP",
        "MRU",
        "MUR",
        "MVR",
        "MWK",
        "MXN",
        "MXV",
        "MYR",
        "MZN",
        "NAD",
        "NGN",
        "NIO",
        "NOK",
        "NPR",
        "NZD",
        "OMR",
        "OPEN_USD",
        "PAB",
        "PEN",
        "PGK",
        "PHP",
        "PKR",
        "PLN",
        "PYG",
        "QAR",
        "RON",
        "RSD",
        "RUB",
        "RWF",
        "SAR",
        "SBD",
        "SCR",
        "SDG",
        "SEK",
        "SGD",
        "SHP",
        "SLE",
        "SLL",
        "SOS",
        "SRD",
        "SSP",
        "STN",
        "SVC",
        "SYP",
        "SZL",
        "THB",
        "TJS",
        "TMT",
        "TND",
        "TOP",
        "TRY",
        "TTD",
        "TWD",
        "TZS",
        "UAH",
        "UGX",
        "USD",
        "USDB",
        "USDC",
        "USDSUI",
        "USDT",
        "USN",
        "UYI",
        "UYU",
        "UYW",
        "UZS",
        "VED",
        "VES",
        "VND",
        "VUV",
        "WST",
        "XAD",
        "XAF",
        "XAG",
        "XAU",
        "XBA",
        "XBB",
        "XBC",
        "XBD",
        "XCD",
        "XCG",
        "XDR",
        "XOF",
        "XPD",
        "XPF",
        "XPT",
        "XSU",
        "XTS",
        "XUA",
        "XXX",
        "YER",
        "ZAR",
        "ZMW",
        "ZWG",
        "ZWL",
      ],
    },
    custom_record_fields: {
      type: "array",
      items: {
        type: "object",
        properties: {
          column_display_name: {
            type: "string",
          },
          column_id: {
            type: "string",
          },
          value: {
            type: "object",
            properties: {
              display_name: {
                type: "string",
              },
              has_more: {
                type: "boolean",
              },
              rows: {
                type: "array",
                items: {
                  type: "object",
                  properties: {
                    display_name: {
                      type: "string",
                    },
                    external_key: {
                      type: "string",
                    },
                    row_id: {
                      type: "string",
                    },
                    type: {
                      type: "string",
                      enum: ["custom_table"],
                    },
                  },
                  required: ["display_name", "external_key", "row_id", "type"],
                },
              },
              table_name: {
                type: "string",
              },
              type: {
                type: "string",
                enum: ["boolean"],
              },
              value: {
                type: "boolean",
              },
            },
            required: ["type"],
          },
        },
        required: ["column_display_name", "column_id", "value"],
      },
    },
    default_bill_pay_payment_account_id: {
      type: ["string", "null"],
      format: "uuid",
    },
    entity_name: {
      type: "string",
    },
    id: {
      type: "string",
      format: "uuid",
    },
    is_primary: {
      type: ["boolean", "null"],
    },
    location_ids: {
      type: "array",
      items: {
        type: "string",
        format: "uuid",
      },
    },
    payment_accounts: {
      type: "array",
      items: {
        type: "object",
        properties: {
          account_name: {
            type: "string",
          },
          account_number_last_four: {
            type: "string",
          },
          currency: {
            type: "string",
          },
          id: {
            type: "string",
            format: "uuid",
          },
        },
        required: [
          "account_name",
          "account_number_last_four",
          "currency",
          "id",
        ],
      },
    },
  },
  required: [
    "accounts",
    "connected_subsidiary",
    "currency",
    "default_bill_pay_payment_account_id",
    "entity_name",
    "id",
    "is_primary",
    "location_ids",
    "payment_accounts",
  ],
};
export const getBusinessEntityOutputSchema = businessEntitySchema;
export const listBusinessEntitiesOutputSchema = {
  type: "object" as const,
  properties: {
    data: {
      type: "array",
      items: businessEntitySchema,
    },
    page: pageSchema,
  },
  required: ["data", "page"],
};
