import { pageSchema } from "./shared";
const reimbursementSchema = {
  type: "object" as const,
  properties: {
    accounting_date: {
      type: ["string", "null"],
      format: "date-time",
    },
    accounting_field_selections: {
      type: "array",
      items: {
        type: "object",
        properties: {
          category_info: {
            type: ["object", "null"],
            properties: {
              external_id: {
                type: ["string", "null"],
              },
              id: {
                type: ["string", "null"],
              },
              name: {
                type: ["string", "null"],
              },
              type: {
                type: ["string", "null"],
                enum: [
                  "AMORTIZATION_TEMPLATE",
                  "BILLABLE",
                  "COST_CENTER",
                  "CUSTOMERS_JOBS",
                  "DEFERRAL_CODE",
                  "EXPENSE_ENTITY",
                  "GL_ACCOUNT",
                  "INVENTORY_ITEM",
                  "JOURNAL",
                  "MERCHANT",
                  "NON_ERP",
                  "OTHER",
                  "PROJECT",
                  "REPORTING_TAG",
                  "SUBSIDIARY",
                  "TAX_CODE",
                  "UNIT_OF_MEASURE",
                ],
              },
            },
            required: ["external_id", "id", "name", "type"],
          },
          display_name: {
            type: ["string", "null"],
          },
          external_code: {
            type: ["string", "null"],
          },
          external_id: {
            type: ["string", "null"],
          },
          id: {
            type: ["string", "null"],
          },
          name: {
            type: ["string", "null"],
          },
          provider_name: {
            type: ["string", "null"],
          },
          source: {
            type: ["object", "null"],
            properties: {
              type: {
                type: "string",
              },
            },
          },
          type: {
            type: ["string", "null"],
            enum: [
              "AMORTIZATION_TEMPLATE",
              "BILLABLE",
              "COST_CENTER",
              "CUSTOMERS_JOBS",
              "DEFERRAL_CODE",
              "EXPENSE_ENTITY",
              "GL_ACCOUNT",
              "INVENTORY_ITEM",
              "JOURNAL",
              "MERCHANT",
              "NON_ERP",
              "OTHER",
              "PROJECT",
              "REPORTING_TAG",
              "SUBSIDIARY",
              "TAX_CODE",
              "UNIT_OF_MEASURE",
            ],
          },
        },
        required: [
          "category_info",
          "display_name",
          "external_code",
          "external_id",
          "id",
          "name",
          "provider_name",
          "source",
          "type",
        ],
      },
    },
    approved_at: {
      type: ["string", "null"],
      format: "date-time",
    },
    attendees: {
      type: "array",
      items: {
        type: "object",
        properties: {
          name: {
            type: "string",
          },
          user_id: {
            type: ["string", "null"],
            format: "uuid",
          },
        },
        required: ["name", "user_id"],
      },
    },
    created_at: {
      type: "string",
      format: "date-time",
    },
    direction: {
      type: "string",
      enum: ["BUSINESS_TO_USER", "USER_TO_BUSINESS"],
    },
    distance: {
      type: ["number", "null"],
    },
    employee_id: {
      type: ["string", "null"],
    },
    end_location: {
      type: ["string", "null"],
    },
    entity_amount: {
      type: ["object", "null"],
      properties: {
        currency: {
          type: "string",
          enum: [
            "AED",
            "AFN",
            "ALL",
            "AMD",
            "ANG",
            "AOA",
            "ARS",
            "AUD",
            "AWG",
            "AZN",
            "BAM",
            "BBD",
            "BDT",
            "BGN",
            "BHD",
            "BIF",
            "BMD",
            "BND",
            "BOB",
            "BOV",
            "BRL",
            "BSD",
            "BTN",
            "BWP",
            "BYN",
            "BZD",
            "CAD",
            "CDF",
            "CHE",
            "CHF",
            "CHW",
            "CLF",
            "CLP",
            "CNH",
            "CNY",
            "COP",
            "COU",
            "CRC",
            "CUC",
            "CUP",
            "CVE",
            "CZK",
            "DJF",
            "DKK",
            "DOP",
            "DZD",
            "EGP",
            "ERN",
            "ETB",
            "EUR",
            "EURC",
            "FJD",
            "FKP",
            "GBP",
            "GEL",
            "GHS",
            "GIP",
            "GMD",
            "GNF",
            "GTQ",
            "GYD",
            "HKD",
            "HNL",
            "HRK",
            "HTG",
            "HUF",
            "IDR",
            "ILS",
            "INR",
            "IQD",
            "IRR",
            "ISK",
            "JMD",
            "JOD",
            "JPY",
            "KES",
            "KGS",
            "KHR",
            "KMF",
            "KPW",
            "KRW",
            "KWD",
            "KYD",
            "KZT",
            "LAK",
            "LBP",
            "LKR",
            "LRD",
            "LSL",
            "LYD",
            "MAD",
            "MDL",
            "MGA",
            "MKD",
            "MMK",
            "MNT",
            "MOP",
            "MRU",
            "MUR",
            "MVR",
            "MWK",
            "MXN",
            "MXV",
            "MYR",
            "MZN",
            "NAD",
            "NGN",
            "NIO",
            "NOK",
            "NPR",
            "NZD",
            "OMR",
            "OPEN_USD",
            "PAB",
            "PEN",
            "PGK",
            "PHP",
            "PKR",
            "PLN",
            "PYG",
            "QAR",
            "RON",
            "RSD",
            "RUB",
            "RWF",
            "SAR",
            "SBD",
            "SCR",
            "SDG",
            "SEK",
            "SGD",
            "SHP",
            "SLE",
            "SLL",
            "SOS",
            "SRD",
            "SSP",
            "STN",
            "SVC",
            "SYP",
            "SZL",
            "THB",
            "TJS",
            "TMT",
            "TND",
            "TOP",
            "TRY",
            "TTD",
            "TWD",
            "TZS",
            "UAH",
            "UGX",
            "USD",
            "USDB",
            "USDC",
            "USDSUI",
            "USDT",
            "USN",
            "UYI",
            "UYU",
            "UYW",
            "UZS",
            "VED",
            "VES",
            "VND",
            "VUV",
            "WST",
            "XAD",
            "XAF",
            "XAG",
            "XAU",
            "XBA",
            "XBB",
            "XBC",
            "XBD",
            "XCD",
            "XCG",
            "XDR",
            "XOF",
            "XPD",
            "XPF",
            "XPT",
            "XSU",
            "XTS",
            "XUA",
            "XXX",
            "YER",
            "ZAR",
            "ZMW",
            "ZWG",
            "ZWL",
          ],
        },
        value: {
          type: "integer",
        },
      },
      required: ["currency", "value"],
    },
    entity_id: {
      type: ["string", "null"],
      format: "uuid",
    },
    fund_id: {
      type: ["string", "null"],
      format: "uuid",
    },
    id: {
      type: "string",
      format: "uuid",
    },
    line_items: {
      type: "array",
      items: {
        type: "object",
        properties: {
          accounting_field_selections: {
            type: "array",
            items: {
              type: "object",
              properties: {
                category_info: {
                  type: ["object", "null"],
                  properties: {
                    external_id: {
                      type: ["string", "null"],
                    },
                    id: {
                      type: ["string", "null"],
                    },
                    name: {
                      type: ["string", "null"],
                    },
                    type: {
                      type: ["string", "null"],
                      enum: [
                        "AMORTIZATION_TEMPLATE",
                        "BILLABLE",
                        "COST_CENTER",
                        "CUSTOMERS_JOBS",
                        "DEFERRAL_CODE",
                        "EXPENSE_ENTITY",
                        "GL_ACCOUNT",
                        "INVENTORY_ITEM",
                        "JOURNAL",
                        "MERCHANT",
                        "NON_ERP",
                        "OTHER",
                        "PROJECT",
                        "REPORTING_TAG",
                        "SUBSIDIARY",
                        "TAX_CODE",
                        "UNIT_OF_MEASURE",
                      ],
                    },
                  },
                  required: ["external_id", "id", "name", "type"],
                },
                display_name: {
                  type: ["string", "null"],
                },
                external_code: {
                  type: ["string", "null"],
                },
                external_id: {
                  type: ["string", "null"],
                },
                id: {
                  type: ["string", "null"],
                },
                name: {
                  type: ["string", "null"],
                },
                provider_name: {
                  type: ["string", "null"],
                },
                source: {
                  type: ["object", "null"],
                  properties: {
                    type: {
                      type: "string",
                    },
                  },
                },
                type: {
                  type: ["string", "null"],
                  enum: [
                    "AMORTIZATION_TEMPLATE",
                    "BILLABLE",
                    "COST_CENTER",
                    "CUSTOMERS_JOBS",
                    "DEFERRAL_CODE",
                    "EXPENSE_ENTITY",
                    "GL_ACCOUNT",
                    "INVENTORY_ITEM",
                    "JOURNAL",
                    "MERCHANT",
                    "NON_ERP",
                    "OTHER",
                    "PROJECT",
                    "REPORTING_TAG",
                    "SUBSIDIARY",
                    "TAX_CODE",
                    "UNIT_OF_MEASURE",
                  ],
                },
              },
              required: [
                "category_info",
                "display_name",
                "external_code",
                "external_id",
                "id",
                "name",
                "provider_name",
                "source",
                "type",
              ],
            },
          },
          amount: {
            type: ["object", "null"],
            properties: {
              amount: {
                type: "integer",
              },
              currency_code: {
                type: "string",
              },
              minor_unit_conversion_rate: {
                type: ["integer", "null"],
              },
            },
            required: ["amount", "currency_code", "minor_unit_conversion_rate"],
          },
          memo: {
            type: ["string", "null"],
          },
        },
        required: ["accounting_field_selections", "amount", "memo"],
      },
    },
    memo: {
      type: ["string", "null"],
    },
    merchant: {
      type: ["string", "null"],
    },
    merchant_amount: {
      type: ["object", "null"],
      properties: {
        currency: {
          type: "string",
          enum: [
            "AED",
            "AFN",
            "ALL",
            "AMD",
            "ANG",
            "AOA",
            "ARS",
            "AUD",
            "AWG",
            "AZN",
            "BAM",
            "BBD",
            "BDT",
            "BGN",
            "BHD",
            "BIF",
            "BMD",
            "BND",
            "BOB",
            "BOV",
            "BRL",
            "BSD",
            "BTN",
            "BWP",
            "BYN",
            "BZD",
            "CAD",
            "CDF",
            "CHE",
            "CHF",
            "CHW",
            "CLF",
            "CLP",
            "CNH",
            "CNY",
            "COP",
            "COU",
            "CRC",
            "CUC",
            "CUP",
            "CVE",
            "CZK",
            "DJF",
            "DKK",
            "DOP",
            "DZD",
            "EGP",
            "ERN",
            "ETB",
            "EUR",
            "EURC",
            "FJD",
            "FKP",
            "GBP",
            "GEL",
            "GHS",
            "GIP",
            "GMD",
            "GNF",
            "GTQ",
            "GYD",
            "HKD",
            "HNL",
            "HRK",
            "HTG",
            "HUF",
            "IDR",
            "ILS",
            "INR",
            "IQD",
            "IRR",
            "ISK",
            "JMD",
            "JOD",
            "JPY",
            "KES",
            "KGS",
            "KHR",
            "KMF",
            "KPW",
            "KRW",
            "KWD",
            "KYD",
            "KZT",
            "LAK",
            "LBP",
            "LKR",
            "LRD",
            "LSL",
            "LYD",
            "MAD",
            "MDL",
            "MGA",
            "MKD",
            "MMK",
            "MNT",
            "MOP",
            "MRU",
            "MUR",
            "MVR",
            "MWK",
            "MXN",
            "MXV",
            "MYR",
            "MZN",
            "NAD",
            "NGN",
            "NIO",
            "NOK",
            "NPR",
            "NZD",
            "OMR",
            "OPEN_USD",
            "PAB",
            "PEN",
            "PGK",
            "PHP",
            "PKR",
            "PLN",
            "PYG",
            "QAR",
            "RON",
            "RSD",
            "RUB",
            "RWF",
            "SAR",
            "SBD",
            "SCR",
            "SDG",
            "SEK",
            "SGD",
            "SHP",
            "SLE",
            "SLL",
            "SOS",
            "SRD",
            "SSP",
            "STN",
            "SVC",
            "SYP",
            "SZL",
            "THB",
            "TJS",
            "TMT",
            "TND",
            "TOP",
            "TRY",
            "TTD",
            "TWD",
            "TZS",
            "UAH",
            "UGX",
            "USD",
            "USDB",
            "USDC",
            "USDSUI",
            "USDT",
            "USN",
            "UYI",
            "UYU",
            "UYW",
            "UZS",
            "VED",
            "VES",
            "VND",
            "VUV",
            "WST",
            "XAD",
            "XAF",
            "XAG",
            "XAU",
            "XBA",
            "XBB",
            "XBC",
            "XBD",
            "XCD",
            "XCG",
            "XDR",
            "XOF",
            "XPD",
            "XPF",
            "XPT",
            "XSU",
            "XTS",
            "XUA",
            "XXX",
            "YER",
            "ZAR",
            "ZMW",
            "ZWG",
            "ZWL",
          ],
        },
        value: {
          type: "integer",
        },
      },
      required: ["currency", "value"],
    },
    merchant_id: {
      type: ["string", "null"],
      format: "uuid",
    },
    payee_amount: {
      type: ["object", "null"],
      properties: {
        amount: {
          type: "integer",
        },
        currency_code: {
          type: "string",
        },
        minor_unit_conversion_rate: {
          type: ["integer", "null"],
        },
      },
      required: ["amount", "currency_code", "minor_unit_conversion_rate"],
    },
    payment_batch_id: {
      type: ["string", "null"],
      format: "uuid",
    },
    payment_id: {
      type: ["string", "null"],
    },
    payment_processed_at: {
      type: ["string", "null"],
      format: "date-time",
    },
    receipts: {
      type: "array",
      items: {
        type: "string",
        format: "uuid",
      },
    },
    spend_limit_id: {
      type: ["string", "null"],
      format: "uuid",
    },
    start_location: {
      type: ["string", "null"],
    },
    state: {
      type: "string",
      enum: [
        "APPROVED",
        "AWAITING_EXPORT",
        "AWAITING_PAYMENT",
        "AWAITING_PUSH_PAYMENT",
        "CANCELED",
        "DELETED",
        "DRAFT",
        "EXPORTED",
        "EXPORT_FAILED",
        "EXPORT_INITIATED",
        "EXPORT_MARKED_AS_FAILED",
        "EXPORT_SUCCESSFUL",
        "FAILED_REIMBURSEMENT",
        "INIT",
        "MANUALLY_REIMBURSED",
        "MISSING_ACH",
        "PENDING",
        "PROCESSING",
        "PUSH_PAYMENT_FAILED",
        "PUSH_PAYMENT_INITIATED",
        "REIMBURSED",
        "REIMBURSED_VIA_PUSH",
        "REJECTED",
      ],
    },
    submitted_at: {
      type: ["string", "null"],
      format: "date-time",
    },
    sync_status: {
      type: "string",
      enum: ["NOT_SYNC_READY", "SYNCED", "SYNC_READY"],
    },
    synced_at: {
      type: ["string", "null"],
      format: "date-time",
    },
    trace_id: {
      type: "object",
      properties: {
        descriptor: {
          type: ["string", "null"],
        },
        trace_id: {
          type: ["string", "null"],
        },
      },
      required: ["descriptor", "trace_id"],
    },
    transaction_date: {
      type: ["string", "null"],
      format: "date",
    },
    trip_id: {
      type: ["string", "null"],
      format: "uuid",
    },
    type: {
      type: "string",
      enum: [
        "MILEAGE",
        "OUT_OF_POCKET",
        "PAYBACK_FULL",
        "PAYBACK_PARTIAL",
        "PER_DIEM",
      ],
    },
    updated_at: {
      type: ["string", "null"],
      format: "date-time",
    },
    user_email: {
      type: "string",
    },
    user_full_name: {
      type: "string",
    },
    user_id: {
      type: "string",
      format: "uuid",
    },
    waypoints: {
      type: "array",
      items: {
        type: "string",
      },
    },
  },
  required: [
    "accounting_date",
    "accounting_field_selections",
    "approved_at",
    "attendees",
    "created_at",
    "direction",
    "distance",
    "employee_id",
    "end_location",
    "entity_amount",
    "entity_id",
    "fund_id",
    "id",
    "line_items",
    "memo",
    "merchant",
    "merchant_amount",
    "merchant_id",
    "payee_amount",
    "payment_batch_id",
    "payment_id",
    "payment_processed_at",
    "receipts",
    "spend_limit_id",
    "start_location",
    "state",
    "submitted_at",
    "sync_status",
    "synced_at",
    "transaction_date",
    "trip_id",
    "type",
    "updated_at",
    "user_email",
    "user_full_name",
    "user_id",
    "waypoints",
  ],
};
export const getReimbursementOutputSchema = reimbursementSchema;
export const listReimbursementsOutputSchema = {
  type: "object" as const,
  properties: {
    data: {
      type: "array",
      items: reimbursementSchema,
    },
    page: pageSchema,
  },
  required: ["data", "page"],
};
