import { pageSchema } from "./shared";
const transactionSchema = {
  type: "object" as const,
  properties: {
    accounting_categories: {
      type: "array",
      items: {
        type: "object",
        properties: {
          category_id: {
            type: "string",
          },
          category_name: {
            type: "string",
          },
          tracking_category_remote_id: {
            type: "string",
          },
          tracking_category_remote_name: {
            type: "string",
          },
          tracking_category_remote_type: {
            type: "string",
          },
        },
      },
    },
    accounting_date: {
      type: ["string", "null"],
      format: "date-time",
    },
    accounting_field_selections: {
      type: "array",
      items: {
        type: "object",
        properties: {
          category_info: {
            type: "object",
            properties: {
              external_id: {
                type: "string",
              },
              id: {
                type: "string",
                format: "uuid",
              },
              name: {
                type: "string",
              },
              type: {
                type: "string",
                enum: [
                  "AMORTIZATION_TEMPLATE",
                  "BILLABLE",
                  "COST_CENTER",
                  "CUSTOMERS_JOBS",
                  "DEFERRAL_CODE",
                  "EXPENSE_ENTITY",
                  "GL_ACCOUNT",
                  "INVENTORY_ITEM",
                  "JOURNAL",
                  "MERCHANT",
                  "NON_ERP",
                  "OTHER",
                  "PROJECT",
                  "REPORTING_TAG",
                  "SUBSIDIARY",
                  "TAX_CODE",
                  "UNIT_OF_MEASURE",
                ],
              },
            },
          },
          display_name: {
            type: ["string", "null"],
          },
          external_code: {
            type: "string",
          },
          external_id: {
            type: "string",
          },
          id: {
            type: "string",
            format: "uuid",
          },
          name: {
            type: "string",
          },
          provider_name: {
            type: "string",
          },
          source: {
            type: "object",
            properties: {
              type: {
                type: "string",
              },
            },
          },
          type: {
            type: "string",
            enum: [
              "AMORTIZATION_TEMPLATE",
              "BILLABLE",
              "COST_CENTER",
              "CUSTOMERS_JOBS",
              "DEFERRAL_CODE",
              "EXPENSE_ENTITY",
              "GL_ACCOUNT",
              "INVENTORY_ITEM",
              "JOURNAL",
              "MERCHANT",
              "NON_ERP",
              "OTHER",
              "PROJECT",
              "REPORTING_TAG",
              "SUBSIDIARY",
              "TAX_CODE",
              "UNIT_OF_MEASURE",
            ],
          },
        },
        required: ["display_name", "provider_name"],
      },
    },
    all_requirements_met_and_approved: {
      type: "boolean",
    },
    amount: {
      type: "number",
    },
    attendees: {
      type: "array",
      items: {
        type: "object",
        properties: {
          name: {
            type: "string",
          },
          user_id: {
            type: ["string", "null"],
            format: "uuid",
          },
        },
        required: ["name", "user_id"],
      },
    },
    card_holder: {
      type: "object",
      properties: {
        department_id: {
          type: "string",
          format: "uuid",
        },
        department_name: {
          type: "string",
        },
        employee_id: {
          type: "string",
        },
        first_name: {
          type: "string",
        },
        last_name: {
          type: "string",
        },
        location_id: {
          type: "string",
          format: "uuid",
        },
        location_name: {
          type: "string",
        },
        user_id: {
          type: "string",
          format: "uuid",
        },
      },
    },
    card_id: {
      type: "string",
      format: "uuid",
    },
    card_present: {
      type: "boolean",
    },
    currency_code: {
      type: "string",
    },
    decline_details: {
      type: "object",
      properties: {
        amount: {
          type: "number",
        },
        declined_amount: {
          type: ["object", "null"],
          properties: {
            currency: {
              type: "string",
              enum: [
                "AED",
                "AFN",
                "ALL",
                "AMD",
                "ANG",
                "AOA",
                "ARS",
                "AUD",
                "AWG",
                "AZN",
                "BAM",
                "BBD",
                "BDT",
                "BGN",
                "BHD",
                "BIF",
                "BMD",
                "BND",
                "BOB",
                "BOV",
                "BRL",
                "BSD",
                "BTN",
                "BWP",
                "BYN",
                "BZD",
                "CAD",
                "CDF",
                "CHE",
                "CHF",
                "CHW",
                "CLF",
                "CLP",
                "CNH",
                "CNY",
                "COP",
                "COU",
                "CRC",
                "CUC",
                "CUP",
                "CVE",
                "CZK",
                "DJF",
                "DKK",
                "DOP",
                "DZD",
                "EGP",
                "ERN",
                "ETB",
                "EUR",
                "EURC",
                "FJD",
                "FKP",
                "GBP",
                "GEL",
                "GHS",
                "GIP",
                "GMD",
                "GNF",
                "GTQ",
                "GYD",
                "HKD",
                "HNL",
                "HRK",
                "HTG",
                "HUF",
                "IDR",
                "ILS",
                "INR",
                "IQD",
                "IRR",
                "ISK",
                "JMD",
                "JOD",
                "JPY",
                "KES",
                "KGS",
                "KHR",
                "KMF",
                "KPW",
                "KRW",
                "KWD",
                "KYD",
                "KZT",
                "LAK",
                "LBP",
                "LKR",
                "LRD",
                "LSL",
                "LYD",
                "MAD",
                "MDL",
                "MGA",
                "MKD",
                "MMK",
                "MNT",
                "MOP",
                "MRU",
                "MUR",
                "MVR",
                "MWK",
                "MXN",
                "MXV",
                "MYR",
                "MZN",
                "NAD",
                "NGN",
                "NIO",
                "NOK",
                "NPR",
                "NZD",
                "OMR",
                "OPEN_USD",
                "PAB",
                "PEN",
                "PGK",
                "PHP",
                "PKR",
                "PLN",
                "PYG",
                "QAR",
                "RON",
                "RSD",
                "RUB",
                "RWF",
                "SAR",
                "SBD",
                "SCR",
                "SDG",
                "SEK",
                "SGD",
                "SHP",
                "SLE",
                "SLL",
                "SOS",
                "SRD",
                "SSP",
                "STN",
                "SVC",
                "SYP",
                "SZL",
                "THB",
                "TJS",
                "TMT",
                "TND",
                "TOP",
                "TRY",
                "TTD",
                "TWD",
                "TZS",
                "UAH",
                "UGX",
                "USD",
                "USDB",
                "USDC",
                "USDSUI",
                "USDT",
                "USN",
                "UYI",
                "UYU",
                "UYW",
                "UZS",
                "VED",
                "VES",
                "VND",
                "VUV",
                "WST",
                "XAD",
                "XAF",
                "XAG",
                "XAU",
                "XBA",
                "XBB",
                "XBC",
                "XBD",
                "XCD",
                "XCG",
                "XDR",
                "XOF",
                "XPD",
                "XPF",
                "XPT",
                "XSU",
                "XTS",
                "XUA",
                "XXX",
                "YER",
                "ZAR",
                "ZMW",
                "ZWG",
                "ZWL",
              ],
            },
            value: {
              type: "integer",
            },
          },
          required: ["currency", "value"],
        },
        reason: {
          type: "string",
          enum: [
            "AUTHORIZER",
            "AUTHORIZER_AP_CARD_VELOCITY_LIMIT",
            "AUTHORIZER_BUSINESS_LIMIT",
            "AUTHORIZER_BUSINESS_SUSPENDED",
            "AUTHORIZER_BUSINESS_VENDOR_BLACKLIST",
            "AUTHORIZER_CARD_AUTO_LOCK_DATE",
            "AUTHORIZER_CARD_CATEGORY_BLACKLIST",
            "AUTHORIZER_CARD_CATEGORY_WHITELIST",
            "AUTHORIZER_CARD_LIMIT",
            "AUTHORIZER_CARD_MCC_BLACKLIST",
            "AUTHORIZER_CARD_MISSING_POLICY_ITEMS",
            "AUTHORIZER_CARD_NOT_ACTIVATED",
            "AUTHORIZER_CARD_PARTIALLY_ACTIVATED",
            "AUTHORIZER_CARD_START_DATE",
            "AUTHORIZER_CARD_SUSPENDED",
            "AUTHORIZER_CARD_TASK_SANCTION",
            "AUTHORIZER_CARD_TOTAL_ACTIVATION_REQUIRED",
            "AUTHORIZER_CARD_VENDOR_BLACKLIST",
            "AUTHORIZER_CARD_VENDOR_WHITELIST",
            "AUTHORIZER_COMMANDO_MODE",
            "AUTHORIZER_FRAUD",
            "AUTHORIZER_FREEZE_TRANSACTIONS_RISK",
            "AUTHORIZER_GLOBAL_MCC_BLACKLIST",
            "AUTHORIZER_MEMBER_LIMIT",
            "AUTHORIZER_NON_AP_CARD_VELOCITY_LIMIT",
            "AUTHORIZER_OOB_BLOCKED_MERCHANT",
            "AUTHORIZER_OOB_DAILY_BUSINESS_BALANCE",
            "AUTHORIZER_OOB_DAILY_CARD_SPEND",
            "AUTHORIZER_RAMP_AUTHORIZATION_METHODS",
            "AUTHORIZER_RAMP_TRANSACTION_AMOUNT_LIMIT",
            "AUTHORIZER_RAMP_VENDOR_RESTRICTIONS",
            "AUTHORIZER_SPEND_ALLOCATION_ARCHIVED_FUNDS",
            "AUTHORIZER_SPEND_ALLOCATION_MEMBER_SUSPENDED",
            "AUTHORIZER_SPEND_ALLOCATION_SUSPENDED",
            "AUTHORIZER_TRANSACTION_AMOUNT_LIMIT",
            "AUTHORIZER_UNAUTHORIZED_USER",
            "AUTHORIZER_UNDER_TRANSACTION_AMOUNT_LIMIT",
            "AUTHORIZER_USER_LIMIT",
            "AUTHORIZER_USER_SUSPENDED",
            "BLOCKED_COUNTRY",
            "CARD_EXPIRED",
            "CARD_LOST_OR_STOLEN",
            "CARD_TERMINATED",
            "CHIP_FAILURE",
            "FORBIDDEN_CATEGORY",
            "INSECURE_AUTHORIZATION_METHOD",
            "INSUFFICIENT_FUNDS",
            "INVALID_PIN",
            "MISSING_CVV",
            "MISSING_EXPIRATION",
            "MOBILE_WALLET_FAILURE",
            "MOBILE_WALLET_TOKEN_NOT_FOUND",
            "MOBILE_WALLET_TOKEN_TERMINATED",
            "NETWORK_DECLINE_ACCOUNT_VERIFICATION",
            "NETWORK_DECLINE_ADVICE",
            "NETWORK_DECLINE_ADVICE_ACQUIRER_ISSUE",
            "NETWORK_DECLINE_ADVICE_ADDITIONAL_AUTHENTICATION_REQUIRED",
            "NETWORK_DECLINE_ADVICE_FORCED_STIP_BY_ISSUER",
            "NETWORK_DECLINE_ADVICE_ISSUER_LOGGED_OFF",
            "NETWORK_DECLINE_ADVICE_ISSUER_TIMEOUT",
            "NETWORK_DECLINE_ADVICE_ISSUER_UNAVAILABLE",
            "NETWORK_DECLINE_ADVICE_PIN_ERROR",
            "NETWORK_DECLINE_ADVICE_RECURRING_PAYMENT",
            "NETWORK_DECLINE_ADVICE_SELECTIVE_ACCEPTANCE_SERVICE",
            "NETWORK_DECLINE_ADVICE_SUSPECTED_FRAUD_TRANSACTION",
            "NETWORK_DECLINE_ADVICE_TOKEN_PROVISIONING_SERVICE",
            "NETWORK_DECLINE_ADVICE_VISA_PAYMENT_CONTROLS_RULE",
            "NOT_ACTIVE",
            "NOT_ALLOWED",
            "NO_AUTO_ROUTED_LIMITS_AVAILABLE",
            "NO_LINKED_SPEND_ALLOCATION",
            "OFAC_VERIFICATION_NEEDED",
            "OPEN_TO_BUY_LIMIT",
            "OTHER",
            "PIN_BLOCKED",
            "PIN_TRY_LIMIT_EXCEEDED",
            "PROCESSOR_CAP",
            "QUASI_CASH",
            "ROUTED_TO_TERMINATED_SPEND_ALLOCATION",
            "STRIPE_WEBHOOK_TIMEOUT",
            "SUSPECTED_BIN_ATTACK",
            "SUSPECTED_FRAUD",
            "THREE_D_SECURE_REQUIRED",
            "USER_BLOCKED",
            "USER_TERMINATED",
            "WRONG_ADDRESS",
            "WRONG_CVV",
            "WRONG_EXPIRATION",
            "WRONG_POSTAL_CODE",
          ],
        },
      },
      required: ["declined_amount"],
    },
    disputes: {
      type: "array",
      items: {
        type: "object",
        properties: {
          created_at: {
            type: "string",
            format: "date-time",
          },
          id: {
            type: "string",
            format: "uuid",
          },
          memo: {
            type: "string",
          },
          type: {
            type: "string",
          },
        },
      },
    },
    entity_amount: {
      type: ["object", "null"],
      properties: {
        currency: {
          type: "string",
          enum: [
            "AED",
            "AFN",
            "ALL",
            "AMD",
            "ANG",
            "AOA",
            "ARS",
            "AUD",
            "AWG",
            "AZN",
            "BAM",
            "BBD",
            "BDT",
            "BGN",
            "BHD",
            "BIF",
            "BMD",
            "BND",
            "BOB",
            "BOV",
            "BRL",
            "BSD",
            "BTN",
            "BWP",
            "BYN",
            "BZD",
            "CAD",
            "CDF",
            "CHE",
            "CHF",
            "CHW",
            "CLF",
            "CLP",
            "CNH",
            "CNY",
            "COP",
            "COU",
            "CRC",
            "CUC",
            "CUP",
            "CVE",
            "CZK",
            "DJF",
            "DKK",
            "DOP",
            "DZD",
            "EGP",
            "ERN",
            "ETB",
            "EUR",
            "EURC",
            "FJD",
            "FKP",
            "GBP",
            "GEL",
            "GHS",
            "GIP",
            "GMD",
            "GNF",
            "GTQ",
            "GYD",
            "HKD",
            "HNL",
            "HRK",
            "HTG",
            "HUF",
            "IDR",
            "ILS",
            "INR",
            "IQD",
            "IRR",
            "ISK",
            "JMD",
            "JOD",
            "JPY",
            "KES",
            "KGS",
            "KHR",
            "KMF",
            "KPW",
            "KRW",
            "KWD",
            "KYD",
            "KZT",
            "LAK",
            "LBP",
            "LKR",
            "LRD",
            "LSL",
            "LYD",
            "MAD",
            "MDL",
            "MGA",
            "MKD",
            "MMK",
            "MNT",
            "MOP",
            "MRU",
            "MUR",
            "MVR",
            "MWK",
            "MXN",
            "MXV",
            "MYR",
            "MZN",
            "NAD",
            "NGN",
            "NIO",
            "NOK",
            "NPR",
            "NZD",
            "OMR",
            "OPEN_USD",
            "PAB",
            "PEN",
            "PGK",
            "PHP",
            "PKR",
            "PLN",
            "PYG",
            "QAR",
            "RON",
            "RSD",
            "RUB",
            "RWF",
            "SAR",
            "SBD",
            "SCR",
            "SDG",
            "SEK",
            "SGD",
            "SHP",
            "SLE",
            "SLL",
            "SOS",
            "SRD",
            "SSP",
            "STN",
            "SVC",
            "SYP",
            "SZL",
            "THB",
            "TJS",
            "TMT",
            "TND",
            "TOP",
            "TRY",
            "TTD",
            "TWD",
            "TZS",
            "UAH",
            "UGX",
            "USD",
            "USDB",
            "USDC",
            "USDSUI",
            "USDT",
            "USN",
            "UYI",
            "UYU",
            "UYW",
            "UZS",
            "VED",
            "VES",
            "VND",
            "VUV",
            "WST",
            "XAD",
            "XAF",
            "XAG",
            "XAU",
            "XBA",
            "XBB",
            "XBC",
            "XBD",
            "XCD",
            "XCG",
            "XDR",
            "XOF",
            "XPD",
            "XPF",
            "XPT",
            "XSU",
            "XTS",
            "XUA",
            "XXX",
            "YER",
            "ZAR",
            "ZMW",
            "ZWG",
            "ZWL",
          ],
        },
        value: {
          type: "integer",
        },
      },
      required: ["currency", "value"],
    },
    entity_id: {
      type: ["string", "null"],
      format: "uuid",
    },
    fund_id: {
      type: "string",
      format: "uuid",
    },
    id: {
      type: "string",
      format: "uuid",
    },
    limit_id: {
      type: "string",
      format: "uuid",
    },
    line_items: {
      type: "array",
      items: {
        type: "object",
        properties: {
          accounting_field_selections: {
            type: "array",
            items: {
              type: "object",
              properties: {
                category_info: {
                  type: "object",
                  properties: {
                    external_id: {
                      type: "string",
                    },
                    id: {
                      type: "string",
                      format: "uuid",
                    },
                    name: {
                      type: "string",
                    },
                    type: {
                      type: "string",
                      enum: [
                        "AMORTIZATION_TEMPLATE",
                        "BILLABLE",
                        "COST_CENTER",
                        "CUSTOMERS_JOBS",
                        "DEFERRAL_CODE",
                        "EXPENSE_ENTITY",
                        "GL_ACCOUNT",
                        "INVENTORY_ITEM",
                        "JOURNAL",
                        "MERCHANT",
                        "NON_ERP",
                        "OTHER",
                        "PROJECT",
                        "REPORTING_TAG",
                        "SUBSIDIARY",
                        "TAX_CODE",
                        "UNIT_OF_MEASURE",
                      ],
                    },
                  },
                },
                display_name: {
                  type: ["string", "null"],
                },
                external_code: {
                  type: "string",
                },
                external_id: {
                  type: "string",
                },
                id: {
                  type: "string",
                  format: "uuid",
                },
                name: {
                  type: "string",
                },
                provider_name: {
                  type: "string",
                },
                source: {
                  type: "object",
                  properties: {
                    type: {
                      type: "string",
                    },
                  },
                },
                type: {
                  type: "string",
                  enum: [
                    "AMORTIZATION_TEMPLATE",
                    "BILLABLE",
                    "COST_CENTER",
                    "CUSTOMERS_JOBS",
                    "DEFERRAL_CODE",
                    "EXPENSE_ENTITY",
                    "GL_ACCOUNT",
                    "INVENTORY_ITEM",
                    "JOURNAL",
                    "MERCHANT",
                    "NON_ERP",
                    "OTHER",
                    "PROJECT",
                    "REPORTING_TAG",
                    "SUBSIDIARY",
                    "TAX_CODE",
                    "UNIT_OF_MEASURE",
                  ],
                },
              },
              required: ["display_name", "provider_name"],
            },
          },
          amount: {
            type: ["object", "null"],
            properties: {
              amount: {
                type: "integer",
              },
              currency_code: {
                type: "string",
              },
              minor_unit_conversion_rate: {
                type: ["integer", "null"],
              },
            },
            required: ["amount", "currency_code", "minor_unit_conversion_rate"],
          },
          converted_amount: {
            type: ["object", "null"],
            properties: {
              amount: {
                type: "integer",
              },
              currency_code: {
                type: "string",
              },
              minor_unit_conversion_rate: {
                type: ["integer", "null"],
              },
            },
            required: ["amount", "currency_code", "minor_unit_conversion_rate"],
          },
          memo: {
            type: "string",
          },
        },
        required: ["amount", "converted_amount"],
      },
    },
    memo: {
      type: ["string", "null"],
    },
    merchant_amount: {
      type: ["object", "null"],
      properties: {
        currency: {
          type: "string",
          enum: [
            "AED",
            "AFN",
            "ALL",
            "AMD",
            "ANG",
            "AOA",
            "ARS",
            "AUD",
            "AWG",
            "AZN",
            "BAM",
            "BBD",
            "BDT",
            "BGN",
            "BHD",
            "BIF",
            "BMD",
            "BND",
            "BOB",
            "BOV",
            "BRL",
            "BSD",
            "BTN",
            "BWP",
            "BYN",
            "BZD",
            "CAD",
            "CDF",
            "CHE",
            "CHF",
            "CHW",
            "CLF",
            "CLP",
            "CNH",
            "CNY",
            "COP",
            "COU",
            "CRC",
            "CUC",
            "CUP",
            "CVE",
            "CZK",
            "DJF",
            "DKK",
            "DOP",
            "DZD",
            "EGP",
            "ERN",
            "ETB",
            "EUR",
            "EURC",
            "FJD",
            "FKP",
            "GBP",
            "GEL",
            "GHS",
            "GIP",
            "GMD",
            "GNF",
            "GTQ",
            "GYD",
            "HKD",
            "HNL",
            "HRK",
            "HTG",
            "HUF",
            "IDR",
            "ILS",
            "INR",
            "IQD",
            "IRR",
            "ISK",
            "JMD",
            "JOD",
            "JPY",
            "KES",
            "KGS",
            "KHR",
            "KMF",
            "KPW",
            "KRW",
            "KWD",
            "KYD",
            "KZT",
            "LAK",
            "LBP",
            "LKR",
            "LRD",
            "LSL",
            "LYD",
            "MAD",
            "MDL",
            "MGA",
            "MKD",
            "MMK",
            "MNT",
            "MOP",
            "MRU",
            "MUR",
            "MVR",
            "MWK",
            "MXN",
            "MXV",
            "MYR",
            "MZN",
            "NAD",
            "NGN",
            "NIO",
            "NOK",
            "NPR",
            "NZD",
            "OMR",
            "OPEN_USD",
            "PAB",
            "PEN",
            "PGK",
            "PHP",
            "PKR",
            "PLN",
            "PYG",
            "QAR",
            "RON",
            "RSD",
            "RUB",
            "RWF",
            "SAR",
            "SBD",
            "SCR",
            "SDG",
            "SEK",
            "SGD",
            "SHP",
            "SLE",
            "SLL",
            "SOS",
            "SRD",
            "SSP",
            "STN",
            "SVC",
            "SYP",
            "SZL",
            "THB",
            "TJS",
            "TMT",
            "TND",
            "TOP",
            "TRY",
            "TTD",
            "TWD",
            "TZS",
            "UAH",
            "UGX",
            "USD",
            "USDB",
            "USDC",
            "USDSUI",
            "USDT",
            "USN",
            "UYI",
            "UYU",
            "UYW",
            "UZS",
            "VED",
            "VES",
            "VND",
            "VUV",
            "WST",
            "XAD",
            "XAF",
            "XAG",
            "XAU",
            "XBA",
            "XBB",
            "XBC",
            "XBD",
            "XCD",
            "XCG",
            "XDR",
            "XOF",
            "XPD",
            "XPF",
            "XPT",
            "XSU",
            "XTS",
            "XUA",
            "XXX",
            "YER",
            "ZAR",
            "ZMW",
            "ZWG",
            "ZWL",
          ],
        },
        value: {
          type: "integer",
        },
      },
      required: ["currency", "value"],
    },
    merchant_category_code: {
      type: "string",
    },
    merchant_category_code_description: {
      type: "string",
    },
    merchant_data: {
      type: "object",
      properties: {
        auto_rental: {
          type: ["object", "null"],
          properties: {
            check_out: {
              type: "string",
            },
            days: {
              type: "integer",
            },
          },
        },
        flight: {
          type: ["object", "null"],
          properties: {
            departure_date: {
              type: ["string", "null"],
            },
            passenger_name: {
              type: "string",
            },
            segments: {
              type: ["array", "null"],
              items: {
                type: "object",
                properties: {
                  arrival_airport_code: {
                    type: "string",
                  },
                  carrier: {
                    type: "string",
                  },
                  departure_airport_code: {
                    type: "string",
                  },
                  flight_number: {
                    type: "string",
                  },
                  service_class: {
                    type: "string",
                  },
                  stopover_allowed: {
                    type: "boolean",
                  },
                },
              },
            },
          },
          required: ["departure_date", "segments"],
        },
        lodging: {
          type: ["object", "null"],
          properties: {
            check_in: {
              type: "string",
            },
            nights: {
              type: ["integer", "null"],
            },
          },
          required: ["nights"],
        },
        receipt: {
          type: ["object", "null"],
          properties: {
            items: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  commodity_code: {
                    type: ["string", "null"],
                  },
                  description: {
                    type: "string",
                  },
                  discount: {
                    type: ["number", "null"],
                  },
                  quantity: {
                    type: "number",
                  },
                  tax: {
                    type: ["number", "null"],
                  },
                  total: {
                    type: "number",
                  },
                  unit_cost: {
                    type: "number",
                  },
                },
                required: ["commodity_code", "discount", "tax"],
              },
            },
          },
        },
        reference: {
          type: ["string", "null"],
        },
      },
      required: ["auto_rental", "flight", "lodging", "receipt", "reference"],
    },
    merchant_descriptor: {
      type: "string",
    },
    merchant_id: {
      type: ["string", "null"],
      format: "uuid",
    },
    merchant_location: {
      type: ["object", "null"],
      properties: {
        city: {
          type: ["string", "null"],
        },
        country: {
          type: ["string", "null"],
        },
        postal_code: {
          type: ["string", "null"],
        },
        state: {
          type: ["string", "null"],
        },
      },
      required: ["city", "country", "postal_code", "state"],
    },
    merchant_name: {
      type: ["string", "null"],
    },
    minor_unit_conversion_rate: {
      type: ["integer", "null"],
    },
    network_merchant_id: {
      type: ["string", "null"],
    },
    original_transaction_amount: {
      type: ["object", "null"],
      properties: {
        amount: {
          type: "integer",
        },
        currency_code: {
          type: "string",
        },
        minor_unit_conversion_rate: {
          type: ["integer", "null"],
        },
      },
      required: ["amount", "currency_code", "minor_unit_conversion_rate"],
    },
    original_transaction_id: {
      type: ["string", "null"],
    },
    policy_violations: {
      type: "array",
      items: {
        type: "object",
        properties: {
          created_at: {
            type: "string",
            format: "date-time",
          },
          id: {
            type: "string",
            format: "uuid",
          },
          memo: {
            type: "string",
          },
          type: {
            type: "string",
          },
        },
      },
    },
    receipts: {
      type: "array",
      items: {
        type: "string",
        format: "uuid",
      },
    },
    requires_accounting_vendor_creation_to_sync: {
      type: "boolean",
    },
    settlement_date: {
      type: "string",
      format: "date-time",
    },
    sk_category_id: {
      type: ["integer", "null"],
      enum: [
        1, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 2, 20, 21, 23, 24, 25, 26,
        27, 28, 29, 3, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 4, 40, 41, 42,
        43, 44, 5, 6, 7, 8, 9,
      ],
    },
    sk_category_name: {
      type: ["string", "null"],
    },
    spend_program_id: {
      type: "string",
      format: "uuid",
    },
    state: {
      type: "string",
      enum: [
        "ALL",
        "CLEARED",
        "COMPLETION",
        "DECLINED",
        "ERROR",
        "PENDING",
        "PENDING_INITIATION",
      ],
    },
    statement_id: {
      type: "string",
      format: "uuid",
    },
    sync_status: {
      type: "string",
      enum: ["NOT_SYNC_READY", "SYNCED", "SYNC_READY"],
    },
    synced_at: {
      type: ["string", "null"],
      format: "date-time",
    },
    trip_id: {
      type: ["string", "null"],
      format: "uuid",
    },
    trip_name: {
      type: ["string", "null"],
    },
    updated_at: {
      type: ["string", "null"],
      format: "date-time",
    },
    user_transaction_time: {
      type: "string",
      format: "date-time",
    },
  },
  required: [
    "accounting_date",
    "all_requirements_met_and_approved",
    "card_present",
    "entity_amount",
    "entity_id",
    "merchant_amount",
    "merchant_id",
    "merchant_location",
    "minor_unit_conversion_rate",
    "network_merchant_id",
    "original_transaction_amount",
    "original_transaction_id",
    "sk_category_id",
    "sk_category_name",
    "sync_status",
    "synced_at",
    "trip_id",
    "trip_name",
    "updated_at",
  ],
};
export const getTransactionOutputSchema = {
  type: "object" as const,
  properties: {
    ...transactionSchema.properties,
    receipt_affidavit: {
      type: ["string", "null"],
    },
  },
  required: transactionSchema.required,
};
export const listTransactionsOutputSchema = {
  type: "object" as const,
  properties: {
    data: {
      type: "array",
      items: transactionSchema,
    },
    page: pageSchema,
  },
  required: ["data", "page"],
};
