import { action, type Connection, util } from "@prismatic-io/spectral";
import { createClient } from "../client";

const enterpriseAdminListProvisionedGroupsEnterprise = action({
  display: {
    label: "Enterprise Admin List Provisioned Groups Enterprise",
    description: "List provisioned SCIM groups for an enterprise",
  },
  perform: async (
    context,
    { connection, enterprise, startIndex, count, filter, excludedAttributes },
  ) => {
    const client = createClient(connection as Connection, context.debug.enabled);
    const { data } = await client.get(
      `/scim/v2/enterprises/${enterprise}/Groups`,
      {
        params: { startIndex, count, filter, excludedAttributes },
      },
    );
    return { data };
  },
  inputs: {
    connection: {
      label: "Connection",
      type: "connection",
      required: true,
    },
    enterprise: {
      label: "Enterprise",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "The slug version of the enterprise name",
    },
    startIndex: {
      label: "Start Index",
      type: "string",
      required: false,
      clean: (value) => util.types.toNumber(value) || undefined,
      comments: "Used for pagination: the index of the first result to return",
    },
    count: {
      label: "Count",
      type: "string",
      required: false,
      clean: (value) => util.types.toNumber(value) || undefined,
      comments: "Used for pagination: the number of results to return",
    },
    filter: {
      label: "Filter",
      type: "string",
      required: false,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "filter results",
    },
    excludedAttributes: {
      label: "Excluded Attributes",
      type: "string",
      required: false,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "attributes to exclude",
    },
  },
});

const enterpriseAdminProvisionAndInviteEnterpriseGroup = action({
  display: {
    label: "Enterprise Admin Provision And Invite Enterprise Group",
    description: "Provision a SCIM enterprise group and invite users",
  },
  perform: async (
    context,
    { connection, enterprise, schemas, displayName, members },
  ) => {
    const client = createClient(connection as Connection, context.debug.enabled);
    const { data } = await client.post(
      `/scim/v2/enterprises/${enterprise}/Groups`,
      {
        schemas,
        displayName,
        members,
      },
    );
    return { data };
  },
  inputs: {
    connection: {
      label: "Connection",
      type: "connection",
      required: true,
    },
    enterprise: {
      label: "Enterprise",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "The slug version of the enterprise name",
    },
    schemas: {
      label: "Schemas",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "The SCIM schema URIs",
    },
    displayName: {
      label: "Display Name",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "The name of the SCIM group",
    },
    members: {
      label: "Members",
      type: "string",
      required: false,
      clean: (value) => util.types.toString(value) || undefined,
    },
  },
});

const enterpriseAdminGetProvisioningInformationForEnterpriseGroup = action({
  display: {
    label: "Enterprise Admin Get Provisioning Information For Enterprise Group",
    description: "Get SCIM provisioning information for an enterprise group",
  },
  perform: async (
    context,
    { connection, enterprise, scimGroupId, excludedAttributes },
  ) => {
    const client = createClient(connection as Connection, context.debug.enabled);
    const { data } = await client.get(
      `/scim/v2/enterprises/${enterprise}/Groups/${scimGroupId}`,
      { params: { excludedAttributes } },
    );
    return { data };
  },
  inputs: {
    connection: {
      label: "Connection",
      type: "connection",
      required: true,
    },
    enterprise: {
      label: "Enterprise",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "The slug version of the enterprise name",
    },
    scimGroupId: {
      label: "Scim Group Id",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "Identifier generated by the GitHub SCIM endpoint",
    },
    excludedAttributes: {
      label: "Excluded Attributes",
      type: "string",
      required: false,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "Attributes to exclude",
    },
  },
});

const enterpriseAdminSetInformationForProvisionedEnterpriseGroup = action({
  display: {
    label: "Enterprise Admin Set Information For Provisioned Enterprise Group",
    description: "Set SCIM information for a provisioned enterprise group",
  },
  perform: async (
    context,
    { connection, enterprise, scimGroupId, schemas, displayName, members },
  ) => {
    const client = createClient(connection as Connection, context.debug.enabled);
    const { data } = await client.put(
      `/scim/v2/enterprises/${enterprise}/Groups/${scimGroupId}`,
      { schemas, displayName, members },
    );
    return { data };
  },
  inputs: {
    connection: {
      label: "Connection",
      type: "connection",
      required: true,
    },
    enterprise: {
      label: "Enterprise",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "The slug version of the enterprise name",
    },
    scimGroupId: {
      label: "Scim Group Id",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "Identifier generated by the GitHub SCIM endpoint",
    },
    schemas: {
      label: "Schemas",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "The SCIM schema URIs",
    },
    displayName: {
      label: "Display Name",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "The name of the SCIM group",
    },
    members: {
      label: "Members",
      type: "string",
      required: false,
      clean: (value) => util.types.toString(value) || undefined,
    },
  },
});

const enterpriseAdminUpdateAttributeForEnterpriseGroup = action({
  display: {
    label: "Enterprise Admin Update Attribute For Enterprise Group",
    description: "Update an attribute for a SCIM enterprise group",
  },
  perform: async (
    context,
    { connection, enterprise, scimGroupId, schemas, operations },
  ) => {
    const client = createClient(connection as Connection, context.debug.enabled);
    const { data } = await client.patch(
      `/scim/v2/enterprises/${enterprise}/Groups/${scimGroupId}`,
      { schemas, Operations: operations },
    );
    return { data };
  },
  inputs: {
    connection: {
      label: "Connection",
      type: "connection",
      required: true,
    },
    enterprise: {
      label: "Enterprise",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "The slug version of the enterprise name",
    },
    scimGroupId: {
      label: "Scim Group Id",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "Identifier generated by the GitHub SCIM endpoint",
    },
    schemas: {
      label: "Schemas",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "The SCIM schema URIs",
    },
    operations: {
      label: "Operations",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "Array of [SCIM operations](https://tools",
    },
  },
});

const enterpriseAdminDeleteScimGroupFromEnterprise = action({
  display: {
    label: "Enterprise Admin Delete Scim Group From Enterprise",
    description: "Delete a SCIM group from an enterprise",
  },
  perform: async (context, { connection, enterprise, scimGroupId }) => {
    const client = createClient(connection as Connection, context.debug.enabled);
    const { data } = await client.delete(
      `/scim/v2/enterprises/${enterprise}/Groups/${scimGroupId}`,
    );
    return { data };
  },
  inputs: {
    connection: {
      label: "Connection",
      type: "connection",
      required: true,
    },
    enterprise: {
      label: "Enterprise",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "The slug version of the enterprise name",
    },
    scimGroupId: {
      label: "Scim Group Id",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "Identifier generated by the GitHub SCIM endpoint",
    },
  },
});

const enterpriseAdminListProvisionedIdentitiesEnterprise = action({
  display: {
    label: "Enterprise Admin List Provisioned Identities Enterprise",
    description: "List SCIM provisioned identities for an enterprise",
  },
  perform: async (
    context,
    { connection, enterprise, startIndex, count, filter },
  ) => {
    const client = createClient(connection as Connection, context.debug.enabled);
    const { data } = await client.get(
      `/scim/v2/enterprises/${enterprise}/Users`,
      {
        params: { startIndex, count, filter },
      },
    );
    return { data };
  },
  inputs: {
    connection: {
      label: "Connection",
      type: "connection",
      required: true,
    },
    enterprise: {
      label: "Enterprise",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "The slug version of the enterprise name",
    },
    startIndex: {
      label: "Start Index",
      type: "string",
      required: false,
      clean: (value) => util.types.toNumber(value) || undefined,
      comments: "Used for pagination: the index of the first result to return",
    },
    count: {
      label: "Count",
      type: "string",
      required: false,
      clean: (value) => util.types.toNumber(value) || undefined,
      comments: "Used for pagination: the number of results to return",
    },
    filter: {
      label: "Filter",
      type: "string",
      required: false,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "filter results",
    },
  },
});

const enterpriseAdminProvisionAndInviteEnterpriseUser = action({
  display: {
    label: "Enterprise Admin Provision And Invite Enterprise User",
    description: "Provision and invite a SCIM enterprise user",
  },
  perform: async (
    context,
    { connection, enterprise, schemas, userName, name, emails, groups },
  ) => {
    const client = createClient(connection as Connection, context.debug.enabled);
    const { data } = await client.post(
      `/scim/v2/enterprises/${enterprise}/Users`,
      {
        schemas,
        userName,
        name,
        emails,
        groups,
      },
    );
    return { data };
  },
  inputs: {
    connection: {
      label: "Connection",
      type: "connection",
      required: true,
    },
    enterprise: {
      label: "Enterprise",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "The slug version of the enterprise name",
    },
    schemas: {
      label: "Schemas",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "The SCIM schema URIs",
    },
    userName: {
      label: "User Name",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "The username for the user",
    },
    name: {
      label: "Name",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
    },
    emails: {
      label: "Emails",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "List of user emails",
    },
    groups: {
      label: "Groups",
      type: "string",
      required: false,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "List of SCIM group IDs the user is a member of",
    },
  },
});

const enterpriseAdminGetProvisioningInformationForEnterpriseUser = action({
  display: {
    label: "Enterprise Admin Get Provisioning Information For Enterprise User",
    description: "Get SCIM provisioning information for an enterprise user",
  },
  perform: async (context, { connection, enterprise, scimUserId }) => {
    const client = createClient(connection as Connection, context.debug.enabled);
    const { data } = await client.get(
      `/scim/v2/enterprises/${enterprise}/Users/${scimUserId}`,
    );
    return { data };
  },
  inputs: {
    connection: {
      label: "Connection",
      type: "connection",
      required: true,
    },
    enterprise: {
      label: "Enterprise",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "The slug version of the enterprise name",
    },
    scimUserId: {
      label: "Scim User Id",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "The unique identifier of the SCIM user",
    },
  },
});

const enterpriseAdminSetInformationForProvisionedEnterpriseUser = action({
  display: {
    label: "Enterprise Admin Set Information For Provisioned Enterprise User",
    description: "Set SCIM information for a provisioned enterprise user",
  },
  perform: async (
    context,
    {
      connection,
      enterprise,
      scimUserId,
      schemas,
      userName,
      name,
      emails,
      groups,
    },
  ) => {
    const client = createClient(connection as Connection, context.debug.enabled);
    const { data } = await client.put(
      `/scim/v2/enterprises/${enterprise}/Users/${scimUserId}`,
      { schemas, userName, name, emails, groups },
    );
    return { data };
  },
  inputs: {
    connection: {
      label: "Connection",
      type: "connection",
      required: true,
    },
    enterprise: {
      label: "Enterprise",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "The slug version of the enterprise name",
    },
    scimUserId: {
      label: "Scim User Id",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "The unique identifier of the SCIM user",
    },
    schemas: {
      label: "Schemas",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "The SCIM schema URIs",
    },
    userName: {
      label: "User Name",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "The username for the user",
    },
    name: {
      label: "Name",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
    },
    emails: {
      label: "Emails",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "List of user emails",
    },
    groups: {
      label: "Groups",
      type: "string",
      required: false,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "List of SCIM group IDs the user is a member of",
    },
  },
});

const enterpriseAdminUpdateAttributeForEnterpriseUser = action({
  display: {
    label: "Enterprise Admin Update Attribute For Enterprise User",
    description: "Update an attribute for a SCIM enterprise user",
  },
  perform: async (
    context,
    { connection, enterprise, scimUserId, schemas, operations },
  ) => {
    const client = createClient(connection as Connection, context.debug.enabled);
    const { data } = await client.patch(
      `/scim/v2/enterprises/${enterprise}/Users/${scimUserId}`,
      { schemas, Operations: operations },
    );
    return { data };
  },
  inputs: {
    connection: {
      label: "Connection",
      type: "connection",
      required: true,
    },
    enterprise: {
      label: "Enterprise",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "The slug version of the enterprise name",
    },
    scimUserId: {
      label: "Scim User Id",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "The unique identifier of the SCIM user",
    },
    schemas: {
      label: "Schemas",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "The SCIM schema URIs",
    },
    operations: {
      label: "Operations",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "Array of [SCIM operations](https://tools",
    },
  },
});

const enterpriseAdminDeleteUserFromEnterprise = action({
  display: {
    label: "Enterprise Admin Delete User From Enterprise",
    description: "Delete a SCIM user from an enterprise",
  },
  perform: async (context, { connection, enterprise, scimUserId }) => {
    const client = createClient(connection as Connection, context.debug.enabled);
    const { data } = await client.delete(
      `/scim/v2/enterprises/${enterprise}/Users/${scimUserId}`,
    );
    return { data };
  },
  inputs: {
    connection: {
      label: "Connection",
      type: "connection",
      required: true,
    },
    enterprise: {
      label: "Enterprise",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "The slug version of the enterprise name",
    },
    scimUserId: {
      label: "Scim User Id",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "The unique identifier of the SCIM user",
    },
  },
});

const scimListProvisionedIdentities = action({
  display: {
    label: "Scim List Provisioned Identities",
    description: "List SCIM provisioned identities",
  },
  perform: async (context, { connection, org, startIndex, count, filter }) => {
    const client = createClient(connection as Connection, context.debug.enabled);
    const { data } = await client.get(`/scim/v2/organizations/${org}/Users`, {
      params: { startIndex, count, filter },
    });
    return { data };
  },
  inputs: {
    connection: {
      label: "Connection",
      type: "connection",
      required: true,
    },
    org: {
      label: "Org",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "The organization name",
    },
    startIndex: {
      label: "Start Index",
      type: "string",
      required: false,
      clean: (value) => util.types.toNumber(value) || undefined,
      comments: "Used for pagination: the index of the first result to return",
    },
    count: {
      label: "Count",
      type: "string",
      required: false,
      clean: (value) => util.types.toNumber(value) || undefined,
      comments: "Used for pagination: the number of results to return",
    },
    filter: {
      label: "Filter",
      type: "string",
      required: false,
      clean: (value) => util.types.toString(value) || undefined,
      comments:
        'Filters results using the equals query parameter operator ("eq")',
    },
  },
});

const scimProvisionAndInviteUser = action({
  display: {
    label: "Scim Provision And Invite User",
    description: "Provision and invite a SCIM user",
  },
  perform: async (
    context,
    {
      connection,
      org,
      userName,
      displayName,
      name,
      emails,
      schemas,
      externalId,
      groups,
      active,
    },
  ) => {
    const client = createClient(connection as Connection, context.debug.enabled);
    const { data } = await client.post(`/scim/v2/organizations/${org}/Users`, {
      userName,
      displayName,
      name,
      emails,
      schemas,
      externalId,
      groups,
      active,
    });
    return { data };
  },
  inputs: {
    connection: {
      label: "Connection",
      type: "connection",
      required: true,
    },
    org: {
      label: "Org",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "The organization name",
    },
    userName: {
      label: "User Name",
      type: "string",
      required: true,
      example: "someone@example.com",
      clean: (value) => util.types.toString(value) || undefined,
      comments: "Configured by the admin",
    },
    displayName: {
      label: "Display Name",
      type: "string",
      required: false,
      example: "Jon Doe",
      clean: (value) => util.types.toString(value) || undefined,
      comments: "The name of the user, suitable for display to end-users",
    },
    name: {
      label: "Name",
      type: "string",
      required: true,
      example: "[object Object]",
      clean: (value) => util.types.toString(value) || undefined,
    },
    emails: {
      label: "Emails",
      type: "string",
      required: true,
      example: "[object Object],[object Object]",
      clean: (value) => util.types.toString(value) || undefined,
      comments: "user emails",
    },
    schemas: {
      label: "Schemas",
      type: "string",
      required: false,
      clean: (value) => util.types.toString(value) || undefined,
    },
    externalId: {
      label: "External Id",
      type: "string",
      required: false,
      clean: (value) => util.types.toString(value) || undefined,
    },
    groups: {
      label: "Groups",
      type: "string",
      required: false,
      clean: (value) => util.types.toString(value) || undefined,
    },
    active: {
      label: "Active",
      type: "boolean",
      required: false,
      clean: (value) => util.types.toBool(value) || undefined,
    },
  },
});

const scimGetProvisioningInformationForUser = action({
  display: {
    label: "Scim Get Provisioning Information For User",
    description: "Get SCIM provisioning information for a user",
  },
  perform: async (context, { connection, org, scimUserId }) => {
    const client = createClient(connection as Connection, context.debug.enabled);
    const { data } = await client.get(
      `/scim/v2/organizations/${org}/Users/${scimUserId}`,
    );
    return { data };
  },
  inputs: {
    connection: {
      label: "Connection",
      type: "connection",
      required: true,
    },
    org: {
      label: "Org",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "The organization name",
    },
    scimUserId: {
      label: "Scim User Id",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "The unique identifier of the SCIM user",
    },
  },
});

const scimSetInformationForProvisionedUser = action({
  display: {
    label: "Scim Set Information For Provisioned User",
    description: "Update a provisioned organization membership",
  },
  perform: async (
    context,
    {
      connection,
      org,
      scimUserId,
      schemas,
      displayName,
      externalId,
      groups,
      active,
      userName,
      name,
      emails,
    },
  ) => {
    const client = createClient(connection as Connection, context.debug.enabled);
    const { data } = await client.put(
      `/scim/v2/organizations/${org}/Users/${scimUserId}`,
      {
        schemas,
        displayName,
        externalId,
        groups,
        active,
        userName,
        name,
        emails,
      },
    );
    return { data };
  },
  inputs: {
    connection: {
      label: "Connection",
      type: "connection",
      required: true,
    },
    org: {
      label: "Org",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "The organization name",
    },
    scimUserId: {
      label: "Scim User Id",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "The unique identifier of the SCIM user",
    },
    schemas: {
      label: "Schemas",
      type: "string",
      required: false,
      clean: (value) => util.types.toString(value) || undefined,
    },
    displayName: {
      label: "Display Name",
      type: "string",
      required: false,
      example: "Jon Doe",
      clean: (value) => util.types.toString(value) || undefined,
      comments: "The name of the user, suitable for display to end-users",
    },
    externalId: {
      label: "External Id",
      type: "string",
      required: false,
      clean: (value) => util.types.toString(value) || undefined,
    },
    groups: {
      label: "Groups",
      type: "string",
      required: false,
      clean: (value) => util.types.toString(value) || undefined,
    },
    active: {
      label: "Active",
      type: "boolean",
      required: false,
      clean: (value) => util.types.toBool(value) || undefined,
    },
    userName: {
      label: "User Name",
      type: "string",
      required: true,
      example: "someone@example.com",
      clean: (value) => util.types.toString(value) || undefined,
      comments: "Configured by the admin",
    },
    name: {
      label: "Name",
      type: "string",
      required: true,
      example: "[object Object]",
      clean: (value) => util.types.toString(value) || undefined,
    },
    emails: {
      label: "Emails",
      type: "string",
      required: true,
      example: "[object Object],[object Object]",
      clean: (value) => util.types.toString(value) || undefined,
      comments: "user emails",
    },
  },
});

const scimUpdateAttributeForUser = action({
  display: {
    label: "Scim Update Attribute For User",
    description: "Update an attribute for a SCIM user",
  },
  perform: async (
    context,
    { connection, org, scimUserId, schemas, operations },
  ) => {
    const client = createClient(connection as Connection, context.debug.enabled);
    const { data } = await client.patch(
      `/scim/v2/organizations/${org}/Users/${scimUserId}`,
      { schemas, Operations: operations },
    );
    return { data };
  },
  inputs: {
    connection: {
      label: "Connection",
      type: "connection",
      required: true,
    },
    org: {
      label: "Org",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "The organization name",
    },
    scimUserId: {
      label: "Scim User Id",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "The unique identifier of the SCIM user",
    },
    schemas: {
      label: "Schemas",
      type: "string",
      required: false,
      clean: (value) => util.types.toString(value) || undefined,
    },
    operations: {
      label: "Operations",
      type: "string",
      required: true,
      example: "[object Object]",
      clean: (value) => util.types.toString(value) || undefined,
      comments: "Set of operations to be performed",
    },
  },
});

const scimDeleteUserFromOrg = action({
  display: {
    label: "Scim Delete User From Org",
    description: "Delete a SCIM user from an organization",
  },
  perform: async (context, { connection, org, scimUserId }) => {
    const client = createClient(connection as Connection, context.debug.enabled);
    const { data } = await client.delete(
      `/scim/v2/organizations/${org}/Users/${scimUserId}`,
    );
    return { data };
  },
  inputs: {
    connection: {
      label: "Connection",
      type: "connection",
      required: true,
    },
    org: {
      label: "Org",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "The organization name",
    },
    scimUserId: {
      label: "Scim User Id",
      type: "string",
      required: true,
      clean: (value) => util.types.toString(value) || undefined,
      comments: "The unique identifier of the SCIM user",
    },
  },
});

export default {
  enterpriseAdminListProvisionedGroupsEnterprise,
  enterpriseAdminProvisionAndInviteEnterpriseGroup,
  enterpriseAdminGetProvisioningInformationForEnterpriseGroup,
  enterpriseAdminSetInformationForProvisionedEnterpriseGroup,
  enterpriseAdminUpdateAttributeForEnterpriseGroup,
  enterpriseAdminDeleteScimGroupFromEnterprise,
  enterpriseAdminListProvisionedIdentitiesEnterprise,
  enterpriseAdminProvisionAndInviteEnterpriseUser,
  enterpriseAdminGetProvisioningInformationForEnterpriseUser,
  enterpriseAdminSetInformationForProvisionedEnterpriseUser,
  enterpriseAdminUpdateAttributeForEnterpriseUser,
  enterpriseAdminDeleteUserFromEnterprise,
  scimListProvisionedIdentities,
  scimProvisionAndInviteUser,
  scimGetProvisioningInformationForUser,
  scimSetInformationForProvisionedUser,
  scimUpdateAttributeForUser,
  scimDeleteUserFromOrg,
};
