#import "../../fragments/FulfillmentOrderDetails.gql"
query ListFulfillmentOrders($orderId: ID!, $first: Int!, $cursor: String) {
  order(id: $orderId) {
    fulfillmentOrders(first: $first, after: $cursor) {
      nodes {
        ...FulfillmentOrderDetails
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
}
