import type { TriggerPayload } from "@prismatic-io/spectral";
export const createARAdvanceExamplePayload = {
  data: {
    response: {
      control: [
        {
          status: ["success"],
          senderid: ["example"],
          controlid: ["1705003571234"],
          uniqueid: ["false"],
          dtdversion: ["3.0"],
        },
      ],
      operation: [
        {
          authentication: [
            {
              status: ["success"],
              userid: ["UtilizeCore"],
              companyid: ["example-imp"],
              locationid: ["example-location"],
              sessiontimestamp: ["2024-01-10T16:45:20+00:00"],
              sessiontimeout: ["2024-01-11T00:45:20+00:00"],
            },
          ],
          result: [
            {
              status: ["success"],
              function: ["create"],
              controlid: ["a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"],
              key: ["9834"],
            },
          ],
        },
      ],
    },
  },
};
export const createBillExamplePayload = {
  data: {
    response: {
      control: [
        {
          status: ["success"],
          senderid: ["testgroup"],
          controlid: ["1704925436123"],
          uniqueid: ["false"],
          dtdversion: ["3.0"],
        },
      ],
      operation: [
        {
          authentication: [
            {
              status: ["success"],
              userid: ["TestUser"],
              companyid: ["testgroup-imp"],
              locationid: ["firstchoice"],
              sessiontimestamp: ["2024-01-10T22:23:57+00:00"],
              sessiontimeout: ["2024-01-11T06:23:57+00:00"],
            },
          ],
          result: [
            {
              status: ["success"],
              function: ["create"],
              controlid: ["49143589-7eff-4a44-a049-378ed812345"],
              data: [
                {
                  $: {
                    listtype: "objects",
                    count: "1",
                  },
                  apbill: [
                    {
                      RECORDNO: ["4760"],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  },
};
export const createContactExamplePayload = {
  data: {
    _status: "success",
    _functionName: "create",
    _controlId: "b8ff1fd1-10ac-4a3c-aa5b-2cf8494f1234",
    _listType: "objects",
    _count: 1,
    _data: [{ RECORDNO: "19713", CONTACTNAME: "John Doe" }],
  },
};
export const createCustomerExamplePayload = {
  data: {
    _status: "success",
    _functionName: "create",
    _controlId: "8245cb67-8fd6-4785-9008-121acd2d1234",
    _listType: "objects",
    _count: 1,
    _data: [{ RECORDNO: "12499", CUSTOMERID: "C-01564" }],
  },
};
export const createInvoiceExamplePayload = {
  data: {
    response: {
      control: [
        {
          status: ["success"],
          senderid: ["example"],
          controlid: ["1705003571234"],
          uniqueid: ["false"],
          dtdversion: ["3.0"],
        },
      ],
      operation: [
        {
          authentication: [
            {
              status: ["success"],
              userid: ["UtilizeCore"],
              companyid: ["example-imp"],
              locationid: ["example-location"],
              sessiontimestamp: ["2024-01-11T20:06:13+00:00"],
              sessiontimeout: ["2024-01-12T04:06:13+00:00"],
            },
          ],
          result: [
            {
              status: ["success"],
              function: ["create_invoice"],
              controlid: ["3a7463e3-d65e-4056-be1a-158f2cf51234"],
              key: ["4774"],
            },
          ],
        },
      ],
    },
  },
};
export const createProjectExamplePayload = {
  data: {
    RECORDNO: "90320",
    PROJECTID: "21-3457",
  },
};
export const createVendorExamplePayload = {
  data: {
    _status: "success",
    _functionName: "create",
    _controlId: "a30ea5c6-565b-4c31-95a7-b503fe071234",
    _listType: "objects",
    _count: 1,
    _data: [{ RECORDNO: "1234", VENDORID: "V-12345" }],
  },
};
export const deleteObjectExamplePayload = {
  data: {
    response: {
      control: [
        {
          status: ["success"],
          senderid: ["example"],
          controlid: ["1705003571234"],
          uniqueid: ["false"],
          dtdversion: ["3.0"],
        },
      ],
      operation: [
        {
          authentication: [
            {
              status: ["success"],
              userid: ["UtilizeCore"],
              companyid: ["example-imp"],
              locationid: ["example-location"],
              sessiontimestamp: ["2024-01-15T15:20:00+00:00"],
              sessiontimeout: ["2024-01-15T23:20:00+00:00"],
            },
          ],
          result: [
            {
              status: ["success"],
              function: ["delete"],
              controlid: ["c3d4e5f6-a7b8-9c0d-1e2f-3a4b5c6d7e8f"],
            },
          ],
        },
      ],
    },
  },
};
export const getARAdjustmentLineExamplePayload = {
  data: {
    _status: "success",
    _functionName: "read",
    _controlId: "e2f3a4b5-6c7d-8e9f-0a1b-2c3d4e5f6a7b",
    _listType: "ARADJUSTMENTITEM",
    _count: 1,
    _data: [
      {
        RECORDNO: "12456",
        RECORDKEY: "12456",
        ARADJUSTMENTKEY: "8652",
        ADJUSTMENTNO: "ADJ-2024-001",
        LINEITEMKEY: "12456",
        GLACCOUNTNO: "4000",
        GLACCOUNTKEY: "256",
        GLACCOUNTTITLE: "Sales Revenue",
        ACCOUNTLABEL: "",
        ACCOUNTLABELKEY: "",
        AMOUNT: "-250.00",
        TRX_AMOUNT: "-250.00",
        CURRENCY: "USD",
        EXCHRATEDATE: "",
        EXCHRATETYPE: "",
        EXCHRATE: "",
        MEMO: "Credit for defective items",
        LOCATIONID: "100",
        LOCATIONNAME: "Main Office",
        LOCATIONKEY: "36",
        DEPARTMENTID: "SALES",
        DEPARTMENTNAME: "Sales Department",
        DEPARTMENTKEY: "42",
        PROJECTID: "",
        PROJECTNAME: "",
        PROJECTKEY: "",
        CUSTOMERID: "C-01234",
        CUSTOMERNAME: "Acme Corporation",
        CUSTOMERKEY: "12499",
        VENDORID: "",
        VENDORNAME: "",
        VENDORKEY: "",
        EMPLOYEEID: "",
        EMPLOYEENAME: "",
        EMPLOYEEKEY: "",
        ITEMID: "",
        ITEMNAME: "",
        ITEMKEY: "",
        CLASSID: "",
        CLASSNAME: "",
        CLASSKEY: "",
        CONTRACTID: "",
        CONTRACTNAME: "",
        CONTRACTKEY: "",
        WAREHOUSEID: "",
        WAREHOUSENAME: "",
        WAREHOUSEKEY: "",
        STATUS: "active",
        WHENMODIFIED: "2024-01-15T11:15:30Z",
        CREATEDBY: "43",
        MODIFIEDBY: "43",
      },
    ],
  },
};
export const getARAdjustmentExamplePayload = {
  data: {
    _status: "success",
    _functionName: "read",
    _controlId: "c1d2e3f4-5a6b-7c8d-9e0f-1a2b3c4d5e6f",
    _listType: "ARADJUSTMENT",
    _count: 1,
    _data: [
      {
        RECORDNO: "8652",
        RECORDTYPE: "ra",
        RECORDID: "ADJ-2024-001",
        CUSTOMERID: "C-01234",
        CUSTOMERNAME: "Acme Corporation",
        CUSTOMERKEY: "12499",
        STATE: "Posted",
        RAWSTATE: "A",
        DOCNUMBER: "ADJ-2024-001",
        DESCRIPTION: "Credit adjustment for returned goods",
        PONUMBER: "",
        TERMNAME: "",
        TERMKEY: "",
        TERMVALUE: "",
        WHENCREATED: "2024-01-15",
        WHENPOSTED: "2024-01-15",
        WHENDUE: "",
        WHENPAID: "",
        BASECURR: "USD",
        CURRENCY: "USD",
        EXCH_RATE_DATE: "",
        EXCH_RATE_TYPE_ID: "",
        EXCHANGE_RATE: "",
        TOTALENTERED: "-250.00",
        TOTALSELECTED: "0",
        TOTALPAID: "0",
        TOTALDUE: "-250.00",
        TRX_TOTALENTERED: "-250.00",
        TRX_TOTALSELECTED: "0",
        TRX_TOTALPAID: "0",
        TRX_TOTALDUE: "-250.00",
        BILLTOPAYTOCONTACTNAME: "John Doe",
        SHIPTORETURNTOCONTACTNAME: "Jane Smith",
        BILLTOPAYTOKEY: "19714",
        SHIPTORETURNTOKEY: "19715",
        LOCATIONID: "100",
        LOCATIONNAME: "Main Office",
        LOCATIONKEY: "36",
        DEPARTMENTID: "SALES",
        DEPARTMENTNAME: "Sales Department",
        DEPARTMENTKEY: "42",
        PROJECTID: "",
        PROJECTNAME: "",
        PROJECTKEY: "",
        CLASSID: "",
        CLASSNAME: "",
        CLASSKEY: "",
        CONTRACTID: "",
        CONTRACTNAME: "",
        CONTRACTKEY: "",
        SUPDOCID: "",
        ADJUSTMENTNO: "ADJ-2024-001",
        ACTION: "Credit",
        INVOICEKEY: "4774",
        INVOICENO: "INV-2024-001",
        WHENMODIFIED: "2024-01-15T11:15:30Z",
        CREATEDBY: "43",
        MODIFIEDBY: "43",
        MEGAENTITYKEY: "36",
        MEGAENTITYID: "entity",
        MEGAENTITYNAME: "Entity Name",
        ITEMS: [
          {
            RECORDNO: "12456",
            ACCOUNTNO: "4000",
            ACCOUNTTITLE: "Sales Revenue",
            AMOUNT: "-250.00",
            MEMO: "Credit for defective items",
            LOCATIONID: "100",
            DEPARTMENTID: "SALES",
            PROJECTID: "",
            CUSTOMERID: "C-01234",
            CLASSID: "",
            CONTRACTID: "",
          },
        ],
      },
    ],
  },
};
export const getARAdvanceExamplePayload = {
  data: {
    _status: "success",
    _functionName: "read",
    _controlId: "f3a4b5c6-7d8e-9f0a-1b2c-3d4e5f6a7b8c",
    _listType: "ARADVANCE",
    _count: 1,
    _data: [
      {
        RECORDNO: "9834",
        RECORDKEY: "9834",
        CUSTOMERID: "C-01234",
        CUSTOMERNAME: "Acme Corporation",
        CUSTOMERKEY: "12499",
        PAYMENTDATE: "2024-01-10",
        RECEIPTDATE: "2024-01-10",
        PAYMENTMETHOD: "Check",
        FINANCIALENTITY: "Bank of America",
        FINANCIALENTITYKEY: "15",
        UNDEPOSITEDACCOUNTNO: "1200",
        UNDEPOSITEDACCOUNTKEY: "45",
        BASECURR: "USD",
        CURRENCY: "USD",
        EXCH_RATE_DATE: "",
        EXCH_RATE_TYPE_ID: "",
        EXCHANGE_RATE: "",
        TOTALENTERED: "10000.00",
        TOTALSELECTED: "0",
        TOTALAPPLIED: "2500.00",
        TOTALUNAPPLIED: "7500.00",
        TRX_TOTALENTERED: "10000.00",
        TRX_TOTALSELECTED: "0",
        TRX_TOTALAPPLIED: "2500.00",
        TRX_TOTALUNAPPLIED: "7500.00",
        STATE: "Posted",
        RAWSTATE: "A",
        DESCRIPTION: "Advance payment for Q1 services",
        REFERENCENO: "CHK-2024-0015",
        BANKACCOUNTID: "1000",
        BANKACCOUNTKEY: "25",
        DEPOSITDATE: "2024-01-11",
        REFID: "",
        LOCATIONID: "100",
        LOCATIONNAME: "Main Office",
        LOCATIONKEY: "36",
        DEPARTMENTID: "SALES",
        DEPARTMENTNAME: "Sales Department",
        DEPARTMENTKEY: "42",
        PROJECTID: "",
        PROJECTNAME: "",
        PROJECTKEY: "",
        CLASSID: "",
        CLASSNAME: "",
        CLASSKEY: "",
        CONTRACTID: "",
        CONTRACTNAME: "",
        CONTRACTKEY: "",
        WHENCREATED: "2024-01-10",
        WHENMODIFIED: "2024-01-10T16:45:20Z",
        CREATEDBY: "43",
        MODIFIEDBY: "43",
        MEGAENTITYKEY: "36",
        MEGAENTITYID: "entity",
        MEGAENTITYNAME: "Entity Name",
        ITEMS: [
          {
            RECORDNO: "23567",
            ACCOUNTNO: "1200",
            ACCOUNTKEY: "45",
            ACCOUNTTITLE: "Undeposited Funds",
            AMOUNT: "10000.00",
            TRX_AMOUNT: "10000.00",
            MEMO: "Q1 advance payment",
            LOCATIONID: "100",
            DEPARTMENTID: "SALES",
            PROJECTID: "",
            CUSTOMERID: "C-01234",
            CLASSID: "",
            CONTRACTID: "",
          },
        ],
      },
    ],
  },
};
export const getApPaymentExamplePayload = {
  data: {
    _status: "success",
    _functionName: "read",
    _controlId: "dff0b3b1-af3f-4e52-9260-917ab4f61234",
    _listType: "APPYMT",
    _count: 0,
    _data: [],
  },
};
export const getArPaymentExamplePayload = {
  data: {
    _status: "success",
    _functionName: "read",
    _controlId: "9f54dc6e-ddcc-43ed-a979-eed3599b1234",
    _listType: "ARPYMT",
    _count: 0,
    _data: [],
  },
};
export const getBillExamplePayload = {
  data: {
    _status: "success",
    _functionName: "read",
    _controlId: "9b7a9dc1-be4a-471a-95a6-6e8e68dc1234",
    _listType: "APBILL",
    _count: 1,
    _data: [
      {
        RECORDNO: "2746",
        RECORDTYPE: "pi",
        RECORDID: "11111",
        CONTACTTAXGROUP: "",
        FINANCIALENTITY: "",
        STATE: "Posted",
        RAWSTATE: "A",
        VENDORID: "V-01234",
        VENDORNAME: "Changed Name",
        VENDORKEY: "1234",
        FORM1099TYPE: "",
        FORM1099BOX: "",
        VENDTYPE1099TYPE: "",
        TRX_ENTITYDUE: "1902.28",
        DOCNUMBER: "",
        DESCRIPTION: "",
        DESCRIPTION2: "",
        TERMNAME: "",
        TERMKEY: "",
        TERMVALUE: "",
        WHENCREATED: "2023-12-06",
        WHENPOSTED: "2023-12-06",
        WHENDISCOUNT: "",
        WHENDUE: "2023-12-06",
        WHENPAID: "",
        RECPAYMENTDATE: "",
        PAYMENTPRIORITY: "normal",
        ONHOLD: "false",
        BASECURR: "USD",
        CURRENCY: "USD",
        EXCH_RATE_DATE: "",
        EXCH_RATE_TYPE_ID: "",
        EXCHANGE_RATE: "",
        TOTALENTERED: "100.12",
        TOTALSELECTED: "0",
        TOTALPAID: "0",
        TOTALDUE: "100.12",
        TRX_TOTALENTERED: "100.12",
        TRX_TOTALSELECTED: "0",
        TRX_TOTALPAID: "0",
        TRX_TOTALDUE: "100.12",
        BILLTOPAYTOCONTACTNAME: "A vendor(VV-01234)",
        SHIPTORETURNTOCONTACTNAME: "A vendor(VV-01234)",
        BILLTOPAYTOKEY: "22135",
        SHIPTORETURNTOKEY: "22135",
        PRBATCH: "Bills - locationId: 2024/01/02 13:26:29:633 Batch",
        PRBATCHKEY: "2092",
        MODULEKEY: "3.AP",
        DOCUMENT_DOCPARID: "",
        SCHOPKEY: "",
        SYSTEMGENERATED: "F",
        AUWHENCREATED: "2024-01-02T18:26:29Z",
        WHENMODIFIED: "2024-01-02T18:37:32Z",
        CREATEDBY: "43",
        MODIFIEDBY: "43",
        DUE_IN_DAYS: "36",
        PAYTO: { TAXGROUP: { NAME: "", RECORDNO: "" }, TAXID: "" },
        INCLUSIVETAX: "false",
        TAXSOLUTIONKEY: "",
        TAXSOLUTIONID: "",
        SHOWMULTILINETAX: "",
        TAXMETHOD: "",
        RETAINAGEPERCENTAGE: "",
        TRX_TOTALRETAINED: "0",
        TRX_TOTALRELEASED: "0",
        TOTALRETAINED: "0",
        SUPDOCID: "",
        SUPDOCKEY: "",
        BILLBACKTEMPLATE: "",
        USERID: "TestUser",
        CREATEDUSERID: "TestUser",
        DOCSOURCE: "",
        UPLOADSTATUS: "",
        RECIPIENTEMAIL: "",
        SENDEREMAIL: "",
        RETAINAGERELEASED: "false",
        MEGAENTITYKEY: "36",
        MEGAENTITYID: "locationId",
        MEGAENTITYNAME: "Location Name",
        BDC_BILLID: "",
        BDC_ORGID: "",
        BDC_URL_PREFIX: "",
        BUILDOPSUPDATE: "false",
        BO_REC: "",
        EXTERNALURL: "",
        EXCHRATEDATE: "",
        EXCHRATETYPE: "",
        EXCHRATE: "",
        PAYTOCONTACTNAME: "A vendor(VV-01234)",
        RETURNTOCONTACTNAME: "A vendor(VV-01234)",
        APBILLITEMS: {
          apbillitem: {
            RECORDNO: "12996",
            RECORDKEY: "2746",
            ACCOUNTKEY: "261",
            ACCOUNTNO: "10000",
            OFFSETACCOUNTKEY: "65",
            OFFSETGLACCOUNTNO: "20000",
            OFFSETGLACCOUNTTITLE: "Accounts Payable",
            ACCOUNTTITLE: "Account",
            ACCOUNTLABELKEY: "",
            ACCOUNTLABEL: "",
            PRENTRYOFFSETACCOUNTKEY: "65",
            PRENTRYOFFSETACCOUNTNO: "20000",
            ENTRY_DATE: "2023-12-06",
            AMOUNT: "100.12",
            TRX_AMOUNT: "100.12",
            DEPT: "",
            DEPARTMENTID: "",
            DEPARTMENTNAME: "",
            LOCATION: "36",
            LOCATIONID: "locationId",
            LOCATIONNAME: "Location Name",
            ENTRYDESCRIPTION: "Line 1 of my bill",
            EXCH_RATE_DATE: "",
            EXCH_RATE_TYPE_ID: "",
            EXCHANGE_RATE: "1",
            ALLOCATION: "",
            ALLOCATIONKEY: "",
            FORM1099: "false",
            LINEITEM: "T",
            LINE_NO: "1",
            CURRENCY: "USD",
            BASECURR: "USD",
            TOTALPAID: "0",
            TRX_TOTALPAID: "0",
            TOTALSELECTED: "0",
            TRX_TOTALSELECTED: "0",
            BILLABLE: "false",
            BILLED: "false",
            RELEASETOPAY: "false",
            PARENTENTRY: "",
            BASELOCATION: "36",
            STATE: "A",
            RECORDTYPE: "pi",
            FORM1099TYPE: "",
            FORM1099BOX: "",
            DETAILID: "",
            ISTAX: "false",
            DETAILKEY: "",
            WHENCREATED: "2024-01-02T18:26:29Z",
            WHENMODIFIED: "2024-01-02T18:37:32Z",
            CREATEDBY: "43",
            MODIFIEDBY: "43",
            TAXRATE: "",
            RETAINAGEPERCENTAGE: "",
            TRX_AMOUNTRETAINED: "",
            AMOUNTRETAINED: "",
            HASRETAINAGE: "false",
            TRX_AMOUNTRELEASED: "",
            RETAINAGERELEASED: "false",
            RETAINAGE_OFFSETACCOUNTKEY: "",
            RETAINAGE_OFFSETGLACCOUNTNO: "",
            RETAINAGE_OFFSETGLACCOUNTTITLE: "",
            SUBTOTAL: "",
            PARENTTAXENTRY: "",
            PARTIALEXEMPT: "false",
            PAYMENTTAXCAPTURE: "false",
            GLOFFSET: "1",
            RECORDID: "11111",
            NAMEOFACQUIREDASSET: "",
            INCLUDETAXINASSETCOST: "false",
            ITEM_DESC: "",
            DESCRIPTION: "",
            JOB: "",
            BUILDOPSLINK: "",
            GLDIMDIVISION: "10030",
            PROJECTDIMKEY: "",
            PROJECTID: "",
            PROJECTNAME: "",
            CUSTOMERDIMKEY: "",
            CUSTOMERID: "",
            CUSTOMERNAME: "",
            VENDORDIMKEY: "",
            VENDORID: "",
            VENDORNAME: "",
            EMPLOYEEDIMKEY: "",
            EMPLOYEEID: "",
            EMPLOYEENAME: "",
            ITEMDIMKEY: "",
            ITEMID: "",
            ITEMNAME: "",
            CLASSDIMKEY: "",
            CLASSID: "",
            CLASSNAME: "",
            RGLDIM101000000010217_10067: "10030",
            GLACCOUNTNO: "10000",
            GLACCOUNTTITLE: "Account",
            ENTRYEXCHRATEDATE: "",
            ENTRYEXCHRATETYPE: "",
            ENTRYEXCHRATE: "1",
            ENTRYCURRENCY: "USD",
            ENTRYBASECURRENCY: "USD",
          },
        },
        VENDOR: "V-01234--Changed Name",
      },
    ],
  },
};
export const getContactExamplePayload = {
  data: {
    _status: "success",
    _functionName: "read",
    _controlId: "b53e1bee-6ab4-4ba5-955d-731ffcb51234",
    _listType: "CONTACT",
    _count: 1,
    _data: [
      {
        RECORDNO: "12345",
        VERSIONKEY: "22115",
        CONTACTNAME: "A Contact Name Two",
        COMPANYNAME: "",
        PREFIX: "",
        FIRSTNAME: "",
        LASTNAME: "",
        INITIAL: "",
        PRINTAS: "Testing",
        TAXABLE: "false",
        TAXGROUP: "",
        PHONE1: "",
        PHONE2: "",
        CELLPHONE: "",
        PAGER: "",
        FAX: "",
        EMAIL1: "",
        EMAIL2: "",
        URL1: "",
        URL2: "",
        VISIBLE: "true",
        MAILADDRESS: {
          ADDRESS1: "",
          ADDRESS2: "",
          ADDRESS3: "",
          CITY: "",
          STATE: "",
          ZIP: "",
          COUNTRY: "United States",
          COUNTRYCODE: "US",
          LATITUDE: "",
          LONGITUDE: "",
        },
        STATUS: "active",
        PRICESCHEDULE: "",
        DISCOUNT: "",
        PRICELIST: "",
        PRICELISTKEY: "",
        TAXID: "",
        SIRET: "",
        TAXGROUPKEY: "",
        TAXSOLUTIONKEY: "",
        TAXSOLUTIONID: "",
        TAXSCHEDULE: "",
        PRICESCHEDULEKEY: "",
        WHENCREATED: "2023-12-04T01:35:30Z",
        WHENMODIFIED: "2023-12-04T01:35:30Z",
        CREATEDBY: "43",
        MODIFIEDBY: "43",
        MEGAENTITYKEY: "",
        MEGAENTITYID: "",
        MEGAENTITYNAME: "",
      },
    ],
  },
};
export const getCustomerExamplePayload = {
  data: {
    _status: "success",
    _functionName: "read",
    _controlId: "37882748-090a-4131-a6f3-d411d9c22556",
    _listType: "CUSTOMER",
    _count: 1,
    _data: [
      {
        RECORDNO: "12499",
        CUSTOMERID: "C-01234",
        NAME: "John",
        ENTITY: "CC-01234",
        PARENTKEY: "",
        PARENTID: "",
        PARENTNAME: "",
        DISPLAYCONTACT: {
          CONTACTNAME: "John(CC-01234)",
          COMPANYNAME: "Company",
          PREFIX: "Test",
          FIRSTNAME: "John",
          LASTNAME: "Doe",
          INITIAL: "Middle",
          PRINTAS: "Print",
          TAXABLE: "true",
          TAXGROUP: "",
          TAXSOLUTIONKEY: "",
          TAXSOLUTIONID: "",
          TAXSCHEDULE: "",
          TAXID: "",
          SIRET: "",
          PHONE1: "5241234545",
          PHONE2: "5241234545",
          CELLPHONE: "5241234545",
          PAGER: "1",
          FAX: "5241234123",
          TAXIDVALIDATIONDATE: "",
          GSTREGISTERED: "",
          TAXCOMPANYNAME: "",
          TAXADDRESS: "",
          EMAIL1: "user@example.com",
          EMAIL2: "user@example.com",
          URL1: "https://www.example.com",
          URL2: "https://www.example.com",
          VISIBLE: "false",
          MAILADDRESS: {
            ADDRESS1: "Address 1",
            ADDRESS2: "Address 2",
            ADDRESS3: "",
            CITY: "City",
            STATE: "City",
            ZIP: "12100",
            COUNTRY: "United States",
            COUNTRYCODE: "US",
            LATITUDE: "",
            LONGITUDE: "",
          },
          STATUS: "active",
        },
        TERMNAME: "",
        TERMVALUE: "",
        CUSTREPID: "",
        CUSTREPNAME: "",
        RESALENO: "",
        TAXID: "",
        CREDITLIMIT: "1.23",
        TOTALDUE: "0",
        COMMENTS: "",
        ACCOUNTLABEL: "",
        ARACCOUNT: "",
        ARACCOUNTTITLE: "",
        LAST_INVOICEDATE: "",
        LAST_STATEMENTDATE: "",
        DELIVERY_OPTIONS: "Print",
        TERRITORYID: "",
        TERRITORYNAME: "",
        SHIPPINGMETHOD: "",
        CUSTTYPE: "",
        GLGRPKEY: "",
        GLGROUP: "",
        PRICESCHEDULE: "",
        DISCOUNT: "",
        PRICELIST: "",
        VSOEPRICELIST: "",
        CURRENCY: "",
        CONTACTINFO: {
          CONTACTNAME: "",
          PREFIX: "",
          FIRSTNAME: "",
          INITIAL: "",
          LASTNAME: "",
          COMPANYNAME: "",
          PRINTAS: "",
          PHONE1: "",
          PHONE2: "",
          CELLPHONE: "",
          PAGER: "",
          FAX: "",
          EMAIL1: "",
          EMAIL2: "",
          URL1: "",
          URL2: "",
          VISIBLE: "false",
          MAILADDRESS: {
            ADDRESS1: "",
            ADDRESS2: "",
            ADDRESS3: "",
            CITY: "",
            STATE: "",
            ZIP: "",
            COUNTRY: "",
            COUNTRYCODE: "",
          },
        },
        SHIPTO: {
          CONTACTNAME: "",
          PREFIX: "",
          FIRSTNAME: "",
          INITIAL: "",
          LASTNAME: "",
          COMPANYNAME: "",
          PRINTAS: "",
          TAXABLE: "false",
          TAXGROUP: "",
          TAXSOLUTIONKEY: "",
          TAXSOLUTIONID: "",
          TAXSCHEDULE: "",
          TAXID: "",
          PHONE1: "",
          PHONE2: "",
          CELLPHONE: "",
          PAGER: "",
          FAX: "",
          EMAIL1: "",
          EMAIL2: "",
          URL1: "",
          URL2: "",
          VISIBLE: "false",
          MAILADDRESS: {
            ADDRESS1: "",
            ADDRESS2: "",
            ADDRESS3: "",
            CITY: "",
            STATE: "",
            ZIP: "",
            COUNTRY: "",
            COUNTRYCODE: "",
          },
        },
        BILLTO: {
          CONTACTNAME: "",
          PREFIX: "",
          FIRSTNAME: "",
          INITIAL: "",
          LASTNAME: "",
          COMPANYNAME: "",
          PRINTAS: "",
          TAXABLE: "false",
          TAXGROUP: "",
          TAXSOLUTIONKEY: "",
          TAXSOLUTIONID: "",
          TAXSCHEDULE: "",
          PHONE1: "",
          PHONE2: "",
          CELLPHONE: "",
          PAGER: "",
          FAX: "",
          EMAIL1: "",
          EMAIL2: "",
          URL1: "",
          URL2: "",
          VISIBLE: "false",
          MAILADDRESS: {
            ADDRESS1: "",
            ADDRESS2: "",
            ADDRESS3: "",
            CITY: "",
            STATE: "",
            ZIP: "",
            COUNTRY: "",
            COUNTRYCODE: "",
          },
        },
        STATUS: "active",
        ONETIME: "false",
        CUSTMESSAGEID: "",
        ONHOLD: "false",
        PRCLST_OVERRIDE: "C",
        OEPRCLSTKEY: "",
        OEPRICESCHEDKEY: "",
        ENABLEONLINECARDPAYMENT: "true",
        ENABLEONLINEACHPAYMENT: "true",
        VSOEPRCLSTKEY: "",
        WHENMODIFIED: "2024-01-10T23:05:51Z",
        ARINVOICEPRINTTEMPLATEID: "",
        OEQUOTEPRINTTEMPLATEID: "",
        OEORDERPRINTTEMPLATEID: "",
        OELISTPRINTTEMPLATEID: "",
        OEINVOICEPRINTTEMPLATEID: "",
        OEADJPRINTTEMPLATEID: "",
        OEOTHERPRINTTEMPLATEID: "",
        WHENCREATED: "2024-01-10T23:05:51Z",
        CREATEDBY: "43",
        MODIFIEDBY: "43",
        OBJECTRESTRICTION: "Unrestricted",
        DISPLAYCONTACTKEY: "19714",
        CONTACTKEY: "",
        SHIPTOKEY: "",
        BILLTOKEY: "",
        CUSTREPKEY: "",
        SHIPVIAKEY: "",
        TERRITORYKEY: "",
        TERMSKEY: "",
        ACCOUNTLABELKEY: "",
        ACCOUNTKEY: "",
        CUSTTYPEKEY: "",
        PRICESCHEDULEKEY: "",
        OFFSETGLACCOUNTNO: "",
        OFFSETGLACCOUNTNOTITLE: "",
        ADVBILLBY: "",
        ADVBILLBYTYPE: "",
        SUPDOCID: "",
        RETAINAGEPERCENTAGE: "",
        EMAILOPTIN: "false",
        MEGAENTITYKEY: "36",
        MEGAENTITYID: "entity",
        MEGAENTITYNAME: "Entity Name",
        LOCATIONKEY: "36",
        RARNOTES: "",
        HIDEDISPLAYCONTACT: "true",
        SFORCEKEY: "",
      },
    ],
  },
};
export const getInvoiceExamplePayload = {
  data: {
    _status: "success",
    _functionName: "read",
    _controlId: "a5b2c8d1-3e4f-5a6b-7c8d-9e0f1a2b3c4d",
    _listType: "ARINVOICE",
    _count: 1,
    _data: [
      {
        RECORDNO: "4774",
        RECORDTYPE: "ri",
        RECORDID: "INV-2024-001",
        CUSTOMERID: "C-01234",
        CUSTOMERNAME: "Acme Corporation",
        CUSTOMERKEY: "12499",
        STATE: "Posted",
        RAWSTATE: "A",
        DOCNUMBER: "INV-2024-001",
        DESCRIPTION: "Professional Services - January 2024",
        PONUMBER: "PO-5678",
        TERMNAME: "Net 30",
        TERMKEY: "15",
        TERMVALUE: "30",
        WHENCREATED: "2024-01-15",
        WHENPOSTED: "2024-01-15",
        WHENDUE: "2024-02-14",
        WHENPAID: "",
        BASECURR: "USD",
        CURRENCY: "USD",
        EXCH_RATE_DATE: "",
        EXCH_RATE_TYPE_ID: "",
        EXCHANGE_RATE: "",
        TOTALENTERED: "5000.00",
        TOTALSELECTED: "0",
        TOTALPAID: "0",
        TOTALDUE: "5000.00",
        TRX_TOTALENTERED: "5000.00",
        TRX_TOTALSELECTED: "0",
        TRX_TOTALPAID: "0",
        TRX_TOTALDUE: "5000.00",
        BILLTOPAYTOCONTACTNAME: "John Doe",
        SHIPTORETURNTOCONTACTNAME: "Jane Smith",
        BILLTOPAYTOKEY: "19714",
        SHIPTORETURNTOKEY: "19715",
        CONTACT_CELL_PHONE: "555-0123",
        CONTACT_EMAIL1: "john.doe@example.com",
        CONTACT_PHONE1: "555-0100",
        LOCATIONID: "100",
        LOCATIONNAME: "Main Office",
        LOCATIONKEY: "36",
        DEPARTMENTID: "SALES",
        DEPARTMENTNAME: "Sales Department",
        DEPARTMENTKEY: "42",
        PROJECTID: "",
        PROJECTNAME: "",
        PROJECTKEY: "",
        VENDORID: "",
        VENDORKEY: "",
        EMPLOYEEID: "",
        EMPLOYEEKEY: "",
        CLASSID: "",
        CLASSNAME: "",
        CLASSKEY: "",
        CONTRACTID: "",
        CONTRACTNAME: "",
        CONTRACTKEY: "",
        WAREHOUSEID: "",
        WAREHOUSEKEY: "",
        TRX_TOTAL_OPEN: "5000.00",
        SUPDOCID: "",
        TAXSOLUTIONID: "",
        TAXSOLUTIONKEY: "",
        PAYMENTPRIORITY: "Normal",
        ONHOLD: "false",
        RECPAYMENTDATE: "",
        WHENMODIFIED: "2024-01-15T10:30:00Z",
        CREATEDBY: "43",
        MODIFIEDBY: "43",
        MEGAENTITYKEY: "36",
        MEGAENTITYID: "entity",
        MEGAENTITYNAME: "Entity Name",
        ITEMS: [
          {
            RECORDNO: "10234",
            ITEMID: "SERVICE-001",
            ITEMNAME: "Consulting Services",
            ITEMDESC: "Professional consulting hours",
            QUANTITY: "40",
            UNIT: "hours",
            PRICE: "125.00",
            AMOUNT: "5000.00",
            TAXABLE: "true",
            TAXGROUP: "",
            LOCATIONID: "100",
            DEPARTMENTID: "SALES",
            PROJECTID: "",
            CUSTOMERID: "C-01234",
            VENDORID: "",
            EMPLOYEEID: "",
            CLASSID: "",
            CONTRACTID: "",
            WAREHOUSEID: "",
          },
        ],
      },
    ],
  },
};
export const getProjectExamplePayload = {
  data: {
    RECORDNO: "2",
    PROJECTID: "21-1234",
    NAME: "Sample Project",
    DESCRIPTION: "",
    CURRENCY: "USD",
    PROJECTCATEGORY: "Contract",
    PROJECTSTATUSKEY: "",
    PROJECTSTATUS: "",
    PREVENTTIMESHEET: "false",
    PREVENTEXPENSE: "false",
    PREVENTAPPO: "false",
    PREVENTGENINVOICE: "false",
    STATUS: "active",
    BEGINDATE: "2019-01-01",
    ENDDATE: "2022-12-31",
    BUDGETAMOUNT: "",
    CONTRACTAMOUNT: "",
    ACTUALAMOUNT: "",
    BUDGETQTY: "",
    ESTQTY: "",
    ACTUALQTY: "",
    APPROVEDQTY: "",
    REMAININGQTY: "",
    PERCENTCOMPLETE: "",
    OBSPERCENTCOMPLETE: "0",
    BILLINGTYPE: "",
    SONUMBER: "",
    PONUMBER: "",
    POAMOUNT: "",
    PQNUMBER: "",
    SFDCKEY: "",
    QARROWKEY: "",
    OAKEY: "",
    PARENTKEY: "",
    PARENTID: "",
    PARENTNAME: "",
    INVOICEWITHPARENT: "false",
    CUSTOMERKEY: "",
    CUSTOMERID: "",
    CUSTOMERNAME: "",
    SALESCONTACTKEY: "",
    SALESCONTACTID: "",
    SALESCONTACTNAME: "",
    PROJECTTYPEKEY: "",
    PROJECTTYPE: "",
    MANAGERKEY: "",
    MANAGERID: "",
    MANAGERCONTACTNAME: "",
    PROJECTDEPTKEY: "",
    DEPARTMENTID: "",
    DEPARTMENTNAME: "",
    PROJECTLOCATIONKEY: "3",
    LOCATIONID: "",
    LOCATIONNAME: "",
    CONTACTINFO: {
      CONTACTNAME: "",
    },
    SHIPTO: {
      CONTACTNAME: "",
    },
    BILLTO: {
      CONTACTNAME: "",
    },
    TERMSKEY: "",
    TERMNAME: "",
    DOCNUMBER: "",
    CUSTUSERKEY: "",
    CUSTUSERID: "",
    WHENCREATED: "2021-02-09T15:50:29Z",
    WHENMODIFIED: "2021-03-01T16:33:10Z",
    CREATEDBY: "4",
    MODIFIEDBY: "4",
    BUDGETEDCOST: "",
    CLASSID: "",
    CLASSNAME: "",
    CLASSKEY: "",
    USERRESTRICTIONS: "System Default",
    BILLABLEEXPDEFAULT: "false",
    BILLABLEAPPODEFAULT: "false",
    BUDGETID: "",
    BUDGETKEY: "",
    BILLINGRATE: "",
    BILLINGPRICING: "Billing rate",
    EXPENSERATE: "0",
    EXPENSEPRICING: "Cost plus fee",
    POAPRATE: "0",
    POAPPRICING: "Cost plus fee",
    CONTACTKEY: "",
    SHIPTOKEY: "",
    BILLTOKEY: "",
    INVOICEMESSAGE: "",
    INVOICECURRENCY: "",
    BILLINGOVERMAX: "Do nothing",
    EXCLUDEEXPENSES: "false",
    CONTRACTKEY: "",
    CONTRACTID: "",
    ROOTPARENTKEY: "2",
    ROOTPARENTID: "21-1234",
    ROOTPARENTNAME: "Sample Project",
    MEGAENTITYKEY: "",
    MEGAENTITYID: "",
    MEGAENTITYNAME: "",
  },
};
export const getVendorExamplePayload = {
  data: {
    _status: "success",
    _functionName: "read",
    _controlId: "a3f5bbad-6f3f-417d-a8fc-df1646581234",
    _listType: "VENDOR",
    _count: 1,
    _data: [
      {
        RECORDNO: "12345",
        VENDORID: "V-12345",
        NAME: "A vendor",
        NAME1099: "",
        PARENTKEY: "",
        PARENTID: "",
        PARENTNAME: "",
        DISPLAYCONTACT: {
          CONTACTNAME: "A vendor(VV-12345)",
          COMPANYNAME: "Example Company",
          PREFIX: "",
          FIRSTNAME: "",
          LASTNAME: "",
          INITIAL: "",
          PRINTAS: "Example",
          TAXABLE: "false",
          TAXGROUP: "",
          TAXSOLUTIONKEY: "",
          TAXSOLUTIONID: "",
          TAXSCHEDULE: "",
          TAXID: "",
          SIRET: "",
          PHONE1: "",
          PHONE2: "",
          CELLPHONE: "",
          PAGER: "",
          FAX: "",
          TAXIDVALIDATIONDATE: "",
          GSTREGISTERED: "",
          TAXCOMPANYNAME: "",
          TAXADDRESS: "",
          EMAIL1: "",
          EMAIL2: "",
          URL1: "",
          URL2: "",
          VISIBLE: "true",
          MAILADDRESS: {
            ADDRESS1: "",
            ADDRESS2: "",
            ADDRESS3: "",
            CITY: "",
            STATE: "",
            ZIP: "",
            COUNTRY: "United States",
            COUNTRYCODE: "US",
            LATITUDE: "",
            LONGITUDE: "",
          },
          STATUS: "active",
        },
        ENTITY: "VV-12345",
        TERMNAME: "",
        TERMVALUE: "",
        VENDORACCOUNTNO: "",
        TAXID: "",
        CREDITLIMIT: "15.4",
        TOTALDUE: "0",
        BILLINGTYPE: "openitem",
        VENDTYPE: "",
        VENDTYPE1099TYPE: "",
        GLGROUP: "",
        PRICESCHEDULE: "",
        DISCOUNT: "",
        PRICELIST: "",
        COMMENTS: "",
        ACCOUNTLABEL: "",
        APACCOUNT: "",
        APACCOUNTTITLE: "",
        FORM1099TYPE: "",
        FORM1099BOX: "",
        PAYMENTPRIORITY: "Normal",
        CONTACTINFO: {
          CONTACTNAME: "",
          PREFIX: "",
          FIRSTNAME: "",
          INITIAL: "",
          LASTNAME: "",
          COMPANYNAME: "",
          PRINTAS: "",
          PHONE1: "",
          PHONE2: "",
          CELLPHONE: "",
          PAGER: "",
          FAX: "",
          EMAIL1: "",
          EMAIL2: "",
          URL1: "",
          URL2: "",
          VISIBLE: "false",
          MAILADDRESS: {
            ADDRESS1: "",
            ADDRESS2: "",
            ADDRESS3: "",
            CITY: "",
            STATE: "",
            ZIP: "",
            COUNTRY: "",
            COUNTRYCODE: "",
          },
        },
        PAYTO: {
          CONTACTNAME: "",
          PREFIX: "",
          FIRSTNAME: "",
          INITIAL: "",
          LASTNAME: "",
          COMPANYNAME: "",
          PRINTAS: "",
          PHONE1: "",
          PHONE2: "",
          CELLPHONE: "",
          PAGER: "",
          FAX: "",
          EMAIL1: "",
          EMAIL2: "",
          URL1: "",
          URL2: "",
          VISIBLE: "false",
          MAILADDRESS: {
            ADDRESS1: "",
            ADDRESS2: "",
            ADDRESS3: "",
            CITY: "",
            STATE: "",
            ZIP: "",
            COUNTRY: "",
            COUNTRYCODE: "",
          },
          TAXGROUP: "",
          TAXSOLUTIONKEY: "",
          TAXSOLUTIONID: "",
          TAXSCHEDULE: "",
          TAXID: "",
        },
        RETURNTO: {
          CONTACTNAME: "",
          PREFIX: "",
          FIRSTNAME: "",
          INITIAL: "",
          LASTNAME: "",
          COMPANYNAME: "",
          PRINTAS: "",
          PHONE1: "",
          PHONE2: "",
          CELLPHONE: "",
          PAGER: "",
          FAX: "",
          EMAIL1: "",
          EMAIL2: "",
          URL1: "",
          URL2: "",
          VISIBLE: "false",
          MAILADDRESS: {
            ADDRESS1: "",
            ADDRESS2: "",
            ADDRESS3: "",
            CITY: "",
            STATE: "",
            ZIP: "",
            COUNTRY: "",
            COUNTRYCODE: "",
          },
        },
        STATUS: "inactive",
        STATE: "A",
        PAYDATEVALUE: "",
        ONETIME: "false",
        ONHOLD: "false",
        WHENMODIFIED: "2024-01-11T00:48:17Z",
        ISOWNER: "false",
        DONOTCUTCHECK: "false",
        ALWAYSCREATEBILL: "false",
        OWNER: {
          EQGLACCOUNT: "",
          EQGLACCOUNTLABEL: "",
          HOLDDIST: "",
          ACCOUNTLABEL: { LABEL: "" },
        },
        CURRENCY: "",
        PYMTCOUNTRYCODE: "",
        PYMTCURRENCY: "",
        FILEPAYMENTSERVICE: "NONE",
        ACHENABLED: "false",
        WIREENABLED: "false",
        CHECKENABLED: "false",
        ACHBANKROUTINGNUMBER: "",
        ACHACCOUNTNUMBER: "",
        ACHACCOUNTTYPE: "",
        ACHREMITTANCETYPE: "",
        WIREBANKNAME: "",
        WIREBANKROUTINGNUMBER: "",
        WIREACCOUNTNUMBER: "",
        WIREACCOUNTTYPE: "",
        PMPLUSREMITTANCETYPE: "",
        PMPLUSEMAIL: "",
        PMPLUSFAX: "",
        DISPLAYTERMDISCOUNT: "false",
        OEPRCLSTKEY: "",
        DISPLOCACCTNOCHECK: "false",
        WHENCREATED: "2024-01-11T00:48:15Z",
        CREATEDBY: "43",
        MODIFIEDBY: "43",
        PAYMENTNOTIFY: "false",
        PAYMETHODKEY: "",
        OBJECTRESTRICTION: "",
        MERGEPAYMENTREQ: "false",
        DISPLAYCONTACTKEY: "19716",
        PRIMARYCONTACTKEY: "",
        PAYTOKEY: "",
        RETURNTOKEY: "",
        ACCOUNTLABELKEY: "",
        ACCOUNTKEY: "",
        VENDTYPEKEY: "",
        GLGRPKEY: "",
        TERMSKEY: "",
        VENDORACCTNOKEY: "",
        PAYMETHODREC: "",
        OUTSOURCECHECK: "false",
        OUTSOURCECHECKSTATE: "",
        OUTSOURCEACH: "false",
        OUTSOURCEACHSTATE: "",
        OUTSOURCECARD: "false",
        OUTSOURCECARDOVERRIDE: "false",
        CARDSTATE: "",
        VENDORACHACCOUNTID: "",
        VENDORACCOUNTOUTSOURCEACH: "",
        OFFSETGLACCOUNTNO: "",
        OFFSETGLACCOUNTNOTITLE: "",
        CONTACTTO1099: {
          CONTACTNAME: "",
          PREFIX: "",
          FIRSTNAME: "",
          INITIAL: "",
          LASTNAME: "",
          COMPANYNAME: "",
          PRINTAS: "",
          PHONE1: "",
          PHONE2: "",
          CELLPHONE: "",
          PAGER: "",
          FAX: "",
          EMAIL1: "",
          EMAIL2: "",
          URL1: "",
          URL2: "",
          VISIBLE: "false",
          MAILADDRESS: {
            ADDRESS1: "",
            ADDRESS2: "",
            ADDRESS3: "",
            CITY: "",
            STATE: "",
            ZIP: "",
            COUNTRY: "",
            COUNTRYCODE: "",
          },
        },
        CONTACTKEY1099: "",
        SUPDOCID: "",
        VENDOR_AMEX_ORGANIZATION_ID: "",
        VENDOR_AMEX_ORG_ADDRESS_ID: "",
        VENDOR_AMEX_CD_AFFILIATE_ID: "",
        VENDOR_AMEX_CARD_AFFILIATE_ID: "",
        AMEX_BANK_ACCOUNT_ID: "",
        AMEX_BANK_ACCOUNT_ADDRESS_ID: "",
        RETAINAGEPERCENTAGE: "",
        ISINDIVIDUAL: "false",
        PROVIDERSTATUS: "false",
        WHENLASTBILLED: "",
        WHENLASTPAID: "",
        PROVIDERMISMATCH: "false",
        ENABLE_TPAR: "false",
        NAMETPAR: "",
        MEGAENTITYKEY: "36",
        MEGAENTITYID: "entity",
        MEGAENTITYNAME: "Entity Name",
        HIDEDISPLAYCONTACT: "false",
      },
    ],
  },
};
export const queryAndListExamplePayload = {
  data: [
    { RECORDNO: "1234", CUSTOMERNAME: "Test Client" },
    { RECORDNO: "1235", CUSTOMERNAME: "Another Test Client" },
  ],
};
export const rawRequestExamplePayload = {
  data: {
    response: {
      control: [
        {
          status: ["success"],
          senderid: ["example"],
          controlid: ["1705003571234"],
          uniqueid: ["false"],
          dtdversion: ["3.0"],
        },
      ],
      operation: [
        {
          authentication: [
            {
              status: ["success"],
              userid: ["UtilizeCore"],
              companyid: ["example-imp"],
              locationid: ["example-location"],
              sessiontimestamp: ["2024-01-15T16:00:00+00:00"],
              sessiontimeout: ["2024-01-16T00:00:00+00:00"],
            },
          ],
          result: [
            {
              status: ["success"],
              function: ["query"],
              controlid: ["d4e5f6a7-b8c9-0d1e-2f3a-4b5c6d7e8f9a"],
              data: [
                {
                  $: {
                    listtype: "contact",
                    count: "2",
                    totalcount: "2",
                    numremaining: "0",
                    resultId: "",
                  },
                  contact: [
                    {
                      RECORDNO: ["1234"],
                      CONTACTNAME: ["John Doe"],
                      COMPANYNAME: ["Acme Corporation"],
                      FIRSTNAME: ["John"],
                      LASTNAME: ["Doe"],
                      EMAIL1: ["john.doe@example.com"],
                      PHONE1: ["555-0100"],
                      STATUS: ["active"],
                    },
                    {
                      RECORDNO: ["1235"],
                      CONTACTNAME: ["Jane Smith"],
                      COMPANYNAME: ["Beta Industries"],
                      FIRSTNAME: ["Jane"],
                      LASTNAME: ["Smith"],
                      EMAIL1: ["jane.smith@example.com"],
                      PHONE1: ["555-0200"],
                      STATUS: ["active"],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  },
};
export const updateARAdjustmentExamplePayload = {
  data: {
    response: {
      control: [
        {
          status: ["success"],
          senderid: ["example"],
          controlid: ["1705003571234"],
          uniqueid: ["false"],
          dtdversion: ["3.0"],
        },
      ],
      operation: [
        {
          authentication: [
            {
              status: ["success"],
              userid: ["UtilizeCore"],
              companyid: ["example-imp"],
              locationid: ["example-location"],
              sessiontimestamp: ["2024-01-15T14:30:45+00:00"],
              sessiontimeout: ["2024-01-15T22:30:45+00:00"],
            },
          ],
          result: [
            {
              status: ["success"],
              function: ["update"],
              controlid: ["d9e0f1a2-b3c4-5d6e-7f8a-9b0c1d2e3f4a"],
              key: ["8652"],
            },
          ],
        },
      ],
    },
  },
};
export const updateARAdvanceExamplePayload = {
  data: {
    response: {
      control: [
        {
          status: ["success"],
          senderid: ["example"],
          controlid: ["1705003571234"],
          uniqueid: ["false"],
          dtdversion: ["3.0"],
        },
      ],
      operation: [
        {
          authentication: [
            {
              status: ["success"],
              userid: ["UtilizeCore"],
              companyid: ["example-imp"],
              locationid: ["example-location"],
              sessiontimestamp: ["2024-01-10T17:30:15+00:00"],
              sessiontimeout: ["2024-01-11T01:30:15+00:00"],
            },
          ],
          result: [
            {
              status: ["success"],
              function: ["update"],
              controlid: ["b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7e"],
              key: ["9834"],
            },
          ],
        },
      ],
    },
  },
};
export const updateContactExamplePayload = {
  data: {
    _controlId: "64b091d8-4bd6-4f2e-b175-d90d4e3a1234",
    contactName: "John Doe",
    addressLine1: "123 Main St",
    firstName: "John",
    lastName: "Doe",
    pagerNo: "123",
    taxable: false,
  },
};
export const updateCustomerExamplePayload = {
  data: {
    _controlId: "49861154-842a-4d25-ab12-2af79dfc1234",
    customFields: [
      ["fieldName1", 123],
      ["fieldName2", "someStringValue"],
    ],
    customerId: "C-01234",
    customerName: "John Doe",
    excludedFromContactList: false,
  },
};
export const updateInvoiceExamplePayload = {
  data: {
    response: {
      control: [
        {
          status: ["success"],
          senderid: ["example"],
          controlid: ["1705003571234"],
          uniqueid: ["false"],
          dtdversion: ["3.0"],
        },
      ],
      operation: [
        {
          authentication: [
            {
              status: ["success"],
              userid: ["UtilizeCore"],
              companyid: ["example-imp"],
              locationid: ["example-location"],
              sessiontimestamp: ["2024-01-15T14:22:10+00:00"],
              sessiontimeout: ["2024-01-15T22:22:10+00:00"],
            },
          ],
          result: [
            {
              status: ["success"],
              function: ["update_invoice"],
              controlid: ["b8c9d3e4-f5a6-7b8c-9d0e-1f2a3b4c5d6e"],
              key: ["4774"],
            },
          ],
        },
      ],
    },
  },
};
export const updateProjectExamplePayload = {
  data: {
    RECORDNO: "90320",
    PROJECTID: "21-3457",
  },
};
export const updateVendorExamplePayload = {
  data: {
    _status: "success",
    _functionName: "update",
    _controlId: "bf13a0a9-e0c7-4aa6-9003-207076761234",
    _listType: "objects",
    _count: 1,
    _data: [{ RECORDNO: "1234", VENDORID: "V-01234" }],
  },
};
export const selectContactExamplePayload = {
  result: [
    { label: "John Doe", key: "1001" },
    { label: "Jane Smith", key: "1002" },
  ],
};
export const selectCustomerExamplePayload = {
  result: [
    { label: "Acme Corp", key: "1001" },
    { label: "Global Tech", key: "1002" },
  ],
};
export const selectInvoiceExamplePayload = {
  result: [
    { label: "INV-0001", key: "4001" },
    { label: "INV-0002", key: "4002" },
  ],
};
export const selectProjectExamplePayload = {
  result: [
    { label: "Website Redesign", key: "5001" },
    { label: "ERP Migration", key: "5002" },
  ],
};
export const selectVendorExamplePayload = {
  result: [
    { label: "Acme Supplies", key: "2001" },
    { label: "Office Depot", key: "2002" },
  ],
};
export const pollChangesTriggerExamplePayload: {
  payload: TriggerPayload;
} = {
  payload: {
    body: {
      data: {
        created: [
          {
            RECORDNO: "10042",
            WHENMODIFIED: "2026-01-15T14:30:00Z",
            WHENCREATED: "2026-01-15T14:30:00Z",
            VENDORID: "V-1042",
            NAME: "Acme Office Supplies",
            STATUS: "active",
          },
        ],
        updated: [
          {
            RECORDNO: "10001",
            WHENMODIFIED: "2026-01-15T14:35:00Z",
            WHENCREATED: "2025-12-01T09:00:00Z",
            VENDORID: "V-1001",
            NAME: "Global Parts Inc.",
            STATUS: "active",
          },
        ],
      },
    },
    headers: {},
    queryParameters: {},
    rawBody: {
      data: undefined,
      contentType: undefined,
    },
    pathFragment: "",
    webhookUrls: {},
    webhookApiKeys: {},
    invokeUrl: "",
    executionId: "",
    customer: {
      id: "Q3VzdG9tZXI6MTIzNDU2NzgtMTIzNC00NTY3LTg5YWItY2RlZjAxMjM0NTY3",
      name: "Example Customer",
      externalId: "ext-cust-001",
    },
    instance: {
      id: "SW5zdGFuY2U6MTIzNDU2NzgtMTIzNC00NTY3LTg5YWItY2RlZjAxMjM0NTY3",
      name: "Sage Intacct - Production",
    },
    user: {
      id: "VXNlcjoxMjM0NTY3OC0xMjM0LTQ1NjctODlhYi1jZGVmMDEyMzQ1Njc=",
      email: "user@example.com",
      name: "Example User",
      externalId: "ext-user-001",
    },
    integration: {
      id: "SW50ZWdyYXRpb246MTIzNDU2NzgtMTIzNC00NTY3LTg5YWItY2RlZjAxMjM0NTY3",
      name: "Sage Intacct - Record Sync",
      versionSequenceId: "VmVyc2lvbjoxMjM0NTY3OC0xMjM0LTQ1Njc=",
      externalVersion: "1.0.0",
    },
    flow: {
      id: "Rmxvdzo4NzY1NDMyMS0xMjM0LTQ1NjctODlhYi1jZGVmMDEyMzQ1Njc=",
      name: "New and Updated Records",
      stableId: "",
    },
    startedAt: "",
    globalDebug: false,
  },
};
