import { action } from "@prismatic-io/spectral";
import { createZoomClient } from "../../client";
import {
  connection,
  webinarId,
  email,
  firstName,
  lastName,
  address,
  city,
  country,
  zip,
  state,
  phone,
  industry,
  org,
  jobTitle,
  purchasingTimeFrame,
  roleInPurchaseProcess,
  numberOfEmployees,
  comments,
  customQuestions,
  language,
  sourceId,
  ocurrenceIds,
} from "../../inputs";
import { addWebinarRegistrantExamplePayload } from "../../examplePayloads";

export const addWebinarRegistrant = action({
  display: {
    label: "Add Webinar Registrant",
    description: "Add a new registrant of an existing webinar",
  },
  perform: async (
    { debug: { enabled: debug } },
    {
      connection,
      firstName,
      lastName,
      email,
      address,
      city,
      state,
      zip,
      country,
      phone,
      comments,
      customQuestions,
      industry,
      jobTitle,
      numberOfEmployees,
      org,
      purchasingTimeFrame,
      roleInPurchaseProcess,
      language,
      sourceId,
      ocurrenceIds,
    },
  ) => {
    const client = createZoomClient({ connection, debug });

    const { data } = await client.post(
      `/webinars/${webinarId}/registrants`,
      {
        first_name: firstName,
        last_name: lastName,
        email,
        address,
        city,
        state,
        zip,
        country,
        phone,
        comments,
        custom_questions: customQuestions,
        industry,
        job_title: jobTitle,
        no_of_employees: numberOfEmployees,
        org,
        purchasing_time_frame: purchasingTimeFrame,
        role_in_purchase_process: roleInPurchaseProcess,
        language,
        source_id: sourceId,
      },
      { params: { occurrence_ids: ocurrenceIds } },
    );

    return {
      data,
    };
  },
  inputs: {
    connection,
    firstName,
    lastName,
    email,
    address,
    city,
    state,
    zip,
    country,
    phone,
    comments,
    customQuestions,
    industry,
    jobTitle,
    numberOfEmployees,
    org,
    purchasingTimeFrame,
    roleInPurchaseProcess,
    language,
    sourceId,
    ocurrenceIds,
  },
  examplePayload: addWebinarRegistrantExamplePayload,
});
