

export const getARAdjustmentPayload = {
  data: {
    _status: "success",
    _functionName: "read",
    _controlId: "c1d2e3f4-5a6b-7c8d-9e0f-1a2b3c4d5e6f",
    _listType: "ARADJUSTMENT",
    _count: 1,
    _data: [
      {
        RECORDNO: "8652",
        RECORDTYPE: "ra",
        RECORDID: "ADJ-2024-001",
        CUSTOMERID: "C-01234",
        CUSTOMERNAME: "Acme Corporation",
        CUSTOMERKEY: "12499",
        STATE: "Posted",
        RAWSTATE: "A",
        DOCNUMBER: "ADJ-2024-001",
        DESCRIPTION: "Credit adjustment for returned goods",
        PONUMBER: "",
        TERMNAME: "",
        TERMKEY: "",
        TERMVALUE: "",
        WHENCREATED: "2024-01-15",
        WHENPOSTED: "2024-01-15",
        WHENDUE: "",
        WHENPAID: "",
        BASECURR: "USD",
        CURRENCY: "USD",
        EXCH_RATE_DATE: "",
        EXCH_RATE_TYPE_ID: "",
        EXCHANGE_RATE: "",
        TOTALENTERED: "-250.00",
        TOTALSELECTED: "0",
        TOTALPAID: "0",
        TOTALDUE: "-250.00",
        TRX_TOTALENTERED: "-250.00",
        TRX_TOTALSELECTED: "0",
        TRX_TOTALPAID: "0",
        TRX_TOTALDUE: "-250.00",
        BILLTOPAYTOCONTACTNAME: "John Doe",
        SHIPTORETURNTOCONTACTNAME: "Jane Smith",
        BILLTOPAYTOKEY: "19714",
        SHIPTORETURNTOKEY: "19715",
        LOCATIONID: "100",
        LOCATIONNAME: "Main Office",
        LOCATIONKEY: "36",
        DEPARTMENTID: "SALES",
        DEPARTMENTNAME: "Sales Department",
        DEPARTMENTKEY: "42",
        PROJECTID: "",
        PROJECTNAME: "",
        PROJECTKEY: "",
        CLASSID: "",
        CLASSNAME: "",
        CLASSKEY: "",
        CONTRACTID: "",
        CONTRACTNAME: "",
        CONTRACTKEY: "",
        SUPDOCID: "",
        ADJUSTMENTNO: "ADJ-2024-001",
        ACTION: "Credit",
        INVOICEKEY: "4774",
        INVOICENO: "INV-2024-001",
        WHENMODIFIED: "2024-01-15T11:15:30Z",
        CREATEDBY: "43",
        MODIFIEDBY: "43",
        MEGAENTITYKEY: "36",
        MEGAENTITYID: "entity",
        MEGAENTITYNAME: "Entity Name",
        ITEMS: [
          {
            RECORDNO: "12456",
            ACCOUNTNO: "4000",
            ACCOUNTTITLE: "Sales Revenue",
            AMOUNT: "-250.00",
            MEMO: "Credit for defective items",
            LOCATIONID: "100",
            DEPARTMENTID: "SALES",
            PROJECTID: "",
            CUSTOMERID: "C-01234",
            CLASSID: "",
            CONTRACTID: "",
          },
        ],
      },
    ],
  },
};
