

export const getARAdvancePayload = {
  data: {
    _status: "success",
    _functionName: "read",
    _controlId: "f3a4b5c6-7d8e-9f0a-1b2c-3d4e5f6a7b8c",
    _listType: "ARADVANCE",
    _count: 1,
    _data: [
      {
        RECORDNO: "9834",
        RECORDKEY: "9834",
        CUSTOMERID: "C-01234",
        CUSTOMERNAME: "Acme Corporation",
        CUSTOMERKEY: "12499",
        PAYMENTDATE: "2024-01-10",
        RECEIPTDATE: "2024-01-10",
        PAYMENTMETHOD: "Check",
        FINANCIALENTITY: "Bank of America",
        FINANCIALENTITYKEY: "15",
        UNDEPOSITEDACCOUNTNO: "1200",
        UNDEPOSITEDACCOUNTKEY: "45",
        BASECURR: "USD",
        CURRENCY: "USD",
        EXCH_RATE_DATE: "",
        EXCH_RATE_TYPE_ID: "",
        EXCHANGE_RATE: "",
        TOTALENTERED: "10000.00",
        TOTALSELECTED: "0",
        TOTALAPPLIED: "2500.00",
        TOTALUNAPPLIED: "7500.00",
        TRX_TOTALENTERED: "10000.00",
        TRX_TOTALSELECTED: "0",
        TRX_TOTALAPPLIED: "2500.00",
        TRX_TOTALUNAPPLIED: "7500.00",
        STATE: "Posted",
        RAWSTATE: "A",
        DESCRIPTION: "Advance payment for Q1 services",
        REFERENCENO: "CHK-2024-0015",
        BANKACCOUNTID: "1000",
        BANKACCOUNTKEY: "25",
        DEPOSITDATE: "2024-01-11",
        REFID: "",
        LOCATIONID: "100",
        LOCATIONNAME: "Main Office",
        LOCATIONKEY: "36",
        DEPARTMENTID: "SALES",
        DEPARTMENTNAME: "Sales Department",
        DEPARTMENTKEY: "42",
        PROJECTID: "",
        PROJECTNAME: "",
        PROJECTKEY: "",
        CLASSID: "",
        CLASSNAME: "",
        CLASSKEY: "",
        CONTRACTID: "",
        CONTRACTNAME: "",
        CONTRACTKEY: "",
        WHENCREATED: "2024-01-10",
        WHENMODIFIED: "2024-01-10T16:45:20Z",
        CREATEDBY: "43",
        MODIFIEDBY: "43",
        MEGAENTITYKEY: "36",
        MEGAENTITYID: "entity",
        MEGAENTITYNAME: "Entity Name",
        ITEMS: [
          {
            RECORDNO: "23567",
            ACCOUNTNO: "1200",
            ACCOUNTKEY: "45",
            ACCOUNTTITLE: "Undeposited Funds",
            AMOUNT: "10000.00",
            TRX_AMOUNT: "10000.00",
            MEMO: "Q1 advance payment",
            LOCATIONID: "100",
            DEPARTMENTID: "SALES",
            PROJECTID: "",
            CUSTOMERID: "C-01234",
            CLASSID: "",
            CONTRACTID: "",
          },
        ],
      },
    ],
  },
};
