

export const getARAdjustmentLinePayload = {
  data: {
    _status: "success",
    _functionName: "read",
    _controlId: "e2f3a4b5-6c7d-8e9f-0a1b-2c3d4e5f6a7b",
    _listType: "ARADJUSTMENTITEM",
    _count: 1,
    _data: [
      {
        RECORDNO: "12456",
        RECORDKEY: "12456",
        ARADJUSTMENTKEY: "8652",
        ADJUSTMENTNO: "ADJ-2024-001",
        LINEITEMKEY: "12456",
        GLACCOUNTNO: "4000",
        GLACCOUNTKEY: "256",
        GLACCOUNTTITLE: "Sales Revenue",
        ACCOUNTLABEL: "",
        ACCOUNTLABELKEY: "",
        AMOUNT: "-250.00",
        TRX_AMOUNT: "-250.00",
        CURRENCY: "USD",
        EXCHRATEDATE: "",
        EXCHRATETYPE: "",
        EXCHRATE: "",
        MEMO: "Credit for defective items",
        LOCATIONID: "100",
        LOCATIONNAME: "Main Office",
        LOCATIONKEY: "36",
        DEPARTMENTID: "SALES",
        DEPARTMENTNAME: "Sales Department",
        DEPARTMENTKEY: "42",
        PROJECTID: "",
        PROJECTNAME: "",
        PROJECTKEY: "",
        CUSTOMERID: "C-01234",
        CUSTOMERNAME: "Acme Corporation",
        CUSTOMERKEY: "12499",
        VENDORID: "",
        VENDORNAME: "",
        VENDORKEY: "",
        EMPLOYEEID: "",
        EMPLOYEENAME: "",
        EMPLOYEEKEY: "",
        ITEMID: "",
        ITEMNAME: "",
        ITEMKEY: "",
        CLASSID: "",
        CLASSNAME: "",
        CLASSKEY: "",
        CONTRACTID: "",
        CONTRACTNAME: "",
        CONTRACTKEY: "",
        WAREHOUSEID: "",
        WAREHOUSENAME: "",
        WAREHOUSEKEY: "",
        STATUS: "active",
        WHENMODIFIED: "2024-01-15T11:15:30Z",
        CREATEDBY: "43",
        MODIFIEDBY: "43",
      },
    ],
  },
};
