export const getContactPayload = {
  data: {
    _status: "success",
    _functionName: "read",
    _controlId: "b53e1bee-6ab4-4ba5-955d-731ffcb51234",
    _listType: "CONTACT",
    _count: 1,
    _data: [
      {
        RECORDNO: "12345",
        VERSIONKEY: "22115",
        CONTACTNAME: "A Contact Name Two",
        COMPANYNAME: "",
        PREFIX: "",
        FIRSTNAME: "",
        LASTNAME: "",
        INITIAL: "",
        PRINTAS: "Testing",
        TAXABLE: "false",
        TAXGROUP: "",
        PHONE1: "",
        PHONE2: "",
        CELLPHONE: "",
        PAGER: "",
        FAX: "",
        EMAIL1: "",
        EMAIL2: "",
        URL1: "",
        URL2: "",
        VISIBLE: "true",
        MAILADDRESS: {
          ADDRESS1: "",
          ADDRESS2: "",
          ADDRESS3: "",
          CITY: "",
          STATE: "",
          ZIP: "",
          COUNTRY: "United States",
          COUNTRYCODE: "US",
          LATITUDE: "",
          LONGITUDE: "",
        },
        STATUS: "active",
        PRICESCHEDULE: "",
        DISCOUNT: "",
        PRICELIST: "",
        PRICELISTKEY: "",
        TAXID: "",
        SIRET: "",
        TAXGROUPKEY: "",
        TAXSOLUTIONKEY: "",
        TAXSOLUTIONID: "",
        TAXSCHEDULE: "",
        PRICESCHEDULEKEY: "",
        WHENCREATED: "2023-12-04T01:35:30Z",
        WHENMODIFIED: "2023-12-04T01:35:30Z",
        CREATEDBY: "43",
        MODIFIEDBY: "43",
        MEGAENTITYKEY: "",
        MEGAENTITYID: "",
        MEGAENTITYNAME: "",
      },
    ],
  },
};
