

export const getInvoicePayload = {
  data: {
    _status: "success",
    _functionName: "read",
    _controlId: "a5b2c8d1-3e4f-5a6b-7c8d-9e0f1a2b3c4d",
    _listType: "ARINVOICE",
    _count: 1,
    _data: [
      {
        RECORDNO: "4774",
        RECORDTYPE: "ri",
        RECORDID: "INV-2024-001",
        CUSTOMERID: "C-01234",
        CUSTOMERNAME: "Acme Corporation",
        CUSTOMERKEY: "12499",
        STATE: "Posted",
        RAWSTATE: "A",
        DOCNUMBER: "INV-2024-001",
        DESCRIPTION: "Professional Services - January 2024",
        PONUMBER: "PO-5678",
        TERMNAME: "Net 30",
        TERMKEY: "15",
        TERMVALUE: "30",
        WHENCREATED: "2024-01-15",
        WHENPOSTED: "2024-01-15",
        WHENDUE: "2024-02-14",
        WHENPAID: "",
        BASECURR: "USD",
        CURRENCY: "USD",
        EXCH_RATE_DATE: "",
        EXCH_RATE_TYPE_ID: "",
        EXCHANGE_RATE: "",
        TOTALENTERED: "5000.00",
        TOTALSELECTED: "0",
        TOTALPAID: "0",
        TOTALDUE: "5000.00",
        TRX_TOTALENTERED: "5000.00",
        TRX_TOTALSELECTED: "0",
        TRX_TOTALPAID: "0",
        TRX_TOTALDUE: "5000.00",
        BILLTOPAYTOCONTACTNAME: "John Doe",
        SHIPTORETURNTOCONTACTNAME: "Jane Smith",
        BILLTOPAYTOKEY: "19714",
        SHIPTORETURNTOKEY: "19715",
        CONTACT_CELL_PHONE: "555-0123",
        CONTACT_EMAIL1: "john.doe@example.com",
        CONTACT_PHONE1: "555-0100",
        LOCATIONID: "100",
        LOCATIONNAME: "Main Office",
        LOCATIONKEY: "36",
        DEPARTMENTID: "SALES",
        DEPARTMENTNAME: "Sales Department",
        DEPARTMENTKEY: "42",
        PROJECTID: "",
        PROJECTNAME: "",
        PROJECTKEY: "",
        VENDORID: "",
        VENDORKEY: "",
        EMPLOYEEID: "",
        EMPLOYEEKEY: "",
        CLASSID: "",
        CLASSNAME: "",
        CLASSKEY: "",
        CONTRACTID: "",
        CONTRACTNAME: "",
        CONTRACTKEY: "",
        WAREHOUSEID: "",
        WAREHOUSEKEY: "",
        TRX_TOTAL_OPEN: "5000.00",
        SUPDOCID: "",
        TAXSOLUTIONID: "",
        TAXSOLUTIONKEY: "",
        PAYMENTPRIORITY: "Normal",
        ONHOLD: "false",
        RECPAYMENTDATE: "",
        WHENMODIFIED: "2024-01-15T10:30:00Z",
        CREATEDBY: "43",
        MODIFIEDBY: "43",
        MEGAENTITYKEY: "36",
        MEGAENTITYID: "entity",
        MEGAENTITYNAME: "Entity Name",
        ITEMS: [
          {
            RECORDNO: "10234",
            ITEMID: "SERVICE-001",
            ITEMNAME: "Consulting Services",
            ITEMDESC: "Professional consulting hours",
            QUANTITY: "40",
            UNIT: "hours",
            PRICE: "125.00",
            AMOUNT: "5000.00",
            TAXABLE: "true",
            TAXGROUP: "",
            LOCATIONID: "100",
            DEPARTMENTID: "SALES",
            PROJECTID: "",
            CUSTOMERID: "C-01234",
            VENDORID: "",
            EMPLOYEEID: "",
            CLASSID: "",
            CONTRACTID: "",
            WAREHOUSEID: "",
          },
        ],
      },
    ],
  },
};
