export const getProjectPayload = {
  data: {
    RECORDNO: "2",
    PROJECTID: "21-1234",
    NAME: "Sample Project",
    DESCRIPTION: "",
    CURRENCY: "USD",
    PROJECTCATEGORY: "Contract",
    PROJECTSTATUSKEY: "",
    PROJECTSTATUS: "",
    PREVENTTIMESHEET: "false",
    PREVENTEXPENSE: "false",
    PREVENTAPPO: "false",
    PREVENTGENINVOICE: "false",
    STATUS: "active",
    BEGINDATE: "2019-01-01",
    ENDDATE: "2022-12-31",
    BUDGETAMOUNT: "",
    CONTRACTAMOUNT: "",
    ACTUALAMOUNT: "",
    BUDGETQTY: "",
    ESTQTY: "",
    ACTUALQTY: "",
    APPROVEDQTY: "",
    REMAININGQTY: "",
    PERCENTCOMPLETE: "",
    OBSPERCENTCOMPLETE: "0",
    BILLINGTYPE: "",
    SONUMBER: "",
    PONUMBER: "",
    POAMOUNT: "",
    PQNUMBER: "",
    SFDCKEY: "",
    QARROWKEY: "",
    OAKEY: "",
    PARENTKEY: "",
    PARENTID: "",
    PARENTNAME: "",
    INVOICEWITHPARENT: "false",
    CUSTOMERKEY: "",
    CUSTOMERID: "",
    CUSTOMERNAME: "",
    SALESCONTACTKEY: "",
    SALESCONTACTID: "",
    SALESCONTACTNAME: "",
    PROJECTTYPEKEY: "",
    PROJECTTYPE: "",
    MANAGERKEY: "",
    MANAGERID: "",
    MANAGERCONTACTNAME: "",
    PROJECTDEPTKEY: "",
    DEPARTMENTID: "",
    DEPARTMENTNAME: "",
    PROJECTLOCATIONKEY: "3",
    LOCATIONID: "",
    LOCATIONNAME: "",
    CONTACTINFO: {
      CONTACTNAME: "",
    },
    SHIPTO: {
      CONTACTNAME: "",
    },
    BILLTO: {
      CONTACTNAME: "",
    },
    TERMSKEY: "",
    TERMNAME: "",
    DOCNUMBER: "",
    CUSTUSERKEY: "",
    CUSTUSERID: "",
    WHENCREATED: "2021-02-09T15:50:29Z",
    WHENMODIFIED: "2021-03-01T16:33:10Z",
    CREATEDBY: "4",
    MODIFIEDBY: "4",
    BUDGETEDCOST: "",
    CLASSID: "",
    CLASSNAME: "",
    CLASSKEY: "",
    USERRESTRICTIONS: "System Default",
    BILLABLEEXPDEFAULT: "false",
    BILLABLEAPPODEFAULT: "false",
    BUDGETID: "",
    BUDGETKEY: "",
    BILLINGRATE: "",
    BILLINGPRICING: "Billing rate",
    EXPENSERATE: "0",
    EXPENSEPRICING: "Cost plus fee",
    POAPRATE: "0",
    POAPPRICING: "Cost plus fee",
    CONTACTKEY: "",
    SHIPTOKEY: "",
    BILLTOKEY: "",
    INVOICEMESSAGE: "",
    INVOICECURRENCY: "",
    BILLINGOVERMAX: "Do nothing",
    EXCLUDEEXPENSES: "false",
    CONTRACTKEY: "",
    CONTRACTID: "",
    ROOTPARENTKEY: "2",
    ROOTPARENTID: "21-1234",
    ROOTPARENTNAME: "Sample Project",
    MEGAENTITYKEY: "",
    MEGAENTITYID: "",
    MEGAENTITYNAME: "",
  },
};
