export const userSchema = {
  type: "object" as const,
  properties: {
    kind: { type: "string" },
    displayName: { type: "string" },
    photoLink: { type: "string" },
    me: { type: "boolean" },
    permissionId: { type: "string" },
    emailAddress: { type: "string" },
  },
  required: [],
};
export const permissionSchema = {
  type: "object" as const,
  properties: {
    id: { type: "string" },
    displayName: { type: "string" },
    type: { type: "string" },
    kind: { type: "string" },
    permissionDetails: {
      type: "array",
      items: {
        type: "object",
        properties: {
          permissionType: { type: "string" },
          inheritedFrom: { type: "string" },
          role: { type: "string" },
          inherited: { type: "boolean" },
        },
        required: [],
      },
    },
    photoLink: { type: "string" },
    emailAddress: { type: "string" },
    role: { type: "string" },
    allowFileDiscovery: { type: "boolean" },
    domain: { type: "string" },
    expirationTime: { type: "string", format: "date-time" },
    teamDrivePermissionDetails: {
      type: "array",
      items: {
        type: "object",
        properties: {
          teamDrivePermissionType: { type: "string" },
          inheritedFrom: { type: "string" },
          role: { type: "string" },
          inherited: { type: "boolean" },
        },
        required: [],
      },
    },
    deleted: { type: "boolean" },
    view: { type: "string" },
    pendingOwner: { type: "boolean" },
    inheritedPermissionsDisabled: { type: "boolean" },
  },
  required: [],
};
export const contentRestrictionSchema = {
  type: "object" as const,
  properties: {
    readOnly: { type: "boolean" },
    reason: { type: "string" },
    type: { type: "string" },
    restrictingUser: userSchema,
    restrictionTime: { type: "string", format: "date-time" },
    ownerRestricted: { type: "boolean" },
    systemRestricted: { type: "boolean" },
  },
  required: [],
};
export const labelFieldSchema = {
  type: "object" as const,
  properties: {
    kind: { type: "string" },
    id: { type: "string" },
    valueType: { type: "string" },
    dateString: { type: "array", items: { type: "string", format: "date" } },
    integer: { type: "array", items: { type: "string" } },
    selection: { type: "array", items: { type: "string" } },
    text: { type: "array", items: { type: "string" } },
    user: { type: "array", items: userSchema },
  },
  required: [],
};
export const labelSchema = {
  type: "object" as const,
  properties: {
    kind: { type: "string" },
    id: { type: "string" },
    revisionId: { type: "string" },
    fields: { type: "object", additionalProperties: labelFieldSchema },
  },
  required: [],
};
export const downloadRestrictionSchema = {
  type: "object" as const,
  properties: {
    restrictedForReaders: { type: "boolean" },
    restrictedForWriters: { type: "boolean" },
  },
  required: [],
};
export const driveSchema = {
  type: "object" as const,
  properties: {
    id: { type: "string" },
    name: { type: "string" },
    colorRgb: { type: "string" },
    kind: { type: "string" },
    backgroundImageFile: {
      type: "object",
      properties: {
        id: { type: "string" },
        xCoordinate: { type: "number" },
        yCoordinate: { type: "number" },
        width: { type: "number" },
      },
      required: [],
    },
    backgroundImageLink: { type: "string" },
    capabilities: {
      type: "object",
      properties: {
        canAddChildren: { type: "boolean" },
        canComment: { type: "boolean" },
        canCopy: { type: "boolean" },
        canDeleteDrive: { type: "boolean" },
        canDownload: { type: "boolean" },
        canEdit: { type: "boolean" },
        canListChildren: { type: "boolean" },
        canManageMembers: { type: "boolean" },
        canReadRevisions: { type: "boolean" },
        canRename: { type: "boolean" },
        canRenameDrive: { type: "boolean" },
        canChangeDriveBackground: { type: "boolean" },
        canShare: { type: "boolean" },
        canChangeCopyRequiresWriterPermissionRestriction: { type: "boolean" },
        canChangeDomainUsersOnlyRestriction: { type: "boolean" },
        canChangeDriveMembersOnlyRestriction: { type: "boolean" },
        canChangeSharingFoldersRequiresOrganizerPermissionRestriction: {
          type: "boolean",
        },
        canResetDriveRestrictions: { type: "boolean" },
        canDeleteChildren: { type: "boolean" },
        canTrashChildren: { type: "boolean" },
      },
      required: [],
    },
    themeId: { type: "string" },
    createdTime: { type: "string", format: "date-time" },
    hidden: { type: "boolean" },
    restrictions: {
      type: "object",
      properties: {
        copyRequiresWriterPermission: { type: "boolean" },
        domainUsersOnly: { type: "boolean" },
        driveMembersOnly: { type: "boolean" },
        adminManagedRestrictions: { type: "boolean" },
        sharingFoldersRequiresOrganizerPermission: { type: "boolean" },
        downloadRestriction: downloadRestrictionSchema,
      },
      required: [],
    },
    orgUnitId: { type: "string" },
  },
  required: [],
};
export const fileSchema = {
  type: "object" as const,
  properties: {
    kind: { type: "string" },
    driveId: { type: "string" },
    fileExtension: { type: "string" },
    copyRequiresWriterPermission: { type: "boolean" },
    md5Checksum: { type: "string" },
    contentHints: {
      type: "object",
      properties: {
        thumbnail: {
          type: "object",
          properties: {
            image: { type: "string" },
            mimeType: { type: "string" },
          },
          required: [],
        },
        indexableText: { type: "string" },
      },
      required: [],
    },
    writersCanShare: { type: "boolean" },
    viewedByMe: { type: "boolean" },
    mimeType: { type: "string" },
    exportLinks: { type: "object", additionalProperties: { type: "string" } },
    parents: { type: "array", items: { type: "string" } },
    thumbnailLink: { type: "string" },
    iconLink: { type: "string" },
    shared: { type: "boolean" },
    lastModifyingUser: userSchema,
    owners: { type: "array", items: userSchema },
    headRevisionId: { type: "string" },
    sharingUser: userSchema,
    webViewLink: { type: "string" },
    webContentLink: { type: "string" },
    size: { type: "string" },
    viewersCanCopyContent: { type: "boolean" },
    permissions: { type: "array", items: permissionSchema },
    hasThumbnail: { type: "boolean" },
    spaces: { type: "array", items: { type: "string" } },
    folderColorRgb: { type: "string" },
    id: { type: "string" },
    name: { type: "string" },
    description: { type: "string" },
    starred: { type: "boolean" },
    trashed: { type: "boolean" },
    explicitlyTrashed: { type: "boolean" },
    createdTime: { type: "string", format: "date-time" },
    modifiedTime: { type: "string", format: "date-time" },
    modifiedByMeTime: { type: "string", format: "date-time" },
    viewedByMeTime: { type: "string", format: "date-time" },
    sharedWithMeTime: { type: "string", format: "date-time" },
    quotaBytesUsed: { type: "string" },
    version: { type: "string" },
    originalFilename: { type: "string" },
    ownedByMe: { type: "boolean" },
    fullFileExtension: { type: "string" },
    properties: { type: "object", additionalProperties: { type: "string" } },
    appProperties: { type: "object", additionalProperties: { type: "string" } },
    isAppAuthorized: { type: "boolean" },
    capabilities: {
      type: "object",
      properties: {
        canChangeViewersCanCopyContent: { type: "boolean" },
        canMoveChildrenOutOfDrive: { type: "boolean" },
        canReadDrive: { type: "boolean" },
        canEdit: { type: "boolean" },
        canCopy: { type: "boolean" },
        canComment: { type: "boolean" },
        canAddChildren: { type: "boolean" },
        canDelete: { type: "boolean" },
        canDownload: { type: "boolean" },
        canListChildren: { type: "boolean" },
        canRemoveChildren: { type: "boolean" },
        canRename: { type: "boolean" },
        canTrash: { type: "boolean" },
        canReadRevisions: { type: "boolean" },
        canChangeCopyRequiresWriterPermission: { type: "boolean" },
        canMoveItemIntoTeamDrive: { type: "boolean" },
        canUntrash: { type: "boolean" },
        canModifyContent: { type: "boolean" },
        canMoveItemWithinTeamDrive: { type: "boolean" },
        canMoveItemOutOfTeamDrive: { type: "boolean" },
        canDeleteChildren: { type: "boolean" },
        canMoveChildrenOutOfTeamDrive: { type: "boolean" },
        canMoveChildrenWithinTeamDrive: { type: "boolean" },
        canTrashChildren: { type: "boolean" },
        canMoveItemOutOfDrive: { type: "boolean" },
        canAddMyDriveParent: { type: "boolean" },
        canRemoveMyDriveParent: { type: "boolean" },
        canMoveItemWithinDrive: { type: "boolean" },
        canShare: { type: "boolean" },
        canMoveChildrenWithinDrive: { type: "boolean" },
        canModifyContentRestriction: { type: "boolean" },
        canAddFolderFromAnotherDrive: { type: "boolean" },
        canChangeSecurityUpdateEnabled: { type: "boolean" },
        canAcceptOwnership: { type: "boolean" },
        canReadLabels: { type: "boolean" },
        canModifyLabels: { type: "boolean" },
        canRemoveContentRestriction: { type: "boolean" },
        canDisableInheritedPermissions: { type: "boolean" },
        canEnableInheritedPermissions: { type: "boolean" },
        canModifyEditorContentRestriction: { type: "boolean" },
        canModifyOwnerContentRestriction: { type: "boolean" },
        canMoveTeamDriveItem: { type: "boolean" },
        canReadTeamDrive: { type: "boolean" },
      },
      required: [],
    },
    hasAugmentedPermissions: { type: "boolean" },
    trashingUser: userSchema,
    thumbnailVersion: { type: "string" },
    trashedTime: { type: "string", format: "date-time" },
    modifiedByMe: { type: "boolean" },
    permissionIds: { type: "array", items: { type: "string" } },
    imageMediaMetadata: {
      type: "object",
      properties: {
        flashUsed: { type: "boolean" },
        meteringMode: { type: "string" },
        sensor: { type: "string" },
        exposureMode: { type: "string" },
        colorSpace: { type: "string" },
        whiteBalance: { type: "string" },
        width: { type: "number" },
        height: { type: "number" },
        location: {
          type: "object",
          properties: {
            latitude: { type: "number" },
            longitude: { type: "number" },
            altitude: { type: "number" },
          },
          required: [],
        },
        rotation: { type: "number" },
        time: { type: "string" },
        cameraMake: { type: "string" },
        cameraModel: { type: "string" },
        exposureTime: { type: "number" },
        aperture: { type: "number" },
        focalLength: { type: "number" },
        isoSpeed: { type: "number" },
        exposureBias: { type: "number" },
        maxApertureValue: { type: "number" },
        subjectDistance: { type: "number" },
        lens: { type: "string" },
      },
      required: [],
    },
    videoMediaMetadata: {
      type: "object",
      properties: {
        width: { type: "number" },
        height: { type: "number" },
        durationMillis: { type: "string" },
      },
      required: [],
    },
    shortcutDetails: {
      type: "object",
      properties: {
        targetId: { type: "string" },
        targetMimeType: { type: "string" },
        targetResourceKey: { type: "string" },
      },
      required: [],
    },
    contentRestrictions: { type: "array", items: contentRestrictionSchema },
    resourceKey: { type: "string" },
    linkShareMetadata: {
      type: "object",
      properties: {
        securityUpdateEligible: { type: "boolean" },
        securityUpdateEnabled: { type: "boolean" },
      },
      required: [],
    },
    labelInfo: {
      type: "object",
      properties: {
        labels: { type: "array", items: labelSchema },
      },
      required: [],
    },
    sha1Checksum: { type: "string" },
    sha256Checksum: { type: "string" },
    inheritedPermissionsDisabled: { type: "boolean" },
    teamDriveId: { type: "string" },
  },
  required: [],
  additionalProperties: true,
};
export const fileListSchema = {
  type: "object" as const,
  properties: {
    kind: { type: "string", enum: ["drive#fileList"] },
    nextPageToken: { type: "string" },
    incompleteSearch: { type: "boolean" },
    files: { type: "array", items: fileSchema },
  },
  required: [],
  additionalProperties: true,
};
export const emptyResponseSchema = {
  type: "object" as const,
  properties: {},
  required: [],
};
