#import "../../fragments/MetafieldDetails.gql"
mutation SetMetafield($metafields: [MetafieldsSetInput!]!) {
  metafieldsSet(metafields: $metafields) {
    metafields {
      ...MetafieldDetails
    }
    userErrors {
      field
      message
    }
  }
}
