export const MAX_SUBSCRIPTION_EXPIRATION_MINUTES = 10070;
export const DEFAULT_SUBSCRIPTION_EXPIRATION_MINUTES =
  MAX_SUBSCRIPTION_EXPIRATION_MINUTES;

export const MAX_SUBSCRIPTION_EXPIRATION = {
  DEFAULT: 4230,
  CHAT: 60,
  PRESENCE: 60,
  SECURITY: 43200,
  TEAMS_CHANNEL: 60,
} as const;
