import type { ServiceBusMessage } from "@azure/service-bus";
import { action, input, util } from "@prismatic-io/spectral";
import { azureServiceBusClientLibrary } from "../../client";
import {
  sendMessageToQueueExamplePayload,
  sendMessagesToQueueExamplePayload,
} from "../../examplePayloads";
import {
  connection,
  messages,
  namespaceName,
  queueName,
  resourceGroupName,
  subscriptionId,
} from "../../inputs";

export const sendMessagesToQueue = action({
  display: {
    label: "Send Multiple Messages to Queue",
    description: "Send multiple plain text messages to a queue.",
  },
  examplePayload: sendMessagesToQueueExamplePayload,
  perform: async (
    context,
    { connection, messages, queueName, namespaceName },
  ) => {
    const client = azureServiceBusClientLibrary(connection, namespaceName);
    const sender = client.createSender(queueName);
    const mappedMessages = messages.map((message) => ({ body: message }));
    await sender.sendMessages(mappedMessages);
    return {
      data: mappedMessages,
    };
  },
  inputs: {
    connection,
    subscriptionId: { ...subscriptionId, required: false },
    resourceGroupName: { ...resourceGroupName, required: false },
    namespaceName,
    queueName,
    messages,
  },
});

export const sendMessageToQueue = action({
  display: {
    label: "Send Message to Queue",
    description: "Send a single message to a queue.",
  },
  examplePayload: sendMessageToQueueExamplePayload,
  perform: async (context, params) => {
    const client = azureServiceBusClientLibrary(
      params.connection,
      params.namespaceName,
    );
    const sender = client.createSender(params.queueName);
    const message: ServiceBusMessage = {
      body: params.body,
      contentType: params.contentType,
      messageId: params.messageId,
      partitionKey: params.partitionKey,
      replyTo: params.replyTo,
      scheduledEnqueueTimeUtc: params.scheduledEnqueueTimeUtc,
      subject: params.subject,
      to: params.to,
    };
    await sender.sendMessages(message);
    return {
      data: message,
    };
  },
  inputs: {
    connection,
    subscriptionId: { ...subscriptionId, required: false },
    resourceGroupName: { ...resourceGroupName, required: false },
    namespaceName,
    queueName,
    body: input({
      label: "Body",
      type: "string",
      required: true,
      comments: "The body of the message.",
    }),
    contentType: input({
      label: "Content Type",
      type: "string",
      comments: "The content type of the message.",
      example: "application/json",
      required: false,
      clean: (val) => util.types.toString(val) || undefined,
    }),
    messageId: input({
      label: "Message ID",
      type: "string",
      comments:
        "An optional unique ID of the message to be used for deduplication. If omitted, a unique ID will be generated by Microsoft.",
      required: false,
      clean: (val) => util.types.toString(val) || undefined,
    }),
    partitionKey: input({
      label: "Partition Key",
      type: "string",
      comments:
        "An optional partition key https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusmessage.partitionkey",
      required: false,
      clean: (val) => util.types.toString(val) || undefined,
    }),
    replyTo: input({
      label: "Reply To",
      type: "string",
      comments:
        "An optional address that the receiver can use to reply to the message. https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusmessage.replyto",
      required: false,
      clean: (val) => util.types.toString(val) || undefined,
    }),
    scheduledEnqueueTimeUtc: input({
      label: "Scheduled Enqueue Time UTC",
      type: "string",
      comments:
        "An optional time at which the message should be enqueued. If omitted, the message will be enqueued immediately.",
      required: false,
      clean: (val) => (val ? util.types.toDate(val) : undefined),
    }),
    subject: input({
      label: "Subject",
      type: "string",
      comments: "An optional subject for the message.",
      required: false,
      clean: (val) => util.types.toString(val) || undefined,
    }),
    to: input({
      label: "To",
      type: "string",
      comments:
        "An optional address that specifies the intended recipient of the message. https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusmessage.to",
      required: false,
      clean: (val) => util.types.toString(val) || undefined,
    }),
  },
});

export default { sendMessagesToQueue, sendMessageToQueue };
