import { action, input } from "@prismatic-io/spectral";
import { createClient } from "../../client";
import {
  clustering,
  connectionInput,
  datasetId,
  defaultCollation,
  defaultRoundingMode,
  description,
  encryptionConfiguration,
  expirationTime,
  externalDataConfiguration,
  friendlyName,
  kind,
  labels,
  materializedView,
  maxStaleness,
  projectId,
  rangePartitioning,
  requirePartitionFilter,
  schema,
  tableReference,
  tableView,
  timePartitioning,
} from "../../inputs";

export const createTable = action({
  display: {
    description: "Creates a new, empty table in the dataset.",
    label: "Create Table",
  },
  inputs: {
    connectionInput,
    kind,
    tableReference,
    friendlyName,
    description,
    labels,
    schema,
    timePartitioning,
    rangePartitioning,
    clustering,
    requirePartitionFilter,
    expirationTime,
    view: tableView,
    materializedView,
    externalDataConfiguration,
    encryptionConfiguration,
    defaultCollation,
    defaultRoundingMode,
    maxStaleness,
    datasetId: input({
      ...datasetId,
      required: true,
      comments: "Dataset ID of the table to update.",
    }),
    projectId: input({
      ...projectId,
      required: true,
      comments: "Project ID of the table to update.",
    }),
  },
  perform: async (
    _context,
    {
      connectionInput,
      datasetId,
      projectId,
      kind,
      tableReference,
      friendlyName,
      description,
      labels,
      schema,
      timePartitioning,
      rangePartitioning,
      clustering,
      requirePartitionFilter,
      expirationTime,
      view,
      materializedView,
      externalDataConfiguration,
      encryptionConfiguration,
      defaultCollation,
      defaultRoundingMode,
      maxStaleness,
    },
  ) => {
    const client = createClient(connectionInput);
    const { data } = await client.tables.insert({
      datasetId: datasetId || undefined,
      projectId: projectId || undefined,
      requestBody: {
        kind: kind || undefined,
        tableReference: tableReference || undefined,
        friendlyName: friendlyName || undefined,
        description: description || undefined,
        labels: labels || undefined,
        schema: schema || undefined,
        timePartitioning: timePartitioning || undefined,
        rangePartitioning: rangePartitioning || undefined,
        clustering: clustering || undefined,
        requirePartitionFilter,
        expirationTime: expirationTime || undefined,
        view: view || undefined,
        materializedView: materializedView || undefined,
        externalDataConfiguration: externalDataConfiguration || undefined,
        encryptionConfiguration: encryptionConfiguration || undefined,
        defaultCollation: defaultCollation || undefined,
        defaultRoundingMode: defaultRoundingMode || undefined,
        maxStaleness: maxStaleness || undefined,
      },
    });
    return {
      data,
    };
  },
});
