import { input, structuredObjectInput, util } from "@prismatic-io/spectral";
import { toOptionalBoolean, toOptionalString } from "../util";
import {
  connectionInput,
  pagination,
  projectId,
  searchString,
  timeout,
  userId,
  workbookId,
} from "./common";
const workbookName = input({
  label: "Workbook Name",
  type: "string",
  required: true,
  comments: "The display name shown for the workbook in Tableau.",
  example: "My Workbook",
  placeholder: "Enter workbook name",
  clean: util.types.toString,
});
const showTabs = input({
  label: "Show Tabs",
  type: "boolean",
  required: false,
  default: "false",
  comments: "When true, the updated workbook shows views in tabs.",
  clean: toOptionalBoolean,
});
const workbookSearchField = input({
  label: "Search Field",
  type: "string",
  required: true,
  comments: "The field to search.",
  example: "Tags",
  clean: util.types.toString,
  model: [
    { label: "Name", value: "name" },
    { label: "Owner Name", value: "ownerName" },
    { label: "Tags", value: "tags" },
  ],
});
const filterOperator = input({
  label: "Filter Operator",
  type: "string",
  required: true,
  comments: "The operator to use when searching.",
  example: "eq",
  clean: util.types.toString,
  model: [
    { label: "Equals", value: "eq" },
    { label: "In", value: "in" },
  ],
});
const uploadSessionId = input({
  label: "Upload Session ID",
  type: "string",
  required: false,
  comments:
    "When committing a file that was uploaded in parts, this value contains the upload session ID generated by a call to Initiate File Upload.",
  example: "12ab34cd-5e67-8f90-1234-56789abcdef0",
  placeholder: "Enter upload session ID",
  clean: toOptionalString,
});
const workbookType = input({
  label: "Workbook Type",
  type: "string",
  required: false,
  comments:
    "The file format of the uploaded workbook: twb for a workbook file or twbx for a packaged workbook file.",
  model: [
    { label: "", value: "" },
    { label: "twb", value: "twb" },
    { label: "twbx", value: "twbx" },
  ],
  default: "",
  clean: util.types.toString,
});
const overwrite = input({
  label: "Overwrite",
  type: "boolean",
  required: false,
  comments:
    "When true, overwrites a workbook that has the same name. When false, the request fails if the specified workbook already exists.",
  default: "false",
  clean: util.types.toBool,
});
const asJob = input({
  label: "As Job",
  type: "boolean",
  required: false,
  comments:
    "When false, the workbook publishing process runs synchronously and may time out for very large workbooks. When true, the process runs asynchronously and a job starts to perform the publishing process and return the job ID.",
  default: "false",
  clean: util.types.toBool,
});
const skipConnectionCheck = input({
  label: "Skip Connection Check",
  type: "boolean",
  required: false,
  comments:
    "When true, the Tableau server does not check whether a non-published connection of a workbook is reachable.",
  default: "false",
  clean: util.types.toBool,
});
const publishOptions = structuredObjectInput({
  label: "Publish Options",
  required: false,
  comments:
    "Upload session, file type, and publishing behavior controls for the workbook.",
  inputs: {
    uploadSessionId,
    workbookType,
    overwrite,
    asJob,
    skipConnectionCheck,
  },
});
const workbookXml = input({
  label: "Workbook XML",
  type: "code",
  language: "xml",
  required: true,
  comments:
    "The XML request body describing the workbook to publish. Must be a valid tsRequest document.",
  example: `<tsRequest>
  <workbook name="workbook-name">
      <project id="project-id"></project>
  </workbook>
</tsRequest>`,
  clean: util.types.toString,
});
const workbookFileContents = input({
  label: "Workbook File Contents",
  type: "data",
  required: true,
  comments: "The twbx file to upload as binary data.",
  clean: util.types.toBufferDataPayload,
});
export const listWorkbooksInputs = {
  timeout,
  pagination,
  tableauConnection: connectionInput,
};
export const searchWorkbooksInputs = {
  searchField: workbookSearchField,
  filterOperator: filterOperator,
  searchString: { ...searchString, example: "Tag 1, Tag 2, My 3rd Tag" },
  timeout,
  tableauConnection: connectionInput,
  pagination,
};
export const getWorkbookInputs = {
  workbookId,
  timeout,
  tableauConnection: connectionInput,
};
export const deleteWorkbookInputs = {
  workbookId,
  timeout,
  tableauConnection: connectionInput,
};
export const publishWorkbookInputs = {
  timeout,
  tableauConnection: connectionInput,
  publishOptions,
  workbookXml,
  workbookFileContents,
};
export const updateWorkbookInputs = {
  workbookId,
  workbookName,
  projectId,
  userId,
  showTabs,
  timeout,
  tableauConnection: connectionInput,
};
