import { action } from "@prismatic-io/spectral";
import { createZoomClient } from "../../client";
import {
  connection,
  userId,
  topic,
  meetingType,
  startTime,
  duration,
  timezone,
  password,
  agenda,
  recurrence,
  repeatInterval,
  weeklyDay,
  monthlyDay,
  monthlyWeek,
  monthlyWeekDay,
  endDateTime,
  hostVideo,
  participantVideo,
  joinBeforeHost,
  muteUponEntry,
  watermark,
  usePMI,
  approvalType,
  registrationType,
  registrationEmailNotifications,
  audio,
  autoRecording,
  availableDialInCountries,
  defaultPassword,
  preSchedule,
  endTimes,
  scheduleFor,
  settingsExtraFields,
  templateId,
  trackingFields,
} from "../../inputs";
import { createMeetingExamplePayload } from "../../examplePayloads";

export const createMeeting = action({
  display: {
    label: "Create Meeting",
    description: "Create a new meeting with an existing user as the host",
  },
  perform: async (
    { debug: { enabled: debug } },
    {
      connection,
      userId,
      topic,
      meetingType,
      startTime,
      duration,
      timezone,
      password,
      agenda,
      recurrence,
      repeatInterval,
      weeklyDay,
      monthlyDay,
      monthlyWeek,
      monthlyWeekDay,
      endDateTime,
      hostVideo,
      participantVideo,
      joinBeforeHost,
      muteUponEntry,
      watermark,
      usePMI,
      approvalType,
      registrationType,
      registrationEmailNotifications,
      settingsExtraFields,
      audio,
      autoRecording,
      availableDialInCountries,
      defaultPassword,
      preSchedule,
      endTimes,
      scheduleFor,
      templateId,
      trackingFields,
    },
  ) => {
    const client = createZoomClient({
      connection,
      debug,
    });

    const meetingData = {
      agenda,
      default_password: defaultPassword,
      duration,
      password,
      pre_schedule: preSchedule,
      recurrence: recurrence
        ? {
            end_date_time: endDateTime,
            end_times: endTimes,
            monthly_day: monthlyDay,
            monthly_week: monthlyWeek,
            monthly_week_day: monthlyWeekDay,
            repeat_interval: repeatInterval,
            type: recurrence,
            weekly_days: weeklyDay,
          }
        : undefined,
      schedule_for: scheduleFor,
      settings: {
        host_video: hostVideo,
        participant_video: participantVideo,
        join_before_host: joinBeforeHost,
        mute_upon_entry: muteUponEntry,
        watermark: watermark,
        use_pmi: usePMI,
        approval_type: approvalType,
        registration_type: registrationType,
        audio,
        auto_recording: autoRecording,
        global_dial_in_countries: availableDialInCountries,
        registrants_email_notification: registrationEmailNotifications,
        ...(settingsExtraFields || {}),
      },
      start_time: startTime,
      template_id: templateId,
      timezone,
      topic,
      tracking_fields: trackingFields,
      type: meetingType,
    };

    const { data } = await client.post(
      `/users/${userId}/meetings`,
      meetingData,
    );

    return {
      data,
    };
  },
  inputs: {
    connection,
    userId,
    topic: { ...topic, comments: "The meeting's topic." },
    meetingType,
    startTime,
    duration,
    timezone: {
      ...timezone,
      comments:
        "The timezone to assign to the 'Start Time' input value. This field is only used for scheduled or recurring meetings with a fixed time. For a list of supported timezones and their formats, see https://developers.zoom.us/docs/api/rest/other-references/abbreviation-lists/#timezones",
    },
    password,
    agenda,
    recurrence: { ...recurrence, required: false },
    repeatInterval,
    weeklyDay,
    monthlyDay,
    monthlyWeek,
    monthlyWeekDay,
    endDateTime,
    hostVideo,
    participantVideo,
    joinBeforeHost,
    muteUponEntry,
    watermark,
    usePMI,
    approvalType,
    registrationType,
    registrationEmailNotifications,
    settingsExtraFields,
    audio,
    autoRecording,
    availableDialInCountries,
    defaultPassword,
    preSchedule,
    endTimes,
    scheduleFor,
    templateId,
    trackingFields,
  },
  examplePayload: createMeetingExamplePayload,
});
