import { action } from "@prismatic-io/spectral";
import { createZoomClient } from "../../client";
import {
  connection,
  topic,
  meetingType,
  startTime,
  duration,
  timezone,
  password,
  agenda,
  recurrence,
  repeatInterval,
  weeklyDay,
  monthlyDay,
  monthlyWeek,
  monthlyWeekDay,
  endDateTime,
  hostVideo,
  participantVideo,
  joinBeforeHost,
  muteUponEntry,
  watermark,
  usePMI,
  approvalType,
  registrationType,
  registrationEmailNotifications,
  audio,
  autoRecording,
  availableDialInCountries,
  meetingId,
  occurrenceIdQuery,
  preSchedule,
  scheduleFor,
  endTimes,
  settingsExtraFields,
  templateId,
  trackingFields,
} from "../../inputs";

export const updateMeeting = action({
  display: {
    label: "Update Meeting",
    description:
      "Update the information and metadata of an existing meeting by Id",
  },
  perform: async (
    { debug: { enabled: debug } },
    {
      connection,
      meetingId,
      topic,
      meetingType,
      startTime,
      duration,
      timezone,
      password,
      agenda,
      recurrence,
      repeatInterval,
      weeklyDay,
      monthlyDay,
      monthlyWeek,
      monthlyWeekDay,
      endDateTime,
      hostVideo,
      participantVideo,
      joinBeforeHost,
      muteUponEntry,
      watermark,
      usePMI,
      approvalType,
      registrationType,
      registrationEmailNotifications,
      settingsExtraFields,
      audio,
      autoRecording,
      availableDialInCountries,
      preSchedule,
      endTimes,
      scheduleFor,
      templateId,
      trackingFields,
      occurrenceIdQuery,
    },
  ) => {
    const client = createZoomClient({ connection, debug });

    const { data } = await client.patch(
      `/meetings/${meetingId}`,
      {
        agenda,
        duration,
        password,
        pre_schedule: preSchedule,
        schedule_for: scheduleFor,
        recurrence: {
          end_date_time: endDateTime,
          end_times: endTimes,
          monthly_day: monthlyDay,
          monthly_week: monthlyWeek,
          monthly_week_day: monthlyWeekDay,
          repeat_interval: repeatInterval,
          type: recurrence,
          weekly_days: weeklyDay,
        },
        settings: {
          host_video: hostVideo,
          participant_video: participantVideo,
          join_before_host: joinBeforeHost,
          mute_upon_entry: muteUponEntry,
          watermark: watermark,
          use_pmi: usePMI,
          approval_type: approvalType,
          registration_type: registrationType,
          audio,
          auto_recording: autoRecording,
          global_dial_in_countries: availableDialInCountries,
          registrants_email_notification: registrationEmailNotifications,
          ...(settingsExtraFields || {}),
        },
        start_time: startTime,
        template_id: templateId,
        timezone,
        topic,
        tracking_fields: trackingFields,
        type: meetingType,
      },
      { params: { occurrence_id: occurrenceIdQuery } },
    );

    return {
      data,
    };
  },
  inputs: {
    connection,
    meetingId,
    meetingType,
    recurrence,
    topic,
    startTime,
    duration,
    timezone,
    password,
    preSchedule,
    scheduleFor,
    templateId,
    agenda,
    repeatInterval,
    weeklyDay,
    monthlyDay,
    monthlyWeek,
    monthlyWeekDay,
    endDateTime,
    endTimes,
    hostVideo,
    participantVideo,
    joinBeforeHost,
    muteUponEntry,
    watermark,
    usePMI,
    approvalType,
    registrationType,
    registrationEmailNotifications,
    settingsExtraFields,
    audio,
    autoRecording,
    availableDialInCountries,
    occurrenceIdQuery,
    trackingFields,
  },
  examplePayload: { data: {} },
});
