import { userMiniSchema } from "./common";
const webhookTargetSchema = {
  type: "object" as const,
  properties: {
    id: { type: "string" },
    type: { type: "string", enum: ["file", "folder"] },
  },
};
export const createWebhookOutputSchema = {
  type: ["object", "null"],
  properties: {
    id: { type: "string" },
    type: { type: "string", enum: ["webhook"] },
    target: webhookTargetSchema,
    created_by: userMiniSchema,
    created_at: { type: "string", format: "date-time" },
    address: { type: "string", format: "uri" },
    triggers: {
      type: "array",
      items: {
        type: "string",
        enum: [
          "FILE.UPLOADED",
          "FILE.PREVIEWED",
          "FILE.DOWNLOADED",
          "FILE.TRASHED",
          "FILE.DELETED",
          "FILE.RESTORED",
          "FILE.COPIED",
          "FILE.MOVED",
          "FILE.LOCKED",
          "FILE.UNLOCKED",
          "FILE.RENAMED",
          "COMMENT.CREATED",
          "COMMENT.UPDATED",
          "COMMENT.DELETED",
          "TASK_ASSIGNMENT.CREATED",
          "TASK_ASSIGNMENT.UPDATED",
          "METADATA_INSTANCE.CREATED",
          "METADATA_INSTANCE.UPDATED",
          "METADATA_INSTANCE.DELETED",
          "FOLDER.CREATED",
          "FOLDER.RENAMED",
          "FOLDER.DOWNLOADED",
          "FOLDER.RESTORED",
          "FOLDER.DELETED",
          "FOLDER.COPIED",
          "FOLDER.MOVED",
          "FOLDER.TRASHED",
          "WEBHOOK.DELETED",
          "COLLABORATION.CREATED",
          "COLLABORATION.ACCEPTED",
          "COLLABORATION.REJECTED",
          "COLLABORATION.REMOVED",
          "COLLABORATION.UPDATED",
          "SHARED_LINK.DELETED",
          "SHARED_LINK.CREATED",
          "SHARED_LINK.UPDATED",
          "SIGN_REQUEST.COMPLETED",
          "SIGN_REQUEST.DECLINED",
          "SIGN_REQUEST.EXPIRED",
          "SIGN_REQUEST.SIGNER_EMAIL_BOUNCED",
          "SIGN_REQUEST.SIGN_SIGNER_SIGNED",
          "SIGN_REQUEST.SIGN_DOCUMENT_CREATED",
          "SIGN_REQUEST.SIGN_ERROR_FINALIZING",
        ],
      },
    },
  },
  required: ["id", "type"],
};
export const listWebhooksOutputSchema = {
  type: "object" as const,
  properties: {
    limit: { type: "integer" },
    next_marker: { type: ["string", "null"] },
    entries: {
      type: "array",
      items: {
        type: "object",
        properties: {
          id: { type: "string" },
          type: { type: "string", enum: ["webhook"] },
          target: webhookTargetSchema,
        },
        required: ["id", "type"],
      },
    },
  },
  required: ["entries"],
};
