import { input, structuredObjectInput, util } from "@prismatic-io/spectral";
import { cleanString, toOptionalNumber } from "../utils";
export const owner = input({
  label: "Owner",
  type: "string",
  required: true,
  placeholder: "Enter repository owner",
  example: "octocat",
  clean: util.types.toString,
  comments:
    "The account owner of the repository. For example, in https://github.com/octocat/Hello-World, the owner is 'octocat'.",
  dataSource: "selectUserFromOrganization",
});
export const repo = input({
  label: "Repository Name",
  type: "string",
  required: true,
  placeholder: "Enter repository name",
  example: "Hello-World",
  clean: util.types.toString,
  comments:
    "The name of the repository. For example, in https://github.com/octocat/Hello-World, the repository name is 'Hello-World'.",
  dataSource: "listReposForAuthenticatedUser",
});
const githubEvents = [
  "commit_comment",
  "create",
  "delete",
  "deploy_key",
  "deployment",
  "deployment_status",
  "discussion",
  "discussion_comment",
  "fork",
  "github_app_authorization",
  "gollum",
  "installation",
  "installation_repositories",
  "issue_comment",
  "issues",
  "label",
  "marketplace_purchase",
  "member",
  "membership",
  "meta",
  "milestone",
  "organization",
  "org_block",
  "package",
  "page_build",
  "ping",
  "project",
  "project_card",
  "project_column",
  "projects_v2_item",
  "public",
  "pull_request",
  "pull_request_review",
  "pull_request_review_comment",
  "pull_request_review_thread",
  "push",
  "release",
  "repository_dispatch",
  "repository",
  "repository_import",
  "repository_vulnerability_alert",
  "security_advisory",
  "sponsorship",
  "star",
  "status",
  "team",
  "team_add",
  "watch",
  "workflow_dispatch",
  "workflow_job",
  "workflow_run",
];
export const events = input({
  label: "Events",
  type: "string",
  required: true,
  collection: "valuelist",
  placeholder: "Select event types",
  model: githubEvents.map((event) => ({ label: event, value: event })),
  comments: "The list of event types that will trigger the webhook.",
});
export const webhookSecretInput = input({
  label: "Webhook Secret",
  type: "string",
  required: false,
  clean: cleanString,
  comments:
    "An optional secret used to verify webhook authenticity. See [GitHub's documentation](https://docs.github.com/en/webhooks/using-webhooks/validating-webhook-deliveries) for details.",
});
export const connectionInput = input({
  label: "Connection",
  type: "connection",
  required: true,
});
export const perPage = input({
  label: "Per Page",
  type: "string",
  required: false,
  default: "30",
  placeholder: "Enter number of results per page",
  example: "30",
  clean: toOptionalNumber,
  comments: "The number of results per page (max 100)",
});
export const page = input({
  label: "Page",
  type: "string",
  required: false,
  default: "1",
  placeholder: "Enter page number",
  example: "1",
  clean: toOptionalNumber,
  comments: "Page number of the results to fetch",
});
export const fetchAll = input({
  label: "Fetch All",
  type: "boolean",
  required: false,
  default: "false",
  clean: util.types.toBool,
  comments: "When true, automatically fetches all pages of results.",
});
export const pagination = structuredObjectInput({
  label: "Pagination",
  required: false,
  comments: "Page number and results-per-page controls.",
  inputs: { page, perPage },
});
