export const ADD_FEATURES_EXAMPLE_PAYLOAD = {
  addResults: [
    { objectId: 17, uniqueId: 17, globalId: null, success: true },
    { objectId: 18, uniqueId: 18, globalId: null, success: true },
  ],
};

export const ADD_HOSTED_LAYER_TO_FEATURE_SERVICE_EXAMPLE_PAYLOAD = {
  success: true,
  layers: [{ name: "public_layer", id: 4 }],
};

export const CREATE_FEATURE_SERVICE_EXAMPLE_PAYLOAD = {
  encodedServiceURL:
    "https://services2.arcgis.com/ABCD12345abcd1234/arcgis/rest/services/Example/FeatureServer",
  itemId: "3d1f09bb8fbb4fa8926bf43d85f21234",
  name: "Example",
  serviceItemId: "3d1f09bb8fbb4fa8926bf43d85f21234",
  serviceurl:
    "https://services2.arcgis.com/ABCD12345abcd1234/arcgis/rest/services/Example/FeatureServer",
  size: -1,
  success: true,
  type: "Feature Service",
  typeKeywords: [],
  isView: false,
};

export const CREATE_WEB_MAP_EXAMPLE_PAYLOAD = {
  success: true,
  id: "2e1ac491fdcd4d7dbd7bd25418ea1234",
  folder: "",
};

export const EXPORT_LAYERS_EXAMPLE_PAYLOAD = {
  type: "file",
  size: 32768,
  jobId: "0312180b-45e1-4e0f-9e06-ac22957a4203::ABCD12345abcd1234",
  serviceItemId: "9a6c4ffffa8341619081987680312345",
  exportFormat: "Shapefile",
  exportItemId: "2123466496e645f488e63f3f37e12345",
};

export const GEOCODE_EXAMPLE_PAYLOAD = {
  spatialReference: { wkid: 4326, latestWkid: 4326 },
  candidates: [
    {
      address: "El Paso International Airport",
      location: {
        x: -106.37832,
        y: 31.80677,
        spatialReference: { wkid: 4326, latestWkid: 4326 },
      },
      score: 100,
      attributes: {},
      extent: {
        xmin: -106.40832,
        ymin: 31.77677,
        xmax: -106.34832,
        ymax: 31.83677,
        spatialReference: { wkid: 4326, latestWkid: 4326 },
      },
    },
    {
      address: "El Paso Intl Airport",
      location: {
        x: -106.376361111,
        y: 31.807333333,
        spatialReference: { wkid: 4326, latestWkid: 4326 },
      },
      score: 100,
      attributes: {},
      extent: {
        xmin: -106.401361111,
        ymin: 31.782333333,
        xmax: -106.351361111,
        ymax: 31.832333333,
        spatialReference: { wkid: 4326, latestWkid: 4326 },
      },
    },
    {
      address: "El Paso Int'l Airport",
      location: {
        x: -106.39353,
        y: 31.79799,
        spatialReference: { wkid: 4326, latestWkid: 4326 },
      },
      score: 100,
      attributes: {},
      extent: {
        xmin: -106.42153,
        ymin: 31.76999,
        xmax: -106.36553,
        ymax: 31.82599,
        spatialReference: { wkid: 4326, latestWkid: 4326 },
      },
    },
    {
      address: "El Paso Int'l Airport-Arrival",
      location: {
        x: -106.39594,
        y: 31.7989,
        spatialReference: { wkid: 4326, latestWkid: 4326 },
      },
      score: 95.23,
      attributes: {},
      extent: {
        xmin: -106.40094,
        ymin: 31.7939,
        xmax: -106.39094,
        ymax: 31.8039,
        spatialReference: { wkid: 4326, latestWkid: 4326 },
      },
    },
  ],
  geoJson: {
    type: "FeatureCollection",
    features: [
      {
        type: "Feature",
        geometry: { type: "Point", coordinates: [-106.37832, 31.80677] },
        properties: { address: "El Paso International Airport", score: 100 },
      },
      {
        type: "Feature",
        geometry: {
          type: "Point",
          coordinates: [-106.376361111, 31.807333333],
        },
        properties: { address: "El Paso Intl Airport", score: 100 },
      },
      {
        type: "Feature",
        geometry: { type: "Point", coordinates: [-106.39353, 31.79799] },
        properties: { address: "El Paso Int'l Airport", score: 100 },
      },
      {
        type: "Feature",
        geometry: { type: "Point", coordinates: [-106.39594, 31.7989] },
        properties: { address: "El Paso Int'l Airport-Arrival", score: 95.23 },
      },
    ],
  },
};

export const GET_ALL_LAYERS_AND_TABLES_EXAMPLE_PAYLOAD = {
  layers: [
    {
      currentVersion: 11.2,
      id: 0,
      name: "layer_name",
      type: "Feature Layer",
      serviceItemId: "9a6c4ffffa8341619081987680351bee",
      displayField: "",
      description: "",
      copyrightText: "",
      defaultVisibility: true,
      editingInfo: {
        lastEditDate: 1706742514371,
        schemaLastEditDate: 1706265068599,
        dataLastEditDate: 1706742514371,
      },
      relationships: [],
      isDataVersioned: false,
      hasContingentValuesDefinition: false,
      supportsAppend: true,
      supportsCalculate: true,
      supportsASyncCalculate: true,
      supportsTruncate: false,
      supportsAttachmentsByUploadId: true,
      supportsAttachmentsResizing: true,
      supportsRollbackOnFailureParameter: true,
      supportsStatistics: true,
      supportsExceedsLimitStatistics: true,
      supportsAdvancedQueries: true,
      supportsValidateSql: true,
      supportsCoordinatesQuantization: true,
      supportsLayerOverrides: true,
      supportsTilesAndBasicQueriesMode: true,
      supportsFieldDescriptionProperty: true,
      supportsQuantizationEditMode: true,
      supportsApplyEditsWithGlobalIds: false,
      supportsReturningQueryGeometry: true,
      advancedQueryCapabilities: {
        supportsPagination: true,
        supportsQueryAttachmentsCountOnly: true,
        supportsPaginationOnAggregatedQueries: true,
        supportsQueryRelatedPagination: true,
        supportsQueryWithDistance: true,
        supportsReturningQueryExtent: true,
        supportsStatistics: true,
        supportsOrderBy: true,
        supportsDistinct: true,
        supportsQueryWithResultType: true,
        supportsSqlExpression: true,
        supportsAdvancedQueryRelated: true,
        supportsCountDistinct: true,
        supportsPercentileStatistics: true,
        supportsSpatialAggregationStatistics: true,
        supportedSpatialAggregationStatistics: [
          "EnvelopeAggregate",
          "CentroidAggregate",
          "ConvexHullAggregate",
        ],
        supportsQueryAttachments: true,
        supportsLod: true,
        supportsQueryWithLodSR: false,
        supportedLodTypes: ["geohash"],
        supportsReturningGeometryCentroid: false,
        supportsReturningGeometryEnvelope: true,
        supportsQueryWithDatumTransformation: true,
        supportsCurrentUserQueries: true,
        supportsHavingClause: true,
        supportsOutFieldSQLExpression: true,
        supportsMaxRecordCountFactor: true,
        supportsTopFeaturesQuery: true,
        supportsDisjointSpatialRel: true,
        supportsQueryWithCacheHint: true,
        supportedOperationsWithCacheHint: [
          "query",
          "queryTopFilter",
          "queryAnalytics",
          "queryAttachments",
          "queryRelated",
        ],
        supportsQueryAttachmentsWithReturnUrl: true,
        supportsQueryAnalytic: true,
        supportsDefaultSR: true,
        supportsFullTextSearch: true,
      },
      advancedQueryAnalyticCapabilities: {
        supportsLinearRegression: true,
        supportsAsync: true,
        supportsPercentileAnalytic: true,
      },
      advancedEditingCapabilities: {
        supportedSqlFormatsInCalculate: ["standard"],
        supportsAsyncApplyEdits: true,
        supportsReturnEditResults: true,
        supportsApplyEditsbyUploadID: true,
        supportedApplyEditsUploadIDFormats: "JSON",
      },
      infoInEstimates: ["extent", "count"],
      useStandardizedQueries: true,
      geometryType: "esriGeometryPoint",
      minScale: 73957191,
      maxScale: 0,
      extent: {
        xmin: -134.74729261792592,
        ymin: 23.56096242376989,
        xmax: -55.69554761540939,
        ymax: 50.309217030288835,
        spatialReference: { wkid: 4326, latestWkid: 4326 },
      },
      drawingInfo: {
        transparency: 0,
        labelingInfo: null,
        renderer: {
          type: "simple",
          symbol: {
            color: [20, 158, 206, 130],
            size: 18,
            angle: 0,
            xoffset: 0,
            yoffset: 0,
            type: "esriSMS",
            style: "esriSMSCircle",
            outline: {
              color: [255, 255, 255, 220],
              width: 2.25,
              type: "esriSLS",
              style: "esriSLSSolid",
            },
          },
        },
      },
      allowGeometryUpdates: true,
      hasAttachments: true,
      attachmentProperties: [
        { name: "id", fieldName: "ATTACHMENTID", isEnabled: true },
        { name: "globalId", fieldName: "AttachmentGlobalID", isEnabled: true },
        { name: "name", fieldName: "ATT_NAME", isEnabled: true },
        { name: "size", fieldName: "DATA_SIZE", isEnabled: true },
        { name: "contentType", fieldName: "CONTENT_TYPE", isEnabled: true },
        { name: "keywords", fieldName: "Keywords", isEnabled: true },
        { name: "exifInfo", fieldName: "ExifInfo", isEnabled: true },
      ],
      htmlPopupType: "esriServerHTMLPopupTypeNone",
      hasM: false,
      hasZ: false,
      objectIdField: "OBJECTID",
      uniqueIdField: { name: "OBJECTID", isSystemMaintained: true },
      globalIdField: "",
      typeIdField: "",
      fields: [
        {
          name: "OBJECTID",
          type: "esriFieldTypeOID",
          alias: "OBJECTID",
          sqlType: "sqlTypeOther",
          nullable: false,
          editable: false,
          domain: null,
          defaultValue: null,
        },
        {
          name: "id",
          type: "esriFieldTypeInteger",
          alias: "id",
          sqlType: "sqlTypeInteger",
          nullable: true,
          editable: true,
          domain: null,
          defaultValue: null,
        },
        {
          name: "name",
          type: "esriFieldTypeString",
          alias: "name",
          sqlType: "sqlTypeNVarchar",
          length: 256,
          nullable: true,
          editable: true,
          domain: null,
          defaultValue: null,
        },
        {
          name: "rating",
          type: "esriFieldTypeString",
          alias: "rating",
          sqlType: "sqlTypeNVarchar",
          length: 256,
          nullable: true,
          editable: true,
          domain: null,
          defaultValue: null,
        },
      ],
      indexes: [
        {
          name: "Acme_Layers_MY_POINTS_Shape_sidx",
          fields: "Shape",
          isAscending: true,
          isUnique: false,
          description: "Shape Index",
          indexType: "Spatial",
        },
        {
          name: "PK__Prismati__F4B70D85EF1C08A2",
          fields: "OBJECTID",
          isAscending: true,
          isUnique: true,
          description: "clustered, unique, primary key",
          indexType: "Attribute",
        },
      ],
      dateFieldsTimeReference: {
        timeZone: "UTC",
        respectsDaylightSaving: false,
      },
      preferredTimeReference: null,
      types: [],
      templates: [
        {
          name: "New Feature",
          description: "",
          drawingTool: "esriFeatureEditToolPoint",
          prototype: { attributes: { id: null, name: null, rating: null } },
        },
      ],
      supportedQueryFormats: "JSON, geoJSON, PBF",
      supportedAppendFormats:
        "sqlite,geoPackage,shapefile,filegdb,featureCollection,geojson,csv,excel,jsonl,imageCollection",
      supportedExportFormats:
        "csv,shapefile,sqlite,geoPackage,filegdb,featureCollection,geojson,excel",
      supportedSpatialRelationships: [
        "esriSpatialRelIntersects",
        "esriSpatialRelContains",
        "esriSpatialRelCrosses",
        "esriSpatialRelEnvelopeIntersects",
        "esriSpatialRelIndexIntersects",
        "esriSpatialRelOverlaps",
        "esriSpatialRelTouches",
        "esriSpatialRelWithin",
        "esriSpatialRelDisjoint",
        "esriSpatialRelRelation",
      ],
      supportedContingentValuesFormats: "JSON, PBF",
      supportedSyncDataOptions: 4,
      hasStaticData: false,
      maxRecordCount: 10000,
      standardMaxRecordCount: 32000,
      standardMaxRecordCountNoGeometry: 32000,
      tileMaxRecordCount: 8000,
      maxRecordCountFactor: 1,
      capabilities: "Create,Delete,Query,Update,Editing",
    },
  ],
  tables: [],
};

export const GET_FEATURE_SERVICE_URL_EXAMPLE_PAYLOAD =
  "https://services2.arcgis.com/ABCD12345abcd1234/arcgis/rest/services/Search_location_layer/FeatureServer";

export const GET_LAYER_ID_EXAMPLE_PAYLOAD = [{ id: 0, name: "Layer_1" }];

export const LIST_FEATURE_SERVICES_EXAMPLE_PAYLOAD = {
  total: 3,
  start: 1,
  num: 10,
  nextStart: -1,
  results: [
    {
      id: "89d7c5f2d82b4e5dbf88d248011a1234",
      owner: "AnOwner",
      created: 1706260469000,
      isOrgItem: true,
      modified: 1706260487000,
      guid: null,
      name: "Test",
      title: "Test",
      type: "Feature Service",
      typeKeywords: [
        "ArcGIS Server",
        "Data",
        "Feature Access",
        "Feature Service",
        "Multilayer",
        "Service",
        "Hosted Service",
      ],
      description: null,
      tags: [],
      snippet: null,
      thumbnail: "thumbnail/ago_downloaded.png",
      documentation: null,
      extent: [
        [-18000000, -12000000],
        [18000000, 16000000],
      ],
      categories: [],
      spatialReference: "102100",
      accessInformation: null,
      classification: null,
      licenseInfo: null,
      culture: "",
      properties: null,
      advancedSettings: null,
      url: "https://services2.arcgis.com/ABCD12345abcd1234/arcgis/rest/services/Test/FeatureServer",
      proxyFilter: null,
      access: "private",
      size: -1,
      subInfo: 0,
      appCategories: [],
      industries: [],
      languages: [],
      largeThumbnail: null,
      banner: null,
      screenshots: [],
      listed: false,
      ownerFolder: null,
      protected: false,
      numComments: 0,
      numRatings: 0,
      avgRating: 0,
      numViews: 4,
      scoreCompleteness: 16,
      groupDesignations: null,
      tokenExpirationDate: -1,
      token2ExpirationDate: -1,
      lastViewed: 1706259600000,
    },
  ],
};

export const SEARCH_ITEMS_EXAMPLE_PAYLOAD = {
  total: 10000,
  start: 1,
  num: 1,
  nextStart: 2,
  results: [
    {
      id: "30e7dfdf98b84b8188d0af1a361e6e1c",
      owner: "MRA_Admin",
      created: 1518371873000,
      modified: 1645568035000,
      guid: null,
      name: "MRA_Mission_Data_2018_Public",
      title: "MRA Missions Public Layer - 2018 1e6e1c",
      type: "Feature Service",
      typeKeywords: [
        "ArcGIS Server",
        "Data",
        "Feature Access",
        "Feature Service",
        "Multilayer",
        "Service",
        "Hosted Service",
        "View Service",
      ],
      description: "<div>HTML description</div>",
      tags: [
        "MRA",
        "2018",
        "Mission Data",
        "Incident Data",
        "Layer",
        "Public",
        "1e6e1c",
      ],
      snippet:
        "This is the MRA Mission Data feature layer view for sharing with the Public (View Only). Not all fields are visible.",
      thumbnail: "thumbnail/thumbnail.png",
      documentation: null,
      extent: [
        [-167.827, 20.427],
        [-58.14, 71.897],
      ],
      categories: [],
      spatialReference: null,
      accessInformation: "Caroline Rose, Paul Doherty, Mark Johnson",
      classification: null,
      licenseInfo: "<div>HTML license info</div>",
      culture: "en-us",
      properties: null,
      advancedSettings: null,
      url: "https://services2.arcgis.com/4VBZFeVR0gsH1234/arcgis/rest/services/MRA_Mission_Data_2018_Public/FeatureServer",
      proxyFilter: null,
      access: "public",
      size: -1,
      subInfo: 0,
      appCategories: [],
      industries: [],
      languages: [],
      largeThumbnail: null,
      banner: null,
      screenshots: [],
      listed: false,
      numComments: 0,
      numRatings: 0,
      avgRating: 0,
      numViews: 28348,
      scoreCompleteness: 96,
      groupDesignations: null,
      tokenExpirationDate: -1,
      token2ExpirationDate: -1,
      lastViewed: 1706720400000,
    },
  ],
};
