export const listCompaniesResponse = {
  data: [
    {
      type: "company",
      company_id: "remote_companies_scroll_2",
      id: "6657add06abd0167d9419cc3",
      app_id: "this_is_an_id158_that_should_be_at_least_",
      name: "IntercomQATest1",
      remote_created_at: 1717022160,
      created_at: 1717022160,
      updated_at: 1717022160,
      monthly_spend: 0,
      session_count: 0,
      user_count: 4,
      tags: {
        type: "tag.list",
        tags: [],
      },
      segments: {
        type: "segment.list",
        segments: [],
      },
      plan: {},
      custom_attributes: {},
    },
  ],
  pages: {
    type: "companies",
    next: null,
    page: 1,
    per_page: 15,
    total_pages: 1,
  },
};

export const createTicketResponse = {
  type: "ticket",
  id: "773",
  ticket_id: "35",
  ticket_attributes: {
    _default_title_: "example",
    _default_description_: "there is a problem",
  },
  ticket_state: "submitted",
  ticket_state_internal_label: "Submitted",
  ticket_state_external_label: "Submitted",
  ticket_type: {
    type: "ticket_type",
    id: "147",
    name: "my-ticket-type-15",
    description: "my ticket type description is awesome.",
    icon: "🦁",
    workspace_id: "this_is_an_id648_that_should_be_at_least_",
    archived: false,
    created_at: 1717022465,
    updated_at: 1717022465,
    is_internal: false,
    ticket_type_attributes: {
      type: "list",
      data: [
        {
          type: "ticket_type_attribute",
          id: "388",
          workspace_id: "this_is_an_id648_that_should_be_at_least_",
          name: "_default_title_",
          description: "ola",
          data_type: "string",
          input_options: null,
          order: 0,
          required_to_create: true,
          required_to_create_for_contacts: false,
          visible_on_create: true,
          visible_to_contacts: false,
          default: false,
          ticket_type_id: 147,
          archived: false,
          created_at: 1717022465,
          updated_at: 1717022465,
        },
        {
          type: "ticket_type_attribute",
          id: "389",
          workspace_id: "this_is_an_id648_that_should_be_at_least_",
          name: "_default_description_",
          description: "ola",
          data_type: "string",
          input_options: null,
          order: 0,
          required_to_create: true,
          required_to_create_for_contacts: false,
          visible_on_create: true,
          visible_to_contacts: false,
          default: false,
          ticket_type_id: 147,
          archived: false,
          created_at: 1717022465,
          updated_at: 1717022465,
        },
      ],
    },
    category: "Back-office",
  },
  contacts: {
    type: "contact.list",
    contacts: [
      {
        type: "contact",
        id: "6657af026abd0167d9419def",
        external_id: "70",
      },
    ],
  },
  admin_assignee_id: "0",
  team_assignee_id: "0",
  created_at: 1717022466,
  updated_at: 1717022466,
  ticket_parts: {
    type: "ticket_part.list",
    ticket_parts: [
      {
        type: "ticket_part",
        id: "199",
        part_type: "ticket_state_updated_by_admin",
        ticket_state: "submitted",
        previous_ticket_state: "submitted",
        created_at: 1717022466,
        updated_at: 1717022466,
        author: {
          id: "991268827",
          type: "bot",
          name: "Operator",
          email:
            "operator+this_is_an_id648_that_should_be_at_least_@intercom.io",
        },
        attachments: [],
        redacted: false,
      },
    ],
    total_count: 1,
  },
  open: true,
  linked_objects: {
    type: "list",
    data: [],
    total_count: 0,
    has_more: false,
  },
  category: "Back-office",
  is_shared: false,
};

export const listTicketTypesResponse = {
  type: "list",
  data: [
    {
      type: "ticket_type",
      id: "126",
      name: "Bug Report",
      description: "Bug Report Template",
      icon: "🎟️",
      workspace_id: "this_is_an_id608_that_should_be_at_least_",
      archived: false,
      created_at: 1717022435,
      updated_at: 1717022435,
      is_internal: false,
      ticket_type_attributes: {
        type: "list",
        data: [
          {
            type: "ticket_type_attribute",
            id: "354",
            workspace_id: "this_is_an_id608_that_should_be_at_least_",
            name: "_default_title_",
            description: "",
            data_type: "string",
            input_options: {
              multiline: false,
            },
            order: 0,
            required_to_create: false,
            required_to_create_for_contacts: false,
            visible_on_create: true,
            visible_to_contacts: true,
            default: true,
            ticket_type_id: 126,
            archived: false,
            created_at: 1717022435,
            updated_at: 1717022435,
          },
          {
            type: "ticket_type_attribute",
            id: "356",
            workspace_id: "this_is_an_id608_that_should_be_at_least_",
            name: "name",
            description: "description",
            data_type: "string",
            input_options: null,
            order: 0,
            required_to_create: false,
            required_to_create_for_contacts: false,
            visible_on_create: false,
            visible_to_contacts: false,
            default: false,
            ticket_type_id: 126,
            archived: false,
            created_at: 1717022435,
            updated_at: 1717022435,
          },
          {
            type: "ticket_type_attribute",
            id: "355",
            workspace_id: "this_is_an_id608_that_should_be_at_least_",
            name: "_default_description_",
            description: "",
            data_type: "string",
            input_options: {
              multiline: true,
            },
            order: 1,
            required_to_create: false,
            required_to_create_for_contacts: false,
            visible_on_create: true,
            visible_to_contacts: true,
            default: true,
            ticket_type_id: 126,
            archived: false,
            created_at: 1717022435,
            updated_at: 1717022435,
          },
        ],
      },
      category: "Customer",
    },
  ],
};

export const listContactsResponse = {
  data: [
    {
      type: "contact",
      id: "5ba682d23d7cf92bef87bfd4",
      external_id: "f3b87a2e09d514c6c2e79b9a",
      workspace_id: "ecahpwf5",
      role: "user",
      email: "joe@example.com",
      email_domain: "example.com",
      phone: "+1123456789",
      formatted_phone: "+1123456789",
      name: "John Doe",
      owner_id: 123,
      has_hard_bounced: true,
      marked_email_as_spam: true,
      unsubscribed_from_emails: true,
      created_at: 1571672154,
      updated_at: 1571672154,
      signed_up_at: 1571672154,
      last_seen_at: 1571672154,
      last_replied_at: 1571672154,
      last_contacted_at: 1571672154,
      last_email_opened_at: 1571672154,
      last_email_clicked_at: 1571672154,
      language_override: "en",
      browser: "Chrome",
      browser_version: "80.0.3987.132",
      browser_language: "en-US",
      os: "Mac OS X",
      android_app_name: "Intercom",
      android_app_version: "5.0.0",
      android_device: "Pixel 3",
      android_os_version: "10",
      android_sdk_version: "28",
      android_last_seen_at: 1571672154,
      ios_app_name: "Intercom",
      ios_app_version: "5.0.0",
      ios_device: "iPhone 11",
      ios_os_version: "13.3.1",
      ios_sdk_version: "13.3.1",
      ios_last_seen_at: 1571672154,
      custom_attributes: {},
      avatar: {
        type: "avatar",
        image_url: "https://example.org/128Wash.jpg",
      },
      tags: {
        data: [
          {
            type: "note",
            id: "123",
            url: "/contacts/5ba682d23d7cf92bef87bfd4/notes",
          },
        ],
        url: "/contacts/5ba682d23d7cf92bef87bfd4/tags",
        total_count: 100,
        has_more: true,
      },
      notes: {
        data: [
          {
            type: "note",
            id: "123",
            url: "/contacts/5ba682d23d7cf92bef87bfd4/notes",
          },
        ],
        url: "/contacts/5ba682d23d7cf92bef87bfd4/notes",
        total_count: 100,
        has_more: true,
      },
      companies: {
        url: "/contacts/5ba682d23d7cf92bef87bfd4/companies",
        total_count: 100,
        has_more: true,
      },
      location: {
        type: "location",
        country: "Ireland",
        region: "Dublin",
        city: "Dublin",
      },
      social_profiles: {
        data: [
          {
            type: "social_profile",
            name: "Facebook",
            url: "http://twitter.com/th1sland",
          },
        ],
      },
    },
  ],
  total_count: 100,
  pages: {
    type: "pages",
    page: 1,
    next: {
      per_page: 2,
      starting_after: "your-cursor-from-response",
    },
    per_page: 2,
    total_pages: 13,
  },
};

export const getTicketResponse = {
  type: "ticket",
  id: "777",
  ticket_id: "39",
  ticket_attributes: {
    _default_title_: "attribute_value",
    _default_description_: null,
  },
  ticket_state: "submitted",
  ticket_state_internal_label: "Submitted",
  ticket_state_external_label: "Submitted",
  ticket_type: {
    type: "ticket_type",
    id: "153",
    name: "my-ticket-type-21",
    description: "my ticket type description is awesome.",
    icon: "🦁",
    workspace_id: "this_is_an_id660_that_should_be_at_least_",
    archived: false,
    created_at: 1717022478,
    updated_at: 1717022478,
    is_internal: false,
    ticket_type_attributes: {
      type: "list",
      data: [
        {
          type: "ticket_type_attribute",
          id: "404",
          workspace_id: "this_is_an_id660_that_should_be_at_least_",
          name: "_default_title_",
          description: "ola",
          data_type: "string",
          input_options: null,
          order: 0,
          required_to_create: true,
          required_to_create_for_contacts: false,
          visible_on_create: true,
          visible_to_contacts: false,
          default: false,
          ticket_type_id: 153,
          archived: false,
          created_at: 1717022478,
          updated_at: 1717022478,
        },
        {
          type: "ticket_type_attribute",
          id: "405",
          workspace_id: "this_is_an_id660_that_should_be_at_least_",
          name: "_default_description_",
          description: "ola",
          data_type: "string",
          input_options: null,
          order: 0,
          required_to_create: true,
          required_to_create_for_contacts: false,
          visible_on_create: true,
          visible_to_contacts: false,
          default: false,
          ticket_type_id: 153,
          archived: false,
          created_at: 1717022479,
          updated_at: 1717022479,
        },
      ],
    },
    category: "Back-office",
  },
  contacts: {
    type: "contact.list",
    contacts: [
      {
        type: "contact",
        id: "6657af0f6abd0167d9419df3",
        external_id: "2274eea8-d400-48f6-9345-2fb84a96e94d",
      },
    ],
  },
  admin_assignee_id: "0",
  team_assignee_id: "0",
  created_at: 1717022479,
  updated_at: 1717022479,
  ticket_parts: {
    type: "ticket_part.list",
    ticket_parts: [
      {
        type: "ticket_part",
        id: "208",
        part_type: "ticket_state_updated_by_admin",
        ticket_state: "submitted",
        previous_ticket_state: "submitted",
        created_at: 1717022479,
        updated_at: 1717022479,
        author: {
          id: "991268868",
          type: "admin",
          name: "Ciaran445 Lee",
          email: "admin445@email.com",
        },
        attachments: [],
        redacted: false,
      },
    ],
    total_count: 1,
  },
  open: true,
  linked_objects: {
    type: "list",
    data: [],
    total_count: 0,
    has_more: false,
  },
  category: "Back-office",
  is_shared: false,
};
