mutation ProductImageCreate($id: ID!, $originalSource: String!, $alt: String!) {
  productCreateMedia(
    productId: $id
    media: [{ mediaContentType: IMAGE, originalSource: $originalSource, alt: $alt }]
  ) {
    media {
      ... on MediaImage {
        id
        alt
        status
        image {
          url
        }
      }
    }
    mediaUserErrors {
      field
      message
    }
  }
}
