query Image($productId: ID!, $query: String!) {
  product(id: $productId) {
    media(query: $query, first: 1) {
      nodes {
        alt
        id
        mediaContentType
        status
        preview {
          image {
            altText
            height
            id
            originalSrc
            url
            width
            src
          }
          status
        }
      }
    }
  }
}
