import {
  createContact,
  deleteContact,
  getContact,
  getContactsStream,
  listContacts,
  updateContact,
  upsertContact,
} from "./contacts";
import {
  createDeal,
  deleteDeal,
  getDeal,
  getDealsStream,
  listDeals,
  updateDeal,
} from "./deals";
import {
  createLead,
  deleteLead,
  getLead,
  getLeadsStream,
  listLeads,
  updateLead,
  upsertLead,
} from "./leads";
import {
  getCustomFieldsStream,
  getProductsStream,
  getStream,
  listAccountDetails,
  listCustomFields,
  rawRequest,
} from "./misc";
import {
  createNote,
  deleteNote,
  getNote,
  getNotesStream,
  listNotes,
  updateNote,
} from "./notes";
import {
  createOrder,
  deleteOrder,
  getOrder,
  getOrdersStream,
  listOrder,
  updateOrder,
} from "./orders";
import { listPipelines } from "./pipelines";
import { getStagesStream, listStages } from "./stages";
import {
  createTask,
  deleteTask,
  getTask,
  getTasksStream,
  listTasks,
  updateTask,
} from "./tasks";

export default {
  listContacts,
  getContact,
  createContact,
  updateContact,
  upsertContact,
  deleteContact,
  listAccountDetails,
  listCustomFields,
  listNotes,
  getNote,
  createNote,
  updateNote,
  deleteNote,
  listPipelines,
  listTasks,
  getTask,
  createTask,
  updateTask,
  deleteTask,
  listLeads,
  getLead,
  createLead,
  updateLead,
  upsertLead,
  deleteLead,
  listDeals,
  getDeal,
  createDeal,
  updateDeal,
  deleteDeal,
  getStream,
  listStages,
  listOrder,
  getOrder,
  createOrder,
  updateOrder,
  deleteOrder,
  rawRequest,
  getContactsStream,
  getCustomFieldsStream,
  getDealsStream,
  getLeadsStream,
  getNotesStream,
  getOrdersStream,
  getProductsStream,
  getStagesStream,
  getTasksStream,
};
