export const MAX_AGREEMENTS_PAGE_SIZE = 500;
export const MAX_USERS_PAGE_SIZE = 100;
export const MAX_WEBHOOKS_PAGE_SIZE = 100;
export const MAX_GROUPS_PAGE_SIZE = 100;
export const MAX_GROUP_EVENTS_PAGE_SIZE = 100;





export const POLL_PAGE_SIZE = 100;



export const MAX_POLL_PAGES = 50;


export const POLL_BOOTSTRAP_WINDOW_MS = 24 * 60 * 60 * 1000; 



export const POLL_OWNERSHIP_SCOPE = "OWNED";




export const MAX_PAGE_SIZE_BY_ITEMS_KEY: Record<string, number> = {
  userAgreementList: MAX_AGREEMENTS_PAGE_SIZE,
  userInfoList: MAX_USERS_PAGE_SIZE,
  userWebhookList: MAX_WEBHOOKS_PAGE_SIZE,
  groupInfoList: MAX_GROUPS_PAGE_SIZE,
  groupEvents: MAX_GROUP_EVENTS_PAGE_SIZE,
};

export const WEBHOOK_SUBSCRIPTION_EVENT_TYPES = [
  "AGREEMENT_CREATED",
  "AGREEMENT_ACTION_DELEGATED",
  "AGREEMENT_RECALLED",
  "AGREEMENT_REJECTED",
  "AGREEMENT_EXPIRED",
  "AGREEMENT_ACTION_COMPLETED",
  "AGREEMENT_WORKFLOW_COMPLETED",
  "AGREEMENT_RESTARTED",
  "AGREEMENT_EMAIL_VIEWED",
  "AGREEMENT_MODIFIED",
  "AGREEMENT_SHARED",
  "AGREEMENT_UNSHARED",
  "AGREEMENT_UNSHARED_AUTO",
  "AGREEMENT_READY_TO_VAULT",
  "AGREEMENT_VAULTED",
  "AGREEMENT_ACTION_REQUESTED",
  "AGREEMENT_ACTION_REPLACED_SIGNER",
  "AGREEMENT_AUTO_CANCELLED_CONVERSION_PROBLEM",
  "AGREEMENT_DOCUMENTS_DELETED",
  "AGREEMENT_EMAIL_BOUNCED",
  "AGREEMENT_KBA_AUTHENTICATED",
  "AGREEMENT_OFFLINE_SYNC",
  "AGREEMENT_USER_ACK_AGREEMENT_MODIFIED",
  "AGREEMENT_WEB_IDENTITY_AUTHENTICATED",
  "AGREEMENT_READY_TO_NOTARIZE",
  "AGREEMENT_EXPIRATION_UPDATED",
  "AGREEMENT_REMINDER_SENT",
  "AGREEMENT_SIGNER_NAME_CHANGED_BY_SIGNER",
  "AGREEMENT_REMINDER_INITIATED",
  "AGREEMENT_DOCUMENTS_VIEWED",
  "AGREEMENT_DOCUMENTS_VIEWED_PASSWORD_PROTECTED",
  "AGREEMENT_ALL",
  "MEGASIGN_CREATED",
  "MEGASIGN_RECALLED",
  "MEGASIGN_SHARED",
  "MEGASIGN_REMINDER_SENT",
  "MEGASIGN_REMINDER_INITIATED",
  "MEGASIGN_ALL",
  "WIDGET_CREATED",
  "WIDGET_MODIFIED",
  "WIDGET_SHARED",
  "WIDGET_ENABLED",
  "WIDGET_DISABLED",
  "WIDGET_AUTO_CANCELLED_CONVERSION_PROBLEM",
  "WIDGET_ALL",
  "LIBRARY_DOCUMENT_CREATED",
  "LIBRARY_DOCUMENT_AUTO_CANCELLED_CONVERSION_PROBLEM",
  "LIBRARY_DOCUMENT_MODIFIED",
  "LIBRARY_DOCUMENT_ALL",
] as const;

export const PARTICIPANT_SET_INFO_ROLES = [
  "SIGNER",
  "APPROVER",
  "ACCEPTOR",
  "CERTIFIED_RECIPIENT",
  "FORM_FILLER",
  "DELEGATE_TO_SIGNER",
  "DELEGATE_TO_APPROVER",
  "DELEGATE_TO_ACCEPTOR",
  "DELEGATE_TO_CERTIFIED_RECIPIENT",
  "DELEGATE_TO_FORM_FILLER",
  "NOTARY_SIGNER",
  "ELECTRONIC_SEALER",
] as const;

export const SEARCH_USER_ROLES = [
  "SENDER",
  "CC",
  "SIGNER",
  "APPROVER",
  "FORM_FILLER",
  "ACCEPTOR",
  "CERTIFIED_RECIPIENT",
  "DELEGATE_TO_SIGNER",
  "DELEGATE_TO_APPROVER",
  "DELEGATE_TO_FORM_FILLER",
  "DELEGATE_TO_ACCEPTOR",
  "DELEGATE_TO_CERTIFIED_RECIPIENT",
  "NOTARY_SIGNER",
  "SHARE",
  "OTHER",
] as const;

export const SORT_BY_FIELD_OPTIONS = [
  "CREATED_DATE",
  "MODIFIED_DATE",
  "EXPIRATION_DATE",
  "NAME",
  "STATUS",
  "SENDER",
] as const;

export const STATUS_TYPES = [
  "WAITING_FOR_MY_SIGNATURE",
  "WAITING_FOR_MY_APPROVAL",
  "WAITING_FOR_MY_DELEGATION",
  "WAITING_FOR_MY_ACKNOWLEDGEMENT",
  "WAITING_FOR_MY_ACCEPTANCE",
  "WAITING_FOR_MY_FORM_FILLING",
  "WAITING_FOR_PREFILL",
  "WAITING_FOR_AUTHORING",
  "WAITING_FOR_PREFILL",
  "OUT_FOR_SIGNATURE",
  "OUT_FOR_APPROVAL",
  "OUT_FOR_DELIVERY",
  "OUT_FOR_ACCEPTANCE",
  "OUT_FOR_FORM_FILLING",
  "SIGNED",
  "APPROVED",
  "FORM_FILLED",
  "DELIVERED",
  "ACCEPTED",
  "ARCHIVED",
  "CANCELLED",
  "REMOVED",
  "EXPIRED",
  "AUTHORING",
  "ACTIVE",
  "DISABLED",
  "WAITING_FOR_NOTARIZATION",
  "ACCEPT_BEFORE_NOTARIZATION",
  "OTHER",
] as const;
