export const createCandidateInfoExample = {
  candidateId: ["string", "null"],
  createdBy: ["string", "null"],
  createdDateTime: "/Date(1492098664000)/",
  crossboarded: true,
  department: ["string", "null"],
  division: ["string", "null"],
  email: ["string", "null"],
  externalName_de_DE: ["string", "null"],
  externalName_defaultValue: ["string", "null"],
  externalName_en_GB: ["string", "null"],
  externalName_en_US: ["string", "null"],
  externalName_es_ES: ["string", "null"],
  externalName_fr_FR: ["string", "null"],
  externalName_ja_JP: ["string", "null"],
  externalName_ko_KR: ["string", "null"],
  externalName_localized: ["string", "null"],
  externalName_nl_NL: ["string", "null"],
  externalName_pt_BR: ["string", "null"],
  externalName_pt_PT: ["string", "null"],
  externalName_ru_RU: ["string", "null"],
  externalName_zh_CN: ["string", "null"],
  externalName_zh_TW: ["string", "null"],
  fName: ["string", "null"],
  failedSEBEventsOccured: true,
  fromExternalATS: true,
  globalAssignment: true,
  hireDate: ["string", "null"],
  hired: true,
  hrManagerId: ["string", "null"],
  internalHire: true,
  jobReqId: ["string", "null"],
  jobTitle: ["string", "null"],
  kmsUserId: ["string", "null"],
  lName: ["string", "null"],
  lastModifiedBy: ["string", "null"],
  lastModifiedDateTime: "/Date(1492098664000)/",
  location: ["string", "null"],
  managerId: ["string", "null"],
  mdfSystemRecordStatus: ["string", "null"],
  onboardingLocale: ["string", "null"],
  payGrade: ["string", "null"],
  processorId: ["string", "null"],
  readyToHire: true,
  userId: ["string", "null"],
  workCountry: ["string", "null"],
};

export const createJobApplicationInfoExample = {
  __metadata: {
    uri: "https://api68sales.successfactors.com/odata/v2/JobApplication(388L)",
    type: "SFOData.JobApplication",
  },
  applicationId: "388",
  posTitle: null,
  lastName: "Reis",
  firstName: "Marcelo",
  jobCode: null,
  status: "Open",
};
