export const getWarehouseLocationExamplePayload = {
  data: {
    Code: 1,
    Name: "Delhi",
    LSTVATNumber: null,
    CSTNumber: "07AAFCE3317E1Z1",
    ExemptionNumber: null,
    TANNumber: null,
    ServiceTaxNumber: null,
    AssesseeType: null,
    CompanyType: null,
    NatureOfBusiness: null,
    TINNumber: null,
    RegistrationType: "XM",
    EccNumber: "AABPS8791RXM001",
    CERange: null,
    CEDivision: null,
    CECommissionerate: null,
    ManufacturerCode: null,
    Jurisdiction: null,
    Street: "B-2/3 , Second Floor, Mohan Co-Operative Industrial Estate",
    Block: "Mathura Road",
    ZipCode: "110044",
    City: "New Delhi",
    County: null,
    Country: "IN",
    State: "DL",
    PANNumber: "AABPS8791R",
    CERegisterNumber: null,
    BuildingFloorRoom: null,
    GSTIN: "07AAFCE3317E1Z1",
    GstType: "gstRegularTDSISD",
    GSTTDS: null,
    GSTISD: null,
    U_UTL_ST_OWID: "6daf01b8-77bc-467d-91e8-d00d1fc53d45",
    U_CID: null,
    U_SECRET: null,
    U_UTL_EUID: null,
    U_UTL_EPSW: null,
    U_UTL_ST_PAYUPID: null,
    U_UTL_ST_PAYNM: null,
    U_UTL_ST_PAYACNO: null,
    U_UTL_ST_PAYIFSC: null,
  },
};

export const listWarehouseLocationsExamplePayload = {
  data: [getWarehouseLocationExamplePayload.data],
};
