






export const getDealsExamplePayload = {
  data: [
    {
      id: 1,
      creator_user_id: {
        id: 18487521,
        name: "Developer",
        email: "dummy@test.dev",
        has_pic: 0,
        pic_hash: null,
        active_flag: true,
        value: 18487521,
      },
      user_id: {
        id: 18487521,
        name: "Developer",
        email: "dummy@test.dev",
        has_pic: 0,
        pic_hash: null,
        active_flag: true,
        value: 18487521,
      },
      person_id: {
        active_flag: true,
        name: "test person",
        email: [
          {
            value: "",
            primary: true,
          },
        ],
        phone: [
          {
            value: "",
            primary: true,
          },
        ],
        owner_id: 18487521,
        value: 3,
      },
      org_id: {
        name: "test",
        people_count: 2,
        owner_id: 18487521,
        address: null,
        active_flag: true,
        cc_email: "test-sandbox@pipedrivemail.com",
        label_ids: [],
        owner_name: "Developer",
        value: 2,
      },
      stage_id: 1,
      title: "test deal",
      value: 2,
      currency: "USD",
      add_time: "2024-09-27 14:25:27",
      update_time: "2024-09-27 14:25:28",
      stage_change_time: null,
      active: true,
      deleted: false,
      status: "open",
      probability: null,
      next_activity_date: null,
      next_activity_time: null,
      next_activity_id: null,
      last_activity_id: null,
      last_activity_date: null,
      lost_reason: null,
      visible_to: "3",
      close_time: null,
      pipeline_id: 1,
      won_time: null,
      first_won_time: null,
      lost_time: null,
      products_count: 0,
      files_count: 0,
      notes_count: 0,
      followers_count: 1,
      email_messages_count: 0,
      activities_count: 0,
      done_activities_count: 0,
      undone_activities_count: 0,
      participants_count: 1,
      expected_close_date: null,
      last_incoming_mail_time: null,
      last_outgoing_mail_time: null,
      label: null,
      local_won_date: null,
      local_lost_date: null,
      local_close_date: null,
      origin: "ManuallyCreated",
      origin_id: null,
      channel: null,
      channel_id: null,
      stage_order_nr: 0,
      person_name: "test person",
      org_name: "test",
      next_activity_subject: null,
      next_activity_type: null,
      next_activity_duration: null,
      next_activity_note: null,
      formatted_value: "$2",
      weighted_value: 2,
      formatted_weighted_value: "$2",
      weighted_value_currency: "USD",
      rotten_time: null,
      owner_name: "Developer",
      cc_email: "test-sandbox+deal1@pipedrivemail.com",
      org_hidden: false,
      person_hidden: false,
    },
    {
      id: 2,
      creator_user_id: {
        id: 18487521,
        name: "Developer",
        email: "dummy@test.dev",
        has_pic: 0,
        pic_hash: null,
        active_flag: true,
        value: 18487521,
      },
      user_id: {
        id: 18487521,
        name: "Developer",
        email: "dummy@test.dev",
        has_pic: 0,
        pic_hash: null,
        active_flag: true,
        value: 18487521,
      },
      person_id: {
        active_flag: true,
        name: "awesome person",
        email: [
          {
            value: "",
            primary: true,
          },
        ],
        phone: [
          {
            value: "",
            primary: true,
          },
        ],
        owner_id: 18487521,
        value: 4,
      },
      org_id: {
        name: "test",
        people_count: 2,
        owner_id: 18487521,
        address: null,
        active_flag: true,
        cc_email: "test-sandbox@pipedrivemail.com",
        label_ids: [],
        owner_name: "Developer",
        value: 2,
      },
      stage_id: 4,
      title: "test deal 2",
      value: 3,
      currency: "USD",
      add_time: "2024-09-27 14:25:53",
      update_time: "2024-09-27 14:31:57",
      stage_change_time: "2024-09-27 14:31:45",
      active: false,
      deleted: false,
      status: "won",
      probability: null,
      next_activity_date: null,
      next_activity_time: null,
      next_activity_id: null,
      last_activity_id: null,
      last_activity_date: null,
      lost_reason: null,
      visible_to: "3",
      close_time: "2024-09-27 14:31:57",
      pipeline_id: 1,
      won_time: "2024-09-27 14:31:57",
      first_won_time: "2024-09-27 14:31:57",
      lost_time: null,
      products_count: 0,
      files_count: 0,
      notes_count: 0,
      followers_count: 1,
      email_messages_count: 0,
      activities_count: 0,
      done_activities_count: 0,
      undone_activities_count: 0,
      participants_count: 1,
      expected_close_date: null,
      last_incoming_mail_time: null,
      last_outgoing_mail_time: null,
      label: null,
      local_won_date: "2024-09-27",
      local_lost_date: null,
      local_close_date: "2024-09-27",
      origin: "ManuallyCreated",
      origin_id: null,
      channel: null,
      channel_id: null,
      stage_order_nr: 3,
      person_name: "awesome person",
      org_name: "test",
      next_activity_subject: null,
      next_activity_type: null,
      next_activity_duration: null,
      next_activity_note: null,
      formatted_value: "$3",
      weighted_value: 3,
      formatted_weighted_value: "$3",
      weighted_value_currency: "USD",
      rotten_time: null,
      owner_name: "Developer",
      cc_email: "test-sandbox+deal2@pipedrivemail.com",
      org_hidden: false,
      person_hidden: false,
    },
  ],
  additional_data: {
    next_cursor: "1234567890",
  },
};
