






export const getPersonsExamplePayload = {
  data: [
    {
      id: 1,
      company_id: 12882925,
      owner_id: {
        id: 18487521,
        name: "Test Developer",
        email: "dev@test.dev",
        has_pic: 0,
        pic_hash: null,
        active_flag: true,
        value: 18487521,
      },
      org_id: {
        name: "Acme",
        people_count: 2,
        owner_id: 18487521,
        address: null,
        active_flag: true,
        cc_email: "test-sandbox@pipedrivemail.com",
        label_ids: [],
        owner_name: "Test Developer",
        value: 1,
      },
      name: "John",
      first_name: "John",
      last_name: null,
      open_deals_count: 0,
      related_open_deals_count: 0,
      closed_deals_count: 0,
      related_closed_deals_count: 0,
      participant_open_deals_count: 0,
      participant_closed_deals_count: 0,
      email_messages_count: 0,
      activities_count: 0,
      done_activities_count: 0,
      undone_activities_count: 0,
      files_count: 5,
      notes_count: 0,
      followers_count: 1,
      won_deals_count: 0,
      related_won_deals_count: 0,
      lost_deals_count: 0,
      related_lost_deals_count: 0,
      active_flag: true,
      phone: [
        {
          value: "",
          primary: true,
        },
      ],
      email: [
        {
          value: "",
          primary: true,
        },
      ],
      first_char: "t",
      update_time: "2023-08-14 22:49:23",
      delete_time: null,
      add_time: "2023-04-06 02:51:24",
      visible_to: "3",
      picture_id: null,
      next_activity_date: null,
      next_activity_time: null,
      next_activity_id: null,
      last_activity_id: null,
      last_activity_date: null,
      last_incoming_mail_time: null,
      last_outgoing_mail_time: null,
      label: null,
      label_ids: [],
      im: [
        {
          value: "",
          primary: true,
        },
      ],
      postal_address: null,
      postal_address_lat: null,
      postal_address_long: null,
      postal_address_subpremise: null,
      postal_address_street_number: null,
      postal_address_route: null,
      postal_address_sublocality: null,
      postal_address_locality: null,
      postal_address_admin_area_level_1: null,
      postal_address_admin_area_level_2: null,
      postal_address_country: null,
      postal_address_postal_code: null,
      postal_address_formatted_address: null,
      notes: null,
      birthday: null,
      job_title: null,
      org_name: "Acme",
      owner_name: "Test Developer",
      primary_email: null,
      "5f1513c3d8ba7f34c0164f3f909280c3fa0c592e": "15",
      "3cf151d1c54a8c13329a97403054d6306fe4680c": "17",
      cc_email: "test-sandbox@pipedrivemail.com",
    },
    {
      id: 2,
      company_id: 12882925,
      owner_id: {
        id: 18487521,
        name: "Test Developer",
        email: "dev@test.dev",
        has_pic: 0,
        pic_hash: null,
        active_flag: true,
        value: 18487521,
      },
      org_id: {
        name: "Acme",
        people_count: 2,
        owner_id: 18487521,
        address: null,
        active_flag: true,
        cc_email: "test-sandbox@pipedrivemail.com",
        label_ids: [],
        owner_name: "Test Developer",
        value: 1,
      },
      name: "John",
      first_name: "John",
      last_name: null,
      open_deals_count: 0,
      related_open_deals_count: 0,
      closed_deals_count: 0,
      related_closed_deals_count: 0,
      participant_open_deals_count: 0,
      participant_closed_deals_count: 0,
      email_messages_count: 0,
      activities_count: 0,
      done_activities_count: 0,
      undone_activities_count: 0,
      files_count: 0,
      notes_count: 0,
      followers_count: 1,
      won_deals_count: 0,
      related_won_deals_count: 0,
      lost_deals_count: 0,
      related_lost_deals_count: 0,
      active_flag: true,
      phone: [
        {
          value: "",
          primary: true,
        },
      ],
      email: [
        {
          label: "work",
          value: "john.doe@example.com",
          primary: true,
        },
      ],
      first_char: "j",
      update_time: "2023-07-13 21:26:05",
      delete_time: null,
      add_time: "2023-07-13 20:47:38",
      visible_to: "3",
      picture_id: null,
      next_activity_date: null,
      next_activity_time: null,
      next_activity_id: null,
      last_activity_id: null,
      last_activity_date: null,
      last_incoming_mail_time: null,
      last_outgoing_mail_time: null,
      label: null,
      label_ids: [],
      im: [
        {
          value: "",
          primary: true,
        },
      ],
      postal_address: null,
      postal_address_lat: null,
      postal_address_long: null,
      postal_address_subpremise: null,
      postal_address_street_number: null,
      postal_address_route: null,
      postal_address_sublocality: null,
      postal_address_locality: null,
      postal_address_admin_area_level_1: null,
      postal_address_admin_area_level_2: null,
      postal_address_country: null,
      postal_address_postal_code: null,
      postal_address_formatted_address: null,
      notes: null,
      birthday: null,
      job_title: null,
      org_name: "Acme",
      owner_name: "Test Developer",
      primary_email: "john.doe@example.com",
      "5f1513c3d8ba7f34c0164f3f909280c3fa0c592e": "15",
      "3cf151d1c54a8c13329a97403054d6306fe4680c": "19",
      cc_email: "test-sandbox@pipedrivemail.com",
    },
    {
      id: 3,
      company_id: 12882925,
      owner_id: {
        id: 18487521,
        name: "Test Developer",
        email: "dev@test.dev",
        has_pic: 0,
        pic_hash: null,
        active_flag: true,
        value: 18487521,
      },
      org_id: {
        name: "Test",
        people_count: 2,
        owner_id: 18487521,
        address: null,
        active_flag: true,
        cc_email: "test-sandbox@pipedrivemail.com",
        label_ids: [],
        owner_name: "Test Developer",
        value: 2,
      },
      name: "test person",
      first_name: "test",
      last_name: "person",
      open_deals_count: 1,
      related_open_deals_count: 0,
      closed_deals_count: 0,
      related_closed_deals_count: 0,
      participant_open_deals_count: 0,
      participant_closed_deals_count: 0,
      email_messages_count: 0,
      activities_count: 0,
      done_activities_count: 0,
      undone_activities_count: 0,
      files_count: 0,
      notes_count: 0,
      followers_count: 1,
      won_deals_count: 0,
      related_won_deals_count: 0,
      lost_deals_count: 0,
      related_lost_deals_count: 0,
      active_flag: true,
      phone: [
        {
          value: "",
          primary: true,
        },
      ],
      email: [
        {
          value: "",
          primary: true,
        },
      ],
      first_char: "t",
      update_time: "2024-09-27 14:25:28",
      delete_time: null,
      add_time: "2024-09-27 14:25:27",
      visible_to: "3",
      picture_id: null,
      next_activity_date: null,
      next_activity_time: null,
      next_activity_id: null,
      last_activity_id: null,
      last_activity_date: null,
      last_incoming_mail_time: null,
      last_outgoing_mail_time: null,
      label: null,
      label_ids: [],
      im: [
        {
          value: "",
          primary: true,
        },
      ],
      postal_address: null,
      postal_address_lat: null,
      postal_address_long: null,
      postal_address_subpremise: null,
      postal_address_street_number: null,
      postal_address_route: null,
      postal_address_sublocality: null,
      postal_address_locality: null,
      postal_address_admin_area_level_1: null,
      postal_address_admin_area_level_2: null,
      postal_address_country: null,
      postal_address_postal_code: null,
      postal_address_formatted_address: null,
      notes: null,
      birthday: null,
      job_title: null,
      org_name: "Test",
      owner_name: "Test Developer",
      primary_email: null,
      "5f1513c3d8ba7f34c0164f3f909280c3fa0c592e": null,
      "3cf151d1c54a8c13329a97403054d6306fe4680c": null,
      cc_email: "test-sandbox@pipedrivemail.com",
    },
    {
      id: 4,
      company_id: 12882925,
      owner_id: {
        id: 18487521,
        name: "Test Developer",
        email: "dev@test.dev",
        has_pic: 0,
        pic_hash: null,
        active_flag: true,
        value: 18487521,
      },
      org_id: {
        name: "Test",
        people_count: 2,
        owner_id: 18487521,
        address: null,
        active_flag: true,
        cc_email: "test-sandbox@pipedrivemail.com",
        label_ids: [],
        owner_name: "Test Developer",
        value: 2,
      },
      name: "awesome person",
      first_name: "awesome",
      last_name: "person",
      open_deals_count: 1,
      related_open_deals_count: 0,
      closed_deals_count: 0,
      related_closed_deals_count: 0,
      participant_open_deals_count: 0,
      participant_closed_deals_count: 0,
      email_messages_count: 0,
      activities_count: 0,
      done_activities_count: 0,
      undone_activities_count: 0,
      files_count: 0,
      notes_count: 0,
      followers_count: 1,
      won_deals_count: 0,
      related_won_deals_count: 0,
      lost_deals_count: 0,
      related_lost_deals_count: 0,
      active_flag: true,
      phone: [
        {
          value: "",
          primary: true,
        },
      ],
      email: [
        {
          value: "",
          primary: true,
        },
      ],
      first_char: "a",
      update_time: "2024-09-27 14:25:53",
      delete_time: null,
      add_time: "2024-09-27 14:25:53",
      visible_to: "3",
      picture_id: null,
      next_activity_date: null,
      next_activity_time: null,
      next_activity_id: null,
      last_activity_id: null,
      last_activity_date: null,
      last_incoming_mail_time: null,
      last_outgoing_mail_time: null,
      label: null,
      label_ids: [],
      im: [
        {
          value: "",
          primary: true,
        },
      ],
      postal_address: null,
      postal_address_lat: null,
      postal_address_long: null,
      postal_address_subpremise: null,
      postal_address_street_number: null,
      postal_address_route: null,
      postal_address_sublocality: null,
      postal_address_locality: null,
      postal_address_admin_area_level_1: null,
      postal_address_admin_area_level_2: null,
      postal_address_country: null,
      postal_address_postal_code: null,
      postal_address_formatted_address: null,
      notes: null,
      birthday: null,
      job_title: null,
      org_name: "Test",
      owner_name: "Test Developer",
      primary_email: null,
      "5f1513c3d8ba7f34c0164f3f909280c3fa0c592e": null,
      "3cf151d1c54a8c13329a97403054d6306fe4680c": null,
      cc_email: "test-sandbox@pipedrivemail.com",
    },
  ],
  additional_data: {
    next_cursor: "1234567890",
  },
};
