import {
  createAccount,
  deleteAccount,
  getAccounts,
  listAccounts,
  shareAccount,
  updateAccount,
} from "./accounts";
import {
  createDataSet,
  deleteDataSet,
  exportDataFromDataSet,
  getDataSet,
  importDataIntoDataSet,
  listDataSets,
  queryDataSet,
  updateDataSet,
} from "./datasets";
import {
  addUserToGroup,
  createGroup,
  deleteGroup,
  getGroup,
  listGroups,
  listUsersInGroup,
  removeUserFromGroup,
  updateGroup,
} from "./groups";
import { getActivityLogEntries, rawRequest } from "./misc";
import {
  createPage,
  deletePage,
  getPage,
  listPages,
  updatePage,
} from "./pages";
import {
  addAttachment,
  createList,
  createProject,
  createTask,
  deleteAttachment,
  deleteList,
  deleteProject,
  downloadAttachment,
  getList,
  getListOfAttachments,
  getProject,
  getProjectMembers,
  getTask,
  listProjectLists,
  listProjectListTasks,
  listProjects,
  updateList,
  updateProject,
  updateProjectMembers,
  updateTask,
} from "./projects";
import {
  abortStreamExecution,
  commitStreamExecution,
  createStream,
  createStreamExecution,
  deleteStream,
  getStream,
  getStreamExecution,
  listStreamExecution,
  listStreams,
  searchStream,
  updateStream,
  uploadDataPart,
} from "./streams";
import {
  createUser,
  deleteUser,
  getUser,
  listUsers,
  updateUser,
} from "./users";

export default {
  listAccounts,
  getAccounts,
  createAccount,
  updateAccount,
  deleteAccount,
  shareAccount,
  listUsers,
  getUser,
  createUser,
  updateUser,
  deleteUser,
  getActivityLogEntries,
  listDataSets,
  getDataSet,
  createDataSet,
  updateDataSet,
  deleteDataSet,
  queryDataSet,
  importDataIntoDataSet,
  exportDataFromDataSet,
  listGroups,
  getGroup,
  createGroup,
  updateGroup,
  deleteGroup,
  addUserToGroup,
  removeUserFromGroup,
  listUsersInGroup,
  listPages,
  getPage,
  createPage,
  updatePage,
  deletePage,
  listProjects,
  getProject,
  createProject,
  updateProject,
  deleteProject,
  addAttachment,
  downloadAttachment,
  deleteAttachment,
  getListOfAttachments,
  getProjectMembers,
  updateProjectMembers,
  listProjectLists,
  getList,
  createList,
  updateList,
  deleteList,
  listProjectListTasks,
  getTask,
  createTask,
  updateTask,
  listStreams,
  getStream,
  createStream,
  updateStream,
  deleteStream,
  searchStream,
  listStreamExecution,
  getStreamExecution,
  createStreamExecution,
  uploadDataPart,
  commitStreamExecution,
  abortStreamExecution,
  rawRequest,
};
