import { action } from "@prismatic-io/spectral";
import { createClient } from "../../client";
import {
  connectionInput,
  merchantId,
  offerId,
  title,
  description,
  link,
  imageLink,
  additionalImageLinks,
  lifestyleImageLinks,
  contentLanguage,
  targetCountry,
  feedLabel,
  channel,
  expirationDate,
  adult,
  kind,
  brand,
  color,
  googleProductCategory,
  gtin,
  itemGroupId,
  material,
  mpn,
  pattern,
  price,
  salePrice,
  salePriceEffectiveDate,
  productHeight,
  productLength,
  productWidth,
  productWeight,
  shipping,
  shippingWeight,
  sizes,
  taxes,
  customAttributes,
  identifierExists,
  installment,
  multipack,
  customLabel0,
  customLabel1,
  customLabel2,
  customLabel3,
  customLabel4,
  isBundle,
  mobileLink,
  availabilityDate,
  shippingLabel,
  unitPricingMeasure,
  unitPricingBaseMeasure,
  shippingLength,
  shippingWidth,
  shippingHeight,
  displayAdsId,
  displayAdsSimilarIds,
  displayAdsTitle,
  displayAdsLink,
  displayAdsValue,
  sellOnGoogleQuantity,
  promotionIds,
  maxHandlingTime,
  minHandlingTime,
  costOfGoodsSold,
  source,
  includedDestinations,
  excludedDestinations,
  adsGrouping,
  adsLabels,
  adsRedirect,
  productTypes,
  ageGroup,
  availability,
  condition,
  gender,
  sizeSystem,
  sizeType,
  additionalSizeType,
  energyEfficiencyClass,
  minEnergyEfficiencyClass,
  maxEnergyEfficiencyClass,
  taxCategory,
  transitTimeLabel,
  shoppingAdsExcludedCountries,
  pickupMethod,
  pickupSla,
  linkTemplate,
  mobileLinkTemplate,
  productDetails,
  productHighlights,
  subscriptionCost,
  canonicalLink,
  externalSellerId,
  pause,
  productId,
  updateMask,
} from "../../inputs";
import { updateProductExamplePayload } from "../../examplePayloads";

export const updateProduct = action({
  display: {
    description:
      "Updates an existing product in your Merchant Center account. Only updates attributes provided in the request.",
    label: "Update Product",
  },
  inputs: {
    connectionInput,
    merchantId,
    productId,
    offerId: { ...offerId, required: false },
    contentLanguage: { ...contentLanguage, required: false },
    targetCountry: { ...targetCountry, required: false },
    externalSellerId: { ...externalSellerId, required: false },
    channel: { ...channel, required: false },
    feedLabel,
    title,
    description,
    link,
    imageLink,
    additionalImageLinks,
    lifestyleImageLinks,
    expirationDate,
    adult,
    kind: { ...kind, required: false },
    brand,
    color,
    googleProductCategory,
    gtin,
    itemGroupId,
    material,
    mpn,
    pattern,
    price,
    salePrice,
    salePriceEffectiveDate,
    productHeight,
    productLength,
    productWidth,
    productWeight,
    shipping,
    shippingWeight,
    sizes,
    taxes,
    customAttributes,
    identifierExists,
    installment,
    multipack,
    customLabel0,
    customLabel1,
    customLabel2,
    customLabel3,
    customLabel4,
    isBundle,
    mobileLink,
    availabilityDate,
    shippingLabel,
    unitPricingMeasure,
    unitPricingBaseMeasure,
    shippingLength,
    shippingWidth,
    shippingHeight,
    displayAdsId,
    displayAdsSimilarIds,
    displayAdsTitle,
    displayAdsLink,
    displayAdsValue,
    sellOnGoogleQuantity,
    promotionIds,
    maxHandlingTime,
    minHandlingTime,
    costOfGoodsSold,
    source,
    includedDestinations,
    excludedDestinations,
    adsGrouping,
    adsLabels,
    adsRedirect,
    productTypes,
    ageGroup,
    availability,
    condition,
    gender,
    sizeSystem,
    sizeType,
    additionalSizeType,
    energyEfficiencyClass,
    minEnergyEfficiencyClass,
    maxEnergyEfficiencyClass,
    taxCategory,
    transitTimeLabel,
    shoppingAdsExcludedCountries,
    pickupMethod,
    pickupSla,
    linkTemplate,
    mobileLinkTemplate,
    productDetails,
    productHighlights,
    subscriptionCost,
    canonicalLink,
    pause,
    updateMask,
  },
  perform: async (
    _context,
    {
      connectionInput,
      merchantId,
      externalSellerId,
      productId,
      offerId,
      contentLanguage,
      targetCountry,
      feedLabel,
      title,
      description,
      link,
      imageLink,
      additionalImageLinks,
      lifestyleImageLinks,
      channel,
      expirationDate,
      adult,
      kind,
      brand,
      color,
      googleProductCategory,
      gtin,
      itemGroupId,
      material,
      mpn,
      pattern,
      price,
      salePrice,
      salePriceEffectiveDate,
      productHeight,
      productLength,
      productWidth,
      productWeight,
      shipping,
      shippingWeight,
      sizes,
      taxes,
      customAttributes,
      identifierExists,
      installment,
      multipack,
      customLabel0,
      customLabel1,
      customLabel2,
      customLabel3,
      customLabel4,
      isBundle,
      mobileLink,
      availabilityDate,
      shippingLabel,
      unitPricingMeasure,
      unitPricingBaseMeasure,
      shippingLength,
      shippingWidth,
      shippingHeight,
      displayAdsId,
      displayAdsSimilarIds,
      displayAdsTitle,
      displayAdsLink,
      displayAdsValue,
      sellOnGoogleQuantity,
      promotionIds,
      maxHandlingTime,
      minHandlingTime,
      costOfGoodsSold,
      source,
      includedDestinations,
      excludedDestinations,
      adsGrouping,
      adsLabels,
      adsRedirect,
      productTypes,
      ageGroup,
      availability,
      condition,
      gender,
      sizeSystem,
      sizeType,
      additionalSizeType,
      energyEfficiencyClass,
      minEnergyEfficiencyClass,
      maxEnergyEfficiencyClass,
      taxCategory,
      transitTimeLabel,
      shoppingAdsExcludedCountries,
      pickupMethod,
      pickupSla,
      linkTemplate,
      mobileLinkTemplate,
      productDetails,
      productHighlights,
      subscriptionCost,
      canonicalLink,
      pause,
      updateMask,
    },
  ) => {
    const client = createClient(connectionInput);
    const { data } = await client.products.update({
      merchantId,
      productId,
      updateMask,
      requestBody: {
        id: null,
        offerId: offerId || undefined,
        contentLanguage: contentLanguage || undefined,
        targetCountry: targetCountry || undefined,
        feedLabel: feedLabel || undefined,
        title: title || undefined,
        description: description || undefined,
        link: link || undefined,
        imageLink: imageLink || undefined,
        additionalImageLinks: additionalImageLinks || undefined,
        lifestyleImageLinks: lifestyleImageLinks || undefined,
        channel: channel || undefined,
        expirationDate: expirationDate || undefined,
        adult: adult || undefined,
        kind: kind || undefined,
        brand: brand || undefined,
        color: color || undefined,
        googleProductCategory: googleProductCategory || undefined,
        gtin: gtin || undefined,
        itemGroupId: itemGroupId || undefined,
        material: material || undefined,
        mpn: mpn || undefined,
        pattern: pattern || undefined,
        price: price || undefined,
        salePrice: salePrice || undefined,
        salePriceEffectiveDate: salePriceEffectiveDate || undefined,
        productHeight: productHeight || undefined,
        productLength: productLength || undefined,
        productWidth: productWidth || undefined,
        productWeight: productWeight || undefined,
        shipping: shipping || undefined,
        shippingWeight: shippingWeight || undefined,
        sizes: sizes || undefined,
        taxes: taxes || undefined,
        customAttributes: customAttributes || undefined,
        identifierExists: identifierExists || undefined,
        installment: installment || undefined,
        multipack: multipack || undefined,
        customLabel0: customLabel0 || undefined,
        customLabel1: customLabel1 || undefined,
        customLabel2: customLabel2 || undefined,
        customLabel3: customLabel3 || undefined,
        customLabel4: customLabel4 || undefined,
        isBundle: isBundle || undefined,
        mobileLink: mobileLink || undefined,
        availabilityDate: availabilityDate || undefined,
        shippingLabel: shippingLabel || undefined,
        unitPricingMeasure: unitPricingMeasure || undefined,
        unitPricingBaseMeasure: unitPricingBaseMeasure || undefined,
        shippingLength: shippingLength || undefined,
        shippingWidth: shippingWidth || undefined,
        shippingHeight: shippingHeight || undefined,
        displayAdsId: displayAdsId || undefined,
        displayAdsSimilarIds: displayAdsSimilarIds || undefined,
        displayAdsTitle: displayAdsTitle || undefined,
        displayAdsLink: displayAdsLink || undefined,
        displayAdsValue: displayAdsValue || undefined,
        sellOnGoogleQuantity: sellOnGoogleQuantity || undefined,
        promotionIds: promotionIds || undefined,
        maxHandlingTime: maxHandlingTime || undefined,
        minHandlingTime: minHandlingTime || undefined,
        costOfGoodsSold: costOfGoodsSold || undefined,
        source: source || undefined,
        includedDestinations: includedDestinations || undefined,
        excludedDestinations: excludedDestinations || undefined,
        adsGrouping: adsGrouping || undefined,
        adsLabels: adsLabels || undefined,
        adsRedirect: adsRedirect || undefined,
        productTypes: productTypes || undefined,
        ageGroup: ageGroup || undefined,
        availability: availability || undefined,
        condition: condition || undefined,
        gender: gender || undefined,
        sizeSystem: sizeSystem || undefined,
        sizeType: sizeType || undefined,
        additionalSizeType: additionalSizeType || undefined,
        energyEfficiencyClass: energyEfficiencyClass || undefined,
        minEnergyEfficiencyClass: minEnergyEfficiencyClass || undefined,
        maxEnergyEfficiencyClass: maxEnergyEfficiencyClass || undefined,
        taxCategory: taxCategory || undefined,
        transitTimeLabel: transitTimeLabel || undefined,
        shoppingAdsExcludedCountries: shoppingAdsExcludedCountries || undefined,
        pickupMethod: pickupMethod || undefined,
        pickupSla: pickupSla || undefined,
        linkTemplate: linkTemplate || undefined,
        mobileLinkTemplate: mobileLinkTemplate || undefined,
        productDetails: productDetails || undefined,
        productHighlights: productHighlights || undefined,
        subscriptionCost: subscriptionCost || undefined,
        canonicalLink: canonicalLink || undefined,
        externalSellerId: externalSellerId || undefined,
        pause: pause || undefined,
      },
    });
    return {
      data,
    };
  },
  examplePayload: updateProductExamplePayload,
});
