




import type {
  CreateCustomerResponse,
  GetCustomerResponse,
  ListCustomersResponse,
  UpdateCustomerResponse,
} from "../interfaces/customers";

export const createCustomerExamplePayload: { data: CreateCustomerResponse } = {
  data: {
    id: 3924,
    created_datetime: "2019-04-13T03:27:56.973873",
    email: "john@example.com",
    external_id: "customer-84203241",
    firstname: "John",
    integrations: {
      "6": {
        orders: [
          {
            id: 772803526679,
            total_tax: "0.02",
            created_at: "2018-12-04T03:29:37-08:00",
            line_items: [
              {
                id: 1760305053719,
                sku: "0987654321",
                name: "Acidulous candy",
                grams: 10,
                price: "0.10",
                title: "Acidulous candy",
                taxable: true,
                quantity: 1,
                price_set: {
                  shop_money: {
                    amount: "0.10",
                    currency_code: "USD",
                  },
                  presentment_money: {
                    amount: "0.10",
                    currency_code: "USD",
                  },
                },
                tax_lines: [
                  {
                    rate: 0.2,
                    price: "0.02",
                    title: "TVA",
                    price_set: {
                      shop_money: {
                        amount: "0.02",
                        currency_code: "USD",
                      },
                      presentment_money: {
                        amount: "0.02",
                        currency_code: "USD",
                      },
                    },
                  },
                ],
                product_id: 8345093387,
                variant_id: 28442938955,
                total_discount: "0.00",
                requires_shipping: true,
                fulfillment_status: null,
                total_discount_set: {
                  shop_money: {
                    amount: "0.00",
                    currency_code: "USD",
                  },
                  presentment_money: {
                    amount: "0.00",
                    currency_code: "USD",
                  },
                },
                fulfillment_service: "manual",
                fulfillable_quantity: 1,
              },
            ],
            contact_email: "marie@gorgias.io",
            billing_address: {
              zip: "94103",
              city: "SAN FRANCISCO",
              name: "Marie Curie",
              country: "United States",
              address1: "52 Washburn Street",
              address2: "",
              province: "California",
              last_name: "Curie",
              first_name: "Marie",
              country_code: "US",
              province_code: "CA",
            },
          },
        ],
        customer: {
          id: 667928133655,
          note: "",
          tags: "",
          email: "marie@gorgias.io",
          firstname: "Marie",
          lastname: "Curie",
          orders_count: 1,
          default_address: {
            id: 707106144279,
            zip: "94103",
            city: "SAN FRANCISCO",
            name: "Marie Curie",
            country: "United States",
            default: true,
            address1: "52 Washburn Street",
            address2: "",
            province: "California",
            last_name: "Curie",
            first_name: "Marie",
            customer_id: 667928133655,
            country_code: "US",
            country_name: "United States",
            province_code: "CA",
          },
        },
        __integration_type__: "shopify",
      },
    },
    language: "fr",
    lastname: "Smith",
    name: "John Smith",
    note: "Our best customer.",
    timezone: "UTC",
    updated_datetime: "2019-09-25T06:18:22.839271",
  },
};

export const getCustomerExamplePayload: { data: GetCustomerResponse } = {
  data: {
    id: 3924,
    channels: [
      {
        id: 49182,
      },
    ],
    created_datetime: "2019-04-13T03:27:56.973873",
    email: "john@example.com",
    external_id: "customer-84203241",
    firstname: "John",
    integrations: {
      "6": {
        orders: [
          {
            id: 772803526679,
            total_tax: "0.02",
            created_at: "2018-12-04T03:29:37-08:00",
            line_items: [
              {
                id: 1760305053719,
                sku: "0987654321",
                name: "Acidulous candy",
                grams: 10,
                price: "0.10",
                title: "Acidulous candy",
                taxable: true,
                quantity: 1,
                price_set: {
                  shop_money: {
                    amount: "0.10",
                    currency_code: "USD",
                  },
                  presentment_money: {
                    amount: "0.10",
                    currency_code: "USD",
                  },
                },
                tax_lines: [
                  {
                    rate: 0.2,
                    price: "0.02",
                    title: "TVA",
                    price_set: {
                      shop_money: {
                        amount: "0.02",
                        currency_code: "USD",
                      },
                      presentment_money: {
                        amount: "0.02",
                        currency_code: "USD",
                      },
                    },
                  },
                ],
                product_id: 8345093387,
                variant_id: 28442938955,
                total_discount: "0.00",
                requires_shipping: true,
                fulfillment_status: null,
                total_discount_set: {
                  shop_money: {
                    amount: "0.00",
                    currency_code: "USD",
                  },
                  presentment_money: {
                    amount: "0.00",
                    currency_code: "USD",
                  },
                },
                fulfillment_service: "manual",
                fulfillable_quantity: 1,
              },
            ],
            contact_email: "marie@gorgias.io",
            billing_address: {
              zip: "94103",
              city: "SAN FRANCISCO",
              name: "Marie Curie",
              country: "United States",
              address1: "52 Washburn Street",
              address2: "",
              province: "California",
              last_name: "Curie",
              first_name: "Marie",
              country_code: "US",
              province_code: "CA",
            },
          },
        ],
        customer: {
          id: 667928133655,
          note: "",
          tags: "",
          email: "marie@gorgias.io",
          firstname: "Marie",
          lastname: "Curie",
          orders_count: 1,
          default_address: {
            id: 707106144279,
            zip: "94103",
            city: "SAN FRANCISCO",
            name: "Marie Curie",
            country: "United States",
            default: true,
            address1: "52 Washburn Street",
            address2: "",
            province: "California",
            last_name: "Curie",
            first_name: "Marie",
            customer_id: 667928133655,
            country_code: "US",
            country_name: "United States",
            province_code: "CA",
          },
        },
        __integration_type__: "shopify",
      },
    },
    language: "fr",
    lastname: "Smith",
    name: "John Smith",
    note: "Our best customer.",
    timezone: "UTC",
    updated_datetime: "2019-09-25T06:18:22.839271",
    external_data: {
      "my-awesome-3rd-party-app-ID": {
        badge: "Best customer",
        points: 22,
        __app_name__: "My awesome 3rd party app",
      },
    },
    ecommerce_data: {
      additionalProp: {
        store: {
          id: 123456,
          type: "woocommerce",
          helpdesk_integration_id: 123456,
          default_currency: "usd",
          url: "https://my-demo-store.com/",
          updated_datetime: "2023-07-15T00:00:00.000000+00:00",
          currencies: ["usd", "eur"],
          display_name: "My Demo Store",
          created_datetime: "2023-07-15T00:00:00.000000+00:00",
          name: "my-demo-store",
          deleted_datetime: "2023-07-15T00:00:00.000000+00:00",
          uuid: "7736626b-0d5f-4e2c-86de-8b74e3401c26",
        },
        shopper: {
          id: 123456,
          first_name: "Jean",
          helpdesk_customer_id: 123456,
          updated_datetime: "2023-07-15T00:00:00.000000+00:00",
          phone_number: "+1 123 456 7890",
          middle_name: "Mary",
          deleted_datetime: "2023-07-15T00:00:00.000000+00:00",
          birthdate: "2023-07-15",
          status: "tax_exempt",
          external_id: "example-id-123",
          email_address: "foo@bar.com",
          accepts_marketing_sms: true,
          accepts_marketing_email: true,
          last_name: "Doe",
          created_datetime: "2023-07-15T00:00:00.000000+00:00",
        },
        orders: [
          {
            external_status: "pending",
            total_amount: "20",
            number: 123456,
            billing_address: {
              id: 123456,
              first_name: "Jane",
              line_1: "123 Main Street",
              city: "Miami",
              zip_code: "123456",
              updated_datetime: "2023-07-15T00:00:00.000000+00:00",
              preferred: true,
              phone_number: "+1 123 456 7890",
              shopper_external_id: "example-id-123",
              country: "USA",
              line_2: "Apt 123, Floor 2",
              deleted_datetime: "2023-07-15T00:00:00.000000+00:00",
              last_name: "Doe",
              external_id: "example-id-123",
              state: "FL",
              created_datetime: "2023-07-15T00:00:00.000000+00:00",
            },
            tax_amount: "20",
            discount_codes: ["DISCOUNT_CODE_1", "DISCOUNT_CODE_2"],
            line_items: [
              {
                id: 123456,
                unit_price: "123456",
                discount_reason: "Refurbished product",
                discount_type: "percentage",
                title: "My Awesome Product",
                total_amount: "5",
                fulfilled_quantity: 5,
                updated_datetime: "2023-07-15T00:00:00.000000+00:00",
                taxable: true,
                discount_amount: "20",
                product_options: {
                  size: 10,
                },
                quantity: 5,
                deleted_datetime: "2023-07-15T00:00:00.000000+00:00",
                requires_shipping: true,
                created_datetime: "2023-07-15T00:00:00.000000+00:00",
              },
            ],
            status: "completed",
            external_fulfillment_status: "fulfilled",
            payment_status: "paid",
            shopper_external_id: "example-id-123",
            external_payment_status: "paid",
            name: "Order #123456",
            currency: "usd",
            created_datetime: "2023-07-15T00:00:00.000000+00:00",
            id: 123456,
            updated_datetime: "2023-07-15T00:00:00.000000+00:00",
            subtotal_amount: "20",
            deleted_datetime: "2023-07-15T00:00:00.000000+00:00",
            external_id: "example-id-123",
            shipping_address: {
              id: 123456,
              first_name: "Jane",
              line_1: "123 Main Street",
              city: "Miami",
              zip_code: "123456",
              updated_datetime: "2023-07-15T00:00:00.000000+00:00",
              preferred: true,
              phone_number: "+1 123 456 7890",
              shopper_external_id: "example-id-123",
              country: "USA",
              line_2: "Apt 123, Floor 2",
              deleted_datetime: "2023-07-15T00:00:00.000000+00:00",
              last_name: "Doe",
              external_id: "example-id-123",
              state: "FL",
              created_datetime: "2023-07-15T00:00:00.000000+00:00",
            },
            discount_amount: "20",
            shipping_amount: "20",
          },
        ],
        addresses: [
          {
            id: 123456,
            first_name: "Jane",
            line_1: "123 Main Street",
            city: "Miami",
            zip_code: "123456",
            updated_datetime: "2023-07-15T00:00:00.000000+00:00",
            preferred: true,
            phone_number: "+1 123 456 7890",
            shopper_external_id: "example-id-123",
            country: "USA",
            line_2: "Apt 123, Floor 2",
            deleted_datetime: "2023-07-15T00:00:00.000000+00:00",
            last_name: "Doe",
            external_id: "example-id-123",
            state: "FL",
            created_datetime: "2023-07-15T00:00:00.000000+00:00",
          },
        ],
      },
    },
  },
};

export const updateCustomerExamplePayload: { data: UpdateCustomerResponse } = {
  data: {
    id: 3924,
    created_datetime: "2019-04-13T03:27:56.973873",
    email: "john@example.com",
    external_id: "customer-84203241",
    firstname: "John",
    integrations: {
      "6": {
        orders: [
          {
            id: 772803526679,
            total_tax: "0.02",
            created_at: "2018-12-04T03:29:37-08:00",
            line_items: [
              {
                id: 1760305053719,
                sku: "0987654321",
                name: "Acidulous candy",
                grams: 10,
                price: "0.10",
                title: "Acidulous candy",
                taxable: true,
                quantity: 1,
                price_set: {
                  shop_money: {
                    amount: "0.10",
                    currency_code: "USD",
                  },
                  presentment_money: {
                    amount: "0.10",
                    currency_code: "USD",
                  },
                },
                tax_lines: [
                  {
                    rate: 0.2,
                    price: "0.02",
                    title: "TVA",
                    price_set: {
                      shop_money: {
                        amount: "0.02",
                        currency_code: "USD",
                      },
                      presentment_money: {
                        amount: "0.02",
                        currency_code: "USD",
                      },
                    },
                  },
                ],
                product_id: 8345093387,
                variant_id: 28442938955,
                total_discount: "0.00",
                requires_shipping: true,
                fulfillment_status: null,
                total_discount_set: {
                  shop_money: {
                    amount: "0.00",
                    currency_code: "USD",
                  },
                  presentment_money: {
                    amount: "0.00",
                    currency_code: "USD",
                  },
                },
                fulfillment_service: "manual",
                fulfillable_quantity: 1,
              },
            ],
            contact_email: "marie@gorgias.io",
            billing_address: {
              zip: "94103",
              city: "SAN FRANCISCO",
              name: "Marie Curie",
              country: "United States",
              address1: "52 Washburn Street",
              address2: "",
              province: "California",
              last_name: "Curie",
              first_name: "Marie",
              country_code: "US",
              province_code: "CA",
            },
          },
        ],
        customer: {
          id: 667928133655,
          note: "",
          tags: "",
          email: "marie@gorgias.io",
          firstname: "Marie",
          lastname: "Curie",
          orders_count: 1,
          default_address: {
            id: 707106144279,
            zip: "94103",
            city: "SAN FRANCISCO",
            name: "Marie Curie",
            country: "United States",
            default: true,
            address1: "52 Washburn Street",
            address2: "",
            province: "California",
            last_name: "Curie",
            first_name: "Marie",
            customer_id: 667928133655,
            country_code: "US",
            country_name: "United States",
            province_code: "CA",
          },
        },
        __integration_type__: "shopify",
      },
    },
    language: "fr",
    lastname: "Smith",
    name: "John Smith",
    note: "Our best customer.",
    timezone: "UTC",
    updated_datetime: "2019-09-25T06:18:22.839271",
  },
};

export const listCustomersExamplePayload: { data: ListCustomersResponse } = {
  data: {
    data: [
      {
        id: 1,
        created_datetime: null,
        email: null,
        external_id: null,
        firstname: "Jane",
        language: null,
        lastname: "Doe",
        name: null,
        timezone: null,
        updated_datetime: "20190925T06:18:22.839271",
      },
    ],
    object: "list",
    uri: "/customers",
    meta: {
      prev_cursor: null,
      next_cursor: null,
    },
  },
};
