




import type {
  CreateTicketResponse,
  GetTicketResponse,
  ListTicketCustomFieldsResponse,
  ListTicketsResponse,
  UpdateTicketCustomFieldsResponse,
  UpdateTicketResponse,
} from "../interfaces/tickets";

export const createTicketExamplePayload: { data: CreateTicketResponse } = {
  data: {
    id: 1234,
    assignee_user: {
      id: 567,
      email: "assignee@example.com",
      name: "Alex Johnson",
      firstname: "Alex",
      lastname: "Johnson",
      meta: {
        sso: "sso-link",
        profile_picture_url: "https://www.example.com/images/profile.jpg",
      },
    },
    channel: "Email",
    closed_datetime: null,
    created_datetime: "2024-08-21T12:00:00Z",
    customer: {
      id: 789,
      channels: [{ id: 1 }, { id: 2 }],
      email: "customer@example.com",
      external_id: "C123456",
      firstname: "Sam",
      integrations: { CRM: { customer_level: "Gold", points: 1200 } },
      lastname: "Doe",
      name: "Sam Doe",
      note: "VIP Customer, handle with care.",
    },
    external_id: "EXT1234",
    from_agent: false,
    is_unread: true,
    language: "en",
    last_message_datetime: "2024-08-21T12:05:00Z",
    last_received_message_datetime: "2024-08-21T12:04:00Z",
    messages: [
      {
        id: 2345,
        attachments: [
          {
            url: "https://www.example.com/attachments/info.pdf",
            name: "Information.pdf",
            size: 1024,
            content_type: "application/pdf",
            public: true,
            extra: "User manual",
          },
        ],
        body_html:
          "<p>Please see the attached user manual for more information.</p>",
        body_text: "Please see the attached user manual for more information.",
        channel: "Email",
        created_datetime: "2024-08-21T12:05:00Z",
        external_id: null,
        failed_datetime: null,
        from_agent: true,
        integration_id: 456,
        last_sending_error: null,
        message_id: "MSG4567",
        receiver: {
          id: 789,
          email: "customer@example.com",
          name: "Sam Doe",
          firstname: "Sam",
          lastname: "Doe",
          meta: null,
        },
        rule_id: 321,
        sender: {
          id: 567,
          email: "support@example.com",
          name: "Support Team",
          firstname: "Support",
          lastname: "Team",
          meta: null,
        },
        sent_datetime: "2024-08-21T12:05:00Z",
        source: {
          type: "email",
          to: [{ name: "Sam Doe", address: "customer@example.com" }],
          cc: [],
          bcc: [],
          from: { name: "Support Team", address: "support@example.com" },
        },
        stripped_html:
          "<p>Please see the attached user manual for more information.</p>",
        stripped_text:
          "Please see the attached user manual for more information.",
        subject: "User Manual",
        ticket_id: 1234,
        via: "Email",
        uri: "https://www.example.com/tickets/1234",
      },
    ],
    meta: { issue_type: "technical", priority: "high" },
    opened_datetime: "2024-08-21T12:00:00Z",
    reply_options: "Reply, Forward, Archive",
    satisfaction_survey: {
      id: 876,
      body_text: "Please rate our service.",
      created_datetime: "2024-08-21T12:30:00Z",
      customer_id: 789,
      meta: { survey_type: "email" },
      score: null,
      scored_datetime: null,
      sent_datetime: null,
      should_send_datetime: "2024-08-22T12:30:00Z",
      ticket_id: 1234,
    },
    snoozed_datetime: null,
    spam: false,
    status: "open",
    subject: "Technical Support Inquiry",
    tags: [
      {
        id: 1,
        name: "Technical",
        uri: "https://www.example.com/tags/technical",
        decoration: { color: "#FF5733" },
      },
      {
        id: 2,
        name: "High Priority",
        uri: "https://www.example.com/tags/high_priority",
        decoration: { color: "#C70039" },
      },
    ],
    trashed_datetime: null,
    updated_datetime: "2024-08-21T12:10:00Z",
    via: "Email",
    uri: "https://www.example.com/tickets/1234",
  },
};

export const getTicketExamplePayload: { data: GetTicketResponse } = {
  data: {
    id: 101,
    url: "https://www.example.com/tickets/101",
    external_id: "EXT1001",
    events: [
      {
        idcreated_datetime: "2024-08-22T10:00:00Z",
        data: {
          action: "Ticket Created",
          details: "Initial creation of the ticket",
        },
        type: "Creation",
        user: {
          id: 2001,
          firstname: "Alice",
          lastname: "Johnson",
          name: "Alice Johnson",
          email: "alice.johnson@example.com",
        },
        uri: "https://www.example.com/events/1001",
      },
    ],
    status: "Open",
    channel: "Email",
    via: "Web",
    from_agent: false,
    is_unread: true,
    spam: null,
    customer: {
      id: 501,
      channels: [
        {
          id: 1,
          type: "Email",
          address: "customer501@example.com",
          preferred: true,
          created_datetime: "2024-01-01T12:00:00Z",
          updated_datetime: "2024-01-02T12:00:00Z",
          deleted_datetime: null,
          user: {
            id: 501,
            name: "John Doe",
          },
          customer: {
            id: 501,
            name: "John Doe",
          },
        },
      ],
      email: "customer501@example.com",
      external_id: "CUST1001",
      firstname: "John",
      integrations: { CRM: { customer_level: "Gold" } },
      external_data: [{ loyalty_points: 1200 }],
      ecommerce_data: { last_purchase: { date: "2024-01-10", amount: 300.0 } },
      lastname: "Doe",
      meta: null,
      name: "John Doe",
      note: "High value customer",
    },
    assignee_user: {
      id: 301,
      email: "agent301@example.com",
      name: "Sarah Parker",
      firstname: "Sarah",
      lastname: "Parker",
      meta: {
        sso: "sso-agent-link",
        profile_picture_url: "https://www.example.com/images/agent301.jpg",
      },
    },
    language: "en",
    subject: "Support Request",
    meta: { priority: "high", category: "technical" },
    tags: [
      {
        id: 1,
        name: "Urgent",
        uri: "https://www.example.com/tags/urgent",
        decoration: {
          color: "#FF0000",
        },
      },
    ],
    custom_fields: null,
    messages: [
      {
        id: 201,
        attachments: [
          {
            url: "https://www.example.com/attachments/guide.pdf",
            name: "UserGuide.pdf",
            size: 1024,
            content_type: "application/pdf",
            public: true,
            extra: "Attachment with additional details",
          },
        ],
        body_html:
          "<p>Please see the attached user guide for more information.</p>",
        body_text: "Please see the attached user guide for more information.",
        channel: "Email",
        created_datetime: "2024-08-22T10:05:00Z",
        external_id: null,
        failed_datetime: null,
        from_agent: true,
        integration_id: 101,
        last_sending_error: null,
        message_id: "MSG2001",
        receiver: {
          id: 501,
          email: "customer501@example.com",
          name: "John Doe",
          firstname: "John",
          lastname: "Doe",
          meta: null,
        },
        rule_id: 101,
        sender: {
          id: 301,
          email: "agent301@example.com",
          name: "Sarah Parker",
          firstname: "Sarah",
          lastname: "Parker",
          meta: null,
        },
        sent_datetime: "2024-08-22T10:05:00Z",
        source: {
          type: "email",
          to: [{ name: "John Doe", address: "customer501@example.com" }],
          cc: [],
          bcc: [],
          from: { name: "Sarah Parker", address: "agent301@example.com" },
        },
        stripped_html:
          "<p>Please see the attached user guide for more information.</p>",
        stripped_text:
          "Please see the attached user guide for more information.",
        subject: "User Guide",
        ticket_id: 101,
        via: "Email",
        uri: "https://www.example.com/messages/201",
      },
    ],
    created_datetime: "2024-08-22T10:00:00Z",
    opened_datetime: "2024-08-22T10:01:00Z",
    last_received_message_datetime: "2024-08-22T10:04:00Z",
    last_message_datetime: "2024-08-22T10:05:00Z",
    updated_datetime: "2024-08-22T10:06:00Z",
    closed_datetime: null,
    trashed_datetime: null,
    snooze_datetime: null,
    satisfaction_survey: {
      id: 401,
      body_text: "Please rate our service.",
      created_datetime: "2024-08-22T10:30:00Z",
      customer_id: 501,
      meta: null,
      score: null,
      scored_datetime: null,
      sent_datetime: null,
      should_send_datetime: "2024-08-23T10:30:00Z",
      ticket_id: 101,
    },
    reply_options: "Reply, Forward, Archive",
  },
};

export const listTicketCustomFieldsExamplePayload: {
  data: ListTicketCustomFieldsResponse;
} = {
  data: [
    {
      field: {
        id: 101,
        external_id: "EXT001",
        object_type: "ticket",
        label: "Customer Satisfaction Score",
        description:
          "A score representing customer satisfaction on a scale of 1 to 10.",
        priority: 10,
        required: true,
        managed_by: "system",
        definition: {
          input_settings: "DROPDOWN",
          data_type: "integer",
        },
        created_datetime: "2024-08-21T12:00:00Z",
        updated_datetime: "2024-08-21T12:30:00Z",
        deactivated_datetime: null,
      },
      value: "8",
      prediction: {
        predicted: "7",
        confidence: 75.0,
        display: true,
        confirmed: false,
        modified: false,
      },
    },
  ],
};

export const listTicketsExamplePayload: { data: ListTicketsResponse } = {
  data: {
    data: [
      {
        id: 1001,
        assignee_user: {
          id: 201,
          email: "jane.doe@example.com",
          name: "Jane Doe",
          firstname: "Jane",
          lastname: "Doe",
          meta: {
            sso: "sso-link",
            profile_picture_url: "https://www.example.com/images/jane.jpg",
          },
        },
        channel: "Email",
        closed_datetime: "2024-08-21T19:00:00Z",
        created_datetime: "2024-08-21T08:30:00Z",
        customer: {
          id: 301,
          email: "customer301@example.com",
          name: "John Smith",
          firstname: "John",
          lastname: "Smith",
        },
        excerpt: "Urgent issue regarding account access...",
        external_id: "EXT-1001",
        from_agent: false,
        integrations: { CRM: { customer_id: "1001", interaction_count: 5 } },
        is_unread: true,
        language: "en",
        last_message_datetime: "2024-08-21T18:45:00Z",
        last_received_message_datetime: "2024-08-21T18:44:00Z",
        messages_count: 5,
        meta: { priority: "high", category: "account issue" },
        opened_datetime: "2024-08-21T09:00:00Z",
        snoozed_datetime: null,
        status: "Closed",
        subject: "Account Access Problem",
        tags: [
          {
            id: 101,
            name: "urgent",
            uri: "https://www.example.com/tags/urgent",
            decoration: { color: "#FF0000" },
          },
          {
            id: 102,
            name: "account-issue",
            uri: "https://www.example.com/tags/account-issue",
            decoration: { color: "#0000FF" },
          },
        ],
        spam: false,
        trashed_datetime: null,
        updated_datetime: "2024-08-21T18:50:00Z",
        via: "web",
        uri: "https://www.example.com/tickets/1001",
      },
      {
        id: 1002,
        assignee_user: {
          id: 202,
          email: "tom.black@example.com",
          name: "Tom Black",
          firstname: "Tom",
          lastname: "Black",
          meta: {
            sso: null,
            profile_picture_url: null,
          },
        },
        channel: "Phone",
        closed_datetime: null,
        created_datetime: "2024-08-21T10:00:00Z",
        customer: {
          id: 302,
          email: "customer302@example.com",
          name: "Alice Johnson",
          firstname: "Alice",
          lastname: "Johnson",
        },
        excerpt: "Inquiry about billing adjustments...",
        external_id: "EXT-1002",
        from_agent: true,
        integrations: {
          BillingSystem: { account_id: "302", last_payment_date: "2024-08-15" },
        },
        is_unread: false,
        language: "es",
        last_message_datetime: "2024-08-21T15:30:00Z",
        last_received_message_datetime: "2024-08-21T15:29:00Z",
        messages_count: 3,
        meta: { priority: "medium", category: "billing" },
        opened_datetime: "2024-08-21T10:15:00Z",
        snoozed_datetime: null,
        status: "Open",
        subject: "Billing Adjustment Request",
        tags: [
          {
            id: 103,
            name: "billing",
            uri: "https://www.example.com/tags/billing",
            decoration: { color: "#00FF00" },
          },
        ],
        spam: null,
        trashed_datetime: null,
        updated_datetime: "2024-08-21T15:35:00Z",
        via: "phone",
        uri: "https://www.example.com/tickets/1002",
      },
    ],
    object: "list",
    uri: "/tickets",
    meta: {
      prev_cursor: null,
      next_cursor: null,
    },
  },
};

export const updateTicketExamplePayload: { data: UpdateTicketResponse } = {
  data: {
    id: 2201,
    assignee_user: {
      id: 450,
      email: "sara.jones@example.com",
      name: "Sara Jones",
      firstname: "Sara",
      lastname: "Jones",
      meta: {
        sso: "sso-jones-link",
        profile_picture_url: "https://www.example.com/images/sara.jpg",
      },
    },
    channel: "Web",
    closed_datetime: null,
    created_datetime: "2024-08-22T10:00:00Z",
    customer: {
      id: 550,
      channels: [
        {
          id: 1,
        },
      ],
      email: "customer550@example.com",
      external_id: "550-external",
      firstname: "Michael",
      integrations: {
        CRM: { customer_level: "Silver", interaction_count: 10 },
      },
      lastname: "Brown",
      name: "Michael Brown",
      note: "Needs follow-up on previous issue",
    },
    external_id: "EXT-2201",
    from_agent: true,
    is_unread: true,
    language: "en",
    last_message_datetime: "2024-08-22T10:15:00Z",
    last_received_message_datetime: "2024-08-22T10:14:00Z",
    messages: [
      {
        id: 3301,
        attachments: [
          {
            url: "https://www.example.com/attachments/info.pdf",
            name: "Details.pdf",
            size: 2048,
            content_type: "application/pdf",
            public: true,
            extra: "Detailed document",
          },
        ],
        body_html:
          "<p>Thank you for reaching out. Please see the attached document for more information.</p>",
        body_text:
          "Thank you for reaching out. Please see the attached document for more information.",
        channel: "Email",
        created_datetime: "2024-08-22T10:15:00Z",
        external_id: "MSG-3301",
        failed_datetime: null,
        from_agent: true,
        integration_id: 501,
        last_sending_error: null,
        message_id: "MSG-3301",
        receiver: {
          id: 550,
          email: "customer550@example.com",
          name: "Michael Brown",
          firstname: "Michael",
          lastname: "Brown",
          meta: null,
        },
        rule_id: 101,
        sender: {
          id: 450,
          email: "sara.jones@example.com",
          name: "Sara Jones",
          firstname: "Sara",
          lastname: "Jones",
          meta: null,
        },
        sent_datetime: "2024-08-22T10:15:00Z",
        source: {
          type: "Email",
          to: [{ name: "Michael Brown", address: "customer550@example.com" }],
          cc: [],
          bcc: [],
          from: { name: "Sara Jones", address: "sara.jones@example.com" },
        },
        stripped_html:
          "<p>Thank you for reaching out. Please see the attached document for more information.</p>",
        stripped_text:
          "Thank you for reaching out. Please see the attached document for more information.",
        subject: "Further Information Required",
        ticket_id: 2201,
        via: "Email",
        uri: "https://www.example.com/messages/3301",
      },
    ],
    meta: { issue_type: "technical", priority: "high" },
    opened_datetime: "2024-08-22T10:01:00Z",
    reply_options: "Reply, Forward, Archive",
    satisfaction_survey: {
      id: 402,
      body_text: "Please rate our service.",
      created_datetime: "2024-08-22T12:30:00Z",
      customer_id: 550,
      meta: { survey_type: "email" },
      score: null,
      scored_datetime: null,
      sent_datetime: null,
      should_send_datetime: "2024-08-23T12:30:00Z",
      ticket_id: 2201,
    },
    snoozed_datetime: null,
    spam: false,
    status: "Open",
    subject: "Support Inquiry",
    tags: [
      {
        id: 301,
        name: "Technical Support",
        uri: "https://www.example.com/tags/technical-support",
        decoration: { color: "#007BFF" },
      },
    ],
    trashed_datetime: null,
    updated_datetime: "2024-08-22T10:20:00Z",
    via: "Web",
    uri: "https://www.example.com/tickets/2201",
  },
};

export const updateTicketCustomFieldsExamplePayload: {
  data: UpdateTicketCustomFieldsResponse;
} = {
  data: [
    {
      field: {
        id: 101,
        external_id: "CF-101",
        object_type: "ticket",
        label: "Urgency Level",
        description:
          "A measure of how urgently the issue needs to be resolved.",
        priority: 5,
        required: true,
        managed_by: "system",
        definition: {
          input_settings: "DROPDOWN",
          data_type: "integer",
        },
        created_datetime: "2024-01-01T12:00:00Z",
        updated_datetime: "2024-08-21T12:30:00Z",
        deactivated_datetime: null,
      },
      value: "High",
      prediction: {
        predicted: "Medium",
        confidence: 85.0,
        display: true,
        confirmed: false,
        modified: true,
      },
    },
    {
      field: {
        id: 102,
        external_id: "CF-102",
        object_type: "ticket",
        label: "Resolution Time",
        description: "Estimated time to resolve the ticket.",
        priority: 3,
        required: false,
        managed_by: "admin",
        definition: {
          input_settings: "INPUT_NUMBER",
          data_type: "integer",
        },
        created_datetime: "2024-01-02T13:00:00Z",
        updated_datetime: "2024-08-21T14:00:00Z",
        deactivated_datetime: null,
      },
      value: "48",
      prediction: {
        predicted: "72",
        confidence: 70.0,
        display: true,
        confirmed: true,
        modified: false,
      },
    },
    {
      field: {
        id: 103,
        external_id: "CF-103",
        object_type: "ticket",
        label: "Customer Satisfaction",
        description: "Predicted customer satisfaction based on resolution.",
        priority: 2,
        required: true,
        managed_by: "system",
        definition: {
          input_settings: "INPUT",
          data_type: "integer",
        },
        created_datetime: "2024-01-03T14:00:00Z",
        updated_datetime: "2024-08-21T15:00:00Z",
        deactivated_datetime: null,
      },
      value: "5",
      prediction: {
        predicted: "6",
        confidence: 65.0,
        display: true,
        confirmed: false,
        modified: true,
      },
    },
  ],
};
