export const sandboxUrl = "https://commercedeveloper-sandbox-api.adobe.com";

export const productionUrl = "https://commercedeveloper-api.adobe.com";





export const POLL_PAGE_SIZE = 100;
export const MAX_POLL_PAGES = 50;






export const POLL_RESOURCE_CONFIG: Record<string, { endpoint: string; idField: string }> = {
  orders: { endpoint: "/orders", idField: "entity_id" },
  customers: { endpoint: "/customers/search", idField: "id" },
  products: { endpoint: "/products", idField: "id" },
};

export const productJson = {
  product: {
    id: 0,
    sku: "string",
    name: "string",
    attribute_set_id: 0,
    price: 0,
    status: 0,
    visibility: 0,
    type_id: "string",
    created_at: "string",
    updated_at: "string",
    weight: 0,
    extension_attributes: {
      website_ids: [0],
      category_links: [
        {
          position: 0,
          category_id: "string",
          extension_attributes: {},
        },
      ],
      discounts: [
        {
          discount_data: {
            amount: 0,
            base_amount: 0,
            original_amount: 0,
            base_original_amount: 0,
          },
          rule_label: "string",
          rule_id: 0,
        },
      ],
      bundle_product_options: [
        {
          option_id: 0,
          title: "string",
          required: true,
          type: "string",
          position: 0,
          sku: "string",
          product_links: [
            {
              id: "string",
              sku: "string",
              option_id: 0,
              qty: 0,
              position: 0,
              is_default: true,
              price: 0,
              price_type: 0,
              can_change_quantity: 0,
              extension_attributes: {},
            },
          ],
          extension_attributes: {},
        },
      ],
      stock_item: {
        item_id: 0,
        product_id: 0,
        stock_id: 0,
        qty: 0,
        is_in_stock: true,
        is_qty_decimal: true,
        show_default_notification_message: true,
        use_config_min_qty: true,
        min_qty: 0,
        use_config_min_sale_qty: 0,
        min_sale_qty: 0,
        use_config_max_sale_qty: true,
        max_sale_qty: 0,
        use_config_backorders: true,
        backorders: 0,
        use_config_notify_stock_qty: true,
        notify_stock_qty: 0,
        use_config_qty_increments: true,
        qty_increments: 0,
        use_config_enable_qty_inc: true,
        enable_qty_increments: true,
        use_config_manage_stock: true,
        manage_stock: true,
        low_stock_date: "string",
        is_decimal_divided: true,
        stock_status_changed_auto: 0,
        extension_attributes: {},
      },
      downloadable_product_links: [
        {
          id: 0,
          title: "string",
          sort_order: 0,
          is_shareable: 0,
          price: 0,
          number_of_downloads: 0,
          link_type: "string",
          link_file: "string",
          link_file_content: {
            file_data: "string",
            name: "string",
            extension_attributes: {},
          },
          link_url: "string",
          sample_type: "string",
          sample_file: "string",
          sample_file_content: {
            file_data: "string",
            name: "string",
            extension_attributes: {},
          },
          sample_url: "string",
          extension_attributes: {},
        },
      ],
      downloadable_product_samples: [
        {
          id: 0,
          title: "string",
          sort_order: 0,
          sample_type: "string",
          sample_file: "string",
          sample_file_content: {
            file_data: "string",
            name: "string",
            extension_attributes: {},
          },
          sample_url: "string",
          extension_attributes: {},
        },
      ],
      giftcard_amounts: [
        {
          attribute_id: 0,
          website_id: 0,
          value: 0,
          website_value: 0,
          extension_attributes: {},
        },
      ],
      configurable_product_options: [
        {
          id: 0,
          attribute_id: "string",
          label: "string",
          position: 0,
          is_use_default: true,
          values: [
            {
              value_index: 0,
              extension_attributes: {},
            },
          ],
          extension_attributes: {},
          product_id: 0,
        },
      ],
      configurable_product_links: [0],
    },
    product_links: [
      {
        sku: "string",
        link_type: "string",
        linked_product_sku: "string",
        linked_product_type: "string",
        position: 0,
        extension_attributes: {
          qty: 0,
        },
      },
    ],
    options: [
      {
        product_sku: "string",
        option_id: 0,
        title: "string",
        type: "string",
        sort_order: 0,
        is_require: true,
        price: 0,
        price_type: "string",
        sku: "string",
        file_extension: "string",
        max_characters: 0,
        image_size_x: 0,
        image_size_y: 0,
        values: [
          {
            title: "string",
            sort_order: 0,
            price: 0,
            price_type: "string",
            sku: "string",
            option_type_id: 0,
          },
        ],
        extension_attributes: {},
      },
    ],
    media_gallery_entries: [
      {
        id: 0,
        media_type: "string",
        label: "string",
        position: 0,
        disabled: true,
        types: ["string"],
        file: "string",
        content: {
          base64_encoded_data: "string",
          type: "string",
          name: "string",
        },
        extension_attributes: {
          video_content: {
            media_type: "string",
            video_provider: "string",
            video_url: "string",
            video_title: "string",
            video_description: "string",
            video_metadata: "string",
          },
        },
      },
    ],
    tier_prices: [
      {
        customer_group_id: 0,
        qty: 0,
        value: 0,
        extension_attributes: {
          percentage_value: 0,
          website_id: 0,
        },
      },
    ],
    custom_attributes: [
      {
        attribute_code: "string",
        value: "string",
      },
    ],
  },
  saveOptions: true,
};

export const attributeJson = {
  attribute: {
    extension_attributes: {
      is_pagebuilder_enabled: true,
    },
    is_wysiwyg_enabled: true,
    is_html_allowed_on_front: true,
    used_for_sort_by: true,
    is_filterable: true,
    is_filterable_in_search: true,
    is_used_in_grid: true,
    is_visible_in_grid: true,
    is_filterable_in_grid: true,
    position: 0,
    apply_to: ["string"],
    is_searchable: "string",
    is_visible_in_advanced_search: "string",
    is_comparable: "string",
    is_used_for_promo_rules: "string",
    is_visible_on_front: "string",
    used_in_product_listing: "string",
    is_visible: true,
    scope: "string",
    attribute_id: 0,
    attribute_code: "string",
    frontend_input: "string",
    entity_type_id: "string",
    is_required: true,
    options: [
      {
        label: "string",
        value: "string",
        sort_order: 0,
        is_default: true,
        store_labels: [
          {
            store_id: 0,
            label: "string",
          },
        ],
      },
    ],
    is_user_defined: true,
    default_frontend_label: "string",
    frontend_labels: [
      {
        store_id: 0,
        label: "string",
      },
    ],
    note: "string",
    backend_type: "string",
    backend_model: "string",
    source_model: "string",
    default_value: "string",
    is_unique: "string",
    frontend_class: "string",
    validation_rules: [
      {
        key: "string",
        value: "string",
      },
    ],
    custom_attributes: [
      {
        attribute_code: "string",
        value: "string",
      },
    ],
  },
};

export const optionJson = {
  option: {
    product_sku: "string",
    option_id: 0,
    title: "string",
    type: "string",
    sort_order: 0,
    is_require: true,
    price: 0,
    price_type: "string",
    sku: "string",
    file_extension: "string",
    max_characters: 0,
    image_size_x: 0,
    image_size_y: 0,
    values: [
      {
        title: "string",
        sort_order: 0,
        price: 0,
        price_type: "string",
        sku: "string",
        option_type_id: 0,
      },
    ],
    extension_attributes: {},
  },
};

export const entityJson = {
  entity: {
    adjustment_negative: 0,
    adjustment_positive: 0,
    applied_rule_ids: "string",
    base_adjustment_negative: 0,
    base_adjustment_positive: 0,
    base_currency_code: "string",
    base_discount_amount: 0,
    base_discount_canceled: 0,
    base_discount_invoiced: 0,
    base_discount_refunded: 0,
    base_grand_total: 0,
    base_discount_tax_compensation_amount: 0,
    base_discount_tax_compensation_invoiced: 0,
    base_discount_tax_compensation_refunded: 0,
    base_shipping_amount: 0,
    base_shipping_canceled: 0,
    base_shipping_discount_amount: 0,
    base_shipping_discount_tax_compensation_amnt: 0,
    base_shipping_incl_tax: 0,
    base_shipping_invoiced: 0,
    base_shipping_refunded: 0,
    base_shipping_tax_amount: 0,
    base_shipping_tax_refunded: 0,
    base_subtotal: 0,
    base_subtotal_canceled: 0,
    base_subtotal_incl_tax: 0,
    base_subtotal_invoiced: 0,
    base_subtotal_refunded: 0,
    base_tax_amount: 0,
    base_tax_canceled: 0,
    base_tax_invoiced: 0,
    base_tax_refunded: 0,
    base_total_canceled: 0,
    base_total_due: 0,
    base_total_invoiced: 0,
    base_total_invoiced_cost: 0,
    base_total_offline_refunded: 0,
    base_total_online_refunded: 0,
    base_total_paid: 0,
    base_total_qty_ordered: 0,
    base_total_refunded: 0,
    base_to_global_rate: 0,
    base_to_order_rate: 0,
    billing_address_id: 0,
    can_ship_partially: 0,
    can_ship_partially_item: 0,
    coupon_code: "string",
    created_at: "string",
    customer_dob: "string",
    customer_email: "string",
    customer_firstname: "string",
    customer_gender: 0,
    customer_group_id: 0,
    customer_id: 0,
    customer_is_guest: 0,
    customer_lastname: "string",
    customer_middlename: "string",
    customer_note: "string",
    customer_note_notify: 0,
    customer_prefix: "string",
    customer_suffix: "string",
    customer_taxvat: "string",
    discount_amount: 0,
    discount_canceled: 0,
    discount_description: "string",
    discount_invoiced: 0,
    discount_refunded: 0,
    edit_increment: 0,
    email_sent: 0,
    entity_id: 0,
    ext_customer_id: "string",
    ext_order_id: "string",
    forced_shipment_with_invoice: 0,
    global_currency_code: "string",
    grand_total: 0,
    discount_tax_compensation_amount: 0,
    discount_tax_compensation_invoiced: 0,
    discount_tax_compensation_refunded: 0,
    hold_before_state: "string",
    hold_before_status: "string",
    increment_id: "string",
    is_virtual: 0,
    order_currency_code: "string",
    original_increment_id: "string",
    payment_authorization_amount: 0,
    payment_auth_expiration: 0,
    protect_code: "string",
    quote_address_id: 0,
    quote_id: 0,
    relation_child_id: "string",
    relation_child_real_id: "string",
    relation_parent_id: "string",
    relation_parent_real_id: "string",
    remote_ip: "string",
    shipping_amount: 0,
    shipping_canceled: 0,
    shipping_description: "string",
    shipping_discount_amount: 0,
    shipping_discount_tax_compensation_amount: 0,
    shipping_incl_tax: 0,
    shipping_invoiced: 0,
    shipping_refunded: 0,
    shipping_tax_amount: 0,
    shipping_tax_refunded: 0,
    state: "string",
    status: "string",
    store_currency_code: "string",
    store_id: 0,
    store_name: "string",
    store_to_base_rate: 0,
    store_to_order_rate: 0,
    subtotal: 0,
    subtotal_canceled: 0,
    subtotal_incl_tax: 0,
    subtotal_invoiced: 0,
    subtotal_refunded: 0,
    tax_amount: 0,
    tax_canceled: 0,
    tax_invoiced: 0,
    tax_refunded: 0,
    total_canceled: 0,
    total_due: 0,
    total_invoiced: 0,
    total_item_count: 0,
    total_offline_refunded: 0,
    total_online_refunded: 0,
    total_paid: 0,
    total_qty_ordered: 0,
    total_refunded: 0,
    updated_at: "string",
    weight: 0,
    x_forwarded_for: "string",
    items: [
      {
        additional_data: "string",
        amount_refunded: 0,
        applied_rule_ids: "string",
        base_amount_refunded: 0,
        base_cost: 0,
        base_discount_amount: 0,
        base_discount_invoiced: 0,
        base_discount_refunded: 0,
        base_discount_tax_compensation_amount: 0,
        base_discount_tax_compensation_invoiced: 0,
        base_discount_tax_compensation_refunded: 0,
        base_original_price: 0,
        base_price: 0,
        base_price_incl_tax: 0,
        base_row_invoiced: 0,
        base_row_total: 0,
        base_row_total_incl_tax: 0,
        base_tax_amount: 0,
        base_tax_before_discount: 0,
        base_tax_invoiced: 0,
        base_tax_refunded: 0,
        base_weee_tax_applied_amount: 0,
        base_weee_tax_applied_row_amnt: 0,
        base_weee_tax_disposition: 0,
        base_weee_tax_row_disposition: 0,
        created_at: "string",
        description: "string",
        discount_amount: 0,
        discount_invoiced: 0,
        discount_percent: 0,
        discount_refunded: 0,
        event_id: 0,
        ext_order_item_id: "string",
        free_shipping: 0,
        gw_base_price: 0,
        gw_base_price_invoiced: 0,
        gw_base_price_refunded: 0,
        gw_base_tax_amount: 0,
        gw_base_tax_amount_invoiced: 0,
        gw_base_tax_amount_refunded: 0,
        gw_id: 0,
        gw_price: 0,
        gw_price_invoiced: 0,
        gw_price_refunded: 0,
        gw_tax_amount: 0,
        gw_tax_amount_invoiced: 0,
        gw_tax_amount_refunded: 0,
        discount_tax_compensation_amount: 0,
        discount_tax_compensation_canceled: 0,
        discount_tax_compensation_invoiced: 0,
        discount_tax_compensation_refunded: 0,
        is_qty_decimal: 0,
        is_virtual: 0,
        item_id: 0,
        locked_do_invoice: 0,
        locked_do_ship: 0,
        name: "string",
        no_discount: 0,
        order_id: 0,
        original_price: 0,
        parent_item_id: 0,
        price: 0,
        price_incl_tax: 0,
        product_id: 0,
        product_type: "string",
        qty_backordered: 0,
        qty_canceled: 0,
        qty_invoiced: 0,
        qty_ordered: 0,
        qty_refunded: 0,
        qty_returned: 0,
        qty_shipped: 0,
        quote_item_id: 0,
        row_invoiced: 0,
        row_total: 0,
        row_total_incl_tax: 0,
        row_weight: 0,
        sku: "string",
        store_id: 0,
        tax_amount: 0,
        tax_before_discount: 0,
        tax_canceled: 0,
        tax_invoiced: 0,
        tax_percent: 0,
        tax_refunded: 0,
        updated_at: "string",
        weee_tax_applied: "string",
        weee_tax_applied_amount: 0,
        weee_tax_applied_row_amount: 0,
        weee_tax_disposition: 0,
        weee_tax_row_disposition: 0,
        weight: 0,
        parent_item: {},
        product_option: {
          extension_attributes: {
            custom_options: [
              {
                option_id: null,
                option_value: null,
                extension_attributes: null,
              },
            ],
            bundle_options: [
              {
                option_id: null,
                option_qty: null,
                option_selections: [],
                extension_attributes: null,
              },
            ],
            downloadable_option: {
              downloadable_links: [null],
            },
            giftcard_item_option: {
              giftcard_amount: "string",
              custom_giftcard_amount: 0,
              giftcard_sender_name: "string",
              giftcard_recipient_name: "string",
              giftcard_sender_email: "string",
              giftcard_recipient_email: "string",
              giftcard_message: "string",
              extension_attributes: {
                giftcard_created_codes: [],
              },
            },
            configurable_item_options: [
              {
                option_id: null,
                option_value: null,
                extension_attributes: null,
              },
            ],
          },
        },
        extension_attributes: {
          gift_message: {
            gift_message_id: 0,
            customer_id: 0,
            sender: "string",
            recipient: "string",
            message: "string",
            extension_attributes: {
              entity_id: "string",
              entity_type: "string",
              wrapping_id: 0,
              wrapping_allow_gift_receipt: true,
              wrapping_add_printed_card: true,
            },
          },
          gw_id: "string",
          gw_base_price: "string",
          gw_price: "string",
          gw_base_tax_amount: "string",
          gw_tax_amount: "string",
          gw_base_price_invoiced: "string",
          gw_price_invoiced: "string",
          gw_base_tax_amount_invoiced: "string",
          gw_tax_amount_invoiced: "string",
          gw_base_price_refunded: "string",
          gw_price_refunded: "string",
          gw_base_tax_amount_refunded: "string",
          gw_tax_amount_refunded: "string",
        },
      },
    ],
    billing_address: {
      address_type: "string",
      city: "string",
      company: "string",
      country_id: "string",
      customer_address_id: 0,
      customer_id: 0,
      email: "string",
      entity_id: 0,
      fax: "string",
      firstname: "string",
      lastname: "string",
      middlename: "string",
      parent_id: 0,
      postcode: "string",
      prefix: "string",
      region: "string",
      region_code: "string",
      region_id: 0,
      street: ["string"],
      suffix: "string",
      telephone: "string",
      vat_id: "string",
      vat_is_valid: 0,
      vat_request_date: "string",
      vat_request_id: "string",
      vat_request_success: 0,
      extension_attributes: {},
    },
    payment: {
      account_status: "string",
      additional_data: "string",
      additional_information: ["string"],
      address_status: "string",
      amount_authorized: 0,
      amount_canceled: 0,
      amount_ordered: 0,
      amount_paid: 0,
      amount_refunded: 0,
      anet_trans_method: "string",
      base_amount_authorized: 0,
      base_amount_canceled: 0,
      base_amount_ordered: 0,
      base_amount_paid: 0,
      base_amount_paid_online: 0,
      base_amount_refunded: 0,
      base_amount_refunded_online: 0,
      base_shipping_amount: 0,
      base_shipping_captured: 0,
      base_shipping_refunded: 0,
      cc_approval: "string",
      cc_avs_status: "string",
      cc_cid_status: "string",
      cc_debug_request_body: "string",
      cc_debug_response_body: "string",
      cc_debug_response_serialized: "string",
      cc_exp_month: "string",
      cc_exp_year: "string",
      cc_last4: "string",
      cc_number_enc: "string",
      cc_owner: "string",
      cc_secure_verify: "string",
      cc_ss_issue: "string",
      cc_ss_start_month: "string",
      cc_ss_start_year: "string",
      cc_status: "string",
      cc_status_description: "string",
      cc_trans_id: "string",
      cc_type: "string",
      echeck_account_name: "string",
      echeck_account_type: "string",
      echeck_bank_name: "string",
      echeck_routing_number: "string",
      echeck_type: "string",
      entity_id: 0,
      last_trans_id: "string",
      method: "string",
      parent_id: 0,
      po_number: "string",
      protection_eligibility: "string",
      quote_payment_id: 0,
      shipping_amount: 0,
      shipping_captured: 0,
      shipping_refunded: 0,
      extension_attributes: {
        notification_message: "string",
        vault_payment_token: {
          entity_id: 0,
          customer_id: 0,
          public_hash: "string",
          payment_method_code: "string",
          type: "string",
          created_at: "string",
          expires_at: "string",
          gateway_token: "string",
          token_details: "string",
          is_active: true,
          is_visible: true,
        },
      },
    },
    status_histories: [
      {
        comment: "string",
        created_at: "string",
        entity_id: 0,
        entity_name: "string",
        is_customer_notified: 0,
        is_visible_on_front: 0,
        parent_id: 0,
        status: "string",
        extension_attributes: {},
      },
    ],
    extension_attributes: {
      shipping_assignments: [
        {
          shipping: {
            address: {
              address_type: "string",
              city: "string",
              company: "string",
              country_id: "string",
              customer_address_id: 0,
              customer_id: 0,
              email: "string",
              entity_id: 0,
              fax: "string",
              firstname: "string",
              lastname: "string",
              middlename: "string",
              parent_id: 0,
              postcode: "string",
              prefix: "string",
              region: "string",
              region_code: "string",
              region_id: 0,
              street: [null],
              suffix: "string",
              telephone: "string",
              vat_id: "string",
              vat_is_valid: 0,
              vat_request_date: "string",
              vat_request_id: "string",
              vat_request_success: 0,
              extension_attributes: {},
            },
            method: "string",
            total: {
              base_shipping_amount: 0,
              base_shipping_canceled: 0,
              base_shipping_discount_amount: 0,
              base_shipping_discount_tax_compensation_amnt: 0,
              base_shipping_incl_tax: 0,
              base_shipping_invoiced: 0,
              base_shipping_refunded: 0,
              base_shipping_tax_amount: 0,
              base_shipping_tax_refunded: 0,
              shipping_amount: 0,
              shipping_canceled: 0,
              shipping_discount_amount: 0,
              shipping_discount_tax_compensation_amount: 0,
              shipping_incl_tax: 0,
              shipping_invoiced: 0,
              shipping_refunded: 0,
              shipping_tax_amount: 0,
              shipping_tax_refunded: 0,
              extension_attributes: {},
            },
            extension_attributes: {},
          },
          items: [
            {
              additional_data: "string",
              amount_refunded: 0,
              applied_rule_ids: "string",
              base_amount_refunded: 0,
              base_cost: 0,
              base_discount_amount: 0,
              base_discount_invoiced: 0,
              base_discount_refunded: 0,
              base_discount_tax_compensation_amount: 0,
              base_discount_tax_compensation_invoiced: 0,
              base_discount_tax_compensation_refunded: 0,
              base_original_price: 0,
              base_price: 0,
              base_price_incl_tax: 0,
              base_row_invoiced: 0,
              base_row_total: 0,
              base_row_total_incl_tax: 0,
              base_tax_amount: 0,
              base_tax_before_discount: 0,
              base_tax_invoiced: 0,
              base_tax_refunded: 0,
              base_weee_tax_applied_amount: 0,
              base_weee_tax_applied_row_amnt: 0,
              base_weee_tax_disposition: 0,
              base_weee_tax_row_disposition: 0,
              created_at: "string",
              description: "string",
              discount_amount: 0,
              discount_invoiced: 0,
              discount_percent: 0,
              discount_refunded: 0,
              event_id: 0,
              ext_order_item_id: "string",
              free_shipping: 0,
              gw_base_price: 0,
              gw_base_price_invoiced: 0,
              gw_base_price_refunded: 0,
              gw_base_tax_amount: 0,
              gw_base_tax_amount_invoiced: 0,
              gw_base_tax_amount_refunded: 0,
              gw_id: 0,
              gw_price: 0,
              gw_price_invoiced: 0,
              gw_price_refunded: 0,
              gw_tax_amount: 0,
              gw_tax_amount_invoiced: 0,
              gw_tax_amount_refunded: 0,
              discount_tax_compensation_amount: 0,
              discount_tax_compensation_canceled: 0,
              discount_tax_compensation_invoiced: 0,
              discount_tax_compensation_refunded: 0,
              is_qty_decimal: 0,
              is_virtual: 0,
              item_id: 0,
              locked_do_invoice: 0,
              locked_do_ship: 0,
              name: "string",
              no_discount: 0,
              order_id: 0,
              original_price: 0,
              parent_item_id: 0,
              price: 0,
              price_incl_tax: 0,
              product_id: 0,
              product_type: "string",
              qty_backordered: 0,
              qty_canceled: 0,
              qty_invoiced: 0,
              qty_ordered: 0,
              qty_refunded: 0,
              qty_returned: 0,
              qty_shipped: 0,
              quote_item_id: 0,
              row_invoiced: 0,
              row_total: 0,
              row_total_incl_tax: 0,
              row_weight: 0,
              sku: "string",
              store_id: 0,
              tax_amount: 0,
              tax_before_discount: 0,
              tax_canceled: 0,
              tax_invoiced: 0,
              tax_percent: 0,
              tax_refunded: 0,
              updated_at: "string",
              weee_tax_applied: "string",
              weee_tax_applied_amount: 0,
              weee_tax_applied_row_amount: 0,
              weee_tax_disposition: 0,
              weee_tax_row_disposition: 0,
              weight: 0,
              parent_item: {},
              product_option: {
                extension_attributes: null,
              },
              extension_attributes: {
                gift_message: null,
                gw_id: null,
                gw_base_price: null,
                gw_price: null,
                gw_base_tax_amount: null,
                gw_tax_amount: null,
                gw_base_price_invoiced: null,
                gw_price_invoiced: null,
                gw_base_tax_amount_invoiced: null,
                gw_tax_amount_invoiced: null,
                gw_base_price_refunded: null,
                gw_price_refunded: null,
                gw_base_tax_amount_refunded: null,
                gw_tax_amount_refunded: null,
              },
            },
          ],
          stock_id: 0,
          extension_attributes: {},
        },
      ],
      payment_additional_info: [
        {
          key: "string",
          value: "string",
        },
      ],
      company_order_attributes: {
        order_id: 0,
        company_id: 0,
        company_name: "string",
        extension_attributes: {},
      },
      applied_taxes: [
        {
          code: "string",
          title: "string",
          percent: 0,
          amount: 0,
          base_amount: 0,
          extension_attributes: {
            rates: [
              {
                code: null,
                title: null,
                percent: null,
                extension_attributes: null,
              },
            ],
          },
        },
      ],
      item_applied_taxes: [
        {
          type: "string",
          item_id: 0,
          associated_item_id: 0,
          applied_taxes: [
            {
              code: "string",
              title: "string",
              percent: 0,
              amount: 0,
              base_amount: 0,
              extension_attributes: {
                rates: [],
              },
            },
          ],
          extension_attributes: {},
        },
      ],
      converting_from_quote: true,
      base_customer_balance_amount: 0,
      customer_balance_amount: 0,
      base_customer_balance_invoiced: 0,
      customer_balance_invoiced: 0,
      base_customer_balance_refunded: 0,
      customer_balance_refunded: 0,
      base_customer_balance_total_refunded: 0,
      customer_balance_total_refunded: 0,
      gift_cards: [
        {
          id: 0,
          code: "string",
          amount: 0,
          base_amount: 0,
        },
      ],
      base_gift_cards_amount: 0,
      gift_cards_amount: 0,
      base_gift_cards_invoiced: 0,
      gift_cards_invoiced: 0,
      base_gift_cards_refunded: 0,
      gift_cards_refunded: 0,
      gift_message: {
        gift_message_id: 0,
        customer_id: 0,
        sender: "string",
        recipient: "string",
        message: "string",
        extension_attributes: {
          entity_id: "string",
          entity_type: "string",
          wrapping_id: 0,
          wrapping_allow_gift_receipt: true,
          wrapping_add_printed_card: true,
        },
      },
      gw_id: "string",
      gw_allow_gift_receipt: "string",
      gw_add_card: "string",
      gw_base_price: "string",
      gw_price: "string",
      gw_items_base_price: "string",
      gw_items_price: "string",
      gw_card_base_price: "string",
      gw_card_price: "string",
      gw_base_tax_amount: "string",
      gw_tax_amount: "string",
      gw_items_base_tax_amount: "string",
      gw_items_tax_amount: "string",
      gw_card_base_tax_amount: "string",
      gw_card_tax_amount: "string",
      gw_base_price_incl_tax: "string",
      gw_price_incl_tax: "string",
      gw_items_base_price_incl_tax: "string",
      gw_items_price_incl_tax: "string",
      gw_card_base_price_incl_tax: "string",
      gw_card_price_incl_tax: "string",
      gw_base_price_invoiced: "string",
      gw_price_invoiced: "string",
      gw_items_base_price_invoiced: "string",
      gw_items_price_invoiced: "string",
      gw_card_base_price_invoiced: "string",
      gw_card_price_invoiced: "string",
      gw_base_tax_amount_invoiced: "string",
      gw_tax_amount_invoiced: "string",
      gw_items_base_tax_invoiced: "string",
      gw_items_tax_invoiced: "string",
      gw_card_base_tax_invoiced: "string",
      gw_card_tax_invoiced: "string",
      gw_base_price_refunded: "string",
      gw_price_refunded: "string",
      gw_items_base_price_refunded: "string",
      gw_items_price_refunded: "string",
      gw_card_base_price_refunded: "string",
      gw_card_price_refunded: "string",
      gw_base_tax_amount_refunded: "string",
      gw_tax_amount_refunded: "string",
      gw_items_base_tax_refunded: "string",
      gw_items_tax_refunded: "string",
      gw_card_base_tax_refunded: "string",
      gw_card_tax_refunded: "string",
      pickup_location_code: "string",
      notification_sent: 0,
      send_notification: 0,
      reward_points_balance: 0,
      reward_currency_amount: 0,
      base_reward_currency_amount: 0,
    },
  },
};

export const customerJson = {
  customer: {
    id: 0,
    group_id: 0,
    default_billing: "string",
    default_shipping: "string",
    confirmation: "string",
    created_at: "string",
    updated_at: "string",
    created_in: "string",
    dob: "string",
    email: "string",
    firstname: "string",
    lastname: "string",
    middlename: "string",
    prefix: "string",
    suffix: "string",
    gender: 0,
    store_id: 0,
    taxvat: "string",
    website_id: 0,
    addresses: [
      {
        id: 0,
        customer_id: 0,
        region: {
          region_code: "string",
          region: "string",
          region_id: 0,
          extension_attributes: {},
        },
        region_id: 0,
        country_id: "string",
        street: ["string"],
        company: "string",
        telephone: "string",
        fax: "string",
        postcode: "string",
        city: "string",
        firstname: "string",
        lastname: "string",
        middlename: "string",
        prefix: "string",
        suffix: "string",
        vat_id: "string",
        default_shipping: true,
        default_billing: true,
        extension_attributes: {},
        custom_attributes: [
          {
            attribute_code: "string",
            value: "string",
          },
        ],
      },
    ],
    disable_auto_group_change: 0,
    extension_attributes: {
      company_attributes: {
        customer_id: 0,
        company_id: 0,
        job_title: "string",
        status: 0,
        telephone: "string",
        extension_attributes: {},
      },
      assistance_allowed: 0,
      is_subscribed: true,
    },
    custom_attributes: [
      {
        attribute_code: "string",
        value: "string",
      },
    ],
  },
};
