import type { TriggerPayload } from "@prismatic-io/spectral";
import { toSortedElements } from "./utils/elements";
export const createProductsExamplePayload = {
  data: {
    id: 2079,
    sku: "MS-Champ-S",
    name: "Champ Tee Small",
    attribute_set_id: 9,
    price: 25,
    status: 1,
    visibility: 1,
    type_id: "simple",
    created_at: "2017-11-29 20:40:07",
    updated_at: "2017-11-29 20:40:07",
    weight: 0.5,
    extension_attributes: {
      website_ids: [1],
      category_links: [
        { position: 0, category_id: "11" },
        { position: 1, category_id: "12" },
        { position: 2, category_id: "16" },
      ],
      stock_item: {
        item_id: 2079,
        product_id: 2079,
        stock_id: 1,
        qty: 10,
        is_in_stock: true,
        is_qty_decimal: false,
        show_default_notification_message: false,
        use_config_min_qty: true,
        min_qty: 0,
        use_config_min_sale_qty: 1,
        min_sale_qty: 1,
        use_config_max_sale_qty: true,
        max_sale_qty: 10000,
        use_config_backorders: true,
        backorders: 0,
        use_config_notify_stock_qty: true,
        notify_stock_qty: 1,
        use_config_qty_increments: true,
        qty_increments: 0,
        use_config_enable_qty_inc: true,
        enable_qty_increments: false,
        use_config_manage_stock: true,
        manage_stock: true,
        low_stock_date: null,
        is_decimal_divided: false,
        stock_status_changed_auto: 0,
      },
    },
    product_links: [],
    options: [],
    media_gallery_entries: [],
    tier_prices: [],
    custom_attributes: [
      {
        attribute_code: "description",
        value:
          "The Champ Tee keeps you cool and dry while you do your thing. Let everyone know who you are by adding your name on the back for only $10.",
      },
      { attribute_code: "color", value: "52" },
      { attribute_code: "category_ids", value: ["11", "12", "16"] },
      { attribute_code: "options_container", value: "container2" },
      { attribute_code: "required_options", value: "0" },
      { attribute_code: "has_options", value: "0" },
      { attribute_code: "url_key", value: "champ-tee-small" },
      { attribute_code: "tax_class_id", value: "2" },
      { attribute_code: "material", value: "148" },
      { attribute_code: "size", value: "168" },
      { attribute_code: "pattern", value: "196" },
    ],
  },
};
export const listProductsExamplePayload = {
  data: {
    items: [
      {
        id: 2078,
        sku: "MS-Champ",
        name: "Champ Tee",
        attribute_set_id: 9,
        price: 0,
        status: 1,
        visibility: 4,
        type_id: "configurable",
        created_at: "2017-11-29 19:57:20",
        updated_at: "2017-11-29 19:57:20",
        weight: 0.5,
        extension_attributes: {
          website_ids: [1],
          category_links: [
            { position: 0, category_id: "11" },
            { position: 1, category_id: "12" },
            { position: 2, category_id: "16" },
          ],
          stock_item: {
            item_id: 2078,
            product_id: 2078,
            stock_id: 1,
            qty: 0,
            is_in_stock: false,
            is_qty_decimal: false,
            show_default_notification_message: false,
            use_config_min_qty: true,
            min_qty: 0,
            use_config_min_sale_qty: 1,
            min_sale_qty: 1,
            use_config_max_sale_qty: true,
            max_sale_qty: 10000,
            use_config_backorders: true,
            backorders: 0,
            use_config_notify_stock_qty: true,
            notify_stock_qty: 1,
            use_config_qty_increments: true,
            qty_increments: 0,
            use_config_enable_qty_inc: true,
            enable_qty_increments: false,
            use_config_manage_stock: true,
            manage_stock: true,
            low_stock_date: null,
            is_decimal_divided: false,
            stock_status_changed_auto: 0,
          },
          configurable_product_options: [
            {
              id: 338,
              attribute_id: "141",
              label: "Size",
              position: 0,
              values: [
                { value_index: 168 },
                { value_index: 169 },
                { value_index: 170 },
              ],
              product_id: 2078,
            },
          ],
          configurable_product_links: [2079, 2080, 2081],
        },
        product_links: [],
        options: [
          {
            product_sku: "MS-Champ",
            option_id: 7,
            title: "Add Your Name (Max 15 Characters)",
            type: "field",
            sort_order: 1,
            is_require: false,
            price: 10,
            price_type: "fixed",
            sku: "Personalized",
            max_characters: 15,
          },
        ],
        media_gallery_entries: [],
        tier_prices: [],
        custom_attributes: [
          {
            attribute_code: "description",
            value:
              "The Champ Tee keeps you cool and dry while you do your thing. Let everyone know who you are by adding your name on the back for only $10.",
          },
          { attribute_code: "color", value: "52" },
          { attribute_code: "category_ids", value: ["11", "12", "16"] },
          { attribute_code: "options_container", value: "container2" },
          { attribute_code: "required_options", value: "0" },
          { attribute_code: "has_options", value: "0" },
          { attribute_code: "url_key", value: "champ-tee" },
          { attribute_code: "tax_class_id", value: "2" },
          { attribute_code: "material", value: "148" },
          { attribute_code: "size", value: "91" },
          { attribute_code: "pattern", value: "196" },
        ],
      },
      createProductsExamplePayload.data,
      {
        id: 25,
        sku: "Desktop-Computer",
        name: "Desktop Computer",
        attribute_set_id: 4,
        price: 0,
        status: 1,
        visibility: 4,
        type_id: "bundle",
        created_at: "2022-04-15 18:04:04",
        updated_at: "2022-04-15 18:04:04",
        weight: 0,
        extension_attributes: {
          website_ids: [1],
          category_links: [{ position: 0, category_id: "32" }],
          stock_item: {
            item_id: 25,
            product_id: 25,
            stock_id: 1,
            qty: 0,
            is_in_stock: true,
            is_qty_decimal: false,
            show_default_notification_message: false,
            use_config_min_qty: true,
            min_qty: 0,
            use_config_min_sale_qty: 1,
            min_sale_qty: 1,
            use_config_max_sale_qty: true,
            max_sale_qty: 10000,
            use_config_backorders: true,
            backorders: 0,
            use_config_notify_stock_qty: true,
            notify_stock_qty: 1,
            use_config_qty_increments: true,
            qty_increments: 0,
            use_config_enable_qty_inc: true,
            enable_qty_increments: false,
            use_config_manage_stock: true,
            manage_stock: true,
            low_stock_date: null,
            is_decimal_divided: false,
            stock_status_changed_auto: 0,
          },
          bundle_product_options: [
            {
              option_id: 14,
              title: "RAM",
              required: true,
              type: "select",
              position: 1,
              sku: "Desktop-Computer",
              product_links: [
                {
                  id: "19",
                  sku: "RAM-12GB",
                  option_id: 14,
                  qty: 1,
                  position: 1,
                  is_default: false,
                  price: 25,
                  price_type: null,
                  can_change_quantity: 0,
                },
                {
                  id: "20",
                  sku: "RAM-24GB",
                  option_id: 14,
                  qty: 1,
                  position: 2,
                  is_default: false,
                  price: 50,
                  price_type: null,
                  can_change_quantity: 0,
                },
              ],
            },
            {
              option_id: 15,
              title: "Monitor",
              required: true,
              type: "select",
              position: 2,
              sku: "Desktop-Computer",
              product_links: [
                {
                  id: "21",
                  sku: "Monitor-15",
                  option_id: 15,
                  qty: 1,
                  position: 1,
                  is_default: false,
                  price: 100,
                  price_type: null,
                  can_change_quantity: 0,
                },
                {
                  id: "22",
                  sku: "Monitor-17",
                  option_id: 15,
                  qty: 1,
                  position: 2,
                  is_default: false,
                  price: 150,
                  price_type: null,
                  can_change_quantity: 0,
                },
              ],
            },
          ],
        },
        options: [],
        media_gallery_entries: [],
        custom_attributes: [
          { attribute_code: "shipment_type", value: "0" },
          { attribute_code: "options_container", value: "container2" },
          { attribute_code: "msrp_display_actual_price_type", value: "0" },
          { attribute_code: "url_key", value: "desktop-computer" },
          { attribute_code: "price_view", value: "0" },
          { attribute_code: "required_options", value: "0" },
          { attribute_code: "has_options", value: "0" },
          { attribute_code: "sku_type", value: "0" },
          { attribute_code: "price_type", value: "0" },
          { attribute_code: "tax_class_id", value: "2" },
          { attribute_code: "weight_type", value: "0" },
          { attribute_code: "category_ids", value: ["32"] },
        ],
      },
    ],
    search_criteria: {
      filter_groups: [
        {
          filters: [
            { field: "sku", value: "MS-Champ%", condition_type: "like" },
          ],
        },
      ],
      sort_orders: [{ field: "entity_id", direction: "ASC" }],
      page_size: 20,
      current_page: 1,
    },
    total_count: 3,
  },
};
export const listProductAttributesExamplePayload = {
  data: {
    items: [
      {
        extension_attributes: {
          is_pagebuilder_enabled: false,
        },
        is_wysiwyg_enabled: false,
        is_html_allowed_on_front: false,
        used_for_sort_by: false,
        is_filterable: true,
        is_filterable_in_search: true,
        is_used_in_grid: true,
        is_visible_in_grid: false,
        is_filterable_in_grid: true,
        position: 0,
        apply_to: ["simple", "virtual", "configurable"],
        is_searchable: "0",
        is_visible_in_advanced_search: "0",
        is_comparable: "0",
        is_used_for_promo_rules: "0",
        is_visible_on_front: "0",
        used_in_product_listing: "0",
        is_visible: true,
        scope: "global",
        attribute_id: 141,
        attribute_code: "size",
        frontend_input: "select",
        entity_type_id: "4",
        is_required: false,
        options: [
          { label: " ", value: "" },
          { label: "Small", value: "168" },
          { label: "Medium", value: "169" },
          { label: "Large", value: "170" },
        ],
        is_user_defined: true,
        default_frontend_label: "Size",
        frontend_labels: [],
        note: "",
        backend_type: "int",
        backend_model: null,
        source_model: "Magento\\Eav\\Model\\Entity\\Attribute\\Source\\Table",
        default_value: "",
        is_unique: "0",
        frontend_class: null,
        validation_rules: [],
      },
    ],
    search_criteria: {
      filter_groups: [
        {
          filters: [
            { field: "attribute_code", value: "size", condition_type: "eq" },
          ],
        },
      ],
      sort_orders: [{ field: "attribute_id", direction: "ASC" }],
      page_size: 20,
      current_page: 1,
    },
    total_count: 1,
  },
};
export const createProductAttributesExamplePayload = {
  data: listProductAttributesExamplePayload.data.items[0],
};
export const createProductOptionsExamplePayload = {
  data: {
    product_sku: "MS-Champ",
    option_id: 7,
    title: "Add Your Name (Max 15 Characters)",
    type: "field",
    sort_order: 1,
    is_require: false,
    price: 10,
    price_type: "fixed",
    sku: "Personalized",
    max_characters: 15,
  },
};
export const listProductOptionTypesExamplePayload = {
  data: [
    { label: "Field", code: "field", group: "Text", extension_attributes: {} },
    { label: "Area", code: "area", group: "Text", extension_attributes: {} },
    { label: "File", code: "file", group: "File", extension_attributes: {} },
    {
      label: "Drop-down",
      code: "drop_down",
      group: "Select",
      extension_attributes: {},
    },
    {
      label: "Radio Buttons",
      code: "radio",
      group: "Select",
      extension_attributes: {},
    },
    {
      label: "Checkbox",
      code: "checkbox",
      group: "Select",
      extension_attributes: {},
    },
    {
      label: "Multiple Select",
      code: "multiple",
      group: "Select",
      extension_attributes: {},
    },
    { label: "Date", code: "date", group: "Date", extension_attributes: {} },
    {
      label: "Date & Time",
      code: "date_time",
      group: "Date",
      extension_attributes: {},
    },
    { label: "Time", code: "time", group: "Date", extension_attributes: {} },
  ],
};
export const listProductTypesExamplePayload = {
  data: [
    { name: "simple", label: "Simple Product", extension_attributes: {} },
    { name: "virtual", label: "Virtual Product", extension_attributes: {} },
    {
      name: "configurable",
      label: "Configurable Product",
      extension_attributes: {},
    },
    { name: "grouped", label: "Grouped Product", extension_attributes: {} },
    { name: "bundle", label: "Bundle Product", extension_attributes: {} },
    {
      name: "downloadable",
      label: "Downloadable Product",
      extension_attributes: {},
    },
  ],
};
export const getOrderExamplePayload = {
  data: {
    applied_rule_ids: "1",
    base_currency_code: "USD",
    base_discount_amount: 0,
    base_grand_total: 165,
    base_discount_tax_compensation_amount: 0,
    base_shipping_amount: 5,
    base_shipping_discount_amount: 0,
    base_shipping_incl_tax: 5,
    base_shipping_tax_amount: 0,
    base_subtotal: 160,
    base_subtotal_incl_tax: 160,
    base_tax_amount: 0,
    base_total_due: 165,
    base_to_global_rate: 1,
    base_to_order_rate: 1,
    billing_address_id: 6,
    created_at: "2017-08-21 22:22:19",
    customer_email: "jdoe@example.com",
    customer_firstname: "Jane",
    customer_group_id: 1,
    customer_id: 3,
    customer_is_guest: 0,
    customer_lastname: "Doe",
    customer_note_notify: 1,
    discount_amount: 0,
    email_sent: 1,
    entity_id: 3,
    global_currency_code: "USD",
    grand_total: 165,
    discount_tax_compensation_amount: 0,
    increment_id: "000000003",
    is_virtual: 0,
    order_currency_code: "USD",
    protect_code: "61f76d",
    quote_id: 4,
    shipping_amount: 5,
    shipping_description: "Best Way - Table Rate",
    shipping_discount_amount: 0,
    shipping_discount_tax_compensation_amount: 0,
    shipping_incl_tax: 5,
    shipping_tax_amount: 0,
    state: "new",
    status: "pending",
    store_currency_code: "USD",
    store_id: 1,
    store_name: "Main Website\nMain Website Store\n",
    store_to_base_rate: 0,
    store_to_order_rate: 0,
    subtotal: 160,
    subtotal_incl_tax: 160,
    tax_amount: 0,
    total_due: 165,
    total_item_count: 7,
    total_qty_ordered: 4,
    updated_at: "2017-08-21 22:22:20",
    weight: 2,
    items: [
      {
        amount_refunded: 0,
        applied_rule_ids: "1",
        base_amount_refunded: 0,
        base_discount_amount: 0,
        base_discount_invoiced: 0,
        base_discount_tax_compensation_amount: 0,
        base_original_price: 22,
        base_price: 22,
        base_price_incl_tax: 22,
        base_row_invoiced: 0,
        base_row_total: 22,
        base_row_total_incl_tax: 22,
        base_tax_amount: 0,
        base_tax_invoiced: 0,
        created_at: "2017-08-21 22:22:19",
        discount_amount: 0,
        discount_invoiced: 0,
        discount_percent: 0,
        free_shipping: 0,
        discount_tax_compensation_amount: 0,
        is_qty_decimal: 0,
        is_virtual: 0,
        item_id: 3,
        name: "Radiant Tee-M-Orange",
        no_discount: 0,
        order_id: 3,
        original_price: 22,
        price: 22,
        price_incl_tax: 22,
        product_id: 1553,
        product_type: "simple",
        qty_canceled: 0,
        qty_invoiced: 0,
        qty_ordered: 1,
        qty_refunded: 0,
        qty_shipped: 0,
        quote_item_id: 6,
        row_invoiced: 0,
        row_total: 22,
        row_total_incl_tax: 22,
        row_weight: 1,
        sku: "WS12-M-Orange",
        store_id: 1,
        tax_amount: 0,
        tax_invoiced: 0,
        tax_percent: 0,
        updated_at: "2017-08-21 22:22:19",
        weight: 1,
      },
    ],
    billing_address: {
      address_type: "billing",
      city: "Purchase",
      country_id: "US",
      email: "jdoe@example.com",
      entity_id: 6,
      firstname: "Jane",
      lastname: "Doe",
      parent_id: 3,
      postcode: "10577",
      region: "New York",
      region_code: "NY",
      region_id: 43,
      street: ["123 Oak Ave"],
      telephone: "512-555-1111",
    },
    payment: {
      account_status: null,
      additional_information: ["Bank Transfer Payment", ""],
      amount_ordered: 165,
      base_amount_ordered: 165,
      base_shipping_amount: 5,
      cc_last4: null,
      entity_id: 3,
      method: "banktransfer",
      parent_id: 3,
      shipping_amount: 5,
    },
    status_histories: [],
    extension_attributes: {
      shipping_assignments: [
        {
          shipping: {
            address: {
              address_type: "shipping",
              city: "Purchase",
              country_id: "US",
              email: "jdoe@example.com",
              entity_id: 5,
              firstname: "Jane",
              lastname: "Doe",
              parent_id: 3,
              postcode: "10577",
              region: "New York",
              region_code: "NY",
              region_id: 43,
              street: ["123 Oak Ave"],
              telephone: "512-555-1111",
            },
            method: "tablerate_bestway",
            total: {
              base_shipping_amount: 5,
              base_shipping_discount_amount: 0,
              base_shipping_incl_tax: 5,
              base_shipping_tax_amount: 0,
              shipping_amount: 5,
              shipping_discount_amount: 0,
              shipping_discount_tax_compensation_amount: 0,
              shipping_incl_tax: 5,
              shipping_tax_amount: 0,
            },
          },
          items: [
            {
              amount_refunded: 0,
              applied_rule_ids: "1",
              base_amount_refunded: 0,
              base_discount_amount: 0,
              base_discount_invoiced: 0,
              base_discount_tax_compensation_amount: 0,
              base_original_price: 22,
              base_price: 22,
              base_price_incl_tax: 22,
              base_row_invoiced: 0,
              base_row_total: 22,
              base_row_total_incl_tax: 22,
              base_tax_amount: 0,
              base_tax_invoiced: 0,
              created_at: "2017-08-21 22:22:19",
              discount_amount: 0,
              discount_invoiced: 0,
              discount_percent: 0,
              free_shipping: 0,
              discount_tax_compensation_amount: 0,
              is_qty_decimal: 0,
              is_virtual: 0,
              item_id: 3,
              name: "Radiant Tee-M-Orange",
              no_discount: 0,
              order_id: 3,
              original_price: 22,
              price: 22,
              price_incl_tax: 22,
              product_id: 1553,
              product_type: "simple",
              qty_canceled: 0,
              qty_invoiced: 0,
              qty_ordered: 1,
              qty_refunded: 0,
              qty_shipped: 0,
              quote_item_id: 6,
              row_invoiced: 0,
              row_total: 22,
              row_total_incl_tax: 22,
              row_weight: 1,
              sku: "WS12-M-Orange",
              store_id: 1,
              tax_amount: 0,
              tax_invoiced: 0,
              tax_percent: 0,
              updated_at: "2017-08-21 22:22:19",
              weight: 1,
            },
          ],
        },
      ],
    },
  },
};
export const createOrderExamplePayload = getOrderExamplePayload;
export const listOrdersExamplePayload = {
  data: {
    items: [getOrderExamplePayload.data],
    search_criteria: {
      filter_groups: [
        {
          filters: [
            { field: "status", value: "pending", condition_type: "eq" },
          ],
        },
      ],
      sort_orders: [{ field: "increment_id", direction: "ASC" }],
      page_size: 20,
      current_page: 1,
    },
    total_count: 1,
  },
};
export const listOrderItemsExamplePayload = {
  data: {
    items: [getOrderExamplePayload.data.items[0]],
    search_criteria: {
      filter_groups: [
        {
          filters: [{ field: "order_id", value: "3", condition_type: "eq" }],
        },
      ],
      sort_orders: [{ field: "item_id", direction: "ASC" }],
      page_size: 20,
      current_page: 1,
    },
    total_count: 1,
  },
};
export const cancelOrderExamplePayload = {
  data: true,
};
export const createCustomerExamplePayload = {
  data: {
    id: 2,
    group_id: 1,
    default_billing: "2",
    default_shipping: "2",
    created_at: "2017-01-31 01:18:13",
    updated_at: "2017-01-31 01:18:13",
    created_in: "Default Store View",
    email: "jdoe@example.com",
    firstname: "Jane",
    lastname: "Doe",
    store_id: 1,
    website_id: 1,
    addresses: [
      {
        id: 2,
        customer_id: 2,
        region: {
          region_code: "NY",
          region: "New York",
          region_id: 43,
        },
        region_id: 43,
        country_id: "US",
        street: ["123 Oak Ave"],
        telephone: "512-555-1111",
        postcode: "10755",
        city: "Purchase",
        firstname: "Jane",
        lastname: "Doe",
        default_shipping: true,
        default_billing: true,
      },
    ],
    disable_auto_group_change: 0,
  },
};
export const getCustomerExamplePayload = createCustomerExamplePayload;
export const updateCustomerExamplePayload = {
  data: {
    ...createCustomerExamplePayload.data,
    updated_at: "2017-02-14 09:41:52",
  },
};
export const deleteCustomerExamplePayload = {
  data: true,
};
export const searchCustomersExamplePayload = {
  data: {
    items: [createCustomerExamplePayload.data],
    search_criteria: {
      filter_groups: [
        {
          filters: [
            { field: "email", value: "jdoe@example.com", condition_type: "eq" },
          ],
        },
      ],
      sort_orders: [{ field: "created_at", direction: "DESC" }],
      page_size: 20,
      current_page: 1,
    },
    total_count: 1,
  },
};
export const getTransactionExamplePayload = {
  data: {
    transaction_id: 12,
    parent_id: 11,
    order_id: 3,
    payment_id: 3,
    txn_id: "ch_3PqK8sLkd2FbXyZa1B9Qw7Rt-capture",
    parent_txn_id: "ch_3PqK8sLkd2FbXyZa1B9Qw7Rt",
    txn_type: "capture",
    is_closed: 1,
    additional_information: [],
    created_at: "2017-08-21 22:24:05",
    child_transactions: [],
    extension_attributes: {},
  },
};
export const listTransactionsExamplePayload = {
  data: {
    items: [
      {
        transaction_id: 11,
        parent_id: null,
        order_id: 3,
        payment_id: 3,
        txn_id: "ch_3PqK8sLkd2FbXyZa1B9Qw7Rt",
        parent_txn_id: null,
        txn_type: "authorization",
        is_closed: 1,
        additional_information: [],
        created_at: "2017-08-21 22:22:20",
        child_transactions: [getTransactionExamplePayload.data],
        extension_attributes: {},
      },
    ],
    search_criteria: {
      filter_groups: [
        {
          filters: [{ field: "order_id", value: "3", condition_type: "eq" }],
        },
      ],
      sort_orders: [{ field: "created_at", direction: "DESC" }],
      page_size: 20,
      current_page: 1,
    },
    total_count: 1,
  },
};
export const pollChangesExamplePayload: {
  payload: TriggerPayload;
} = {
  payload: {
    headers: {},
    queryParameters: {},
    rawBody: { data: null },
    body: {
      data: {
        created: [
          {
            entity_id: 1042,
            increment_id: "000000142",
            status: "pending",
            state: "new",
            customer_email: "jane.doe@example.com",
            customer_firstname: "Jane",
            customer_lastname: "Doe",
            grand_total: 199.5,
            base_grand_total: 199.5,
            order_currency_code: "USD",
            created_at: "2026-05-26 14:30:00",
            updated_at: "2026-05-26 14:30:00",
          },
        ],
        updated: [
          {
            entity_id: 980,
            increment_id: "000000087",
            status: "complete",
            state: "complete",
            customer_email: "john.smith@example.com",
            customer_firstname: "John",
            customer_lastname: "Smith",
            grand_total: 75.25,
            base_grand_total: 75.25,
            order_currency_code: "USD",
            created_at: "2026-04-12 09:00:00",
            updated_at: "2026-05-26 15:45:00",
          },
        ],
      },
    },
    pathFragment: "",
    webhookUrls: {},
    webhookApiKeys: {},
    invokeUrl: "",
    executionId: "RXhhbXBsZUV4ZWN1dGlvblJlc3VsdElk",
    customer: {
      id: "testCustomerId",
      name: "Test Customer",
      externalId: "testExternalId",
    },
    instance: { id: "testInstanceId", name: "Test Instance" },
    user: {
      id: "testUserId",
      email: "user@example.com",
      name: "Test User",
      externalId: "testUserExternalId",
    },
    integration: {
      id: "testIntegrationId",
      name: "Test Integration",
      versionSequenceId: "1",
      externalVersion: "",
    },
    flow: { id: "testFlowId", name: "Test Flow", stableId: "testFlowStableId" },
    startedAt: "2024-01-15T00:00:00.000Z",
    globalDebug: false,
  },
};
export const selectCustomerExamplePayload = {
  result: [
    {
      label: "John Doe (john@example.com)",
      key: "1",
    },
  ],
};
export const selectOrderExamplePayload = {
  result: [
    {
      label: "#000000001 - pending ($49.99)",
      key: "1",
    },
  ],
};
export const selectTransactionExamplePayload = {
  result: [
    {
      label: "txn-abc123 (capture - Order #1)",
      key: "1",
    },
  ],
};
export const productTypesExamplePayload = {
  result: toSortedElements(
    listProductTypesExamplePayload.data,
    ({ name, label }) => ({
      label,
      key: name,
    }),
  ),
};
export const productOptionTypesExamplePayload = {
  result: toSortedElements(
    listProductOptionTypesExamplePayload.data,
    ({ code, label }) => ({
      label,
      key: code,
    }),
  ),
};
export const productAttributeTypesExamplePayload = {
  result: [
    { label: "Date", key: "date" },
    { label: "Dropdown", key: "select" },
    { label: "Media Image", key: "media_image" },
    { label: "Multiple Select", key: "multiselect" },
    { label: "Price", key: "price" },
    { label: "Text Area", key: "textarea" },
    { label: "Text Editor", key: "texteditor" },
    { label: "Text Field", key: "text" },
    { label: "Yes/No", key: "boolean" },
  ],
};
