#import "../../fragments/OrderDetails.gql"
mutation CloseOrder($input: OrderCloseInput!) {
  orderClose(input: $input) {
    order {
      ...OrderDetails
    }
    userErrors {
      field
      message
    }
  }
}
