#import "../../fragments/OrderDetails.gql"
mutation CreateOrder($order: OrderCreateOrderInput!, $options: OrderCreateOptionsInput) {
  orderCreate(order: $order, options: $options) {
    order {
      ...OrderDetails
    }
    userErrors {
      field
      message
    }
  }
}
