import { action } from "@prismatic-io/spectral";
import { createClient } from "../../client";
import {
  connection,
  cost,
  description,
  durationBillingId,
  id,
  installedOn,
  inventoryLocationId,
  inventoryWarehouseName,
  invoiceId,
  isAddOn,
  itemGroupName,
  itemGroupRootId,
  quantity,
  signature,
  skipUpdatingMembershipPrices,
  skuId,
  skuName,
  technicianAcknowledgementSignature,
  technicianId,
  unitPrice,
} from "../../inputs";

export const updateInvoiceItems = action({
  display: {
    label: "Update Invoice Items",
    description: "Update invoice items",
  },
  inputs: {
    connection,
    invoiceId,
    description,
    quantity,
    skuId,
    skuName,
    technicianId,
    unitPrice,
    cost,
    isAddOn,
    signature,
    technicianAcknowledgementSignature,
    installedOn,
    inventoryWarehouseName,
    skipUpdatingMembershipPrices,
    itemGroupName,
    itemGroupRootId,
    inventoryLocationId,
    durationBillingId,
    id,
  },
  perform: async (
    context,
    {
      connection,
      invoiceId,
      description,
      quantity,
      skuId,
      skuName,
      technicianId,
      unitPrice,
      cost,
      isAddOn,
      signature,
      technicianAcknowledgementSignature,
      installedOn,
      inventoryWarehouseName,
      skipUpdatingMembershipPrices,
      itemGroupName,
      itemGroupRootId,
      inventoryLocationId,
      durationBillingId,
      id,
    },
  ) => {
    const client = createClient(
      connection,
      "accounting",
      context.debug.enabled,
    );
    const { data } = await client.patch(`/invoices/${invoiceId}/items`, {
      invoiceId,
      description,
      quantity,
      skuId,
      skuName,
      technicianId,
      unitPrice,
      cost,
      isAddOn,
      signature,
      technicianAcknowledgementSignature,
      installedOn,
      inventoryWarehouseName,
      skipUpdatingMembershipPrices,
      itemGroupName,
      itemGroupRootId,
      inventoryLocationId,
      durationBillingId,
      id,
    });
    return {
      data,
    };
  },
  examplePayload: {
    data: {},
  },
});
