import { action, util } from "@prismatic-io/spectral";
import {
  connection,
  activeInput,
  addressLine1Input,
  addressLine2Input,
  cellularPhoneNoInput,
  cityInput,
  companyNameInput,
  contactNameInput,
  contactTaxGroupNameInput,
  countryInput,
  faxNoInput,
  firstNameInput,
  lastNameInput,
  middleNameInput,
  pagerNoInput,
  prefixInput,
  primaryEmailAddressInput,
  primaryPhoneNoInput,
  primaryUrlInput,
  printAsInput,
  secondaryEmailAddressInput,
  secondaryPhoneNoInput,
  secondaryUrlInput,
  stateProvinceInput,
  taxIdInput,
  taxableInput,
  zipPostalCodeInput,
} from "../inputs";
import {
  assignParametersToObject,
  convertResultToGenericObject,
  executeAction,
} from "../utils";
import { Functions } from "@intacct/intacct-sdk";
import type { AbstractContact } from "@intacct/intacct-sdk/dist/Functions/Company";
import { createContactPayload } from "../examplePayloads/createContactPayload";

export const createContact = action({
  display: {
    label: "Create Contact",
    description: "Creates a new contact.",
  },
  perform: async (
    context,
    {
      connection,
      activeInput,
      addressLine1Input,
      addressLine2Input,
      cellularPhoneNoInput,
      cityInput,
      companyNameInput,
      contactNameInput,
      contactTaxGroupNameInput,
      countryInput,
      faxNoInput,
      firstNameInput,
      lastNameInput,
      middleNameInput,
      pagerNoInput,
      prefixInput,
      primaryEmailAddressInput,
      primaryPhoneNoInput,
      primaryUrlInput,
      printAsInput,
      secondaryEmailAddressInput,
      secondaryPhoneNoInput,
      secondaryUrlInput,
      stateProvinceInput,
      taxIdInput,
      taxableInput,
      zipPostalCodeInput,
    },
  ) => {
    const createContact = new Functions.Company.ContactCreate();
    assignParametersToObject(createContact, {
      contactName: contactNameInput,
      printAs: printAsInput,
      active: activeInput === "" ? undefined : util.types.toBool(activeInput),
      addressLine1: addressLine1Input,
      addressLine2: addressLine2Input,
      cellularPhoneNo: cellularPhoneNoInput,
      city: cityInput,
      companyName: companyNameInput,
      contactTaxGroupName: contactTaxGroupNameInput,
      country: countryInput,
      faxNo: faxNoInput,
      firstName: firstNameInput,
      lastName: lastNameInput,
      middleName: middleNameInput,
      pagerNo: pagerNoInput,
      prefix: prefixInput,
      primaryEmailAddress: primaryEmailAddressInput,
      primaryPhoneNo: primaryPhoneNoInput,
      primaryUrl: primaryUrlInput,
      secondaryEmailAddress: secondaryEmailAddressInput,
      secondaryPhoneNo: secondaryPhoneNoInput,
      secondaryUrl: secondaryUrlInput,
      stateProvince: stateProvinceInput,
      taxId: taxIdInput,
      taxable:
        taxableInput === "" ? undefined : util.types.toBool(taxableInput),
      zipPostalCode: zipPostalCodeInput,
    } as unknown as AbstractContact);

    if (context.debug.enabled) {
      context.logger.debug(JSON.stringify(createContact, null, 2));
    }
    const data = await executeAction(connection, createContact);
    return {
      data: convertResultToGenericObject(data),
    };
  },
  inputs: {
    connection,
    contactNameInput: {
      ...contactNameInput,
      comments: "Contact name to create",
    },
    printAsInput: { ...printAsInput, required: true },
    activeInput,
    addressLine1Input,
    addressLine2Input,
    cellularPhoneNoInput,
    cityInput,
    companyNameInput,
    contactTaxGroupNameInput,
    countryInput,
    faxNoInput,
    firstNameInput,
    lastNameInput,
    middleNameInput,
    pagerNoInput,
    prefixInput,
    primaryEmailAddressInput,
    primaryPhoneNoInput,
    primaryUrlInput,
    secondaryEmailAddressInput,
    secondaryPhoneNoInput,
    secondaryUrlInput,
    stateProvinceInput,
    taxIdInput,
    taxableInput,
    zipPostalCodeInput,
  },
  examplePayload: createContactPayload,
});
