import { action, util } from "@prismatic-io/spectral";
import {
  connection,
  customerIdInput,
  customerNameInput,
  oneTimeCustomerInput as oneTimeInput,
  activeInput,
  lastNameInput,
  firstNameInput,
  middleNameInput,
  prefixInput,
  companyNameInput,
  printAsInput,
  primaryPhoneNoInput,
  secondaryPhoneNoInput,
  cellularPhoneNoInput,
  pagerNoInput,
  faxNoInput,
  primaryEmailAddressInput,
  secondaryEmailAddressInput,
  primaryUrlInput,
  secondaryUrlInput,
  addressLine1Input,
  addressLine2Input,
  cityInput,
  stateProvinceInput,
  zipPostalCodeInput,
  countryInput,
  isoCountryCodeInput,
  excludedFromContactListInput,
  customerTypeIdInput,
  salesRepEmployeeIdInput,
  parentCustomerIdInput,
  glGroupNameInput,
  territoryIdInput,
  attachmentsIdInput,
  paymentTermInput,
  offsetArGlAccountNoInput,
  defaultRevenueGlAccountNoInput,
  shippingMethodInput,
  resaleNumberInput,
  taxableInput,
  contactTaxGroupNameInput,
  taxIdInput,
  creditLimitInput,
  onHoldInput,
  deliveryMethodInput,
  defaultInvoiceMessageInput,
  commentsInput,
  defaultCurrencyInput,
  printOptionArInvoiceTemplateNameInput,
  printOptionOeQuoteTemplateNameInput,
  printOptionOeOrderTemplateNameInput,
  printOptionOeListTemplateNameInput,
  printOptionOeInvoiceTemplateNameInput,
  printOptionOeAdjustmentTemplateNameInput,
  printOptionOeOtherTemplateNameInput,
  primaryContactNameInput,
  billToContactNameInput,
  shipToContactNameInput,
  restrictionTypeInput,
  restrictedLocationsInput,
  restrictedDepartmentsInput,
  customFieldsInput,
} from "../inputs";
import {
  assignParametersToObject,
  convertResultToGenericObject,
  executeAction,
} from "../utils";
import { Functions } from "@intacct/intacct-sdk";
import type { AbstractCustomer } from "@intacct/intacct-sdk/dist/Functions/AccountsReceivable";
import { createCustomerPayload } from "../examplePayloads/createCustomerPayload";

export const createCustomer = action({
  display: {
    label: "Create Customer",
    description:
      "Creates a customer and specifies a display contact and a contact list (provided via customer contacts).",
  },
  perform: async (
    context,
    {
      connection,
      customerIdInput,
      customerNameInput,
      oneTimeInput,
      activeInput,
      lastNameInput,
      firstNameInput,
      middleNameInput,
      prefixInput,
      companyNameInput,
      printAsInput,
      primaryPhoneNoInput,
      secondaryPhoneNoInput,
      cellularPhoneNoInput,
      pagerNoInput,
      faxNoInput,
      primaryEmailAddressInput,
      secondaryEmailAddressInput,
      primaryUrlInput,
      secondaryUrlInput,
      addressLine1Input,
      addressLine2Input,
      cityInput,
      stateProvinceInput,
      zipPostalCodeInput,
      countryInput,
      isoCountryCodeInput,
      excludedFromContactListInput,
      customerTypeIdInput,
      salesRepEmployeeIdInput,
      parentCustomerIdInput,
      glGroupNameInput,
      territoryIdInput,
      attachmentsIdInput,
      paymentTermInput,
      offsetArGlAccountNoInput,
      defaultRevenueGlAccountNoInput,
      shippingMethodInput,
      resaleNumberInput,
      taxableInput,
      contactTaxGroupNameInput,
      taxIdInput,
      creditLimitInput,
      onHoldInput,
      deliveryMethodInput,
      defaultInvoiceMessageInput,
      commentsInput,
      defaultCurrencyInput,
      printOptionArInvoiceTemplateNameInput,
      printOptionOeQuoteTemplateNameInput,
      printOptionOeOrderTemplateNameInput,
      printOptionOeListTemplateNameInput,
      printOptionOeInvoiceTemplateNameInput,
      printOptionOeAdjustmentTemplateNameInput,
      printOptionOeOtherTemplateNameInput,
      primaryContactNameInput,
      billToContactNameInput,
      shipToContactNameInput,
      restrictionTypeInput,
      restrictedLocationsInput,
      restrictedDepartmentsInput,
      customFieldsInput,
    },
  ) => {
    const createCustomer = new Functions.AccountsReceivable.CustomerCreate();
    assignParametersToObject(createCustomer, {
      customerId: customerIdInput,
      customerName: customerNameInput,
      oneTime:
        oneTimeInput === "" ? undefined : util.types.toBool(oneTimeInput),
      active: activeInput === "" ? undefined : util.types.toBool(activeInput),
      lastName: lastNameInput,
      firstName: firstNameInput,
      middleName: middleNameInput,
      prefix: prefixInput,
      companyName: companyNameInput,
      printAs: printAsInput,
      primaryPhoneNo: primaryPhoneNoInput,
      secondaryPhoneNo: secondaryPhoneNoInput,
      cellularPhoneNo: cellularPhoneNoInput,
      pagerNo: pagerNoInput,
      faxNo: faxNoInput,
      primaryEmailAddress: primaryEmailAddressInput,
      secondaryEmailAddress: secondaryEmailAddressInput,
      primaryUrl: primaryUrlInput,
      secondaryUrl: secondaryUrlInput,
      addressLine1: addressLine1Input,
      addressLine2: addressLine2Input,
      city: cityInput,
      stateProvince: stateProvinceInput,
      zipPostalCode: zipPostalCodeInput,
      country: countryInput,
      isoCountryCode: isoCountryCodeInput,
      excludedFromContactList:
        excludedFromContactListInput === ""
          ? undefined
          : util.types.toBool(excludedFromContactListInput),
      customerTypeId: customerTypeIdInput,
      salesRepEmployeeId: salesRepEmployeeIdInput,
      parentCustomerId: parentCustomerIdInput,
      glGroupName: glGroupNameInput,
      territoryId: territoryIdInput,
      attachmentsId: attachmentsIdInput,
      paymentTerm: paymentTermInput,
      offsetArGlAccountNo: offsetArGlAccountNoInput,
      defaultRevenueGlAccountNo: defaultRevenueGlAccountNoInput,
      shippingMethod: shippingMethodInput,
      resaleNumber: resaleNumberInput,
      taxable:
        taxableInput === "" ? undefined : util.types.toBool(taxableInput),
      contactTaxGroupName: contactTaxGroupNameInput,
      taxId: taxIdInput,
      creditLimit: creditLimitInput,
      onHold: onHoldInput === "" ? undefined : util.types.toBool(onHoldInput),
      deliveryMethod: deliveryMethodInput,
      defaultInvoiceMessage: defaultInvoiceMessageInput,
      comments: commentsInput,
      defaultCurrency: defaultCurrencyInput,
      printOptionArInvoiceTemplateName: printOptionArInvoiceTemplateNameInput,
      printOptionOeQuoteTemplateName: printOptionOeQuoteTemplateNameInput,
      printOptionOeOrderTemplateName: printOptionOeOrderTemplateNameInput,
      printOptionOeListTemplateName: printOptionOeListTemplateNameInput,
      printOptionOeInvoiceTemplateName: printOptionOeInvoiceTemplateNameInput,
      printOptionOeAdjustmentTemplateName:
        printOptionOeAdjustmentTemplateNameInput,
      printOptionOeOtherTemplateName: printOptionOeOtherTemplateNameInput,
      primaryContactName: primaryContactNameInput,
      billToContactName: billToContactNameInput,
      shipToContactName: shipToContactNameInput,
      restrictionType: restrictionTypeInput,
      restrictedLocations: restrictedLocationsInput,
      restrictedDepartments: restrictedDepartmentsInput,
      customFields: customFieldsInput,
    } as unknown as AbstractCustomer);

    if (context.debug.enabled) {
      context.logger.debug(JSON.stringify(createCustomer, null, 2));
    }
    const data = await executeAction(connection, createCustomer);
    return {
      data: convertResultToGenericObject(data),
    };
  },
  inputs: {
    connection,
    customerIdInput,
    customerNameInput,
    oneTimeInput,
    activeInput,
    lastNameInput,
    firstNameInput,
    middleNameInput,
    prefixInput,
    companyNameInput,
    printAsInput,
    primaryPhoneNoInput,
    secondaryPhoneNoInput,
    cellularPhoneNoInput,
    pagerNoInput,
    faxNoInput,
    primaryEmailAddressInput,
    secondaryEmailAddressInput,
    primaryUrlInput,
    secondaryUrlInput,
    addressLine1Input,
    addressLine2Input,
    cityInput,
    stateProvinceInput,
    zipPostalCodeInput,
    countryInput,
    isoCountryCodeInput,
    excludedFromContactListInput,
    customerTypeIdInput,
    salesRepEmployeeIdInput,
    parentCustomerIdInput,
    glGroupNameInput,
    territoryIdInput,
    attachmentsIdInput,
    paymentTermInput,
    offsetArGlAccountNoInput,
    defaultRevenueGlAccountNoInput,
    shippingMethodInput,
    resaleNumberInput,
    taxableInput,
    contactTaxGroupNameInput,
    taxIdInput,
    creditLimitInput,
    onHoldInput,
    deliveryMethodInput,
    defaultInvoiceMessageInput,
    commentsInput,
    defaultCurrencyInput,
    printOptionArInvoiceTemplateNameInput,
    printOptionOeQuoteTemplateNameInput,
    printOptionOeOrderTemplateNameInput,
    printOptionOeListTemplateNameInput,
    printOptionOeInvoiceTemplateNameInput,
    printOptionOeAdjustmentTemplateNameInput,
    printOptionOeOtherTemplateNameInput,
    primaryContactNameInput,
    billToContactNameInput,
    shipToContactNameInput,
    restrictionTypeInput,
    restrictedLocationsInput,
    restrictedDepartmentsInput,
    customFieldsInput,
  },
  examplePayload: createCustomerPayload,
});
