import { action, util } from "@prismatic-io/spectral";
import {
  connection,
  vendorIdInput,
  vendorNameInput,
  oneTimeVendorInput as oneTimeInput,
  activeInput,
  lastNameInput,
  firstNameInput,
  middleNameInput,
  prefixInput,
  companyNameInput,
  printAsInput,
  primaryPhoneNoInput,
  secondaryPhoneNoInput,
  cellularPhoneNoInput,
  pagerNoInput,
  faxNoInput,
  primaryEmailAddressInput,
  secondaryEmailAddressInput,
  primaryUrlInput,
  secondaryUrlInput,
  addressLine1Input,
  addressLine2Input,
  cityInput,
  stateProvinceInput,
  zipPostalCodeInput,
  countryInput,
  isoCountryCodeInput,
  excludedFromContactListInput,
  vendorTypeIdInput,
  parentVendorIdInput,
  glGroupNameInput,
  taxIdInput,
  form1099NameInput,
  form1099TypeInput,
  form1099BoxInput,
  attachmentsIdInput,
  defaultExpenseGlAccountNoInput,
  offsetGlAccountNoInput,
  taxableInput,
  contactTaxGroupNameInput,
  creditLimitInput,
  onHoldInput,
  doNotPayInput,
  commentsInput,
  defaultCurrencyInput,
  primaryContactNameInput,
  payToContactNameInput,
  returnToContactNameInput,
  preferredPaymentMethodInput,
  sendAutomaticPaymentNotificationInput,
  mergePaymentRequestsInput,
  vendorBillingTypeInput,
  paymentPriorityInput,
  paymentTermInput,
  termDiscountDisplayedOnCheckStubInput,
  achEnabledInput,
  achBankRoutingNoInput,
  achBankAccountNoInput,
  achBankAccountTypeInput,
  achBankAccountClassInput,
  vendorAccountNoInput,
  locationAssignedAccountNoDisplayedOnCheckStubInput,
  restrictionTypeInput,
  restrictedLocationsInput,
  restrictedDepartmentsInput,
  customFieldsInput,
} from "../inputs";
import {
  assignParametersToObject,
  convertResultToGenericObject,
  executeAction,
} from "../utils";
import { Functions } from "@intacct/intacct-sdk";
import type { AbstractVendor } from "@intacct/intacct-sdk/dist/Functions/AccountsPayable";
import { createVendorPayload } from "../examplePayloads/createVendorPayload";

export const createVendor = action({
  display: {
    label: "Create Vendor",
    description: "Creates a new vendor.",
  },
  perform: async (
    context,
    {
      connection,
      vendorIdInput,
      vendorNameInput,
      oneTimeInput,
      activeInput,
      lastNameInput,
      firstNameInput,
      middleNameInput,
      prefixInput,
      companyNameInput,
      printAsInput,
      primaryPhoneNoInput,
      secondaryPhoneNoInput,
      cellularPhoneNoInput,
      pagerNoInput,
      faxNoInput,
      primaryEmailAddressInput,
      secondaryEmailAddressInput,
      primaryUrlInput,
      secondaryUrlInput,
      addressLine1Input,
      addressLine2Input,
      cityInput,
      stateProvinceInput,
      zipPostalCodeInput,
      countryInput,
      isoCountryCodeInput,
      excludedFromContactListInput,
      vendorTypeIdInput,
      parentVendorIdInput,
      glGroupNameInput,
      taxIdInput,
      form1099NameInput,
      form1099TypeInput,
      form1099BoxInput,
      attachmentsIdInput,
      defaultExpenseGlAccountNoInput,
      offsetGlAccountNoInput,
      taxableInput,
      contactTaxGroupNameInput,
      creditLimitInput,
      onHoldInput,
      doNotPayInput,
      commentsInput,
      defaultCurrencyInput,
      primaryContactNameInput,
      payToContactNameInput,
      returnToContactNameInput,
      preferredPaymentMethodInput,
      sendAutomaticPaymentNotificationInput,
      mergePaymentRequestsInput,
      vendorBillingTypeInput,
      paymentPriorityInput,
      paymentTermInput,
      termDiscountDisplayedOnCheckStubInput,
      achEnabledInput,
      achBankRoutingNoInput,
      achBankAccountNoInput,
      achBankAccountTypeInput,
      achBankAccountClassInput,
      vendorAccountNoInput,
      locationAssignedAccountNoDisplayedOnCheckStubInput,
      restrictionTypeInput,
      restrictedLocationsInput,
      restrictedDepartmentsInput,
      customFieldsInput,
    },
  ) => {
    const createVendor = new Functions.AccountsPayable.VendorCreate();

    assignParametersToObject(createVendor, {
      vendorId: vendorIdInput,
      vendorName: vendorNameInput,
      oneTime:
        oneTimeInput === "" ? undefined : util.types.toBool(oneTimeInput),
      active: activeInput === "" ? undefined : util.types.toBool(activeInput),
      lastName: lastNameInput,
      firstName: firstNameInput,
      middleName: middleNameInput,
      prefix: prefixInput,
      companyName: companyNameInput,
      printAs: printAsInput,
      primaryPhoneNo: primaryPhoneNoInput,
      secondaryPhoneNo: secondaryPhoneNoInput,
      cellularPhoneNo: cellularPhoneNoInput,
      pagerNo: pagerNoInput,
      faxNo: faxNoInput,
      primaryEmailAddress: primaryEmailAddressInput,
      secondaryEmailAddress: secondaryEmailAddressInput,
      primaryUrl: primaryUrlInput,
      secondaryUrl: secondaryUrlInput,
      addressLine1: addressLine1Input,
      addressLine2: addressLine2Input,
      city: cityInput,
      stateProvince: stateProvinceInput,
      zipPostalCode: zipPostalCodeInput,
      country: countryInput,
      isoCountryCode: isoCountryCodeInput,
      excludedFromContactList:
        excludedFromContactListInput === ""
          ? undefined
          : util.types.toBool(excludedFromContactListInput),
      vendorTypeId: vendorTypeIdInput,
      parentVendorId: parentVendorIdInput,
      glGroupName: glGroupNameInput,
      taxId: taxIdInput,
      form1099Name: form1099NameInput,
      form1099Type: form1099TypeInput,
      form1099Box: form1099BoxInput,
      attachmentsId: attachmentsIdInput,
      defaultExpenseGlAccountNo: defaultExpenseGlAccountNoInput,
      offsetGlAccountNo: offsetGlAccountNoInput,
      taxable:
        taxableInput === "" ? undefined : util.types.toBool(taxableInput),
      contactTaxGroupName: contactTaxGroupNameInput,
      creditLimit: creditLimitInput,
      onHold: onHoldInput === "" ? undefined : util.types.toBool(onHoldInput),
      doNotPay:
        doNotPayInput === "" ? undefined : util.types.toBool(doNotPayInput),
      comments: commentsInput,
      defaultCurrency: defaultCurrencyInput,
      primaryContactName: primaryContactNameInput,
      payToContactName: payToContactNameInput,
      returnToContactName: returnToContactNameInput,
      preferredPaymentMethod: preferredPaymentMethodInput,
      sendAutomaticPaymentNotification:
        sendAutomaticPaymentNotificationInput === ""
          ? undefined
          : util.types.toBool(sendAutomaticPaymentNotificationInput),
      mergePaymentRequests:
        mergePaymentRequestsInput === ""
          ? undefined
          : util.types.toBool(mergePaymentRequestsInput),
      vendorBillingType: vendorBillingTypeInput,
      paymentPriority: paymentPriorityInput,
      paymentTerm: paymentTermInput,
      termDiscountDisplayedOnCheckStub:
        termDiscountDisplayedOnCheckStubInput === ""
          ? undefined
          : util.types.toBool(termDiscountDisplayedOnCheckStubInput),
      achEnabled:
        achEnabledInput === "" ? undefined : util.types.toBool(achEnabledInput),
      achBankRoutingNo: achBankRoutingNoInput,
      achBankAccountNo: achBankAccountNoInput,
      achBankAccountType: achBankAccountTypeInput,
      achBankAccountClass: achBankAccountClassInput,
      vendorAccountNo: vendorAccountNoInput,
      locationAssignedAccountNoDisplayedOnCheckStub:
        locationAssignedAccountNoDisplayedOnCheckStubInput === ""
          ? undefined
          : util.types.toBool(
              locationAssignedAccountNoDisplayedOnCheckStubInput,
            ),
      restrictionType: restrictionTypeInput,
      restrictedLocations: restrictedLocationsInput,
      restrictedDepartments: restrictedDepartmentsInput,
      customFields: customFieldsInput,
    } as unknown as AbstractVendor);

    if (context.debug.enabled) {
      context.logger.debug(JSON.stringify(createVendor, null, 2));
    }
    const data = await executeAction(connection, createVendor);
    return {
      data: convertResultToGenericObject(data),
    };
  },
  inputs: {
    connection,
    vendorIdInput,
    vendorNameInput,
    oneTimeInput,
    activeInput,
    lastNameInput,
    firstNameInput,
    middleNameInput,
    prefixInput,
    companyNameInput,
    printAsInput: { ...printAsInput, required: true },
    primaryPhoneNoInput,
    secondaryPhoneNoInput,
    cellularPhoneNoInput,
    pagerNoInput,
    faxNoInput,
    primaryEmailAddressInput,
    secondaryEmailAddressInput,
    primaryUrlInput,
    secondaryUrlInput,
    addressLine1Input,
    addressLine2Input,
    cityInput,
    stateProvinceInput,
    zipPostalCodeInput,
    countryInput,
    isoCountryCodeInput,
    excludedFromContactListInput,
    vendorTypeIdInput,
    parentVendorIdInput,
    glGroupNameInput,
    taxIdInput,
    form1099NameInput,
    form1099TypeInput,
    form1099BoxInput,
    attachmentsIdInput,
    defaultExpenseGlAccountNoInput,
    offsetGlAccountNoInput,
    taxableInput,
    contactTaxGroupNameInput,
    creditLimitInput,
    onHoldInput,
    doNotPayInput,
    commentsInput,
    defaultCurrencyInput,
    primaryContactNameInput,
    payToContactNameInput,
    returnToContactNameInput,
    preferredPaymentMethodInput,
    sendAutomaticPaymentNotificationInput,
    mergePaymentRequestsInput,
    vendorBillingTypeInput,
    paymentPriorityInput,
    paymentTermInput,
    termDiscountDisplayedOnCheckStubInput,
    achEnabledInput,
    achBankRoutingNoInput,
    achBankAccountNoInput,
    achBankAccountTypeInput,
    achBankAccountClassInput,
    vendorAccountNoInput,
    locationAssignedAccountNoDisplayedOnCheckStubInput,
    restrictionTypeInput,
    restrictedLocationsInput,
    restrictedDepartmentsInput,
    customFieldsInput,
  },
  examplePayload: createVendorPayload,
});
