export const LIVE_API_URL = "https://account.docusign.com";
export const DEVELOPMENT_API_URL = "https://account-d.docusign.com";
export const WEBHOOK_EVENTS = [
  "envelope-sent",
  "envelope-delivered",
  "envelope-completed",
  "envelope-created",
  "envelope-declined",
  "envelope-voided",
  "envelope-resent",
  "envelope-corrected",
  "envelope-purge",
  "envelope-deleted",
  "envelope-discard",
  "recipient-sent",
  "recipient-autoresponded",
  "recipient-delivered",
  "recipient-completed",
  "recipient-declined",
  "recipient-authenticationfailed",
  "recipient-resent",
  "recipient-delegate",
  "recipient-reassign",
  "recipient-finish-later",
  "template-created",
  "template-modified",
  "template-deleted",
  "click-agreed",
  "click-declined",
  "sms-opt-in",
  "sms-opt-out",
  "identity-verification-completed",
  "identity-verification-pending",
];
