import { metaSchema } from "./common";
const partitionSchema = {
  type: "object" as const,
  properties: {
    autoUnlockEnabled: { type: "boolean" },
    autoUnlockKeyStored: { type: "boolean" },
    driveLetter: { type: "string" },
    encryptionMethod: { type: "string" },
    encryptionPercentage: { type: "integer" },
    fileSystem: { type: "string" },
    fileSystemLabel: { type: "string" },
    freePercent: { type: "integer" },
    healthStatus: { type: "string" },
    id: { type: "string" },
    isBoot: { type: "boolean" },
    isHidden: { type: "boolean" },
    isOffline: { type: "boolean" },
    isSystem: { type: "boolean" },
    keyProtector: { type: "string" },
    lockStatus: { type: "string" },
    operationalStatus: { type: "string" },
    partitionNumber: { type: "integer" },
    partitionType: { type: "string", enum: ["mbr", "gpt"] },
    protectionStatus: { type: "string" },
    sizeKb: { type: "integer" },
    sizeRemainingKb: { type: "integer" },
    type: { type: "string" },
    volumeStatus: { type: "string" },
  },
};
const activeDirectorySchema = {
  type: "object" as const,
  properties: {
    azureAdJoined: { type: "boolean" },
    description: { type: "string" },
    deviceName: { type: "string" },
    distinguishedName: { type: "string" },
    domain: { type: "string" },
    domainController: { type: "string" },
    domainJoined: { type: "boolean" },
    entraDeviceId: { type: "string" },
    entraTenantId: { type: "string" },
    entraTenantName: { type: "string" },
    id: { type: "string" },
    lastLogon: { type: "string", format: "date-time" },
  },
};
const activeDirectoryGroupSchema = {
  type: "object" as const,
  properties: {
    description: { type: "string" },
    distinguishedName: { type: "string" },
    guid: { type: "string" },
    id: { type: "string" },
    name: { type: "string" },
  },
};
const deviceCustomFieldSchema = {
  type: "object" as const,
  properties: {
    id: { type: "string" },
    name: { type: "string" },
    type: { type: "string", enum: ["boolean", "date", "number", "string"] },
    updatedAt: { type: "string", format: "date-time" },
    updatedBy: { type: "string" },
    value: { type: ["boolean", "number", "string"] },
  },
};
const diskSchema = {
  type: "object" as const,
  properties: {
    busType: { type: "string" },
    diskNumber: { type: "integer" },
    driveType: { type: "string" },
    firmwareVersion: { type: "string" },
    healthStatus: { type: "string" },
    id: { type: "string" },
    manufacturer: { type: "string" },
    mediaType: { type: "string" },
    model: { type: "string" },
    operationalStatus: { type: "string" },
    partitions: { type: "array", items: partitionSchema },
    serialNumber: { type: "string" },
    totalSpaceKb: { type: "integer" },
  },
};
const driverSchema = {
  type: "object" as const,
  properties: {
    class: { type: "string" },
    date: { type: "string", format: "date-time" },
    driverId: { type: "string" },
    id: { type: "string" },
    name: { type: "string" },
    provider: { type: "string" },
    signer: { type: "string" },
    version: { type: "string" },
  },
};
const featureSchema = {
  type: "object" as const,
  properties: {
    caption: { type: "string" },
    enabled: { type: "boolean" },
    id: { type: "string" },
    name: { type: "string" },
  },
};
const networkingSchema = {
  type: "object" as const,
  properties: {
    alias: { type: "string" },
    description: { type: "string" },
    dnsServer: { type: "array", items: { type: "string" } },
    id: { type: "string" },
    index: { type: "integer" },
    ipv4Address: { type: "string" },
    ipv4Gateway: { type: "string" },
    ipv6Address: { type: "string" },
    ipv6Gateway: { type: "string" },
    linkSpeed: { type: "string" },
    netAdapterStatus: { type: "string" },
    netProfileName: { type: "string" },
  },
};
const processorSchema = {
  type: "object" as const,
  properties: {
    assetTag: { type: "string" },
    cpuId: { type: "string" },
    description: { type: "string" },
    errorDescription: { type: "string" },
    id: { type: "string" },
    lThreeCacheSize: { type: "integer" },
    lTwoCacheSize: { type: "integer" },
    lastErrorCode: { type: "integer" },
    manufacturer: { type: "string" },
    maxClockSpeed: { type: "integer" },
    name: { type: "string" },
    numberOfCores: { type: "integer" },
    numberOfEnabledCore: { type: "integer" },
    numberOfLogicalProcessors: { type: "integer" },
    status: { type: "string" },
  },
};
const softwareSchema = {
  type: "object" as const,
  properties: {
    hive: { type: "string" },
    id: { type: "string" },
    installedAt: { type: "string", format: "date-time" },
    latestVersion: { type: "string" },
    name: { type: "string" },
    path: { type: "string" },
    publisher: { type: "string" },
    status: { type: "string", enum: ["latest", "outdated", "unknown"] },
    uninstall: { type: "string" },
    version: { type: "array", items: { type: "integer" } },
    versionRaw: { type: "string" },
    versionlessCpe: { type: "string" },
  },
};
const updateSchema = {
  type: "object" as const,
  properties: {
    date: { type: "string", format: "date-time" },
    description: { type: "string" },
    id: { type: "string" },
    result: { type: "string" },
    supportUrl: { type: "string" },
    title: { type: "string" },
  },
};
export const deviceSchema = {
  type: "object" as const,
  properties: {
    activeDirectory: { type: "array", items: activeDirectorySchema },
    activeDirectoryGroups: { type: "array", items: activeDirectoryGroupSchema },
    agentVersion: { type: "string" },
    architecture: { type: "string" },
    biosAssetTag: { type: "string" },
    biosManufacturer: { type: "string" },
    biosVersion: { type: "string" },
    chassis: { type: "string" },
    currentUser: { type: "string" },
    customFields: { type: "array", items: deviceCustomFieldSchema },
    disks: { type: "array", items: diskSchema },
    dotNetVersions: { type: "string" },
    drivers: { type: "array", items: driverSchema },
    family: { type: "string" },
    features: { type: "array", items: featureSchema },
    freePercent: { type: "integer" },
    hostname: { type: "string" },
    id: { type: "string" },
    insertedAt: { type: "string", format: "date-time" },
    isOnline: { type: "boolean" },
    lastBootUpTime: { type: "string", format: "date-time" },
    lastSeenAt: { type: "string", format: "date-time" },
    lastUser: { type: "string" },
    lastUserShortName: { type: "string" },
    macAddress: { type: "string" },
    manufacturer: { type: "string" },
    memory: { type: "integer" },
    model: { type: "string" },
    name: { type: "string" },
    networking: { type: "array", items: networkingSchema },
    os: { type: "string" },
    osFullName: { type: "string" },
    osInstallDate: { type: "string", format: "date-time" },
    osProductType: { type: "string" },
    osVersion: { type: "string" },
    powershellVersion: { type: "string" },
    processors: { type: "array", items: processorSchema },
    publicIpAddress: { type: "string" },
    requireReboot: { type: "boolean" },
    serialNumber: { type: "string" },
    servicePack: { type: "string" },
    sku: { type: "string" },
    smbVersionOne: { type: "boolean" },
    software: { type: "array", items: softwareSchema },
    systemVersion: { type: "string" },
    timezone: { type: "string" },
    updatedAt: { type: "string", format: "date-time" },
    updates: { type: "array", items: updateSchema },
  },
  required: ["id"],
};
export const getDeviceOutputSchema = {
  type: "object" as const,
  properties: {
    data: deviceSchema,
  },
};
export const listDevicesOutputSchema = {
  type: "object" as const,
  properties: {
    data: { type: "array", items: deviceSchema },
    meta: metaSchema,
  },
};
