import { connection } from "@prismatic-io/spectral";
import { BASE_URL } from "../constants";

export const ssvApiKeyConnection = connection({
  key: "ssvApiKeyConnection",
  display: {
    label: "API Key",
    description: "Authenticate requests using an API key.",
  },
  inputs: {
    baseUrl: {
      label: "Base URL",
      placeholder: "https://openapi.systemsurveyor.com",
      type: "string",
      required: true,
      shown: true,
      default: "https://openapi.systemsurveyor.com",
      model: BASE_URL,
      comments: "The base URL for the System Surveyor API environment.",
    },
    apiKey: {
      label: "API Key",
      placeholder: "Enter API key",
      type: "password",
      required: true,
      shown: true,
      comments:
        "The enterprise access token generated by an account administrator.",
    },
  },
});
