import {
  creatorSchema,
  folderRefSchema,
  listRefSchema,
  prioritySchema,
  sharingSchema,
  spaceIdRefSchema,
  statusRefSchema,
  taskCustomFieldSchema,
  taskDependencySchema,
  taskLocationSchema,
  taskTagSchema,
  taskUserSchema,
  userRefSchema,
} from "./shared";
const taskProperties = {
  id: { type: "string" },
  custom_id: { type: ["string", "null"] },
  custom_item_id: { type: ["number", "null"] },
  name: { type: "string" },
  text_content: { type: "string" },
  description: { type: "string" },
  markdown_description: { type: "string" },
  status: statusRefSchema,
  orderindex: { type: "string" },
  date_created: { type: "string" },
  date_updated: { type: "string" },
  date_closed: { type: ["string", "null"] },
  date_done: { type: ["string", "null"] },
  archived: { type: "boolean" },
  creator: creatorSchema,
  assignees: { type: "array", items: taskUserSchema },
  group_assignees: { type: "array", items: { type: "object" } },
  watchers: { type: "array", items: taskUserSchema },
  checklists: { type: "array", items: { type: "object" } },
  tags: { type: "array", items: taskTagSchema },
  parent: { type: ["string", "null"] },
  top_level_parent: { type: ["string", "null"] },
  priority: prioritySchema,
  due_date: { type: ["string", "null"] },
  start_date: { type: ["string", "null"] },
  points: { type: ["number", "null"] },
  time_estimate: { type: ["number", "null"] },
  time_spent: { type: ["number", "null"] },
  custom_fields: { type: "array", items: taskCustomFieldSchema },
  dependencies: { type: "array", items: taskDependencySchema },
  linked_tasks: { type: "array", items: { type: "object" } },
  locations: { type: "array", items: taskLocationSchema },
  team_id: { type: "string" },
  url: { type: "string" },
  sharing: sharingSchema,
  permission_level: { type: "string" },
  list: listRefSchema,
  project: folderRefSchema,
  folder: folderRefSchema,
  space: spaceIdRefSchema,
};
const subtaskSchema = {
  type: "object" as const,
  properties: {
    id: { type: "string" },
    custom_item_id: { type: ["number", "null"] },
    name: { type: "string" },
    status: statusRefSchema,
    orderindex: { type: "string" },
    date_created: { type: "string" },
    date_updated: { type: "string" },
    date_closed: { type: ["string", "null"] },
    date_done: { type: ["string", "null"] },
    archived: { type: "boolean" },
    creator: creatorSchema,
    assignees: { type: "array", items: taskUserSchema },
    group_assignees: { type: "array", items: { type: "object" } },
    watchers: { type: "array", items: taskUserSchema },
    checklists: { type: "array", items: { type: "object" } },
    tags: { type: "array", items: taskTagSchema },
    parent: { type: ["string", "null"] },
    top_level_parent: { type: ["string", "null"] },
    due_date: { type: ["string", "null"] },
    start_date: { type: ["string", "null"] },
    points: { type: ["number", "null"] },
    time_estimate: { type: ["number", "null"] },
    time_spent: { type: ["number", "null"] },
    custom_fields: { type: "array", items: taskCustomFieldSchema },
    dependencies: { type: "array", items: taskDependencySchema },
    linked_tasks: { type: "array", items: { type: "object" } },
    locations: { type: "array", items: taskLocationSchema },
    url: { type: "string" },
  },
};
const taskAttachmentSchema = {
  type: "object" as const,
  properties: {
    id: { type: "string" },
    date: { type: "integer", format: "int64" },
    title: { type: "string" },
    type: { type: "integer" },
    source: { type: "integer" },
    version: { type: "integer" },
    extension: { type: "string" },
    thumbnail_small: { type: "string" },
    thumbnail_medium: { type: "string" },
    thumbnail_large: { type: "string" },
    is_folder: { type: "boolean" },
    mimetype: { type: "string" },
    hidden: { type: "boolean" },
    parent_id: { type: "string" },
    size: { type: "integer", format: "int64" },
    total_comments: { type: "integer" },
    resolved_comments: { type: "integer" },
    user: userRefSchema,
    deleted: { type: "boolean" },
    orientation: { type: "string" },
    url: { type: "string" },
    email_data: { type: "object" },
    url_w_query: { type: "string" },
    url_w_host: { type: "string" },
  },
};
export const getTaskOutputSchema = {
  type: "object" as const,
  properties: {
    ...taskProperties,
    subtasks: { type: "array", items: subtaskSchema },
    attachments: { type: "array", items: taskAttachmentSchema },
  },
};
export const createTaskOutputSchema = {
  type: "object" as const,
  properties: {
    ...taskProperties,
    time_estimate: { type: ["string", "null"] },
    time_spent: { type: "number" },
  },
};
export const updateTaskOutputSchema = {
  type: "object" as const,
  properties: {
    ...taskProperties,
    text_content: { type: ["string", "null"] },
    description: { type: ["string", "null"] },
    time_estimate: { type: ["string", "null"] },
    time_spent: { type: "number" },
    subtasks: { type: "array", items: subtaskSchema },
    attachments: { type: "array", items: taskAttachmentSchema },
  },
};
export const listTasksOutputSchema = {
  type: "object" as const,
  properties: {
    tasks: {
      type: "array",
      items: {
        type: "object" as const,
        properties: {
          ...taskProperties,
          orderindex: { type: ["string", "number"] },
          time_estimate: { type: ["string", "null"] },
          time_spent: { type: "number" },
        },
      },
    },
    last_page: { type: "boolean" },
  },
};
