import { component } from "@prismatic-io/spectral";
import { handleErrors } from "@prismatic-io/spectral/dist/clients/http";
import {
  addCustomFieldToPortfolio,
  addCustomFieldToProject,
  addFollowersToTask,
  addTagToTask,
  addTaskToSection,
  addUser,
  addUserToPortfolio,
  addUserToProject,
  addUserToTeam,
  attachFileToTask,
  createPortfolio,
  createProjects,
  createSection,
  createStatusUpdate,
  createTag,
  createTask,
  createTeam,
  createWebhook,
  deleteAttachment,
  deleteInstanceWebhooks,
  deletePortfolio,
  deleteProjects,
  deleteSection,
  deleteStatus,
  deleteTag,
  deleteTask,
  deleteWebhook,
  findTagByName,
  findTeamByName,
  findUserByNameOrEmail,
  findWorkspaceByName,
  getAttachment,
  getCurrentUser,
  getCustomField,
  getPortfolio,
  getProject,
  getSection,
  getStatusesForObject,
  getStatusUpdate,
  getTag,
  getTask,
  getTeam,
  getUsers,
  getWorkspace,
  listAttachments,
  listCustomFields,
  listPortfolioItems,
  listPortfolios,
  listProjects,
  listSections,
  listSubtasks,
  listTags,
  listTagsInTask,
  listTasks,
  listTeams,
  listUsers,
  listWebhooks,
  listWorkspaces,
  rawRequest,
  removeAssigneeFromTask,
  removeCustomFieldFromPortfolio,
  removeCustomFieldFromProject,
  removeFollowersFromTask,
  removePortfolioItem,
  removeTagFromTask,
  removeUserFromPortfolio,
  updatePortfolio,
  updateProject,
  updateSection,
  updateTag,
  updateTask,
} from "./actions";
import connections from "./connections";
import dataSources from "./dataSources";
import triggers from "./triggers";

export default component({
  key: "asana",
  public: true,
  documentationUrl: "https://prismatic.io/docs/components/asana/",
  display: {
    category: "Application Connectors",
    label: "Asana",
    description: "Manage users, projects, and teams in your Asana workspace.",
    iconPath: "icon.png",
  },
  actions: {
    listProjects,
    listWorkspaces,
    findWorkspaceByName,
    addUser,
    getWorkspace,
    createProjects,
    updateProject,
    deleteProjects,
    getUsers,
    getCurrentUser,
    listUsers,
    findUserByNameOrEmail,
    listTasks,
    getProject,
    createTask,
    deleteTask,
    getTask,
    updateTask,
    addUserToTeam,
    createTeam,
    getTeam,
    listPortfolios,
    getPortfolio,
    addCustomFieldToPortfolio,
    removeCustomFieldFromPortfolio,
    deletePortfolio,
    createPortfolio,
    addUserToPortfolio,
    removeUserFromPortfolio,
    updatePortfolio,
    createTag,
    deleteTag,
    getTag,
    listTags,
    findTagByName,
    listTagsInTask,
    updateTag,
    listSubtasks,
    addTaskToSection,
    createSection,
    deleteSection,
    getSection,
    listSections,
    updateSection,
    removeCustomFieldFromProject,
    addUserToProject,
    addCustomFieldToProject,
    listPortfolioItems,
    removePortfolioItem,
    listCustomFields,
    getCustomField,
    deleteAttachment,
    getAttachment,
    listAttachments,
    attachFileToTask,
    addFollowersToTask,
    removeFollowersFromTask,
    removeAssigneeFromTask,
    addTagToTask,
    removeTagFromTask,
    listTeams,
    findTeamByName,
    createStatusUpdate,
    deleteStatus,
    getStatusesForObject,
    getStatusUpdate,
    rawRequest,
    createWebhook,
    deleteWebhook,
    deleteInstanceWebhooks,
    listWebhooks,
  },
  triggers,
  dataSources,
  hooks: { error: handleErrors },
  connections,
});
