import { onPremConnection, util } from "@prismatic-io/spectral";

export const imapConnection = onPremConnection({
  key: "imap",
  display: {
    label: "IMAP Connection",
    description: "Provide the details of your IMAP server.",
  },
  inputs: {
    host: {
      label: "Host",
      placeholder: "Host",
      type: "string",
      required: true,
      clean: (param: unknown) => util.types.toString(param) || undefined,
      shown: true,
      comments: "Provide the host address for the desired IMAP server.",
      example: "imap.example.com",
      onPremControlled: true,
    },
    port: {
      label: "Port",
      placeholder: "Port",
      type: "string",
      required: true,
      clean: (param: unknown) => util.types.toNumber(param) || undefined,
      shown: true,
      comments: "Provide the port for the desired IMAP server.",
      example: "993",
      default: "993",
      onPremControlled: true,
    },
    secure: {
      label: "Secure",
      placeholder: "Secure",
      type: "boolean",
      clean: (param: unknown) => util.types.toBool(param) || undefined,
      required: true,
      shown: true,
      default: "true",
      comments: "Determines if the connection is secure.",
    },
    user: {
      label: "Username",
      placeholder: "Username",
      type: "string",
      clean: (param: unknown) => util.types.toString(param) || undefined,
      required: true,
      shown: true,
      comments: "Provide a valid username or email.",
      example: "someone@example.com",
    },
    pass: {
      label: "Password",
      placeholder: "Password",
      type: "password",
      required: false,
      shown: true,
      clean: (param: unknown) => util.types.toString(param) || undefined,
      comments:
        "Provide the password for the given user. This value is required if secured is set to true.",
      example: "examplePassword",
    },
    minVersion: {
      label: "Minimum TLS Version",
      type: "string",
      required: true,
      shown: true,
      clean: (param: unknown) => util.types.toString(param) || undefined,
      comments: "Provide a valid TLS version to be used in the connection.",
      example: "TLSv1.1",
      default: "TLSv1.1",
      model: [
        { label: "TLSv1.1", value: "TLSv1.1" },
        { label: "TLSv1.2", value: "TLSv1.2" },
        { label: "TLSv1.3", value: "TLSv1.3" },
      ],
    },
    maxVersion: {
      label: "Maximum TLS Version",
      type: "string",
      required: true,
      shown: true,
      clean: (param: unknown) => util.types.toString(param) || undefined,
      comments: "Provide a valid TLS version to be used in the connection.",
      example: "TLSv1.3",
      default: "TLSv1.3",
      model: [
        { label: "TLSv1.1", value: "TLSv1.1" },
        { label: "TLSv1.2", value: "TLSv1.2" },
        { label: "TLSv1.3", value: "TLSv1.3" },
      ],
    },
    minDHSize: {
      label: "Min DH Size",
      type: "string",
      required: true,
      shown: true,
      clean: (param: unknown) => util.types.toInt(param) || undefined,
      comments: "Minimum size of bits to accept in a TLS connection",
      example: "512",
      default: "1024",
    },
  },
});

export default [imapConnection];
