export const CREATE_CONTACT_EXAMPLE_PAYLOAD = {
  type: "contact",
  id: "5ba682d23d7cf92bef87bfd4",
  workspace_id: "ecahpwf5",
  external_id: "25",
  role: "user",
  email: "wash@serenity.io",
  phone: "+1123456789",
  name: "Hoban Washburn",
  avatar: "https://example.org/128Wash.jpg",
  owner_id: 127,
  social_profiles: {
    type: "list",
    data: [
      {
        type: "social_profile",
        name: "Twitter",
        url: "http://twitter.com/th1sland",
      },
    ],
  },
  unsubscribed_from_emails: false,
  created_at: 1571672154,
  updated_at: 1571672158,
  signed_up_at: 1571069751,
  last_seen_at: 1571069751,
  last_replied_at: 1571672158,
  last_contacted_at: 1571672158,
  last_email_opened_at: 1571673478,
  last_email_clicked_at: 1571676789,
  language_override: null,
  browser: "chrome",
  browser_version: "77.0.3865.90",
  browser_language: "en",
  os: "OS X 10.14.6",
  location: {
    type: "location",
    country: "Ireland",
    region: "Dublin",
    city: "Dublin",
  },
  android_app_name: null,
  android_app_version: null,
  android_device: null,
  android_os_version: null,
  android_sdk_version: null,
  android_last_seen_at: null,
  ios_app_name: null,
  ios_app_version: null,
  ios_device: null,
  ios_os_version: null,
  ios_sdk_version: null,
  ios_last_seen_at: null,
  custom_attributes: {
    paid_subscriber: true,
    monthly_spend: 155.5,
    team_mates: 1,
  },
  tags: {
    type: "list",
    data: [
      {
        type: "tag",
        id: "2",
        url: "/tags/2",
      },
      {
        type: "tag",
        id: "4",
        url: "/tags/4",
      },
      {
        type: "tag",
        id: "5",
        url: "/tags/5",
      },
    ],
    url: "/contacts/5ba682d23d7cf92bef87bfd4/tags",
  },
  notes: {
    type: "list",
    data: [
      {
        type: "note",
        id: "20114858",
        url: "/notes/20114858",
      },
    ],
    url: "/contacts/5ba682d23d7cf92bef87bfd4/notes",
  },
  companies: {
    type: "list",
    data: [
      {
        type: "company",
        id: "5ba686093d7cf93552a3dc99",
        url: "/companies/5ba686093d7cf93552a3dc99",
      },
      {
        type: "company",
        id: "5cee64a03d7cf90c51b36f19",
        url: "/companies/5cee64a03d7cf90c51b36f19",
      },
      {
        type: "company",
        id: "5d7668883d7cf944dbc5c791",
        url: "/companies/5d7668883d7cf944dbc5c791",
      },
    ],
    url: "/contacts/5ba682d23d7cf92bef87bfd4/companies",
  },
};

export const GET_CONTACT_EXAMPLE_PAYLOAD = {
  data: {
    type: "contact",
    id: "667d60a98a68186f43bafdb9",
    workspace_id: "this_is_an_id252_that_should_be_at_least_",
    external_id: "70",
    role: "user",
    email: "joe@bloggs.com",
    phone: null,
    name: "Joe Bloggs",
    avatar: null,
    owner_id: null,
    social_profiles: {
      type: "list",
      data: [],
    },
    has_hard_bounced: false,
    marked_email_as_spam: false,
    unsubscribed_from_emails: false,
    created_at: 1719492777,
    updated_at: 1719492777,
    signed_up_at: 1719492777,
    last_seen_at: null,
    last_replied_at: null,
    last_contacted_at: null,
    last_email_opened_at: null,
    last_email_clicked_at: null,
    language_override: null,
    browser: null,
    browser_version: null,
    browser_language: null,
    os: null,
    location: {
      type: "location",
      country: null,
      region: null,
      city: null,
      country_code: null,
      continent_code: null,
    },
    android_app_name: null,
    android_app_version: null,
    android_device: null,
    android_os_version: null,
    android_sdk_version: null,
    android_last_seen_at: null,
    ios_app_name: null,
    ios_app_version: null,
    ios_device: null,
    ios_os_version: null,
    ios_sdk_version: null,
    ios_last_seen_at: null,
    custom_attributes: {},
    tags: {
      type: "list",
      data: [],
      url: "/contacts/667d60a98a68186f43bafdb9/tags",
      total_count: 0,
      has_more: false,
    },
    notes: {
      type: "list",
      data: [],
      url: "/contacts/667d60a98a68186f43bafdb9/notes",
      total_count: 0,
      has_more: false,
    },
    companies: {
      type: "list",
      data: [],
      url: "/contacts/667d60a98a68186f43bafdb9/companies",
      total_count: 0,
      has_more: false,
    },
    opted_out_subscription_types: {
      type: "list",
      data: [],
      url: "/contacts/667d60a98a68186f43bafdb9/subscriptions",
      total_count: 0,
      has_more: false,
    },
    opted_in_subscription_types: {
      type: "list",
      data: [],
      url: "/contacts/667d60a98a68186f43bafdb9/subscriptions",
      total_count: 0,
      has_more: false,
    },
    utm_campaign: null,
    utm_content: null,
    utm_medium: null,
    utm_source: null,
    utm_term: null,
    referrer: null,
  },
};

export const ATTACH_COMPANY_TO_CONTACT_EXAMPLE_PAYLOAD = {
  data: {
    type: "company",
    company_id: "1",
    id: "667d608d8a68186f43bafd70",
    app_id: "this_is_an_id166_that_should_be_at_least_",
    name: "company6",
    remote_created_at: 1719492749,
    created_at: 1719492749,
    updated_at: 1719492749,
    monthly_spend: 0,
    session_count: 0,
    user_count: 1,
    tags: {
      type: "tag.list",
      tags: [],
    },
    segments: {
      type: "segment.list",
      segments: [],
    },
    plan: {},
    custom_attributes: {},
  },
};

export const DETACH_COMPANY_FROM_CONTACT_EXAMPLE_PAYLOAD = {
  data: {
    type: "company",
    company_id: "1",
    id: "667d60918a68186f43bafd80",
    app_id: "this_is_an_id174_that_should_be_at_least_",
    name: "company8",
    remote_created_at: 1719492753,
    created_at: 1719492753,
    updated_at: 1719492753,
    monthly_spend: 0,
    session_count: 0,
    user_count: 0,
    tags: {
      type: "tag.list",
      tags: [],
    },
    segments: {
      type: "segment.list",
      segments: [],
    },
    plan: {},
    custom_attributes: {},
  },
};

export const ARCHIVE_CONTACT_EXAMPLE_PAYLOAD = {
  data: {
    id: "5ba682d23d7cf92bef87bfd4",
    object: "contact",
    archived: true,
  },
};

export const DELETE_CONTACT_EXAMPLE_PAYLOAD = {
  data: {
    data: {
      id: "5ba682d23d7cf92bef87bfd4",
      object: "contact",
      deleted: true,
    },
  },
};
