export const createEmployeeObj = {
  additionalDirectDeposit: [
    {
      accountNumber: null,
      accountType: null,
      amount: null,
      amountType: null,
      blockSpecial: null,
      isSkipPreNote: null,
      nameOnAccount: null,
      preNoteDate: null,
      routingNumber: null,
    },
  ],
  additionalRate: [
    {
      changeReason: null,
      costCenter1: null,
      costCenter2: null,
      costCenter3: null,
      effectiveDate: null,
      endCheckDate: null,
      job: null,
      rate: null,
      rateCode: null,
      rateNotes: null,
      ratePer: null,
      shift: null,
    },
  ],
  benefitSetup: {
    benefitClass: null,
    benefitClassEffectiveDate: null,
    benefitSalary: null,
    benefitSalaryEffectiveDate: null,
    doNotApplyAdministrativePeriod: null,
    isMeasureAcaEligibility: null,
  },
  birthDate: null,
  companyFEIN: null,
  companyName: null,
  currency: null,
  customBooleanFields: [
    {
      category: "PayrollAndHR",
      label: null,
      value: null,
    },
  ],
  customDateFields: [
    {
      category: "PayrollAndHR",
      label: null,
      value: null,
    },
  ],
  customDropDownFields: [
    {
      category: "PayrollAndHR",
      label: null,
      value: null,
    },
  ],
  customNumberFields: [
    {
      category: "PayrollAndHR",
      label: null,
      value: null,
    },
  ],
  customTextFields: [
    {
      category: "PayrollAndHR",
      label: null,
      value: null,
    },
  ],
  departmentPosition: {
    changeReason: null,
    clockBadgeNumber: null,
    costCenter1: null,
    costCenter2: null,
    costCenter3: null,
    effectiveDate: null,
    employeeType: null,
    equalEmploymentOpportunityClass: null,
    isMinimumWageExempt: null,
    isOvertimeExempt: null,
    isSupervisorReviewer: null,
    isUnionDuesCollected: null,
    isUnionInitiationCollected: null,
    jobTitle: null,
    payGroup: null,
    positionCode: null,
    reviewerCompanyNumber: null,
    reviewerEmployeeId: null,
    shift: null,
    supervisorCompanyNumber: null,
    supervisorEmployeeId: null,
    tipped: null,
    unionAffiliationDate: null,
    unionCode: null,
    unionPosition: null,
    workersCompensation: null,
  },
  disabilityDescription: null,
  emergencyContacts: [
    {
      address1: null,
      address2: null,
      city: null,
      country: null,
      county: null,
      email: null,
      firstName: null,
      homePhone: null,
      lastName: null,
      mobilePhone: null,
      notes: null,
      pager: null,
      primaryPhone: null,
      priority: null,
      relationship: null,
      state: null,
      syncEmployeeInfo: true,
      workExtension: null,
      workPhone: null,
      zip: null,
    },
  ],
  employeeId: null,
  ethnicity: null,
  federalTax: {
    amount: null,
    deductionsAmount: 0,
    dependentsAmount: 0,
    exemptions: null,
    filingStatus: null,
    higherRate: true,
    otherIncomeAmount: 0,
    percentage: null,
    taxCalculationCode: null,
    w4FormYear: 0,
  },
  gender: null,
  homeAddress: {
    address1: null,
    address2: null,
    city: null,
    country: null,
    county: null,
    emailAddress: null,
    mobilePhone: null,
    phone: null,
    postalCode: null,
    state: null,
  },
  isHighlyCompensated: true,
  isSmoker: true,
  localTax: [
    {
      exemptions: null,
      exemptions2: null,
      filingStatus: null,
      residentPSD: null,
      taxCode: null,
      workPSD: null,
    },
  ],
  mainDirectDeposit: {
    accountNumber: null,
    accountType: null,
    blockSpecial: null,
    isSkipPreNote: null,
    nameOnAccount: null,
    preNoteDate: null,
    routingNumber: null,
  },
  maritalStatus: null,
  middleName: null,
  nonPrimaryStateTax: {
    amount: null,
    deductionsAmount: 0,
    dependentsAmount: 0,
    exemptions: null,
    exemptions2: null,
    filingStatus: null,
    higherRate: true,
    otherIncomeAmount: 0,
    percentage: null,
    reciprocityCode: null,
    specialCheckCalc: null,
    taxCalculationCode: null,
    taxCode: null,
    w4FormYear: 0,
  },
  ownerPercent: null,
  preferredName: null,
  primaryPayRate: {
    annualSalary: null,
    baseRate: null,
    beginCheckDate: null,
    changeReason: null,
    defaultHours: null,
    effectiveDate: null,
    isAutoPay: null,
    payFrequency: null,
    payGrade: null,
    payRateNote: null,
    payType: null,
    ratePer: null,
    salary: null,
  },
  primaryStateTax: {
    amount: null,
    deductionsAmount: 0,
    dependentsAmount: 0,
    exemptions: null,
    exemptions2: null,
    filingStatus: null,
    higherRate: true,
    otherIncomeAmount: 0,
    percentage: null,
    specialCheckCalc: null,
    taxCalculationCode: null,
    taxCode: null,
    w4FormYear: 0,
  },
  priorLastName: null,
  salutation: null,
  ssn: null,
  status: {
    adjustedSeniorityDate: null,
    changeReason: null,
    effectiveDate: null,
    employeeStatus: null,
    hireDate: null,
    isEligibleForRehire: null,
    reHireDate: null,
    statusType: null,
    terminationDate: null,
  },
  suffix: null,
  taxSetup: {
    fitwExemptNotes: null,
    fitwExemptReason: null,
    futaExemptNotes: null,
    futaExemptReason: null,
    isEmployee943: true,
    isPension: true,
    isStatutory: true,
    medExemptNotes: null,
    medExemptReason: null,
    sitwExemptNotes: null,
    sitwExemptReason: null,
    ssExemptNotes: null,
    ssExemptReason: null,
    suiExemptNotes: null,
    suiExemptReason: null,
    suiState: null,
    taxDistributionCode1099R: null,
    taxForm: null,
  },
  veteranDescription: null,
  webTime: {
    badgeNumber: null,
    chargeRate: null,
    isTimeLaborEnabled: null,
  },
  workAddress: {
    address1: null,
    address2: null,
    city: null,
    country: null,
    county: null,
    emailAddress: null,
    location: null,
    mailStop: null,
    mobilePhone: null,
    pager: null,
    phone: null,
    phoneExtension: null,
    postalCode: null,
    state: null,
  },
  workEligibility: {
    alienOrAdmissionDocumentNumber: null,
    attestedDate: null,
    countryOfIssuance: null,
    foreignPassportNumber: null,
    i94AdmissionNumber: null,
    i9DateVerified: null,
    i9Notes: null,
    isI9Verified: null,
    isSsnVerified: null,
    ssnDateVerified: null,
    ssnNotes: null,
    visaType: null,
    workAuthorization: null,
    workUntil: null,
  },
};

export const earningInput = {
  agency: null,
  amount: null,
  annualMaximum: null,
  calculationCode: null,
  costCenter1: null,
  costCenter2: null,
  costCenter3: null,
  effectiveDate: null,
  endDate: null,
  frequency: null,
  goal: null,
  hoursOrUnits: null,
  isSelfInsured: null,
  jobCode: null,
  miscellaneousInfo: null,
  paidTowardsGoal: null,
  payPeriodMaximum: null,
  payPeriodMinimum: null,
  rate: null,
  rateCode: null,
};

export const sensitiveDataPayload = {
  disability: {
    disability: null,
    disabilityClassifications: [
      {
        classification: null,
      },
    ],
    hasDisability: null,
  },
  ethnicity: {
    ethnicity: null,
    ethnicRacialIdentities: [
      {
        description: null,
      },
    ],
  },
  gender: {
    displayPronouns: null,
    genderIdentityDescription: null,
    identifyAsLegalGender: null,
    legalGender: null,
    pronouns: null,
    sexualOrientation: null,
  },
  veteran: {
    isVeteran: null,
    veteran: null,
  },
};

export const payEntryInputPayload = {
  AutoAcknowledge: false,
  Batch: {
    BatchName: "string",
    MergeBatchId: 123,
  },
  Calendar: {
    CalendarId: 123,
    PayPeriodBeginDate: "2021-01-01",
    PayPeriodEndDate: "2021-01-01",
    CheckDate: "2021-01-01",
  },
};
