export const LIMIT_MIN = 10;

export const LIMIT_MAX = 100;

export const TIMEZONE_MODEL = [
  { value: "Africa/Abidjan", label: "Africa/Abidjan" },
  { value: "Africa/Accra", label: "Africa/Accra" },
  { value: "Africa/Addis_Ababa", label: "Africa/Addis_Ababa" },
  { value: "Africa/Algiers", label: "Africa/Algiers" },
  { value: "Africa/Asmara", label: "Africa/Asmara" },
  { value: "Africa/Asmera", label: "Africa/Asmera" },
  { value: "Africa/Bamako", label: "Africa/Bamako" },
  { value: "Africa/Bangui", label: "Africa/Bangui" },
  { value: "Africa/Banjul", label: "Africa/Banjul" },
  { value: "Africa/Bissau", label: "Africa/Bissau" },
  { value: "Africa/Blantyre", label: "Africa/Blantyre" },
  { value: "Africa/Brazzaville", label: "Africa/Brazzaville" },
  { value: "Africa/Bujumbura", label: "Africa/Bujumbura" },
  { value: "Africa/Cairo", label: "Africa/Cairo" },
  { value: "Africa/Casablanca", label: "Africa/Casablanca" },
  { value: "Africa/Ceuta", label: "Africa/Ceuta" },
  { value: "Africa/Conakry", label: "Africa/Conakry" },
  { value: "Africa/Dakar", label: "Africa/Dakar" },
  { value: "Africa/Dar_es_Salaam", label: "Africa/Dar_es_Salaam" },
  { value: "Africa/Djibouti", label: "Africa/Djibouti" },
  { value: "Africa/Douala", label: "Africa/Douala" },
  { value: "Africa/El_Aaiun", label: "Africa/El_Aaiun" },
  { value: "Africa/Freetown", label: "Africa/Freetown" },
  { value: "Africa/Gaborone", label: "Africa/Gaborone" },
  { value: "Africa/Harare", label: "Africa/Harare" },
  { value: "Africa/Johannesburg", label: "Africa/Johannesburg" },
  { value: "Africa/Juba", label: "Africa/Juba" },
  { value: "Africa/Kampala", label: "Africa/Kampala" },
  { value: "Africa/Khartoum", label: "Africa/Khartoum" },
  { value: "Africa/Kigali", label: "Africa/Kigali" },
  { value: "Africa/Kinshasa", label: "Africa/Kinshasa" },
  { value: "Africa/Lagos", label: "Africa/Lagos" },
  { value: "Africa/Libreville", label: "Africa/Libreville" },
  { value: "Africa/Lome", label: "Africa/Lome" },
  { value: "Africa/Luanda", label: "Africa/Luanda" },
  { value: "Africa/Lubumbashi", label: "Africa/Lubumbashi" },
  { value: "Africa/Lusaka", label: "Africa/Lusaka" },
  { value: "Africa/Malabo", label: "Africa/Malabo" },
  { value: "Africa/Maputo", label: "Africa/Maputo" },
  { value: "Africa/Maseru", label: "Africa/Maseru" },
  { value: "Africa/Mbabane", label: "Africa/Mbabane" },
  { value: "Africa/Mogadishu", label: "Africa/Mogadishu" },
  { value: "Africa/Monrovia", label: "Africa/Monrovia" },
  { value: "Africa/Nairobi", label: "Africa/Nairobi" },
  { value: "Africa/Ndjamena", label: "Africa/Ndjamena" },
  { value: "Africa/Niamey", label: "Africa/Niamey" },
  { value: "Africa/Nouakchott", label: "Africa/Nouakchott" },
  { value: "Africa/Ouagadougou", label: "Africa/Ouagadougou" },
  { value: "Africa/Porto-Novo", label: "Africa/Porto-Novo" },
  { value: "Africa/Sao_Tome", label: "Africa/Sao_Tome" },
  { value: "Africa/Timbuktu", label: "Africa/Timbuktu" },
  { value: "Africa/Tripoli", label: "Africa/Tripoli" },
  { value: "Africa/Tunis", label: "Africa/Tunis" },
  { value: "Africa/Windhoek", label: "Africa/Windhoek" },
  { value: "America/Adak", label: "America/Adak" },
  { value: "America/Anchorage", label: "America/Anchorage" },
  { value: "America/Anguilla", label: "America/Anguilla" },
  { value: "America/Antigua", label: "America/Antigua" },
  { value: "America/Araguaina", label: "America/Araguaina" },
  {
    value: "America/Argentina/Buenos_Aires",
    label: "America/Argentina/Buenos_Aires",
  },
  {
    value: "America/Argentina/Catamarca",
    label: "America/Argentina/Catamarca",
  },
  {
    value: "America/Argentina/ComodRivadavia",
    label: "America/Argentina/ComodRivadavia",
  },
  { value: "America/Argentina/Cordoba", label: "America/Argentina/Cordoba" },
  { value: "America/Argentina/Jujuy", label: "America/Argentina/Jujuy" },
  { value: "America/Argentina/La_Rioja", label: "America/Argentina/La_Rioja" },
  { value: "America/Argentina/Mendoza", label: "America/Argentina/Mendoza" },
  {
    value: "America/Argentina/Rio_Gallegos",
    label: "America/Argentina/Rio_Gallegos",
  },
  { value: "America/Argentina/Salta", label: "America/Argentina/Salta" },
  { value: "America/Argentina/San_Juan", label: "America/Argentina/San_Juan" },
  { value: "America/Argentina/San_Luis", label: "America/Argentina/San_Luis" },
  { value: "America/Argentina/Tucuman", label: "America/Argentina/Tucuman" },
  { value: "America/Argentina/Ushuaia", label: "America/Argentina/Ushuaia" },
  { value: "America/Aruba", label: "America/Aruba" },
  { value: "America/Asuncion", label: "America/Asuncion" },
  { value: "America/Atikokan", label: "America/Atikokan" },
  { value: "America/Atka", label: "America/Atka" },
  { value: "America/Bahia", label: "America/Bahia" },
  { value: "America/Bahia_Banderas", label: "America/Bahia_Banderas" },
  { value: "America/Barbados", label: "America/Barbados" },
  { value: "America/Belem", label: "America/Belem" },
  { value: "America/Belize", label: "America/Belize" },
  { value: "America/Blanc-Sablon", label: "America/Blanc-Sablon" },
  { value: "America/Boa_Vista", label: "America/Boa_Vista" },
  { value: "America/Bogota", label: "America/Bogota" },
  { value: "America/Boise", label: "America/Boise" },
  { value: "America/Buenos_Aires", label: "America/Buenos_Aires" },
  { value: "America/Cambridge_Bay", label: "America/Cambridge_Bay" },
  { value: "America/Campo_Grande", label: "America/Campo_Grande" },
  { value: "America/Cancun", label: "America/Cancun" },
  { value: "America/Caracas", label: "America/Caracas" },
  { value: "America/Catamarca", label: "America/Catamarca" },
  { value: "America/Cayenne", label: "America/Cayenne" },
  { value: "America/Cayman", label: "America/Cayman" },
  { value: "America/Chicago", label: "America/Chicago" },
  { value: "America/Chihuahua", label: "America/Chihuahua" },
  { value: "America/Coral_Harbour", label: "America/Coral_Harbour" },
  { value: "America/Cordoba", label: "America/Cordoba" },
  { value: "America/Costa_Rica", label: "America/Costa_Rica" },
  { value: "America/Creston", label: "America/Creston" },
  { value: "America/Cuiaba", label: "America/Cuiaba" },
  { value: "America/Curacao", label: "America/Curacao" },
  { value: "America/Danmarkshavn", label: "America/Danmarkshavn" },
  { value: "America/Dawson", label: "America/Dawson" },
  { value: "America/Dawson_Creek", label: "America/Dawson_Creek" },
  { value: "America/Denver", label: "America/Denver" },
  { value: "America/Detroit", label: "America/Detroit" },
  { value: "America/Dominica", label: "America/Dominica" },
  { value: "America/Edmonton", label: "America/Edmonton" },
  { value: "America/Eirunepe", label: "America/Eirunepe" },
  { value: "America/El_Salvador", label: "America/El_Salvador" },
  { value: "America/Ensenada", label: "America/Ensenada" },
  { value: "America/Fort_Nelson", label: "America/Fort_Nelson" },
  { value: "America/Fort_Wayne", label: "America/Fort_Wayne" },
  { value: "America/Fortaleza", label: "America/Fortaleza" },
  { value: "America/Glace_Bay", label: "America/Glace_Bay" },
  { value: "America/Godthab", label: "America/Godthab" },
  { value: "America/Goose_Bay", label: "America/Goose_Bay" },
  { value: "America/Grand_Turk", label: "America/Grand_Turk" },
  { value: "America/Grenada", label: "America/Grenada" },
  { value: "America/Guadeloupe", label: "America/Guadeloupe" },
  { value: "America/Guatemala", label: "America/Guatemala" },
  { value: "America/Guayaquil", label: "America/Guayaquil" },
  { value: "America/Guyana", label: "America/Guyana" },
  { value: "America/Halifax", label: "America/Halifax" },
  { value: "America/Havana", label: "America/Havana" },
  { value: "America/Hermosillo", label: "America/Hermosillo" },
  {
    value: "America/Indiana/Indianapolis",
    label: "America/Indiana/Indianapolis",
  },
  { value: "America/Indiana/Knox", label: "America/Indiana/Knox" },
  { value: "America/Indiana/Marengo", label: "America/Indiana/Marengo" },
  { value: "America/Indiana/Petersburg", label: "America/Indiana/Petersburg" },
  { value: "America/Indiana/Tell_City", label: "America/Indiana/Tell_City" },
  { value: "America/Indiana/Vevay", label: "America/Indiana/Vevay" },
  { value: "America/Indiana/Vincennes", label: "America/Indiana/Vincennes" },
  { value: "America/Indiana/Winamac", label: "America/Indiana/Winamac" },
  { value: "America/Indianapolis", label: "America/Indianapolis" },
  { value: "America/Inuvik", label: "America/Inuvik" },
  { value: "America/Iqaluit", label: "America/Iqaluit" },
  { value: "America/Jamaica", label: "America/Jamaica" },
  { value: "America/Jujuy", label: "America/Jujuy" },
  { value: "America/Juneau", label: "America/Juneau" },
  {
    value: "America/Kentucky/Louisville",
    label: "America/Kentucky/Louisville",
  },
  {
    value: "America/Kentucky/Monticello",
    label: "America/Kentucky/Monticello",
  },
  { value: "America/Knox_IN", label: "America/Knox_IN" },
  { value: "America/Kralendijk", label: "America/Kralendijk" },
  { value: "America/La_Paz", label: "America/La_Paz" },
  { value: "America/Lima", label: "America/Lima" },
  { value: "America/Los_Angeles", label: "America/Los_Angeles" },
  { value: "America/Louisville", label: "America/Louisville" },
  { value: "America/Lower_Princes", label: "America/Lower_Princes" },
  { value: "America/Maceio", label: "America/Maceio" },
  { value: "America/Managua", label: "America/Managua" },
  { value: "America/Manaus", label: "America/Manaus" },
  { value: "America/Marigot", label: "America/Marigot" },
  { value: "America/Martinique", label: "America/Martinique" },
  { value: "America/Matamoros", label: "America/Matamoros" },
  { value: "America/Mazatlan", label: "America/Mazatlan" },
  { value: "America/Mendoza", label: "America/Mendoza" },
  { value: "America/Menominee", label: "America/Menominee" },
  { value: "America/Merida", label: "America/Merida" },
  { value: "America/Metlakatla", label: "America/Metlakatla" },
  { value: "America/Mexico_City", label: "America/Mexico_City" },
  { value: "America/Miquelon", label: "America/Miquelon" },
  { value: "America/Moncton", label: "America/Moncton" },
  { value: "America/Monterrey", label: "America/Monterrey" },
  { value: "America/Montevideo", label: "America/Montevideo" },
  { value: "America/Montreal", label: "America/Montreal" },
  { value: "America/Montserrat", label: "America/Montserrat" },
  { value: "America/Nassau", label: "America/Nassau" },
  { value: "America/New_York", label: "America/New_York" },
  { value: "America/Nipigon", label: "America/Nipigon" },
  { value: "America/Nome", label: "America/Nome" },
  { value: "America/Noronha", label: "America/Noronha" },
  {
    value: "America/North_Dakota/Beulah",
    label: "America/North_Dakota/Beulah",
  },
  {
    value: "America/North_Dakota/Center",
    label: "America/North_Dakota/Center",
  },
  {
    value: "America/North_Dakota/New_Salem",
    label: "America/North_Dakota/New_Salem",
  },
  { value: "America/Nuuk", label: "America/Nuuk" },
  { value: "America/Ojinaga", label: "America/Ojinaga" },
  { value: "America/Panama", label: "America/Panama" },
  { value: "America/Pangnirtung", label: "America/Pangnirtung" },
  { value: "America/Paramaribo", label: "America/Paramaribo" },
  { value: "America/Phoenix", label: "America/Phoenix" },
  { value: "America/Port-au-Prince", label: "America/Port-au-Prince" },
  { value: "America/Port_of_Spain", label: "America/Port_of_Spain" },
  { value: "America/Porto_Acre", label: "America/Porto_Acre" },
  { value: "America/Porto_Velho", label: "America/Porto_Velho" },
  { value: "America/Puerto_Rico", label: "America/Puerto_Rico" },
  { value: "America/Punta_Arenas", label: "America/Punta_Arenas" },
  { value: "America/Rainy_River", label: "America/Rainy_River" },
  { value: "America/Rankin_Inlet", label: "America/Rankin_Inlet" },
  { value: "America/Recife", label: "America/Recife" },
  { value: "America/Regina", label: "America/Regina" },
  { value: "America/Resolute", label: "America/Resolute" },
  { value: "America/Rio_Branco", label: "America/Rio_Branco" },
  { value: "America/Rosario", label: "America/Rosario" },
  { value: "America/Santa_Isabel", label: "America/Santa_Isabel" },
  { value: "America/Santarem", label: "America/Santarem" },
  { value: "America/Santiago", label: "America/Santiago" },
  { value: "America/Santo_Domingo", label: "America/Santo_Domingo" },
  { value: "America/Sao_Paulo", label: "America/Sao_Paulo" },
  { value: "America/Scoresbysund", label: "America/Scoresbysund" },
  { value: "America/Shiprock", label: "America/Shiprock" },
  { value: "America/Sitka", label: "America/Sitka" },
  { value: "America/St_Barthelemy", label: "America/St_Barthelemy" },
  { value: "America/St_Johns", label: "America/St_Johns" },
  { value: "America/St_Kitts", label: "America/St_Kitts" },
  { value: "America/St_Lucia", label: "America/St_Lucia" },
  { value: "America/St_Thomas", label: "America/St_Thomas" },
  { value: "America/St_Vincent", label: "America/St_Vincent" },
  { value: "America/Swift_Current", label: "America/Swift_Current" },
  { value: "America/Tegucigalpa", label: "America/Tegucigalpa" },
  { value: "America/Thule", label: "America/Thule" },
  { value: "America/Thunder_Bay", label: "America/Thunder_Bay" },
  { value: "America/Tijuana", label: "America/Tijuana" },
  { value: "America/Toronto", label: "America/Toronto" },
  { value: "America/Tortola", label: "America/Tortola" },
  { value: "America/Vancouver", label: "America/Vancouver" },
  { value: "America/Virgin", label: "America/Virgin" },
  { value: "America/Whitehorse", label: "America/Whitehorse" },
  { value: "America/Winnipeg", label: "America/Winnipeg" },
  { value: "America/Yakutat", label: "America/Yakutat" },
  { value: "America/Yellowknife", label: "America/Yellowknife" },
  { value: "Antarctica/Casey", label: "Antarctica/Casey" },
  { value: "Antarctica/Davis", label: "Antarctica/Davis" },
  { value: "Antarctica/DumontDUrville", label: "Antarctica/DumontDUrville" },
  { value: "Antarctica/Macquarie", label: "Antarctica/Macquarie" },
  { value: "Antarctica/Mawson", label: "Antarctica/Mawson" },
  { value: "Antarctica/McMurdo", label: "Antarctica/McMurdo" },
  { value: "Antarctica/Palmer", label: "Antarctica/Palmer" },
  { value: "Antarctica/Rothera", label: "Antarctica/Rothera" },
  { value: "Antarctica/South_Pole", label: "Antarctica/South_Pole" },
  { value: "Antarctica/Syowa", label: "Antarctica/Syowa" },
  { value: "Antarctica/Troll", label: "Antarctica/Troll" },
  { value: "Antarctica/Vostok", label: "Antarctica/Vostok" },
  { value: "Arctic/Longyearbyen", label: "Arctic/Longyearbyen" },
  { value: "Asia/Aden", label: "Asia/Aden" },
  { value: "Asia/Almaty", label: "Asia/Almaty" },
  { value: "Asia/Amman", label: "Asia/Amman" },
  { value: "Asia/Anadyr", label: "Asia/Anadyr" },
  { value: "Asia/Aqtau", label: "Asia/Aqtau" },
  { value: "Asia/Aqtobe", label: "Asia/Aqtobe" },
  { value: "Asia/Ashgabat", label: "Asia/Ashgabat" },
  { value: "Asia/Ashkhabad", label: "Asia/Ashkhabad" },
  { value: "Asia/Atyrau", label: "Asia/Atyrau" },
  { value: "Asia/Baghdad", label: "Asia/Baghdad" },
  { value: "Asia/Bahrain", label: "Asia/Bahrain" },
  { value: "Asia/Baku", label: "Asia/Baku" },
  { value: "Asia/Bangkok", label: "Asia/Bangkok" },
  { value: "Asia/Barnaul", label: "Asia/Barnaul" },
  { value: "Asia/Beirut", label: "Asia/Beirut" },
  { value: "Asia/Bishkek", label: "Asia/Bishkek" },
  { value: "Asia/Brunei", label: "Asia/Brunei" },
  { value: "Asia/Calcutta", label: "Asia/Calcutta" },
  { value: "Asia/Chita", label: "Asia/Chita" },
  { value: "Asia/Choibalsan", label: "Asia/Choibalsan" },
  { value: "Asia/Chongqing", label: "Asia/Chongqing" },
  { value: "Asia/Chungking", label: "Asia/Chungking" },
  { value: "Asia/Colombo", label: "Asia/Colombo" },
  { value: "Asia/Dacca", label: "Asia/Dacca" },
  { value: "Asia/Damascus", label: "Asia/Damascus" },
  { value: "Asia/Dhaka", label: "Asia/Dhaka" },
  { value: "Asia/Dili", label: "Asia/Dili" },
  { value: "Asia/Dubai", label: "Asia/Dubai" },
  { value: "Asia/Dushanbe", label: "Asia/Dushanbe" },
  { value: "Asia/Famagusta", label: "Asia/Famagusta" },
  { value: "Asia/Gaza", label: "Asia/Gaza" },
  { value: "Asia/Harbin", label: "Asia/Harbin" },
  { value: "Asia/Hebron", label: "Asia/Hebron" },
  { value: "Asia/Ho_Chi_Minh", label: "Asia/Ho_Chi_Minh" },
  { value: "Asia/Hong_Kong", label: "Asia/Hong_Kong" },
  { value: "Asia/Hovd", label: "Asia/Hovd" },
  { value: "Asia/Irkutsk", label: "Asia/Irkutsk" },
  { value: "Asia/Istanbul", label: "Asia/Istanbul" },
  { value: "Asia/Jakarta", label: "Asia/Jakarta" },
  { value: "Asia/Jayapura", label: "Asia/Jayapura" },
  { value: "Asia/Jerusalem", label: "Asia/Jerusalem" },
  { value: "Asia/Kabul", label: "Asia/Kabul" },
  { value: "Asia/Kamchatka", label: "Asia/Kamchatka" },
  { value: "Asia/Karachi", label: "Asia/Karachi" },
  { value: "Asia/Kashgar", label: "Asia/Kashgar" },
  { value: "Asia/Kathmandu", label: "Asia/Kathmandu" },
  { value: "Asia/Katmandu", label: "Asia/Katmandu" },
  { value: "Asia/Khandyga", label: "Asia/Khandyga" },
  { value: "Asia/Kolkata", label: "Asia/Kolkata" },
  { value: "Asia/Krasnoyarsk", label: "Asia/Krasnoyarsk" },
  { value: "Asia/Kuala_Lumpur", label: "Asia/Kuala_Lumpur" },
  { value: "Asia/Kuching", label: "Asia/Kuching" },
  { value: "Asia/Kuwait", label: "Asia/Kuwait" },
  { value: "Asia/Macao", label: "Asia/Macao" },
  { value: "Asia/Macau", label: "Asia/Macau" },
  { value: "Asia/Magadan", label: "Asia/Magadan" },
  { value: "Asia/Makassar", label: "Asia/Makassar" },
  { value: "Asia/Manila", label: "Asia/Manila" },
  { value: "Asia/Muscat", label: "Asia/Muscat" },
  { value: "Asia/Nicosia", label: "Asia/Nicosia" },
  { value: "Asia/Novokuznetsk", label: "Asia/Novokuznetsk" },
  { value: "Asia/Novosibirsk", label: "Asia/Novosibirsk" },
  { value: "Asia/Omsk", label: "Asia/Omsk" },
  { value: "Asia/Oral", label: "Asia/Oral" },
  { value: "Asia/Phnom_Penh", label: "Asia/Phnom_Penh" },
  { value: "Asia/Pontianak", label: "Asia/Pontianak" },
  { value: "Asia/Pyongyang", label: "Asia/Pyongyang" },
  { value: "Asia/Qatar", label: "Asia/Qatar" },
  { value: "Asia/Qostanay", label: "Asia/Qostanay" },
  { value: "Asia/Qyzylorda", label: "Asia/Qyzylorda" },
  { value: "Asia/Rangoon", label: "Asia/Rangoon" },
  { value: "Asia/Riyadh", label: "Asia/Riyadh" },
  { value: "Asia/Saigon", label: "Asia/Saigon" },
  { value: "Asia/Sakhalin", label: "Asia/Sakhalin" },
  { value: "Asia/Samarkand", label: "Asia/Samarkand" },
  { value: "Asia/Seoul", label: "Asia/Seoul" },
  { value: "Asia/Shanghai", label: "Asia/Shanghai" },
  { value: "Asia/Singapore", label: "Asia/Singapore" },
  { value: "Asia/Srednekolymsk", label: "Asia/Srednekolymsk" },
  { value: "Asia/Taipei", label: "Asia/Taipei" },
  { value: "Asia/Tashkent", label: "Asia/Tashkent" },
  { value: "Asia/Tbilisi", label: "Asia/Tbilisi" },
  { value: "Asia/Tehran", label: "Asia/Tehran" },
  { value: "Asia/Tel_Aviv", label: "Asia/Tel_Aviv" },
  { value: "Asia/Thimbu", label: "Asia/Thimbu" },
  { value: "Asia/Thimphu", label: "Asia/Thimphu" },
  { value: "Asia/Tokyo", label: "Asia/Tokyo" },
  { value: "Asia/Tomsk", label: "Asia/Tomsk" },
  { value: "Asia/Ujung_Pandang", label: "Asia/Ujung_Pandang" },
  { value: "Asia/Ulaanbaatar", label: "Asia/Ulaanbaatar" },
  { value: "Asia/Ulan_Bator", label: "Asia/Ulan_Bator" },
  { value: "Asia/Urumqi", label: "Asia/Urumqi" },
  { value: "Asia/Ust-Nera", label: "Asia/Ust-Nera" },
  { value: "Asia/Vientiane", label: "Asia/Vientiane" },
  { value: "Asia/Vladivostok", label: "Asia/Vladivostok" },
  { value: "Asia/Yakutsk", label: "Asia/Yakutsk" },
  { value: "Asia/Yangon", label: "Asia/Yangon" },
  { value: "Asia/Yekaterinburg", label: "Asia/Yekaterinburg" },
  { value: "Asia/Yerevan", label: "Asia/Yerevan" },
  { value: "Atlantic/Azores", label: "Atlantic/Azores" },
  { value: "Atlantic/Bermuda", label: "Atlantic/Bermuda" },
  { value: "Atlantic/Canary", label: "Atlantic/Canary" },
  { value: "Atlantic/Cape_Verde", label: "Atlantic/Cape_Verde" },
  { value: "Atlantic/Faeroe", label: "Atlantic/Faeroe" },
  { value: "Atlantic/Faroe", label: "Atlantic/Faroe" },
  { value: "Atlantic/Jan_Mayen", label: "Atlantic/Jan_Mayen" },
  { value: "Atlantic/Madeira", label: "Atlantic/Madeira" },
  { value: "Atlantic/Reykjavik", label: "Atlantic/Reykjavik" },
  { value: "Atlantic/South_Georgia", label: "Atlantic/South_Georgia" },
  { value: "Atlantic/St_Helena", label: "Atlantic/St_Helena" },
  { value: "Atlantic/Stanley", label: "Atlantic/Stanley" },
  { value: "Australia/ACT", label: "Australia/ACT" },
  { value: "Australia/Adelaide", label: "Australia/Adelaide" },
  { value: "Australia/Brisbane", label: "Australia/Brisbane" },
  { value: "Australia/Broken_Hill", label: "Australia/Broken_Hill" },
  { value: "Australia/Canberra", label: "Australia/Canberra" },
  { value: "Australia/Currie", label: "Australia/Currie" },
  { value: "Australia/Darwin", label: "Australia/Darwin" },
  { value: "Australia/Eucla", label: "Australia/Eucla" },
  { value: "Australia/Hobart", label: "Australia/Hobart" },
  { value: "Australia/LHI", label: "Australia/LHI" },
  { value: "Australia/Lindeman", label: "Australia/Lindeman" },
  { value: "Australia/Lord_Howe", label: "Australia/Lord_Howe" },
  { value: "Australia/Melbourne", label: "Australia/Melbourne" },
  { value: "Australia/NSW", label: "Australia/NSW" },
  { value: "Australia/North", label: "Australia/North" },
  { value: "Australia/Perth", label: "Australia/Perth" },
  { value: "Australia/Queensland", label: "Australia/Queensland" },
  { value: "Australia/South", label: "Australia/South" },
  { value: "Australia/Sydney", label: "Australia/Sydney" },
  { value: "Australia/Tasmania", label: "Australia/Tasmania" },
  { value: "Australia/Victoria", label: "Australia/Victoria" },
  { value: "Australia/West", label: "Australia/West" },
  { value: "Australia/Yancowinna", label: "Australia/Yancowinna" },
  { value: "Brazil/Acre", label: "Brazil/Acre" },
  { value: "Brazil/DeNoronha", label: "Brazil/DeNoronha" },
  { value: "Brazil/East", label: "Brazil/East" },
  { value: "Brazil/West", label: "Brazil/West" },
  { value: "CET", label: "CET" },
  { value: "CST6CDT", label: "CST6CDT" },
  { value: "Canada/Atlantic", label: "Canada/Atlantic" },
  { value: "Canada/Central", label: "Canada/Central" },
  { value: "Canada/Eastern", label: "Canada/Eastern" },
  { value: "Canada/Mountain", label: "Canada/Mountain" },
  { value: "Canada/Newfoundland", label: "Canada/Newfoundland" },
  { value: "Canada/Pacific", label: "Canada/Pacific" },
  { value: "Canada/Saskatchewan", label: "Canada/Saskatchewan" },
  { value: "Canada/Yukon", label: "Canada/Yukon" },
  { value: "Chile/Continental", label: "Chile/Continental" },
  { value: "Chile/EasterIsland", label: "Chile/EasterIsland" },
  { value: "Cuba", label: "Cuba" },
  { value: "EET", label: "EET" },
  { value: "EST", label: "EST" },
  { value: "EST5EDT", label: "EST5EDT" },
  { value: "Egypt", label: "Egypt" },
  { value: "Eire", label: "Eire" },
  { value: "Etc/GMT", label: "Etc/GMT" },
  { value: "Etc/GMT+0", label: "Etc/GMT+0" },
  { value: "Etc/GMT+1", label: "Etc/GMT+1" },
  { value: "Etc/GMT+10", label: "Etc/GMT+10" },
  { value: "Etc/GMT+11", label: "Etc/GMT+11" },
  { value: "Etc/GMT+12", label: "Etc/GMT+12" },
  { value: "Etc/GMT+2", label: "Etc/GMT+2" },
  { value: "Etc/GMT+3", label: "Etc/GMT+3" },
  { value: "Etc/GMT+4", label: "Etc/GMT+4" },
  { value: "Etc/GMT+5", label: "Etc/GMT+5" },
  { value: "Etc/GMT+6", label: "Etc/GMT+6" },
  { value: "Etc/GMT+7", label: "Etc/GMT+7" },
  { value: "Etc/GMT+8", label: "Etc/GMT+8" },
  { value: "Etc/GMT+9", label: "Etc/GMT+9" },
  { value: "Etc/GMT-0", label: "Etc/GMT-0" },
  { value: "Etc/GMT-1", label: "Etc/GMT-1" },
  { value: "Etc/GMT-10", label: "Etc/GMT-10" },
  { value: "Etc/GMT-11", label: "Etc/GMT-11" },
  { value: "Etc/GMT-12", label: "Etc/GMT-12" },
  { value: "Etc/GMT-13", label: "Etc/GMT-13" },
  { value: "Etc/GMT-14", label: "Etc/GMT-14" },
  { value: "Etc/GMT-2", label: "Etc/GMT-2" },
  { value: "Etc/GMT-3", label: "Etc/GMT-3" },
  { value: "Etc/GMT-4", label: "Etc/GMT-4" },
  { value: "Etc/GMT-5", label: "Etc/GMT-5" },
  { value: "Etc/GMT-6", label: "Etc/GMT-6" },
  { value: "Etc/GMT-7", label: "Etc/GMT-7" },
  { value: "Etc/GMT-8", label: "Etc/GMT-8" },
  { value: "Etc/GMT-9", label: "Etc/GMT-9" },
  { value: "Etc/GMT0", label: "Etc/GMT0" },
  { value: "Etc/Greenwich", label: "Etc/Greenwich" },
  { value: "Etc/UCT", label: "Etc/UCT" },
  { value: "Etc/UTC", label: "Etc/UTC" },
  { value: "Etc/Universal", label: "Etc/Universal" },
  { value: "Etc/Zulu", label: "Etc/Zulu" },
  { value: "Europe/Amsterdam", label: "Europe/Amsterdam" },
  { value: "Europe/Andorra", label: "Europe/Andorra" },
  { value: "Europe/Astrakhan", label: "Europe/Astrakhan" },
  { value: "Europe/Athens", label: "Europe/Athens" },
  { value: "Europe/Belfast", label: "Europe/Belfast" },
  { value: "Europe/Belgrade", label: "Europe/Belgrade" },
  { value: "Europe/Berlin", label: "Europe/Berlin" },
  { value: "Europe/Bratislava", label: "Europe/Bratislava" },
  { value: "Europe/Brussels", label: "Europe/Brussels" },
  { value: "Europe/Bucharest", label: "Europe/Bucharest" },
  { value: "Europe/Budapest", label: "Europe/Budapest" },
  { value: "Europe/Busingen", label: "Europe/Busingen" },
  { value: "Europe/Chisinau", label: "Europe/Chisinau" },
  { value: "Europe/Copenhagen", label: "Europe/Copenhagen" },
  { value: "Europe/Dublin", label: "Europe/Dublin" },
  { value: "Europe/Gibraltar", label: "Europe/Gibraltar" },
  { value: "Europe/Guernsey", label: "Europe/Guernsey" },
  { value: "Europe/Helsinki", label: "Europe/Helsinki" },
  { value: "Europe/Isle_of_Man", label: "Europe/Isle_of_Man" },
  { value: "Europe/Istanbul", label: "Europe/Istanbul" },
  { value: "Europe/Jersey", label: "Europe/Jersey" },
  { value: "Europe/Kaliningrad", label: "Europe/Kaliningrad" },
  { value: "Europe/Kiev", label: "Europe/Kiev" },
  { value: "Europe/Kirov", label: "Europe/Kirov" },
  { value: "Europe/Kyiv", label: "Europe/Kyiv" },
  { value: "Europe/Lisbon", label: "Europe/Lisbon" },
  { value: "Europe/Ljubljana", label: "Europe/Ljubljana" },
  { value: "Europe/London", label: "Europe/London" },
  { value: "Europe/Luxembourg", label: "Europe/Luxembourg" },
  { value: "Europe/Madrid", label: "Europe/Madrid" },
  { value: "Europe/Malta", label: "Europe/Malta" },
  { value: "Europe/Mariehamn", label: "Europe/Mariehamn" },
  { value: "Europe/Minsk", label: "Europe/Minsk" },
  { value: "Europe/Monaco", label: "Europe/Monaco" },
  { value: "Europe/Moscow", label: "Europe/Moscow" },
  { value: "Europe/Nicosia", label: "Europe/Nicosia" },
  { value: "Europe/Oslo", label: "Europe/Oslo" },
  { value: "Europe/Paris", label: "Europe/Paris" },
  { value: "Europe/Podgorica", label: "Europe/Podgorica" },
  { value: "Europe/Prague", label: "Europe/Prague" },
  { value: "Europe/Riga", label: "Europe/Riga" },
  { value: "Europe/Rome", label: "Europe/Rome" },
  { value: "Europe/Samara", label: "Europe/Samara" },
  { value: "Europe/San_Marino", label: "Europe/San_Marino" },
  { value: "Europe/Sarajevo", label: "Europe/Sarajevo" },
  { value: "Europe/Saratov", label: "Europe/Saratov" },
  { value: "Europe/Simferopol", label: "Europe/Simferopol" },
  { value: "Europe/Skopje", label: "Europe/Skopje" },
  { value: "Europe/Sofia", label: "Europe/Sofia" },
  { value: "Europe/Stockholm", label: "Europe/Stockholm" },
  { value: "Europe/Tallinn", label: "Europe/Tallinn" },
  { value: "Europe/Tirane", label: "Europe/Tirane" },
  { value: "Europe/Tiraspol", label: "Europe/Tiraspol" },
  { value: "Europe/Ulyanovsk", label: "Europe/Ulyanovsk" },
  { value: "Europe/Uzhgorod", label: "Europe/Uzhgorod" },
  { value: "Europe/Vaduz", label: "Europe/Vaduz" },
  { value: "Europe/Vatican", label: "Europe/Vatican" },
  { value: "Europe/Vienna", label: "Europe/Vienna" },
  { value: "Europe/Vilnius", label: "Europe/Vilnius" },
  { value: "Europe/Volgograd", label: "Europe/Volgograd" },
  { value: "Europe/Warsaw", label: "Europe/Warsaw" },
  { value: "Europe/Zagreb", label: "Europe/Zagreb" },
  { value: "Europe/Zaporozhye", label: "Europe/Zaporozhye" },
  { value: "Europe/Zurich", label: "Europe/Zurich" },
  { value: "GB", label: "GB" },
  { value: "GB-Eire", label: "GB-Eire" },
  { value: "GMT", label: "GMT" },
  { value: "GMT+0", label: "GMT+0" },
  { value: "GMT-0", label: "GMT-0" },
  { value: "GMT0", label: "GMT0" },
  { value: "Greenwich", label: "Greenwich" },
  { value: "HST", label: "HST" },
  { value: "Hongkong", label: "Hongkong" },
  { value: "Iceland", label: "Iceland" },
  { value: "Indian/Antananarivo", label: "Indian/Antananarivo" },
  { value: "Indian/Chagos", label: "Indian/Chagos" },
  { value: "Indian/Christmas", label: "Indian/Christmas" },
  { value: "Indian/Cocos", label: "Indian/Cocos" },
  { value: "Indian/Comoro", label: "Indian/Comoro" },
  { value: "Indian/Kerguelen", label: "Indian/Kerguelen" },
  { value: "Indian/Mahe", label: "Indian/Mahe" },
  { value: "Indian/Maldives", label: "Indian/Maldives" },
  { value: "Indian/Mauritius", label: "Indian/Mauritius" },
  { value: "Indian/Mayotte", label: "Indian/Mayotte" },
  { value: "Indian/Reunion", label: "Indian/Reunion" },
  { value: "Iran", label: "Iran" },
  { value: "Israel", label: "Israel" },
  { value: "Jamaica", label: "Jamaica" },
  { value: "Japan", label: "Japan" },
  { value: "Kwajalein", label: "Kwajalein" },
  { value: "Libya", label: "Libya" },
  { value: "MET", label: "MET" },
  { value: "MST", label: "MST" },
  { value: "MST7MDT", label: "MST7MDT" },
  { value: "Mexico/BajaNorte", label: "Mexico/BajaNorte" },
  { value: "Mexico/BajaSur", label: "Mexico/BajaSur" },
  { value: "Mexico/General", label: "Mexico/General" },
  { value: "NZ", label: "NZ" },
  { value: "NZ-CHAT", label: "NZ-CHAT" },
  { value: "Navajo", label: "Navajo" },
  { value: "PRC", label: "PRC" },
  { value: "PST8PDT", label: "PST8PDT" },
  { value: "Pacific/Apia", label: "Pacific/Apia" },
  { value: "Pacific/Auckland", label: "Pacific/Auckland" },
  { value: "Pacific/Bougainville", label: "Pacific/Bougainville" },
  { value: "Pacific/Chatham", label: "Pacific/Chatham" },
  { value: "Pacific/Chuuk", label: "Pacific/Chuuk" },
  { value: "Pacific/Easter", label: "Pacific/Easter" },
  { value: "Pacific/Efate", label: "Pacific/Efate" },
  { value: "Pacific/Enderbury", label: "Pacific/Enderbury" },
  { value: "Pacific/Fakaofo", label: "Pacific/Fakaofo" },
  { value: "Pacific/Fiji", label: "Pacific/Fiji" },
  { value: "Pacific/Funafuti", label: "Pacific/Funafuti" },
  { value: "Pacific/Galapagos", label: "Pacific/Galapagos" },
  { value: "Pacific/Gambier", label: "Pacific/Gambier" },
  { value: "Pacific/Guadalcanal", label: "Pacific/Guadalcanal" },
  { value: "Pacific/Guam", label: "Pacific/Guam" },
  { value: "Pacific/Honolulu", label: "Pacific/Honolulu" },
  { value: "Pacific/Johnston", label: "Pacific/Johnston" },
  { value: "Pacific/Kanton", label: "Pacific/Kanton" },
  { value: "Pacific/Kiritimati", label: "Pacific/Kiritimati" },
  { value: "Pacific/Kosrae", label: "Pacific/Kosrae" },
  { value: "Pacific/Kwajalein", label: "Pacific/Kwajalein" },
  { value: "Pacific/Majuro", label: "Pacific/Majuro" },
  { value: "Pacific/Marquesas", label: "Pacific/Marquesas" },
  { value: "Pacific/Midway", label: "Pacific/Midway" },
  { value: "Pacific/Nauru", label: "Pacific/Nauru" },
  { value: "Pacific/Niue", label: "Pacific/Niue" },
  { value: "Pacific/Norfolk", label: "Pacific/Norfolk" },
  { value: "Pacific/Noumea", label: "Pacific/Noumea" },
  { value: "Pacific/Pago_Pago", label: "Pacific/Pago_Pago" },
  { value: "Pacific/Palau", label: "Pacific/Palau" },
  { value: "Pacific/Pitcairn", label: "Pacific/Pitcairn" },
  { value: "Pacific/Pohnpei", label: "Pacific/Pohnpei" },
  { value: "Pacific/Ponape", label: "Pacific/Ponape" },
  { value: "Pacific/Port_Moresby", label: "Pacific/Port_Moresby" },
  { value: "Pacific/Rarotonga", label: "Pacific/Rarotonga" },
  { value: "Pacific/Saipan", label: "Pacific/Saipan" },
  { value: "Pacific/Samoa", label: "Pacific/Samoa" },
  { value: "Pacific/Tahiti", label: "Pacific/Tahiti" },
  { value: "Pacific/Tarawa", label: "Pacific/Tarawa" },
  { value: "Pacific/Tongatapu", label: "Pacific/Tongatapu" },
  { value: "Pacific/Truk", label: "Pacific/Truk" },
  { value: "Pacific/Wake", label: "Pacific/Wake" },
  { value: "Pacific/Wallis", label: "Pacific/Wallis" },
  { value: "Pacific/Yap", label: "Pacific/Yap" },
  { value: "Poland", label: "Poland" },
  { value: "Portugal", label: "Portugal" },
  { value: "ROC", label: "ROC" },
  { value: "ROK", label: "ROK" },
  { value: "Singapore", label: "Singapore" },
  { value: "Turkey", label: "Turkey" },
  { value: "UCT", label: "UCT" },
  { value: "US/Alaska", label: "US/Alaska" },
  { value: "US/Aleutian", label: "US/Aleutian" },
  { value: "US/Arizona", label: "US/Arizona" },
  { value: "US/Central", label: "US/Central" },
  { value: "US/East-Indiana", label: "US/East-Indiana" },
  { value: "US/Eastern", label: "US/Eastern" },
  { value: "US/Hawaii", label: "US/Hawaii" },
  { value: "US/Indiana-Starke", label: "US/Indiana-Starke" },
  { value: "US/Michigan", label: "US/Michigan" },
  { value: "US/Mountain", label: "US/Mountain" },
  { value: "US/Pacific", label: "US/Pacific" },
  { value: "US/Samoa", label: "US/Samoa" },
  { value: "UTC", label: "UTC" },
  { value: "Universal", label: "Universal" },
  { value: "W-SU", label: "W-SU" },
  { value: "WET", label: "WET" },
  { value: "Zulu", label: "Zulu" },
];

export const CHANNEL_MODEL = [
  { value: "aircall", label: "Aircall" },
  { value: "api", label: "API" },
  { value: "chat", label: "Chat" },
  { value: "contact_form", label: "Contact Form" },
  { value: "email", label: "Email" },
  { value: "facebook", label: "Facebook" },
  { value: "facebook-mention", label: "Facebook Mention" },
  { value: "facebook-messenger", label: "Facebook Messenger" },
  { value: "facebook-recommendations", label: "Facebook Recommendations" },
  { value: "help-center", label: "Help Center" },
  { value: "instagram-ad-comment", label: "Instagram Ad Comment" },
  { value: "instagram-comment", label: "Instagram Comment" },
  { value: "instagram-direct-message", label: "Instagram Direct Message" },
  { value: "instagram-mention", label: "Instagram Mention" },
  { value: "internal-note", label: "Internal Note" },
  { value: "phone", label: "Phone" },
  { value: "sms", label: "SMS" },
  { value: "twitter", label: "Twitter" },
  { value: "twitter-direct-message", label: "Twitter Direct Message" },
  { value: "whatsapp", label: "WhatsApp" },
  { value: "yotpo-review", label: "Yotpo Review" },
];

export const VIA_MODEL = [
  { value: "aircall", label: "Aircall" },
  { value: "api", label: "API" },
  { value: "chat", label: "Chat" },
  { value: "contact_form", label: "Contact Form" },
  { value: "email", label: "Email" },
  { value: "facebook", label: "Facebook" },
  { value: "facebook-mention", label: "Facebook Mention" },
  { value: "facebook-messenger", label: "Facebook Messenger" },
  { value: "facebook-recommendations", label: "Facebook Recommendations" },
  { value: "form", label: "Form" },
  { value: "gorgias_chat", label: "Gorgias Chat" },
  { value: "help-center", label: "Help Center" },
  { value: "helpdesk", label: "Helpdesk" },
  { value: "instagram", label: "Instagram" },
  { value: "instagram-ad-comment", label: "Instagram Ad Comment" },
  { value: "instagram-comment", label: "Instagram Comment" },
  { value: "instagram-direct-message", label: "Instagram Direct Message" },
  { value: "instagram-mention", label: "Instagram Mention" },
  { value: "internal-note", label: "Internal Note" },
  { value: "offline_capture", label: "Offline Capture" },
  { value: "phone", label: "Phone" },
  { value: "rule", label: "Rule" },
  { value: "self_service", label: "Self Service" },
  { value: "shopify", label: "Shopify" },
  { value: "sms", label: "SMS" },
  { value: "twilio", label: "Twilio" },
  { value: "twitter", label: "Twitter" },
  { value: "twitter-direct-message", label: "Twitter Direct Message" },
  { value: "whatsapp", label: "WhatsApp" },
  { value: "yotpo", label: "Yotpo" },
  { value: "yotpo-review", label: "Yotpo Review" },
  { value: "zendesk", label: "Zendesk" },
];

export const TYPE_MODEL = [
  { value: "account-created", label: "Account Created" },
  { value: "account-deactivated", label: "Account Deactivated" },
  { value: "account-updated", label: "Account Updated" },
  { value: "customer-created", label: "Customer Created" },
  { value: "customer-deleted", label: "Customer Deleted" },
  { value: "customer-merged", label: "Customer Merged" },
  { value: "customer-updated", label: "Customer Updated" },
  { value: "integration-created", label: "Integration Created" },
  { value: "integration-deleted", label: "Integration Deleted" },
  { value: "integration-updated", label: "Integration Updated" },
  { value: "macro-created", label: "Macro Created" },
  { value: "macro-deleted", label: "Macro Deleted" },
  { value: "macro-updated", label: "Macro Updated" },
  { value: "rule-created", label: "Rule Created" },
  { value: "rule-deleted", label: "Rule Deleted" },
  { value: "rule-updated", label: "Rule Updated" },
  { value: "tag-created", label: "Tag Created" },
  { value: "tag-deleted", label: "Tag Deleted" },
  { value: "tag-merged", label: "Tag Merged" },
  { value: "team-created", label: "Team Created" },
  { value: "team-deleted", label: "Team Deleted" },
  { value: "team-updated", label: "Team Updated" },
  { value: "ticket-assigned", label: "Ticket Assigned" },
  { value: "ticket-closed", label: "Ticket Closed" },
  { value: "ticket-created", label: "Ticket Created" },
  { value: "ticket-customer-updated", label: "Ticket Customer Updated" },
  { value: "ticket-deleted", label: "Ticket Deleted" },
  {
    value: "ticket-excluded-from-auto-merge",
    label: "Ticket Excluded From Auto Merge",
  },
  { value: "ticket-excluded-from-csat", label: "Ticket Excluded From Csat" },
  { value: "ticket-marked-spam", label: "Ticket Marked-spam" },
  { value: "ticket-merged", label: "Ticket Merged" },
  { value: "ticket-message-created", label: "Ticket Message Created" },
  { value: "ticket-message-deleted", label: "Ticket Message Deleted" },
  {
    value: "ticket-message-summary-created",
    label: "Ticket Message-summary Created",
  },
  { value: "ticket-message-updated", label: "Ticket Message Updated" },
  { value: "ticket-reopened", label: "Ticket Reopened" },
  { value: "ticket-self-unsnoozed", label: "Ticket-self Unsnoozed" },
  { value: "ticket-snoozed", label: "Ticket-snoozed" },
  { value: "ticket-subject-updated", label: "Ticket-subject Updated" },
  { value: "ticket-tags-added", label: "Ticket Tags Added" },
  { value: "ticket-tags-removed", label: "Ticket Tags Removed" },
  { value: "ticket-team-assigned", label: "Ticket Team Assigned" },
  { value: "ticket-team-unassigned", label: "Ticket Team Unassigned" },
  { value: "ticket-trashed", label: "Ticket Trashed" },
  { value: "ticket-unassigned", label: "Ticket Unassigned" },
  { value: "ticket-unmarked-spam", label: "Ticket Unmarked-spam" },
  { value: "ticket-untrashed", label: "Ticket Untrashed" },
  { value: "ticket-updated", label: "Ticket Updated" },
  { value: "user-created", label: "User Created" },
  { value: "user-deleted", label: "User Deleted" },
  { value: "user-invited", label: "User Invited" },
  { value: "user-logged-in", label: "User Logged-in" },
  { value: "user-logged-out", label: "User Logged-out" },
  { value: "user-password-changed", label: "User Password Changed" },
  { value: "user-password-reset", label: "User Password Reset" },
  { value: "user-updated", label: "User Updated" },
  { value: "view-created", label: "View Created" },
  { value: "view-deleted", label: "View Deleted" },
  { value: "view-updated", label: "View Updated" },
  { value: "widget-created", label: "widget Created" },
  { value: "widget-deleted", label: "widget Deleted" },
  { value: "widget-updated", label: "widget Updated" },
];

export const BOOLEAN_MODEL = [
  { value: "true", label: "True" },
  { value: "false", label: "False" },
];

export const LANGUAGE_MODEL = [
  { value: "aa", label: "Afar" },
  { value: "ab", label: "Abkhazian" },
  { value: "af", label: "Afrikaans" },
  { value: "ak", label: "Akan" },
  { value: "sq", label: "Albanian" },
  { value: "am", label: "Amharic" },
  { value: "ar", label: "Arabic" },
  { value: "an", label: "Aragonese" },
  { value: "hy", label: "Armenian" },
  { value: "as", label: "Assamese" },
  { value: "av", label: "Avaric" },
  { value: "ae", label: "Avestan" },
  { value: "ay", label: "Aymara" },
  { value: "az", label: "Azerbaijani" },
  { value: "ba", label: "Bashkir" },
  { value: "bm", label: "Bambara" },
  { value: "eu", label: "Basque" },
  { value: "be", label: "Belarusian" },
  { value: "bn", label: "Bengali" },
  { value: "bh", label: "Bihari" },
  { value: "bi", label: "Bislama" },
  { value: "bs", label: "Bosnian" },
  { value: "br", label: "Breton" },
  { value: "bg", label: "Bulgarian" },
  { value: "my", label: "Burmese" },
  { value: "ca", label: "Catalan" },
  { value: "ch", label: "Chamorro" },
  { value: "ce", label: "Chechen" },
  { value: "zh", label: "Chinese" },
  { value: "cu", label: "Church Slavic" },
  { value: "cv", label: "Chuvash" },
  { value: "kw", label: "Cornish" },
  { value: "co", label: "Corsican" },
  { value: "cr", label: "Cree" },
  { value: "cs", label: "Czech" },
  { value: "da", label: "Danish" },
  { value: "dv", label: "Divehi" },
  { value: "nl", label: "Dutch" },
  { value: "dz", label: "Dzongkha" },
  { value: "en", label: "English" },
  { value: "eo", label: "Esperanto" },
  { value: "et", label: "Estonian" },
  { value: "ee", label: "Ewe" },
  { value: "fo", label: "Faroese" },
  { value: "fj", label: "Fijian" },
  { value: "fi", label: "Finnish" },
  { value: "fr", label: "French" },
  { value: "fy", label: "Western Frisian" },
  { value: "ff", label: "Fulah" },
  { value: "ka", label: "Georgian" },
  { value: "de", label: "German" },
  { value: "gd", label: "Scottish Gaelic" },
  { value: "ga", label: "Irish" },
  { value: "gl", label: "Galician" },
  { value: "gv", label: "Manx" },
  { value: "el", label: "Greek" },
  { value: "gn", label: "Guarani" },
  { value: "gu", label: "Gujarati" },
  { value: "ht", label: "Haitian" },
  { value: "ha", label: "Hausa" },
  { value: "he", label: "Hebrew" },
  { value: "hz", label: "Herero" },
  { value: "hi", label: "Hindi" },
  { value: "ho", label: "Hiri Motu" },
  { value: "hr", label: "Croatian" },
  { value: "hu", label: "Hungarian" },
  { value: "ig", label: "Igbo" },
  { value: "is", label: "Icelandic" },
  { value: "io", label: "Ido" },
  { value: "ii", label: "Sichuan Yi" },
  { value: "iu", label: "Inuktitut" },
  { value: "ie", label: "Interlingue" },
  { value: "ia", label: "Interlingua" },
  { value: "id", label: "Indonesian" },
  { value: "ik", label: "Inupiaq" },
  { value: "it", label: "Italian" },
  { value: "jv", label: "Javanese" },
  { value: "ja", label: "Japanese" },
  { value: "kl", label: "Kalaallisut" },
  { value: "kn", label: "Kannada" },
  { value: "ks", label: "Kashmiri" },
  { value: "kr", label: "Kanuri" },
  { value: "kk", label: "Kazakh" },
  { value: "km", label: "Central Khmer" },
  { value: "ki", label: "Kikuyu" },
  { value: "rw", label: "Kinyarwanda" },
  { value: "ky", label: "Kirghiz" },
  { value: "kv", label: "Komi" },
  { value: "kg", label: "Kongo" },
  { value: "ko", label: "Korean" },
  { value: "kj", label: "Kuanyama" },
  { value: "ku", label: "Kurdish" },
  { value: "lo", label: "Lao" },
  { value: "la", label: "Latin" },
  { value: "lv", label: "Latvian" },
  { value: "li", label: "Limburgan" },
  { value: "ln", label: "Lingala" },
  { value: "lt", label: "Lithuanian" },
  { value: "lb", label: "Luxembourgish" },
  { value: "lu", label: "Luba-Katanga" },
  { value: "lg", label: "Ganda" },
  { value: "mk", label: "Macedonian" },
  { value: "mh", label: "Marshallese" },
  { value: "ml", label: "Malayalam" },
  { value: "mi", label: "Maori" },
  { value: "mr", label: "Marathi" },
  { value: "ms", label: "Malay" },
  { value: "mg", label: "Malagasy" },
  { value: "mt", label: "Maltese" },
  { value: "mn", label: "Mongolian" },
  { value: "na", label: "Nauru" },
  { value: "nv", label: "Navajo" },
  { value: "nr", label: "Ndebele, South" },
  { value: "nd", label: "Ndebele, North" },
  { value: "ng", label: "Ndonga" },
  { value: "ne", label: "Nepali" },
  { value: "nn", label: "Norwegian Nynorsk" },
  { value: "nb", label: "Norwegian Bokmål" },
  { value: "no", label: "Norwegian" },
  { value: "ny", label: "Chichewa" },
  { value: "oc", label: "Occitan" },
  { value: "oj", label: "Ojibwa" },
  { value: "or", label: "Oriya" },
  { value: "om", label: "Oromo" },
  { value: "os", label: "Ossetian" },
  { value: "pa", label: "Punjabi" },
  { value: "fa", label: "Persian" },
  { value: "pi", label: "Pali" },
  { value: "pl", label: "Polish" },
  { value: "pt", label: "Portuguese" },
  { value: "ps", label: "Pashto" },
  { value: "qu", label: "Quechua" },
  { value: "rc", label: "Reto-Romance" },
  { value: "rm", label: "Romansh" },
  { value: "ro", label: "Romanian" },
  { value: "rn", label: "Rundi" },
  { value: "ru", label: "Russian" },
  { value: "sg", label: "Sango" },
  { value: "sa", label: "Sanskrit" },
  { value: "si", label: "Sinhala" },
  { value: "sk", label: "Slovak" },
  { value: "sl", label: "Slovenian" },
  { value: "se", label: "Northern Sami" },
  { value: "sm", label: "Samoan" },
  { value: "sn", label: "Shona" },
  { value: "sd", label: "Sindhi" },
  { value: "so", label: "Somali" },
  { value: "st", label: "Southern Sotho" },
  { value: "es", label: "Spanish" },
  { value: "sc", label: "Sardinian" },
  { value: "sr", label: "Serbian" },
  { value: "ss", label: "Swati" },
  { value: "su", label: "Sundanese" },
  { value: "sw", label: "Swahili" },
  { value: "sv", label: "Swedish" },
  { value: "ty", label: "Tahitian" },
  { value: "ta", label: "Tamil" },
  { value: "tt", label: "Tatar" },
  { value: "te", label: "Telugu" },
  { value: "tg", label: "Tajik" },
  { value: "tl", label: "Tagalog" },
  { value: "th", label: "Thai" },
  { value: "bo", label: "Tibetan" },
  { value: "ti", label: "Tigrinya" },
  { value: "to", label: "Tonga" },
  { value: "tn", label: "Tswana" },
  { value: "ts", label: "Tsonga" },
  { value: "tk", label: "Turkmen" },
  { value: "tr", label: "Turkish" },
  { value: "tw", label: "Twi" },
  { value: "ug", label: "Uighur" },
  { value: "uk", label: "Ukrainian" },
  { value: "ur", label: "Urdu" },
  { value: "uz", label: "Uzbek" },
  { value: "ve", label: "Venda" },
  { value: "vi", label: "Vietnamese" },
  { value: "vo", label: "Volapük" },
  { value: "cy", label: "Welsh" },
  { value: "wa", label: "Walloon" },
  { value: "wo", label: "Wolof" },
  { value: "xh", label: "Xhosa" },
  { value: "yi", label: "Yiddish" },
  { value: "yo", label: "Yoruba" },
  { value: "za", label: "Zhuang" },
  { value: "zu", label: "Zulu" },
];

export const ATTACHMENTS_EXAMPLE = [
  {
    url: "string",
    name: "string",
    size: "integer | null",
    content_type: "string",
    public: "boolean. defaults to true",
    extra: "string",
  },
];

export const SOURCE_EXAMPLE = [
  {
    type: "string",
    to: [
      {
        name: "string | null",
        address: "string",
      },
    ],
    cc: [
      {
        name: "string | null",
        address: "string",
      },
    ],
    bcc: [
      {
        name: "string | null",
        address: "string",
      },
    ],
    from: {
      name: "string | null",
      address: "string",
    },
  },
];

export const SENDER_EXAMPLE = {
  id: "number",
  email: "string",
};

export const RECEIVER_EXAMPLE = {
  id: "number",
  email: "string",
};

export enum MESSAGES {
  SUCCESS = "Success",
  ERROR = "Error",
}

export const RESOURCE_CONFIG: Record<string, { endpoint: string }> = {
  tickets: { endpoint: "/tickets" },
  customers: { endpoint: "/customers" },
};

