import { mapS4HanaOptionsToModelElements } from "./util/mappers";

export const ADD_ITEM_TO_PURCHASE_REQUISITION_DEFAULT_VALUE = {
  PurchaseRequisition: "string",
  PurchaseRequisitionItem: "strin",
  PurchasingDocument: "string",
  PurchasingDocumentItem: "strin",
  PurReqnReleaseStatus: "st",
  PurchaseRequisitionType: "stri",
  PurchasingDocumentItemCategory: "s",
  PurchaseRequisitionItemText: "string",
  AccountAssignmentCategory: "s",
  Material: "string",
  MaterialGroup: "string",
  RequestedQuantity: "0",
  BaseUnit: "str",
  PurchaseRequisitionPrice: "0",
  PurReqnPriceQuantity: "0",
  MaterialGoodsReceiptDuration: "0",
  ReleaseCode: "s",
  PurchaseRequisitionReleaseDate: "/Date(1492041600000)/",
  PurchasingOrganization: "stri",
  PurchasingGroup: "str",
  Plant: "stri",
  CompanyCode: "stri",
  SupplyingPlant: "stri",
  OrderedQuantity: "0",
  DeliveryDate: "/Date(1492041600000)/",
  ProcessingStatus: "s",
  ExternalApprovalStatus: "s",
  PurchasingInfoRecord: "string",
  Supplier: "string",
  IsDeleted: "s",
  FixedSupplier: "string",
  RequisitionerName: "string",
  PurReqnItemCurrency: "strin",
  MaterialPlannedDeliveryDurn: "0",
  DelivDateCategory: "s",
  MultipleAcctAssgmtDistribution: "s",
  StorageLocation: "stri",
  PurReqnSSPRequestor: "string",
  PurReqnSSPAuthor: "string",
  PurchaseContract: "string",
  PurchaseContractItem: "strin",
  ConsumptionPosting: "s",
  PurReqnOrigin: "s",
  PurReqnSSPCatalog: "string",
  PurReqnSSPCatalogItem: "string",
  PurReqnSSPCrossCatalogItem: 0,
  IsPurReqnBlocked: "s",
  ItemDeliveryAddressID: "string",
  Language: "st",
  IsClosed: true,
  ReleaseIsNotCompleted: true,
  ServicePerformer: "string",
  ProductType: "st",
  PurchaseRequisitionStatus: "string",
  ReleaseStrategy: "st",
  PerformancePeriodStartDate: "/Date(1492041600000)/",
  PerformancePeriodEndDate: "/Date(1492041600000)/",
  PurchaseOrderPriceType: "s",
  SupplierMaterialNumber: "string",
  Batch: "string",
  MaterialRevisionLevel: "st",
  MinRemainingShelfLife: "0",
  ItemNetAmount: "0",
  GoodsReceiptIsExpected: true,
  InvoiceIsExpected: true,
  GoodsReceiptIsNonValuated: true,
  RequirementTracking: "string",
  MRPController: "str",
  TaxCode: "st",
  PurchaseRequisitionIsFixed: true,
  ExpectedOverallLimitAmount: "0",
  OverallLimitAmount: "0",
  PurContractForOverallLimit: "string",
  PurReqnExternalReference: "string",
  PurReqnItemExternalReference: "string",
  PurReqnExternalSystemId: "string",
  PurReqnExternalSystemType: "s",
  PurReqnTypeExternalReference: "stri",
  PurReqnProcessingType: "s",
  PurReqnProcessingDateTime: "string",
  ProcmtHubBackendBusSyst: "string",
  SSPAuthorExternalBPIdnNumber: "string",
  SSPReqrUserId: "string",
  to_PurchaseReqn: {
    PurchaseRequisition: "string",
    PurchaseRequisitionType: "stri",
    PurReqnDescription: "string",
    SourceDetermination: true,
    PurReqnDoOnlyValidation: true,
    to_PurchaseReqnItem: {
      results: ["string"],
    },
  },
  to_PurchaseReqnAcctAssgmt: {
    results: [
      {
        PurchaseRequisition: "string",
        PurchaseRequisitionItem: "strin",
        PurchaseReqnAcctAssgmtNumber: "st",
        CostCenter: "string",
        MasterFixedAsset: "string",
        ProjectNetwork: "string",
        Quantity: "0",
        MultipleAcctAssgmtDistrPercent: "0",
        PurReqnNetAmount: "0",
        IsDeleted: "s",
        CostElement: "string",
        GLAccount: "string",
        BusinessArea: "stri",
        SDDocument: "string",
        SalesOrder: "string",
        SalesDocumentItem: "string",
        SalesOrderItem: "string",
        ScheduleLine: "stri",
        SalesOrderScheduleLine: "stri",
        FixedAsset: "stri",
        ProcessOrder: "string",
        OrderID: "string",
        UnloadingPointName: "string",
        ControllingArea: "stri",
        CostObject: "string",
        ProfitabilitySegment: "string",
        ProfitCenter: "string",
        ProjectNetworkInternalID: "string",
        CommitmentItem: "string",
        FundsCenter: "string",
        Fund: "string",
        FunctionalArea: "string",
        CreationDate: "/Date(1492041600000)/",
        GoodsRecipientName: "string",
        RealEstateObject: "string",
        NetworkActivityInternalID: "string",
        PartnerAccountNumber: "string",
        JointVentureRecoveryCode: "st",
        SettlementReferenceDate: "/Date(1492041600000)/",
        OrderInternalID: "string",
        OrderIntBillOfOperationsItem: "string",
        EarmarkedFundsDocument: "string",
        CostCtrActivityType: "string",
        BusinessProcess: "string",
        GrantID: "string",
        ValidityDate: "/Date(1492041600000)/",
        ChartOfAccounts: "stri",
        WBSElement: "string",
        NetworkActivity: "stri",
        PurchaseRequisitionType: "stri",
        Plant: "stri",
        PurchasingOrganization: "stri",
        PurchasingGroup: "str",
      },
    ],
  },
  to_PurchaseReqnDeliveryAddress: {
    PurchaseRequisition: "string",
    PurchaseRequisitionItem: "strin",
    Plant: "stri",
    CareOfName: "string",
    AdditionalStreetSuffixName: "string",
    CorrespondenceLanguage: "st",
    PrfrdCommMediumType: "str",
    POBox: "string",
    POBoxIsWithoutNumber: true,
    POBoxPostalCode: "string",
    POBoxLobbyName: "string",
    POBoxDeviatingCityName: "string",
    POBoxDeviatingRegion: "str",
    POBoxDeviatingCountry: "str",
    DeliveryServiceTypeCode: "stri",
    DeliveryServiceNumber: "string",
    AddressTimeZone: "string",
    CityName: "string",
    District: "string",
    CityCode: "string",
    HomeCityName: "string",
    PostalCode: "string",
    CompanyPostalCode: "string",
    StreetName: "string",
    StreetPrefixName: "string",
    AdditionalStreetPrefixName: "string",
    StreetSuffixName: "string",
    HouseNumber: "string",
    HouseNumberSupplementText: "string",
    Building: "string",
    Floor: "string",
    RoomNumber: "string",
    Country: "str",
    Region: "str",
    County: "string",
    FormOfAddress: "stri",
    BusinessPartnerName1: "string",
    BusinessPartnerName2: "string",
    Nation: "s",
    PhoneNumber: "string",
    FaxNumber: "string",
    SearchTerm1: "string",
    StreetSearch: "string",
    CitySearch: "string",
    BusinessPartnerName3: "string",
    BusinessPartnerName4: "string",
    TaxJurisdiction: "string",
    TransportZone: "string",
    Person: "string",
  },
  to_PurchaseReqnItemText: {
    results: [
      {
        PurchaseRequisition: "string",
        PurchaseRequisitionItem: "strin",
        DocumentText: "stri",
        TechnicalObjectType: "string",
        Language: "st",
        NoteDescription: "string",
      },
    ],
  },
};

export const CREATE_PURCHASE_REQUISITION_DEFAULT_VALUE = {
  PurchaseRequisition: "string",
  PurchaseRequisitionType: "string",
  PurReqnDescription: "string",
  SourceDetermination: true,
  PurReqnDoOnlyValidation: true,
  to_PurchaseReqnItem: {
    results: [
      {
        PurchaseRequisition: "string",
        PurchaseRequisitionItem: "strin",
        PurchasingDocument: "string",
        PurchasingDocumentItem: "strin",
        PurReqnReleaseStatus: "st",
        PurchaseRequisitionType: "stri",
        PurchasingDocumentItemCategory: "s",
        PurchaseRequisitionItemText: "string",
        AccountAssignmentCategory: "s",
        Material: "string",
        MaterialGroup: "string",
        RequestedQuantity: "0",
        BaseUnit: "str",
        PurchaseRequisitionPrice: "0",
        PurReqnPriceQuantity: "0",
        MaterialGoodsReceiptDuration: "0",
        ReleaseCode: "s",
        PurchaseRequisitionReleaseDate: "/Date(1492041600000)/",
        PurchasingOrganization: "stri",
        PurchasingGroup: "str",
        Plant: "stri",
        CompanyCode: "stri",
        SupplyingPlant: "stri",
        OrderedQuantity: "0",
        DeliveryDate: "/Date(1492041600000)/",
        ProcessingStatus: "s",
        ExternalApprovalStatus: "s",
        PurchasingInfoRecord: "string",
        Supplier: "string",
        IsDeleted: "s",
        FixedSupplier: "string",
        RequisitionerName: "string",
        PurReqnItemCurrency: "strin",
        MaterialPlannedDeliveryDurn: "0",
        DelivDateCategory: "s",
        MultipleAcctAssgmtDistribution: "s",
        StorageLocation: "stri",
        PurReqnSSPRequestor: "string",
        PurReqnSSPAuthor: "string",
        PurchaseContract: "string",
        PurchaseContractItem: "strin",
        ConsumptionPosting: "s",
        PurReqnOrigin: "s",
        PurReqnSSPCatalog: "string",
        PurReqnSSPCatalogItem: "string",
        PurReqnSSPCrossCatalogItem: 0,
        IsPurReqnBlocked: "s",
        ItemDeliveryAddressID: "string",
        Language: "st",
        IsClosed: true,
        ReleaseIsNotCompleted: true,
        ServicePerformer: "string",
        ProductType: "st",
        PurchaseRequisitionStatus: "string",
        ReleaseStrategy: "st",
        PerformancePeriodStartDate: "/Date(1492041600000)/",
        PerformancePeriodEndDate: "/Date(1492041600000)/",
        PurchaseOrderPriceType: "s",
        SupplierMaterialNumber: "string",
        Batch: "string",
        MaterialRevisionLevel: "st",
        MinRemainingShelfLife: "0",
        ItemNetAmount: "0",
        GoodsReceiptIsExpected: true,
        InvoiceIsExpected: true,
        GoodsReceiptIsNonValuated: true,
        RequirementTracking: "string",
        MRPController: "str",
        TaxCode: "st",
        PurchaseRequisitionIsFixed: true,
        ExpectedOverallLimitAmount: "0",
        OverallLimitAmount: "0",
        PurContractForOverallLimit: "string",
        PurReqnExternalReference: "string",
        PurReqnItemExternalReference: "string",
        PurReqnExternalSystemId: "string",
        PurReqnExternalSystemType: "s",
        PurReqnTypeExternalReference: "stri",
        PurReqnProcessingType: "s",
        PurReqnProcessingDateTime: "string",
        ProcmtHubBackendBusSyst: "string",
        SSPAuthorExternalBPIdnNumber: "string",
        SSPReqrUserId: "string",
        to_PurchaseReqn: "string",
        to_PurchaseReqnAcctAssgmt: {
          results: [
            {
              PurchaseRequisition: "string",
              PurchaseRequisitionItem: "strin",
              PurchaseReqnAcctAssgmtNumber: "st",
              CostCenter: "string",
              MasterFixedAsset: "string",
              ProjectNetwork: "string",
              Quantity: "0",
              MultipleAcctAssgmtDistrPercent: "0",
              PurReqnNetAmount: "0",
              IsDeleted: "s",
              CostElement: "string",
              GLAccount: "string",
              BusinessArea: "stri",
              SDDocument: "string",
              SalesOrder: "string",
              SalesDocumentItem: "string",
              SalesOrderItem: "string",
              ScheduleLine: "stri",
              SalesOrderScheduleLine: "stri",
              FixedAsset: "stri",
              ProcessOrder: "string",
              OrderID: "string",
              UnloadingPointName: "string",
              ControllingArea: "stri",
              CostObject: "string",
              ProfitabilitySegment: "string",
              ProfitCenter: "string",
              ProjectNetworkInternalID: "string",
              CommitmentItem: "string",
              FundsCenter: "string",
              Fund: "string",
              FunctionalArea: "string",
              CreationDate: "/Date(1492041600000)/",
              GoodsRecipientName: "string",
              RealEstateObject: "string",
              NetworkActivityInternalID: "string",
              PartnerAccountNumber: "string",
              JointVentureRecoveryCode: "st",
              SettlementReferenceDate: "/Date(1492041600000)/",
              OrderInternalID: "string",
              OrderIntBillOfOperationsItem: "string",
              EarmarkedFundsDocument: "string",
              CostCtrActivityType: "string",
              BusinessProcess: "string",
              GrantID: "string",
              ValidityDate: "/Date(1492041600000)/",
              ChartOfAccounts: "stri",
              WBSElement: "string",
              NetworkActivity: "stri",
              PurchaseRequisitionType: "stri",
              Plant: "stri",
              PurchasingOrganization: "stri",
              PurchasingGroup: "str",
            },
          ],
        },
        to_PurchaseReqnDeliveryAddress: {
          PurchaseRequisition: "string",
          PurchaseRequisitionItem: "strin",
          Plant: "stri",
          CareOfName: "string",
          AdditionalStreetSuffixName: "string",
          CorrespondenceLanguage: "st",
          PrfrdCommMediumType: "str",
          POBox: "string",
          POBoxIsWithoutNumber: true,
          POBoxPostalCode: "string",
          POBoxLobbyName: "string",
          POBoxDeviatingCityName: "string",
          POBoxDeviatingRegion: "str",
          POBoxDeviatingCountry: "str",
          DeliveryServiceTypeCode: "stri",
          DeliveryServiceNumber: "string",
          AddressTimeZone: "string",
          CityName: "string",
          District: "string",
          CityCode: "string",
          HomeCityName: "string",
          PostalCode: "string",
          CompanyPostalCode: "string",
          StreetName: "string",
          StreetPrefixName: "string",
          AdditionalStreetPrefixName: "string",
          StreetSuffixName: "string",
          HouseNumber: "string",
          HouseNumberSupplementText: "string",
          Building: "string",
          Floor: "string",
          RoomNumber: "string",
          Country: "str",
          Region: "str",
          County: "string",
          FormOfAddress: "stri",
          BusinessPartnerName1: "string",
          BusinessPartnerName2: "string",
          Nation: "s",
          PhoneNumber: "string",
          FaxNumber: "string",
          SearchTerm1: "string",
          StreetSearch: "string",
          CitySearch: "string",
          BusinessPartnerName3: "string",
          BusinessPartnerName4: "string",
          TaxJurisdiction: "string",
          TransportZone: "string",
          Person: "string",
        },
        to_PurchaseReqnItemText: {
          results: [
            {
              PurchaseRequisition: "string",
              PurchaseRequisitionItem: "strin",
              DocumentText: "stri",
              TechnicalObjectType: "string",
              Language: "st",
              NoteDescription: "string",
            },
          ],
        },
      },
    ],
  },
};

export const UPDATE_PURCHASE_REQUISITION_DEFAULT_VALUE = {
  d: {
    PurchaseRequisitionType: "string",
    PurReqnDescription: "string",
    SourceDetermination: true,
    PurReqnDoOnlyValidation: true,
  },
};

export const GET_PURCHASE_REQUISITION_ITEM_DETAILS_ORDER_BY_MODEL = [
  "PurchaseRequisition",
  "PurchaseRequisition desc",
  "PurchaseRequisitionItem",
  "PurchaseRequisitionItem desc",
  "PurchasingDocument",
  "PurchasingDocument desc",
  "PurchasingDocumentItem",
  "PurchasingDocumentItem desc",
  "PurReqnReleaseStatus",
  "PurReqnReleaseStatus desc",
  "PurchaseRequisitionType",
  "PurchaseRequisitionType desc",
  "PurchasingDocumentSubtype",
  "PurchasingDocumentSubtype desc",
  "PurchasingDocumentItemCategory",
  "PurchasingDocumentItemCategory desc",
  "PurchaseRequisitionItemText",
  "PurchaseRequisitionItemText desc",
  "AccountAssignmentCategory",
  "AccountAssignmentCategory desc",
  "Material",
  "Material desc",
  "MaterialGroup",
  "MaterialGroup desc",
  "PurchasingDocumentCategory",
  "PurchasingDocumentCategory desc",
  "RequestedQuantity",
  "RequestedQuantity desc",
  "BaseUnit",
  "BaseUnit desc",
  "PurchaseRequisitionPrice",
  "PurchaseRequisitionPrice desc",
  "PurReqnPriceQuantity",
  "PurReqnPriceQuantity desc",
  "MaterialGoodsReceiptDuration",
  "MaterialGoodsReceiptDuration desc",
  "ReleaseCode",
  "ReleaseCode desc",
  "PurchaseRequisitionReleaseDate",
  "PurchaseRequisitionReleaseDate desc",
  "PurchasingOrganization",
  "PurchasingOrganization desc",
  "PurchasingGroup",
  "PurchasingGroup desc",
  "Plant",
  "Plant desc",
  "CompanyCode",
  "CompanyCode desc",
  "SourceOfSupplyIsAssigned",
  "SourceOfSupplyIsAssigned desc",
  "SupplyingPlant",
  "SupplyingPlant desc",
  "OrderedQuantity",
  "OrderedQuantity desc",
  "DeliveryDate",
  "DeliveryDate desc",
  "CreationDate",
  "CreationDate desc",
  "ProcessingStatus",
  "ProcessingStatus desc",
  "ExternalApprovalStatus",
  "ExternalApprovalStatus desc",
  "PurchasingInfoRecord",
  "PurchasingInfoRecord desc",
  "Supplier",
  "Supplier desc",
  "IsDeleted",
  "IsDeleted desc",
  "FixedSupplier",
  "FixedSupplier desc",
  "RequisitionerName",
  "RequisitionerName desc",
  "CreatedByUser",
  "CreatedByUser desc",
  "PurReqCreationDate",
  "PurReqCreationDate desc",
  "DeliveryAddressID",
  "DeliveryAddressID desc",
  "ManualDeliveryAddressID",
  "ManualDeliveryAddressID desc",
  "PurReqnItemCurrency",
  "PurReqnItemCurrency desc",
  "MaterialPlannedDeliveryDurn",
  "MaterialPlannedDeliveryDurn desc",
  "DelivDateCategory",
  "DelivDateCategory desc",
  "MultipleAcctAssgmtDistribution",
  "MultipleAcctAssgmtDistribution desc",
  "StorageLocation",
  "StorageLocation desc",
  "PurReqnSSPRequestor",
  "PurReqnSSPRequestor desc",
  "PurReqnSSPAuthor",
  "PurReqnSSPAuthor desc",
  "PurchaseContract",
  "PurchaseContract desc",
  "PurReqnSourceOfSupplyType",
  "PurReqnSourceOfSupplyType desc",
  "PurchaseContractItem",
  "PurchaseContractItem desc",
  "ConsumptionPosting",
  "ConsumptionPosting desc",
  "PurReqnOrigin",
  "PurReqnOrigin desc",
  "PurReqnSSPCatalog",
  "PurReqnSSPCatalog desc",
  "PurReqnSSPCatalogItem",
  "PurReqnSSPCatalogItem desc",
  "PurReqnSSPCrossCatalogItem",
  "PurReqnSSPCrossCatalogItem desc",
  "IsPurReqnBlocked",
  "IsPurReqnBlocked desc",
  "ItemDeliveryAddressID",
  "ItemDeliveryAddressID desc",
  "Language",
  "Language desc",
  "IsClosed",
  "IsClosed desc",
  "ReleaseIsNotCompleted",
  "ReleaseIsNotCompleted desc",
  "ServicePerformer",
  "ServicePerformer desc",
  "ProductType",
  "ProductType desc",
  "PurchaseRequisitionStatus",
  "PurchaseRequisitionStatus desc",
  "ReleaseStrategy",
  "ReleaseStrategy desc",
  "PerformancePeriodStartDate",
  "PerformancePeriodStartDate desc",
  "PerformancePeriodEndDate",
  "PerformancePeriodEndDate desc",
  "PurchaseOrderPriceType",
  "PurchaseOrderPriceType desc",
  "SupplierMaterialNumber",
  "SupplierMaterialNumber desc",
  "Batch",
  "Batch desc",
  "MaterialRevisionLevel",
  "MaterialRevisionLevel desc",
  "MinRemainingShelfLife",
  "MinRemainingShelfLife desc",
  "ItemNetAmount",
  "ItemNetAmount desc",
  "GoodsReceiptIsExpected",
  "GoodsReceiptIsExpected desc",
  "InvoiceIsExpected",
  "InvoiceIsExpected desc",
  "GoodsReceiptIsNonValuated",
  "GoodsReceiptIsNonValuated desc",
  "RequirementTracking",
  "RequirementTracking desc",
  "MRPController",
  "MRPController desc",
  "TaxCode",
  "TaxCode desc",
  "PurchaseRequisitionIsFixed",
  "PurchaseRequisitionIsFixed desc",
  "AddressID",
  "AddressID desc",
  "LastChangeDateTime",
  "LastChangeDateTime desc",
  "Reservation",
  "Reservation desc",
  "ExpectedOverallLimitAmount",
  "ExpectedOverallLimitAmount desc",
  "OverallLimitAmount",
  "OverallLimitAmount desc",
  "PurContractForOverallLimit",
  "PurContractForOverallLimit desc",
  "PurReqnExternalReference",
  "PurReqnExternalReference desc",
  "PurReqnItemExternalReference",
  "PurReqnItemExternalReference desc",
  "PurReqnExternalSystemId",
  "PurReqnExternalSystemId desc",
  "PurReqnExternalSystemType",
  "PurReqnExternalSystemType desc",
  "PurReqnTypeExternalReference",
  "PurReqnTypeExternalReference desc",
  "PurReqnProcessingType",
  "PurReqnProcessingType desc",
  "PurReqnProcessingDateTime",
  "PurReqnProcessingDateTime desc",
  "ProcmtHubBackendBusSyst",
  "ProcmtHubBackendBusSyst desc",
  "SSPAuthorExternalBPIdnNumber",
  "SSPAuthorExternalBPIdnNumber desc",
  "SSPReqrUserId",
  "SSPReqrUserId desc",
].map(mapS4HanaOptionsToModelElements);

export const GET_PURCHASE_REQUISITION_ITEM_DETAILS_SELECT_MODEL = [
  "PurchaseRequisition",
  "PurchaseRequisitionItem",
  "PurchasingDocument",
  "PurchasingDocumentItem",
  "PurReqnReleaseStatus",
  "PurchaseRequisitionType",
  "PurchasingDocumentSubtype",
  "PurchasingDocumentItemCategory",
  "PurchaseRequisitionItemText",
  "AccountAssignmentCategory",
  "Material",
  "MaterialGroup",
  "PurchasingDocumentCategory",
  "RequestedQuantity",
  "BaseUnit",
  "PurchaseRequisitionPrice",
  "PurReqnPriceQuantity",
  "MaterialGoodsReceiptDuration",
  "ReleaseCode",
  "PurchaseRequisitionReleaseDate",
  "PurchasingOrganization",
  "PurchasingGroup",
  "Plant",
  "CompanyCode",
  "SourceOfSupplyIsAssigned",
  "SupplyingPlant",
  "OrderedQuantity",
  "DeliveryDate",
  "CreationDate",
  "ProcessingStatus",
  "ExternalApprovalStatus",
  "PurchasingInfoRecord",
  "Supplier",
  "IsDeleted",
  "FixedSupplier",
  "RequisitionerName",
  "CreatedByUser",
  "PurReqCreationDate",
  "DeliveryAddressID",
  "ManualDeliveryAddressID",
  "PurReqnItemCurrency",
  "MaterialPlannedDeliveryDurn",
  "DelivDateCategory",
  "MultipleAcctAssgmtDistribution",
  "StorageLocation",
  "PurReqnSSPRequestor",
  "PurReqnSSPAuthor",
  "PurchaseContract",
  "PurReqnSourceOfSupplyType",
  "PurchaseContractItem",
  "ConsumptionPosting",
  "PurReqnOrigin",
  "PurReqnSSPCatalog",
  "PurReqnSSPCatalogItem",
  "PurReqnSSPCrossCatalogItem",
  "IsPurReqnBlocked",
  "ItemDeliveryAddressID",
  "Language",
  "IsClosed",
  "ReleaseIsNotCompleted",
  "ServicePerformer",
  "ProductType",
  "PurchaseRequisitionStatus",
  "ReleaseStrategy",
  "PerformancePeriodStartDate",
  "PerformancePeriodEndDate",
  "PurchaseOrderPriceType",
  "SupplierMaterialNumber",
  "Batch",
  "MaterialRevisionLevel",
  "MinRemainingShelfLife",
  "ItemNetAmount",
  "GoodsReceiptIsExpected",
  "InvoiceIsExpected",
  "GoodsReceiptIsNonValuated",
  "RequirementTracking",
  "MRPController",
  "TaxCode",
  "PurchaseRequisitionIsFixed",
  "AddressID",
  "LastChangeDateTime",
  "Reservation",
  "ExpectedOverallLimitAmount",
  "OverallLimitAmount",
  "PurContractForOverallLimit",
  "PurReqnExternalReference",
  "PurReqnItemExternalReference",
  "PurReqnExternalSystemId",
  "PurReqnExternalSystemType",
  "PurReqnTypeExternalReference",
  "PurReqnProcessingType",
  "PurReqnProcessingDateTime",
  "ProcmtHubBackendBusSyst",
  "SSPAuthorExternalBPIdnNumber",
  "SSPReqrUserId",
  "to_PurchaseReqn",
  "to_PurchaseReqnAcctAssgmt",
  "to_PurchaseReqnDeliveryAddress",
  "to_PurchaseReqnItemText",
].map(mapS4HanaOptionsToModelElements);

export const GET_PURCHASE_REQUISITION_ITEM_DETAILS_EXPAND_MODEL = [
  "to_PurchaseReqn",
  "to_PurchaseReqnAcctAssgmt",
  "to_PurchaseReqnDeliveryAddress",
  "to_PurchaseReqnItemText",
].map(mapS4HanaOptionsToModelElements);





export const CONNECTION_KEYS = {
  API_KEY: "apiKey",
  BASIC_AUTH: "sapBasicAuth",
} as const;

import type { PollResourceConfig } from "./types";

export const POLL_RESOURCE_CONFIG: Record<string, PollResourceConfig> = {
  changeRecords: {
    label: "Change Records",
    endpoint: "/sap/opu/odata/sap/API_CHANGE_RECORD/A_ChangeRecord",
    filterField: "LastChangeDateTime",
    createdAtField: "CreationDateTime",
    updatedAtField: "LastChangeDateTime",
  },
  projects: {
    label: "Projects",
    endpoint: "/sap/opu/odata/CPD/SC_PROJ_ENGMT_CREATE_UPD_SRV/ProjectSet",
    filterField: "ChangedOn",
    createdAtField: "CreatedOn",
    updatedAtField: "ChangedOn",
  },
};

export const pollResourceModel = Object.entries(POLL_RESOURCE_CONFIG).map(([value, { label }]) => ({
  label,
  value,
}));
