import { action } from "@prismatic-io/spectral";
import { createClient } from "../../client";
import {
  connectionInput,
  creationTime,
  datasetId,
  defaultTrialId,
  description,
  encryptionConfiguration,
  etag,
  expirationTime,
  featureColumns,
  friendlyName,
  hparamSearchSpaces,
  hparamTrials,
  labelColumns,
  labels,
  lastModifiedTime,
  location,
  modelId,
  modelReference,
  modelType,
  optimalTrialIds,
  projectId,
  trainingRuns,
} from "../../inputs";

export const updateModel = action({
  display: {
    description: "Patch specific fields in the specified model.",
    label: "Update Model",
  },
  inputs: {
    connectionInput,
    projectId,
    datasetId,
    modelId,
    modelReference,
    etag,
    creationTime,
    lastModifiedTime,
    description,
    friendlyName,
    labels,
    expirationTime,
    location,
    encryptionConfiguration,
    modelType,
    trainingRuns,
    featureColumns,
    labelColumns,
    hparamSearchSpaces,
    defaultTrialId,
    hparamTrials,
    optimalTrialIds,
  },
  perform: async (
    _context,
    {
      connectionInput,
      projectId,
      datasetId,
      modelId,
      etag,
      modelReference,
      creationTime,
      lastModifiedTime,
      description,
      friendlyName,
      labels,
      expirationTime,
      location,
      encryptionConfiguration,
      modelType,
      trainingRuns,
      featureColumns,
      labelColumns,
      hparamSearchSpaces,
      defaultTrialId,
      hparamTrials,
      optimalTrialIds,
    },
  ) => {
    const client = createClient(connectionInput);
    const { data } = await client.models.patch({
      projectId: projectId || undefined,
      datasetId: datasetId || undefined,
      modelId: modelId || undefined,
      requestBody: {
        etag: etag || undefined,
        modelReference: modelReference || undefined,
        creationTime: creationTime || undefined,
        lastModifiedTime: lastModifiedTime || undefined,
        description: description || undefined,
        friendlyName: friendlyName || undefined,
        labels: labels || undefined,
        expirationTime: expirationTime || undefined,
        location: location || undefined,
        encryptionConfiguration: encryptionConfiguration || undefined,
        modelType: modelType || undefined,
        trainingRuns: trainingRuns || undefined,
        featureColumns: featureColumns || undefined,
        labelColumns: labelColumns || undefined,
        hparamSearchSpaces: hparamSearchSpaces || undefined,
        defaultTrialId: defaultTrialId || undefined,
        hparamTrials: hparamTrials || undefined,
        optimalTrialIds: optimalTrialIds || undefined,
      },
    });
    return {
      data,
    };
  },
});
