export const ENGAGEMENT_PROPERTIES = [
  { label: "Task - Timestamp", value: "hs_timestamp" },
  { label: "Task - Body", value: "hs_task_body" },
  { label: "Task - Owner ID", value: "hubspot_owner_id" },
  { label: "Task - Subject", value: "hs_task_subject" },
  { label: "Task - Status", value: "hs_task_status" },
  { label: "Task - Priority", value: "hs_task_priority" },
  { label: "Task - Type", value: "hs_task_type" },
  { label: "Postal Mail - Timestamp", value: "hs_timestamp" },
  { label: "Postal Mail - Body", value: "hs_postal_mail_body" },
  { label: "Postal Mail - Owner ID", value: "hubspot_owner_id" },
  { label: "Postal Mail - Attachment IDs", value: "hs_attachment_ids" },
  { label: "Note - Timestamp", value: "hs_timestamp" },
  { label: "Note - Body", value: "hs_note_body" },
  { label: "Note - Owner ID", value: "hubspot_owner_id" },
  { label: "Note - Attachment IDs", value: "hs_attachment_ids" },
  { label: "Meeting - Timestamp", value: "hs_timestamp" },
  { label: "Meeting - Title", value: "hs_meeting_title" },
  { label: "Meeting - Owner ID", value: "hubspot_owner_id" },
  { label: "Meeting - Body", value: "hs_meeting_body" },
  { label: "Meeting - Internal Notes", value: "hs_internal_meeting_notes" },
  { label: "Meeting - External URL", value: "hs_meeting_external_URL" },
  { label: "Meeting - Location", value: "hs_meeting_location" },
  { label: "Meeting - Start Time", value: "hs_meeting_start_time" },
  { label: "Meeting - End Time", value: "hs_meeting_end_time" },
  { label: "Meeting - Outcome", value: "hs_meeting_outcome" },
  { label: "Meeting - Activity Type", value: "hs_activity_type" },
  { label: "Meeting - Attachment IDs", value: "hs_attachment_ids" },
  { label: "Call - Timestamp", value: "hs_timestamp" },
  { label: "Call - Body", value: "hs_call_body" },
  { label: "Call - Callee Object ID", value: "hs_call_callee_object_id" },
  {
    label: "Call - Callee Object Type ID",
    value: "hs_call_callee_object_type_id",
  },
  { label: "Call - Direction", value: "hs_call_direction" },
  { label: "Call - Disposition", value: "hs_call_disposition" },
  { label: "Call - Duration", value: "hs_call_duration" },
  { label: "Call - From Number", value: "hs_call_from_number" },
  { label: "Call - Recording URL", value: "hs_call_recording_url" },
  { label: "Call - Status", value: "hs_call_status" },
  { label: "Call - Title", value: "hs_call_title" },
  { label: "Call - To Number", value: "hs_call_to_number" },
  { label: "Call - Owner ID", value: "hubspot_owner_id" },
  { label: "Call - Activity Type", value: "hs_activity_type" },
  { label: "Call - Attachment IDs", value: "hs_attachment_ids" },
  { label: "Email - Timestamp", value: "hs_timestamp" },
  { label: "Email - Owner ID", value: "hubspot_owner_id" },
  { label: "Email - Direction", value: "hs_email_direction" },
  { label: "Email - HTML", value: "hs_email_html" },
  { label: "Email - Status", value: "hs_email_status" },
  { label: "Email - Subject", value: "hs_email_subject" },
  { label: "Email - Text", value: "hs_email_text" },
  { label: "Email - Attachment IDs", value: "hs_attachment_ids" },
  { label: "Email - Headers", value: "hs_email_headers" },
  {
    label: "Communication - Channel Type",
    value: "hs_communication_channel_type",
  },
  {
    label: "Communication - Logged From",
    value: "hs_communication_logged_from",
  },
  { label: "Communication - Body", value: "hs_communication_body" },
  { label: "Communication - Timestamp", value: "hs_timestamp" },
];
