export const eventItemSchema = {
  type: "object" as const,
  properties: {
    guid: { type: "string" },
    effectiveItemRevision: {
      type: "object",
      properties: {
        guid: { type: "string" },
        name: { type: "string" },
        number: { type: "string" },
        revisionNumber: { type: "string" },
        lifecyclePhase: {
          type: "object",
          properties: {
            name: { type: "string" },
            stage: { type: "string" },
            guid: { type: "string" },
            id: { type: "integer", format: "int64" },
            plmEntityType: {
              type: "string",
              enum: [
                "ITEM",
                "FILE",
                "FILE_MASTER",
                "REPORT",
                "REPORT_INSTANCE",
                "ITEM_FILE_MAP",
                "AFS_FOLDER",
                "CATEGORY",
                "NUMBER_FORMAT",
                "ITEM_REVISION",
                "BOM_LINE",
                "SUPPLIER",
                "SUPPLIER_ITEM",
                "CHANGE",
                "CHANGE_CUSTOM_ATTRIBUTE",
                "CHANGE_LIFECYCLE",
                "CHANGE_DECISION",
                "REQUEST",
                "REQUEST_CUSTOM_ATTRIBUTE",
                "REQUEST_LIFECYCLE",
                "QUALITY",
                "QUALITY_STEP",
                "PROJECT",
                "PROJECT_SCHEDULE",
                "QUALITY_CUSTOM_ATTRIBUTE",
                "PROJECT_CUSTOM_ATTRIBUTE",
                "DW_EXTRACT",
                "DW_EXTRACT_RUN",
                "DW_EXTRACT_RUNFILE_ASSOCIATION",
                "CHANGE_CUSTOM_CHANGE_VALUE_ID",
                "REQUEST_CUSTOM_ATTRIBUTE_REQUEST_VALUE_ID",
                "EXTRACT_VALUE_ID",
                "ITEM_ADDITIONAL_ATTRIBUTE",
                "ITEM_BOM",
                "ITEM_BOM_SUB",
                "SOURCING_RELATIONSHIP",
                "SUPPLIER_ITEM_GUID",
                "SUPPLIER_GUID",
                "ITEM_CUST_ATTR_SI",
                "ITEM_CUST_ATTR_PROPERTY_ID",
                "REQUEST_ITEM_ECR_ITEM_MAP_ID",
                "QUALITYPROCESS_ASSOCIATION",
                "URL",
                "HISTORY_AUDIT",
                "PROJECT_ITEM_MAP_ID",
                "PROJECT_CHANGE_MAP_ID",
                "PROJECT_ECR_MAP_ID",
                "PROJECT_PROJECT_MAP_ID",
                "CHANGE_ITEM",
                "LIFECYCLE_PHASE",
                "BOMLINE_ADDITIONAL_ATTRIBUTE",
                "SUPPLIER_VALUE_ID",
                "QUALITY_STEP_DECISION",
                "ITEM_COMPLIANCE_REQUIREMENT",
                "ITEM_REQUIREMENT",
                "SUPPLIERITEM_COMPLIANCE_REQUIREMENT",
                "ITEM_BOM_SETTINGS",
                "ITEM_LIFECYCLE_CHANGE",
                "QUALITY_CUSTOM_ATTRIBUTE_QUALITY_PROPERTY_MAP_ID",
                "SUPPLIER_ITEM_RUNFILE_ASSOCIATION",
                "SUPPLIER_ITEM_SUMMARY_ITEM_GUID",
                "PROJECT_ITEM_GUID",
                "QUALITY_AO_ITEM_GUID",
                "SUPPLIER_ITEM_CUST_ATTR_ITEM_ID",
                "CHANGE_REQUEST_ECR_CHANGE_MAP_ID",
                "ATTRIBUTE",
                "BOMLINE_ATTRIBUTE",
                "QUALITY_PREFIX",
                "USER",
                "ADDITIONAL_ATTRIBUTE",
                "REQUEST_EVALUATOR_GROUP",
                "REQUEST_PREFIX",
                "VERIFY",
                "RECENT_ACTIVITY",
                "RECENT_ACTIVITY_USER_ACCESS",
                "RECENT_ACTIVITY_REPORT_RUN",
                "RECENT_ACTIVITY_FILE_ACCESS",
                "RECENT_ACTIVITY_FILE_ACCESS_FILE",
                "RECENT_ACTIVITY_EXPORT",
                "SUPPLIER_RUNFILE_ASSOCIATION",
                "CHANGE_FILE_MAP",
                "REQUEST_FILE_MAP",
                "ITEM_LIFECYCLE_TRANSITION",
                "ITEM_UOM",
                "ROUTING",
                "COST_ATTRIBUTE",
                "AFS_OBJECT",
                "SUPPLIERITEM_REQUIREMENT",
                "BULK_SESSION",
                "REQUEST_ISSUES",
                "CHANGE_NUMBER_FORMAT_SEQUENCE_PREFIX",
                "PROD_REQUIREMENT",
                "SETTINGS_TEMPLATE",
                "PLM_REFERENCE",
                "NON_REVISION_CONTROLLED_ADDITIONAL_ATTRIBUTE_VALUE",
                "NON_REVISION_CONTROLLED_ADDITIONAL_ATTRIBUTE",
                "CHANGE_IMPLEMENTATION_NOTES",
                "REVISION",
                "REQUIREMENT_BASELINE",
                "PLM_WORKFLOW",
                "ITEM_NUMBER_FORMAT_FIELD",
                "ITEM_REFERENCE",
                "TRAINING",
                "TRAINING_ITEMS",
                "TRAINING_USERS",
                "TRAINING_RECORDS",
                "EXPORT_DEFINITION",
                "ITEM_EXPORT_DEFINITION",
                "EXPORT_RUN",
                "QUALITYPROCESS_STATUS_CHANGE",
                "REQUIREMENT",
                "QUALITY_TEMPLATE",
                "PROJECT_PHASE",
                "PROJECT_TASK",
                "PROJECT_MILESTONE",
                "PROJECT_REFERENCE",
                "VERIFY_PREFIX",
                "TRAINING_PREFIX",
                "NUMBER_SEQUENCE",
                "NUMBER_PREFIX",
                "PROJECT_TEMPLATE",
                "PROJECT_TEMPLATE_PHASE",
                "PROJECT_TEMPLATE_TASK",
                "RELATIONSHIP_TYPE",
                "MANUFACTURER_ITEM_GUID",
                "BC_EMAIL_TEMPLATE",
                "FILE_MARKUP_FILE_ASSOCIATION",
                "CHANGE_IMPL_FILE_ASSOCIATION",
                "CHANGE_MARKUP_FILE_ASSOCIATION",
                "REQUEST_MARKUP_FILE_ASSOCIATION",
                "CHANGE_NUMBER_FORMAT",
                "CHANGE_IMPLEMENTATION_STATUS",
                "TRAINING_FILE_ASSOCIATION",
                "REQUIREMENT_FILE_ASSOCIATION",
                "VERIFY_FILE_ASSOCIATION",
                "PROJECT_FILE_ASSOCIATION",
                "REQUEST_ITEM",
                "SI_SCI_RISK_INDICATOR_ID",
                "ITEM_SCI_RISK_INDICATOR_ID",
                "INTEGRATION",
                "INTEGRATION_EVENT",
                "INTEGRATION_EVENT_ITEM",
                "ADDRESS",
                "SUPPLIER_ADDRESS",
                "SUPPLIER_PHONE_NUMBER",
                "CHANGE_IMPLEMENTATION_TASKS",
                "OUTBOUND_EVENT",
                "EVENT_RESOURCE",
                "OUTBOUND_EVENT_INTEGRATION",
                "TRIGGER",
                "SUPPLIER_APPROVAL_STATUS",
                "FILE_CORRECTION",
                "USER_GROUP",
                "ITEM_BULK_CHANGE",
                "WORKFLOW_DECISION",
                "ITEM_TRAINING_ASSOCIATION",
                "USER_GROUP_MEMBER",
                "QUOTE_LINE",
                "PURCHASE_LINE",
                "CONTACT",
                "CONTACT_PHONE_NUMBER",
                "CONTACT_ADDRESS",
                "INTEGRATED_APP",
                "IMPORT_DEFINITION",
                "IMPORT_RUN",
                "ATTRIBUTE_GROUP",
                "ITEM_NUMBER_RESERVATION",
                "REQUIREMENT_TRACE",
                "FOLDER",
                "EXTRACT_OWNER_USER",
                "TICKET",
                "POLICY",
                "USER_2_POLICY",
                "USER_2_USER_GROUP",
                "DASHBOARD",
                "SCHEDULED_TRIGGER",
                "ON_DEMAND_HOMEPAGE_TRIGGER",
                "GLOBAL",
              ],
            },
          },
        },
        modifiedSpecs: { type: "boolean" },
        modifiedBom: { type: "boolean" },
        modifiedSourcing: { type: "boolean" },
        modifiedFiles: { type: "boolean" },
      },
    },
    supersededItemRevision: {
      type: "object",
      properties: {
        guid: { type: "string" },
        name: { type: "string" },
        number: { type: "string" },
        revisionNumber: { type: "string" },
        lifecyclePhase: {
          type: "object",
          properties: {
            name: { type: "string" },
            stage: { type: "string" },
            guid: { type: "string" },
            id: { type: "integer", format: "int64" },
            plmEntityType: {
              type: "string",
              enum: [
                "ITEM",
                "FILE",
                "FILE_MASTER",
                "REPORT",
                "REPORT_INSTANCE",
                "ITEM_FILE_MAP",
                "AFS_FOLDER",
                "CATEGORY",
                "NUMBER_FORMAT",
                "ITEM_REVISION",
                "BOM_LINE",
                "SUPPLIER",
                "SUPPLIER_ITEM",
                "CHANGE",
                "CHANGE_CUSTOM_ATTRIBUTE",
                "CHANGE_LIFECYCLE",
                "CHANGE_DECISION",
                "REQUEST",
                "REQUEST_CUSTOM_ATTRIBUTE",
                "REQUEST_LIFECYCLE",
                "QUALITY",
                "QUALITY_STEP",
                "PROJECT",
                "PROJECT_SCHEDULE",
                "QUALITY_CUSTOM_ATTRIBUTE",
                "PROJECT_CUSTOM_ATTRIBUTE",
                "DW_EXTRACT",
                "DW_EXTRACT_RUN",
                "DW_EXTRACT_RUNFILE_ASSOCIATION",
                "CHANGE_CUSTOM_CHANGE_VALUE_ID",
                "REQUEST_CUSTOM_ATTRIBUTE_REQUEST_VALUE_ID",
                "EXTRACT_VALUE_ID",
                "ITEM_ADDITIONAL_ATTRIBUTE",
                "ITEM_BOM",
                "ITEM_BOM_SUB",
                "SOURCING_RELATIONSHIP",
                "SUPPLIER_ITEM_GUID",
                "SUPPLIER_GUID",
                "ITEM_CUST_ATTR_SI",
                "ITEM_CUST_ATTR_PROPERTY_ID",
                "REQUEST_ITEM_ECR_ITEM_MAP_ID",
                "QUALITYPROCESS_ASSOCIATION",
                "URL",
                "HISTORY_AUDIT",
                "PROJECT_ITEM_MAP_ID",
                "PROJECT_CHANGE_MAP_ID",
                "PROJECT_ECR_MAP_ID",
                "PROJECT_PROJECT_MAP_ID",
                "CHANGE_ITEM",
                "LIFECYCLE_PHASE",
                "BOMLINE_ADDITIONAL_ATTRIBUTE",
                "SUPPLIER_VALUE_ID",
                "QUALITY_STEP_DECISION",
                "ITEM_COMPLIANCE_REQUIREMENT",
                "ITEM_REQUIREMENT",
                "SUPPLIERITEM_COMPLIANCE_REQUIREMENT",
                "ITEM_BOM_SETTINGS",
                "ITEM_LIFECYCLE_CHANGE",
                "QUALITY_CUSTOM_ATTRIBUTE_QUALITY_PROPERTY_MAP_ID",
                "SUPPLIER_ITEM_RUNFILE_ASSOCIATION",
                "SUPPLIER_ITEM_SUMMARY_ITEM_GUID",
                "PROJECT_ITEM_GUID",
                "QUALITY_AO_ITEM_GUID",
                "SUPPLIER_ITEM_CUST_ATTR_ITEM_ID",
                "CHANGE_REQUEST_ECR_CHANGE_MAP_ID",
                "ATTRIBUTE",
                "BOMLINE_ATTRIBUTE",
                "QUALITY_PREFIX",
                "USER",
                "ADDITIONAL_ATTRIBUTE",
                "REQUEST_EVALUATOR_GROUP",
                "REQUEST_PREFIX",
                "VERIFY",
                "RECENT_ACTIVITY",
                "RECENT_ACTIVITY_USER_ACCESS",
                "RECENT_ACTIVITY_REPORT_RUN",
                "RECENT_ACTIVITY_FILE_ACCESS",
                "RECENT_ACTIVITY_FILE_ACCESS_FILE",
                "RECENT_ACTIVITY_EXPORT",
                "SUPPLIER_RUNFILE_ASSOCIATION",
                "CHANGE_FILE_MAP",
                "REQUEST_FILE_MAP",
                "ITEM_LIFECYCLE_TRANSITION",
                "ITEM_UOM",
                "ROUTING",
                "COST_ATTRIBUTE",
                "AFS_OBJECT",
                "SUPPLIERITEM_REQUIREMENT",
                "BULK_SESSION",
                "REQUEST_ISSUES",
                "CHANGE_NUMBER_FORMAT_SEQUENCE_PREFIX",
                "PROD_REQUIREMENT",
                "SETTINGS_TEMPLATE",
                "PLM_REFERENCE",
                "NON_REVISION_CONTROLLED_ADDITIONAL_ATTRIBUTE_VALUE",
                "NON_REVISION_CONTROLLED_ADDITIONAL_ATTRIBUTE",
                "CHANGE_IMPLEMENTATION_NOTES",
                "REVISION",
                "REQUIREMENT_BASELINE",
                "PLM_WORKFLOW",
                "ITEM_NUMBER_FORMAT_FIELD",
                "ITEM_REFERENCE",
                "TRAINING",
                "TRAINING_ITEMS",
                "TRAINING_USERS",
                "TRAINING_RECORDS",
                "EXPORT_DEFINITION",
                "ITEM_EXPORT_DEFINITION",
                "EXPORT_RUN",
                "QUALITYPROCESS_STATUS_CHANGE",
                "REQUIREMENT",
                "QUALITY_TEMPLATE",
                "PROJECT_PHASE",
                "PROJECT_TASK",
                "PROJECT_MILESTONE",
                "PROJECT_REFERENCE",
                "VERIFY_PREFIX",
                "TRAINING_PREFIX",
                "NUMBER_SEQUENCE",
                "NUMBER_PREFIX",
                "PROJECT_TEMPLATE",
                "PROJECT_TEMPLATE_PHASE",
                "PROJECT_TEMPLATE_TASK",
                "RELATIONSHIP_TYPE",
                "MANUFACTURER_ITEM_GUID",
                "BC_EMAIL_TEMPLATE",
                "FILE_MARKUP_FILE_ASSOCIATION",
                "CHANGE_IMPL_FILE_ASSOCIATION",
                "CHANGE_MARKUP_FILE_ASSOCIATION",
                "REQUEST_MARKUP_FILE_ASSOCIATION",
                "CHANGE_NUMBER_FORMAT",
                "CHANGE_IMPLEMENTATION_STATUS",
                "TRAINING_FILE_ASSOCIATION",
                "REQUIREMENT_FILE_ASSOCIATION",
                "VERIFY_FILE_ASSOCIATION",
                "PROJECT_FILE_ASSOCIATION",
                "REQUEST_ITEM",
                "SI_SCI_RISK_INDICATOR_ID",
                "ITEM_SCI_RISK_INDICATOR_ID",
                "INTEGRATION",
                "INTEGRATION_EVENT",
                "INTEGRATION_EVENT_ITEM",
                "ADDRESS",
                "SUPPLIER_ADDRESS",
                "SUPPLIER_PHONE_NUMBER",
                "CHANGE_IMPLEMENTATION_TASKS",
                "OUTBOUND_EVENT",
                "EVENT_RESOURCE",
                "OUTBOUND_EVENT_INTEGRATION",
                "TRIGGER",
                "SUPPLIER_APPROVAL_STATUS",
                "FILE_CORRECTION",
                "USER_GROUP",
                "ITEM_BULK_CHANGE",
                "WORKFLOW_DECISION",
                "ITEM_TRAINING_ASSOCIATION",
                "USER_GROUP_MEMBER",
                "QUOTE_LINE",
                "PURCHASE_LINE",
                "CONTACT",
                "CONTACT_PHONE_NUMBER",
                "CONTACT_ADDRESS",
                "INTEGRATED_APP",
                "IMPORT_DEFINITION",
                "IMPORT_RUN",
                "ATTRIBUTE_GROUP",
                "ITEM_NUMBER_RESERVATION",
                "REQUIREMENT_TRACE",
                "FOLDER",
                "EXTRACT_OWNER_USER",
                "TICKET",
                "POLICY",
                "USER_2_POLICY",
                "USER_2_USER_GROUP",
                "DASHBOARD",
                "SCHEDULED_TRIGGER",
                "ON_DEMAND_HOMEPAGE_TRIGGER",
                "GLOBAL",
              ],
            },
          },
        },
        modifiedSpecs: { type: "boolean" },
        modifiedBom: { type: "boolean" },
        modifiedSourcing: { type: "boolean" },
        modifiedFiles: { type: "boolean" },
      },
    },
    reconciled: { type: "boolean" },
    reconciledDateTime: { type: "string" },
    reconciledUser: {
      type: "object",
      properties: {
        email: { type: "string" },
        fullName: { type: "string" },
        guid: { type: "string" },
      },
    },
  },
};
export const getEventOutputSchema = {
  type: "object" as const,
  properties: {
    change: {
      type: "object",
      properties: {
        number: { type: "string" },
        title: { type: "string" },
        guid: { type: "string" },
        approvedOnDateTime: { type: "string" },
        effectiveDateTime: { type: "string" },
        effectivityPlannedDateTime: { type: "string" },
        effectivityType: { type: "string" },
        expirationDateTime: { type: "string" },
        lifecycleStatus: {
          type: "object",
          properties: {
            type: {
              type: "string",
              enum: [
                "OPEN",
                "SUBMITTED_FOR_APPROVAL",
                "SUBMITTED",
                "APPROVED",
                "EFFECTIVE",
                "EXPIRED",
                "REJECTED",
                "OPEN_AND_UNLOCKED",
                "OPEN_AND_LOCKED",
                "SUBMITTED_FOR_ROUTING",
                "CANCELED",
                "COMPLETED",
              ],
            },
          },
        },
        affectedItemCount: { type: "integer", format: "int64" },
        category: {
          type: "object",
          properties: {
            categoryName: { type: "string" },
            categoryPath: { type: "string" },
            guid: { type: "string" },
            plmEntityType: {
              type: "string",
              enum: [
                "ITEM",
                "FILE",
                "FILE_MASTER",
                "REPORT",
                "REPORT_INSTANCE",
                "ITEM_FILE_MAP",
                "AFS_FOLDER",
                "CATEGORY",
                "NUMBER_FORMAT",
                "ITEM_REVISION",
                "BOM_LINE",
                "SUPPLIER",
                "SUPPLIER_ITEM",
                "CHANGE",
                "CHANGE_CUSTOM_ATTRIBUTE",
                "CHANGE_LIFECYCLE",
                "CHANGE_DECISION",
                "REQUEST",
                "REQUEST_CUSTOM_ATTRIBUTE",
                "REQUEST_LIFECYCLE",
                "QUALITY",
                "QUALITY_STEP",
                "PROJECT",
                "PROJECT_SCHEDULE",
                "QUALITY_CUSTOM_ATTRIBUTE",
                "PROJECT_CUSTOM_ATTRIBUTE",
                "DW_EXTRACT",
                "DW_EXTRACT_RUN",
                "DW_EXTRACT_RUNFILE_ASSOCIATION",
                "CHANGE_CUSTOM_CHANGE_VALUE_ID",
                "REQUEST_CUSTOM_ATTRIBUTE_REQUEST_VALUE_ID",
                "EXTRACT_VALUE_ID",
                "ITEM_ADDITIONAL_ATTRIBUTE",
                "ITEM_BOM",
                "ITEM_BOM_SUB",
                "SOURCING_RELATIONSHIP",
                "SUPPLIER_ITEM_GUID",
                "SUPPLIER_GUID",
                "ITEM_CUST_ATTR_SI",
                "ITEM_CUST_ATTR_PROPERTY_ID",
                "REQUEST_ITEM_ECR_ITEM_MAP_ID",
                "QUALITYPROCESS_ASSOCIATION",
                "URL",
                "HISTORY_AUDIT",
                "PROJECT_ITEM_MAP_ID",
                "PROJECT_CHANGE_MAP_ID",
                "PROJECT_ECR_MAP_ID",
                "PROJECT_PROJECT_MAP_ID",
                "CHANGE_ITEM",
                "LIFECYCLE_PHASE",
                "BOMLINE_ADDITIONAL_ATTRIBUTE",
                "SUPPLIER_VALUE_ID",
                "QUALITY_STEP_DECISION",
                "ITEM_COMPLIANCE_REQUIREMENT",
                "ITEM_REQUIREMENT",
                "SUPPLIERITEM_COMPLIANCE_REQUIREMENT",
                "ITEM_BOM_SETTINGS",
                "ITEM_LIFECYCLE_CHANGE",
                "QUALITY_CUSTOM_ATTRIBUTE_QUALITY_PROPERTY_MAP_ID",
                "SUPPLIER_ITEM_RUNFILE_ASSOCIATION",
                "SUPPLIER_ITEM_SUMMARY_ITEM_GUID",
                "PROJECT_ITEM_GUID",
                "QUALITY_AO_ITEM_GUID",
                "SUPPLIER_ITEM_CUST_ATTR_ITEM_ID",
                "CHANGE_REQUEST_ECR_CHANGE_MAP_ID",
                "ATTRIBUTE",
                "BOMLINE_ATTRIBUTE",
                "QUALITY_PREFIX",
                "USER",
                "ADDITIONAL_ATTRIBUTE",
                "REQUEST_EVALUATOR_GROUP",
                "REQUEST_PREFIX",
                "VERIFY",
                "RECENT_ACTIVITY",
                "RECENT_ACTIVITY_USER_ACCESS",
                "RECENT_ACTIVITY_REPORT_RUN",
                "RECENT_ACTIVITY_FILE_ACCESS",
                "RECENT_ACTIVITY_FILE_ACCESS_FILE",
                "RECENT_ACTIVITY_EXPORT",
                "SUPPLIER_RUNFILE_ASSOCIATION",
                "CHANGE_FILE_MAP",
                "REQUEST_FILE_MAP",
                "ITEM_LIFECYCLE_TRANSITION",
                "ITEM_UOM",
                "ROUTING",
                "COST_ATTRIBUTE",
                "AFS_OBJECT",
                "SUPPLIERITEM_REQUIREMENT",
                "BULK_SESSION",
                "REQUEST_ISSUES",
                "CHANGE_NUMBER_FORMAT_SEQUENCE_PREFIX",
                "PROD_REQUIREMENT",
                "SETTINGS_TEMPLATE",
                "PLM_REFERENCE",
                "NON_REVISION_CONTROLLED_ADDITIONAL_ATTRIBUTE_VALUE",
                "NON_REVISION_CONTROLLED_ADDITIONAL_ATTRIBUTE",
                "CHANGE_IMPLEMENTATION_NOTES",
                "REVISION",
                "REQUIREMENT_BASELINE",
                "PLM_WORKFLOW",
                "ITEM_NUMBER_FORMAT_FIELD",
                "ITEM_REFERENCE",
                "TRAINING",
                "TRAINING_ITEMS",
                "TRAINING_USERS",
                "TRAINING_RECORDS",
                "EXPORT_DEFINITION",
                "ITEM_EXPORT_DEFINITION",
                "EXPORT_RUN",
                "QUALITYPROCESS_STATUS_CHANGE",
                "REQUIREMENT",
                "QUALITY_TEMPLATE",
                "PROJECT_PHASE",
                "PROJECT_TASK",
                "PROJECT_MILESTONE",
                "PROJECT_REFERENCE",
                "VERIFY_PREFIX",
                "TRAINING_PREFIX",
                "NUMBER_SEQUENCE",
                "NUMBER_PREFIX",
                "PROJECT_TEMPLATE",
                "PROJECT_TEMPLATE_PHASE",
                "PROJECT_TEMPLATE_TASK",
                "RELATIONSHIP_TYPE",
                "MANUFACTURER_ITEM_GUID",
                "BC_EMAIL_TEMPLATE",
                "FILE_MARKUP_FILE_ASSOCIATION",
                "CHANGE_IMPL_FILE_ASSOCIATION",
                "CHANGE_MARKUP_FILE_ASSOCIATION",
                "REQUEST_MARKUP_FILE_ASSOCIATION",
                "CHANGE_NUMBER_FORMAT",
                "CHANGE_IMPLEMENTATION_STATUS",
                "TRAINING_FILE_ASSOCIATION",
                "REQUIREMENT_FILE_ASSOCIATION",
                "VERIFY_FILE_ASSOCIATION",
                "PROJECT_FILE_ASSOCIATION",
                "REQUEST_ITEM",
                "SI_SCI_RISK_INDICATOR_ID",
                "ITEM_SCI_RISK_INDICATOR_ID",
                "INTEGRATION",
                "INTEGRATION_EVENT",
                "INTEGRATION_EVENT_ITEM",
                "ADDRESS",
                "SUPPLIER_ADDRESS",
                "SUPPLIER_PHONE_NUMBER",
                "CHANGE_IMPLEMENTATION_TASKS",
                "OUTBOUND_EVENT",
                "EVENT_RESOURCE",
                "OUTBOUND_EVENT_INTEGRATION",
                "TRIGGER",
                "SUPPLIER_APPROVAL_STATUS",
                "FILE_CORRECTION",
                "USER_GROUP",
                "ITEM_BULK_CHANGE",
                "WORKFLOW_DECISION",
                "ITEM_TRAINING_ASSOCIATION",
                "USER_GROUP_MEMBER",
                "QUOTE_LINE",
                "PURCHASE_LINE",
                "CONTACT",
                "CONTACT_PHONE_NUMBER",
                "CONTACT_ADDRESS",
                "INTEGRATED_APP",
                "IMPORT_DEFINITION",
                "IMPORT_RUN",
                "ATTRIBUTE_GROUP",
                "ITEM_NUMBER_RESERVATION",
                "REQUIREMENT_TRACE",
                "FOLDER",
                "EXTRACT_OWNER_USER",
                "TICKET",
                "POLICY",
                "USER_2_POLICY",
                "USER_2_USER_GROUP",
                "DASHBOARD",
                "SCHEDULED_TRIGGER",
                "ON_DEMAND_HOMEPAGE_TRIGGER",
                "GLOBAL",
              ],
            },
          },
        },
        url: {
          type: "object",
          properties: { api: { type: "string" }, app: { type: "string" } },
        },
      },
    },
    revisioningEvent: {
      type: "object",
      properties: {
        number: { type: "string" },
        guid: { type: "string" },
        performedOnDateTime: { type: "string" },
      },
    },
    reconciled: { type: "boolean" },
    reconciledDateTime: { type: "string" },
    reconciledUser: {
      type: "object",
      properties: {
        email: { type: "string" },
        fullName: { type: "string" },
        guid: { type: "string" },
      },
    },
    creator: {
      type: "object",
      properties: {
        email: { type: "string" },
        fullName: { type: "string" },
        guid: { type: "string" },
      },
    },
    creationDateTime: { type: "string" },
    status: { type: "string" },
    eventType: { type: "string" },
    guid: { type: "string" },
    itemsReconciled: { type: "boolean" },
  },
};
export const getIntegrationOutputSchema = {
  type: "object" as const,
  properties: {
    guid: { type: "string" },
    name: { type: "string" },
    enabled: { type: "boolean" },
    status: { type: "string" },
    type: { type: "string" },
    transferType: { type: "string" },
    creator: {
      type: "object",
      properties: {
        email: { type: "string" },
        fullName: { type: "string" },
        guid: { type: "string" },
      },
    },
    creationDateTime: { type: "string" },
    modifyUser: {
      type: "object",
      properties: {
        email: { type: "string" },
        fullName: { type: "string" },
        guid: { type: "string" },
      },
    },
    modifyDateTime: { type: "string" },
    integrationUser: {
      type: "object",
      properties: {
        email: { type: "string" },
        fullName: { type: "string" },
        guid: { type: "string" },
      },
    },
  },
};
export const integrationShortSchema = {
  type: "object" as const,
  properties: {
    guid: { type: "string" },
    name: { type: "string" },
    enabled: { type: "boolean" },
    status: { type: "string" },
    type: { type: "string" },
    transferType: { type: "string" },
  },
};
export const listEventAssociationsOutputSchema = {
  type: "object" as const,
  properties: {
    results: {
      type: "array",
      items: {
        type: "object",
        properties: {
          change: {
            type: "object",
            properties: {
              number: { type: "string" },
              title: { type: "string" },
              guid: { type: "string" },
              approvedOnDateTime: { type: "string" },
              effectiveDateTime: { type: "string" },
              effectivityPlannedDateTime: { type: "string" },
              effectivityType: { type: "string" },
              expirationDateTime: { type: "string" },
              lifecycleStatus: {
                type: "object",
                properties: {
                  type: {
                    type: "string",
                    enum: [
                      "OPEN",
                      "SUBMITTED_FOR_APPROVAL",
                      "SUBMITTED",
                      "APPROVED",
                      "EFFECTIVE",
                      "EXPIRED",
                      "REJECTED",
                      "OPEN_AND_UNLOCKED",
                      "OPEN_AND_LOCKED",
                      "SUBMITTED_FOR_ROUTING",
                      "CANCELED",
                      "COMPLETED",
                    ],
                  },
                },
              },
              affectedItemCount: { type: "integer", format: "int64" },
              category: {
                type: "object",
                properties: {
                  categoryName: { type: "string" },
                  categoryPath: { type: "string" },
                  guid: { type: "string" },
                  plmEntityType: {
                    type: "string",
                    enum: [
                      "ITEM",
                      "FILE",
                      "FILE_MASTER",
                      "REPORT",
                      "REPORT_INSTANCE",
                      "ITEM_FILE_MAP",
                      "AFS_FOLDER",
                      "CATEGORY",
                      "NUMBER_FORMAT",
                      "ITEM_REVISION",
                      "BOM_LINE",
                      "SUPPLIER",
                      "SUPPLIER_ITEM",
                      "CHANGE",
                      "CHANGE_CUSTOM_ATTRIBUTE",
                      "CHANGE_LIFECYCLE",
                      "CHANGE_DECISION",
                      "REQUEST",
                      "REQUEST_CUSTOM_ATTRIBUTE",
                      "REQUEST_LIFECYCLE",
                      "QUALITY",
                      "QUALITY_STEP",
                      "PROJECT",
                      "PROJECT_SCHEDULE",
                      "QUALITY_CUSTOM_ATTRIBUTE",
                      "PROJECT_CUSTOM_ATTRIBUTE",
                      "DW_EXTRACT",
                      "DW_EXTRACT_RUN",
                      "DW_EXTRACT_RUNFILE_ASSOCIATION",
                      "CHANGE_CUSTOM_CHANGE_VALUE_ID",
                      "REQUEST_CUSTOM_ATTRIBUTE_REQUEST_VALUE_ID",
                      "EXTRACT_VALUE_ID",
                      "ITEM_ADDITIONAL_ATTRIBUTE",
                      "ITEM_BOM",
                      "ITEM_BOM_SUB",
                      "SOURCING_RELATIONSHIP",
                      "SUPPLIER_ITEM_GUID",
                      "SUPPLIER_GUID",
                      "ITEM_CUST_ATTR_SI",
                      "ITEM_CUST_ATTR_PROPERTY_ID",
                      "REQUEST_ITEM_ECR_ITEM_MAP_ID",
                      "QUALITYPROCESS_ASSOCIATION",
                      "URL",
                      "HISTORY_AUDIT",
                      "PROJECT_ITEM_MAP_ID",
                      "PROJECT_CHANGE_MAP_ID",
                      "PROJECT_ECR_MAP_ID",
                      "PROJECT_PROJECT_MAP_ID",
                      "CHANGE_ITEM",
                      "LIFECYCLE_PHASE",
                      "BOMLINE_ADDITIONAL_ATTRIBUTE",
                      "SUPPLIER_VALUE_ID",
                      "QUALITY_STEP_DECISION",
                      "ITEM_COMPLIANCE_REQUIREMENT",
                      "ITEM_REQUIREMENT",
                      "SUPPLIERITEM_COMPLIANCE_REQUIREMENT",
                      "ITEM_BOM_SETTINGS",
                      "ITEM_LIFECYCLE_CHANGE",
                      "QUALITY_CUSTOM_ATTRIBUTE_QUALITY_PROPERTY_MAP_ID",
                      "SUPPLIER_ITEM_RUNFILE_ASSOCIATION",
                      "SUPPLIER_ITEM_SUMMARY_ITEM_GUID",
                      "PROJECT_ITEM_GUID",
                      "QUALITY_AO_ITEM_GUID",
                      "SUPPLIER_ITEM_CUST_ATTR_ITEM_ID",
                      "CHANGE_REQUEST_ECR_CHANGE_MAP_ID",
                      "ATTRIBUTE",
                      "BOMLINE_ATTRIBUTE",
                      "QUALITY_PREFIX",
                      "USER",
                      "ADDITIONAL_ATTRIBUTE",
                      "REQUEST_EVALUATOR_GROUP",
                      "REQUEST_PREFIX",
                      "VERIFY",
                      "RECENT_ACTIVITY",
                      "RECENT_ACTIVITY_USER_ACCESS",
                      "RECENT_ACTIVITY_REPORT_RUN",
                      "RECENT_ACTIVITY_FILE_ACCESS",
                      "RECENT_ACTIVITY_FILE_ACCESS_FILE",
                      "RECENT_ACTIVITY_EXPORT",
                      "SUPPLIER_RUNFILE_ASSOCIATION",
                      "CHANGE_FILE_MAP",
                      "REQUEST_FILE_MAP",
                      "ITEM_LIFECYCLE_TRANSITION",
                      "ITEM_UOM",
                      "ROUTING",
                      "COST_ATTRIBUTE",
                      "AFS_OBJECT",
                      "SUPPLIERITEM_REQUIREMENT",
                      "BULK_SESSION",
                      "REQUEST_ISSUES",
                      "CHANGE_NUMBER_FORMAT_SEQUENCE_PREFIX",
                      "PROD_REQUIREMENT",
                      "SETTINGS_TEMPLATE",
                      "PLM_REFERENCE",
                      "NON_REVISION_CONTROLLED_ADDITIONAL_ATTRIBUTE_VALUE",
                      "NON_REVISION_CONTROLLED_ADDITIONAL_ATTRIBUTE",
                      "CHANGE_IMPLEMENTATION_NOTES",
                      "REVISION",
                      "REQUIREMENT_BASELINE",
                      "PLM_WORKFLOW",
                      "ITEM_NUMBER_FORMAT_FIELD",
                      "ITEM_REFERENCE",
                      "TRAINING",
                      "TRAINING_ITEMS",
                      "TRAINING_USERS",
                      "TRAINING_RECORDS",
                      "EXPORT_DEFINITION",
                      "ITEM_EXPORT_DEFINITION",
                      "EXPORT_RUN",
                      "QUALITYPROCESS_STATUS_CHANGE",
                      "REQUIREMENT",
                      "QUALITY_TEMPLATE",
                      "PROJECT_PHASE",
                      "PROJECT_TASK",
                      "PROJECT_MILESTONE",
                      "PROJECT_REFERENCE",
                      "VERIFY_PREFIX",
                      "TRAINING_PREFIX",
                      "NUMBER_SEQUENCE",
                      "NUMBER_PREFIX",
                      "PROJECT_TEMPLATE",
                      "PROJECT_TEMPLATE_PHASE",
                      "PROJECT_TEMPLATE_TASK",
                      "RELATIONSHIP_TYPE",
                      "MANUFACTURER_ITEM_GUID",
                      "BC_EMAIL_TEMPLATE",
                      "FILE_MARKUP_FILE_ASSOCIATION",
                      "CHANGE_IMPL_FILE_ASSOCIATION",
                      "CHANGE_MARKUP_FILE_ASSOCIATION",
                      "REQUEST_MARKUP_FILE_ASSOCIATION",
                      "CHANGE_NUMBER_FORMAT",
                      "CHANGE_IMPLEMENTATION_STATUS",
                      "TRAINING_FILE_ASSOCIATION",
                      "REQUIREMENT_FILE_ASSOCIATION",
                      "VERIFY_FILE_ASSOCIATION",
                      "PROJECT_FILE_ASSOCIATION",
                      "REQUEST_ITEM",
                      "SI_SCI_RISK_INDICATOR_ID",
                      "ITEM_SCI_RISK_INDICATOR_ID",
                      "INTEGRATION",
                      "INTEGRATION_EVENT",
                      "INTEGRATION_EVENT_ITEM",
                      "ADDRESS",
                      "SUPPLIER_ADDRESS",
                      "SUPPLIER_PHONE_NUMBER",
                      "CHANGE_IMPLEMENTATION_TASKS",
                      "OUTBOUND_EVENT",
                      "EVENT_RESOURCE",
                      "OUTBOUND_EVENT_INTEGRATION",
                      "TRIGGER",
                      "SUPPLIER_APPROVAL_STATUS",
                      "FILE_CORRECTION",
                      "USER_GROUP",
                      "ITEM_BULK_CHANGE",
                      "WORKFLOW_DECISION",
                      "ITEM_TRAINING_ASSOCIATION",
                      "USER_GROUP_MEMBER",
                      "QUOTE_LINE",
                      "PURCHASE_LINE",
                      "CONTACT",
                      "CONTACT_PHONE_NUMBER",
                      "CONTACT_ADDRESS",
                      "INTEGRATED_APP",
                      "IMPORT_DEFINITION",
                      "IMPORT_RUN",
                      "ATTRIBUTE_GROUP",
                      "ITEM_NUMBER_RESERVATION",
                      "REQUIREMENT_TRACE",
                      "FOLDER",
                      "EXTRACT_OWNER_USER",
                      "TICKET",
                      "POLICY",
                      "USER_2_POLICY",
                      "USER_2_USER_GROUP",
                      "DASHBOARD",
                      "SCHEDULED_TRIGGER",
                      "ON_DEMAND_HOMEPAGE_TRIGGER",
                      "GLOBAL",
                    ],
                  },
                },
              },
              url: {
                type: "object",
                properties: {
                  api: { type: "string" },
                  app: { type: "string" },
                },
              },
            },
          },
          revisioningEvent: {
            type: "object",
            properties: {
              number: { type: "string" },
              guid: { type: "string" },
              performedOnDateTime: { type: "string" },
            },
          },
          reconciledDateTime: { type: "string" },
          eventType: { type: "string" },
          guid: { type: "string" },
          reconciled: { type: "boolean" },
          status: { type: "string" },
          creationDateTime: { type: "string" },
          itemsReconciled: { type: "boolean" },
        },
      },
    },
    count: { type: "integer", format: "int32" },
  },
};
export const listEventItemGuidsOutputSchema = {
  type: "object" as const,
  properties: {
    results: { type: "array", items: { type: "string" } },
    count: { type: "integer", format: "int32" },
  },
};
export const listEventItemsOutputSchema = {
  type: "object" as const,
  properties: {
    results: { type: "array", items: eventItemSchema },
    count: { type: "integer", format: "int32" },
  },
};
export const listIntegrationFiltersOutputSchema = {
  type: "object" as const,
  properties: {
    lifecyclePhases: {
      type: "array",
      items: {
        type: "object",
        properties: {
          active: { type: "boolean" },
          displayOrder: { type: "integer", format: "int32" },
          guid: { type: "string" },
          name: { type: "string" },
          shortName: { type: "string" },
          stage: { type: "string" },
          type: { type: "string" },
          used: { type: "boolean" },
        },
      },
    },
    categories: {
      type: "array",
      items: {
        type: "object",
        properties: {
          guid: { type: "string" },
          name: { type: "string" },
          path: { type: "string" },
        },
      },
    },
  },
};
export const listIntegrationsOutputSchema = {
  type: "object" as const,
  properties: {
    results: { type: "array", items: integrationShortSchema },
    count: { type: "integer", format: "int32" },
  },
};
export const outboundEventShortSchema = {
  type: "object" as const,
  properties: {
    triggers: {
      type: "array",
      items: {
        type: "object",
        properties: {
          action: { type: "string" },
          description: { type: "string" },
          guid: { type: "string" },
          name: { type: "string" },
          resource: { type: "string" },
        },
      },
    },
    creator: {
      type: "object",
      properties: {
        email: { type: "string" },
        fullName: { type: "string" },
        guid: { type: "string" },
      },
    },
    resourcesReconciled: { type: "boolean" },
    eventType: { type: "string" },
    status: { type: "string" },
    creationDateTime: { type: "string" },
    guid: { type: "string" },
  },
};
export const listOutboundEventIntegrationEventsOutputSchema = {
  type: "object" as const,
  properties: {
    results: { type: "array", items: outboundEventShortSchema },
    count: { type: "integer", format: "int32" },
  },
};
export const outboundEventIntegrationSchema = {
  type: "object" as const,
  properties: {
    name: { type: "string" },
    enabled: { type: "boolean" },
    status: { type: "string" },
    modifyUser: {
      type: "object",
      properties: {
        email: { type: "string" },
        fullName: { type: "string" },
        guid: { type: "string" },
      },
    },
    creator: {
      type: "object",
      properties: {
        email: { type: "string" },
        fullName: { type: "string" },
        guid: { type: "string" },
      },
    },
    lastModifiedDateTime: { type: "string" },
    guid: { type: "string" },
    creationDateTime: { type: "string" },
  },
};
export const listOutboundEventIntegrationsOutputSchema = {
  type: "object" as const,
  properties: {
    results: { type: "array", items: outboundEventIntegrationSchema },
    count: { type: "integer", format: "int32" },
  },
};
export const triggerShortSchema = {
  type: "object" as const,
  properties: {
    action: { type: "string" },
    description: { type: "string" },
    guid: { type: "string" },
    name: { type: "string" },
    resource: { type: "string" },
  },
};
export const listOutboundEventIntegrationTriggersOutputSchema = {
  type: "object" as const,
  properties: {
    results: { type: "array", items: triggerShortSchema },
    count: { type: "integer", format: "int32" },
  },
};
export const outboundEventResourceSchema = {
  type: "object" as const,
  properties: {
    reconciledUser: {
      type: "object",
      properties: {
        email: { type: "string" },
        fullName: { type: "string" },
        guid: { type: "string" },
      },
    },
    reconciledDatetime: { type: "string" },
    guid: { type: "string" },
    reconciled: { type: "boolean" },
    change: {
      type: "object",
      properties: {
        guid: { type: "string" },
        url: {
          type: "object",
          properties: { api: { type: "string" }, app: { type: "string" } },
        },
      },
    },
    item: { type: "object", properties: { guid: { type: "string" } } },
    request: { type: "object", properties: { guid: { type: "string" } } },
    qualityProcess: {
      type: "object",
      properties: { guid: { type: "string" } },
    },
    preEvents: {
      type: "array",
      items: { type: "object", additionalProperties: {} },
    },
    postEvents: {
      type: "array",
      items: { type: "object", additionalProperties: {} },
    },
  },
};
export const listOutboundEventResourcesOutputSchema = {
  type: "object" as const,
  properties: {
    results: { type: "array", items: outboundEventResourceSchema },
    count: { type: "integer", format: "int32" },
  },
};
