export const addRequirementQualityOutputSchema = {
  type: "object" as const,
  properties: {
    guid: { type: "string" },
    creationDateTime: { type: "string" },
    quality: {
      type: "object",
      properties: {
        guid: { type: "string" },
        creationDateTime: { type: "string" },
        number: { type: "string" },
        step: {
          type: "object",
          properties: {
            guid: { type: "string" },
            creationDateTime: { type: "string" },
            name: { type: "string" },
            allowOwnerToAddApprovers: { type: "boolean" },
            users: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  id: { type: "integer", format: "int64" },
                  guid: { type: "string" },
                  creationDateTime: { type: "string" },
                  creatorId: { type: "integer", format: "int64" },
                  mappingId: { type: "integer", format: "int64" },
                  modifierId: { type: "integer", format: "int64" },
                  workspaceId: { type: "integer", format: "int64" },
                  fullName: { type: "string" },
                  email: { type: "string" },
                  type: {
                    type: "string",
                    enum: [
                      "ALL",
                      "EMPLOYEE",
                      "PARTNER",
                      "SUPPLIER",
                      "BASIC_SUPPLIER",
                      "ADVANCED_SUPPLIER",
                      "INTEGRATION_USER",
                    ],
                  },
                  enabled_p: { type: "string" },
                  name: { type: "string" },
                  defaultValue: {},
                  enabled: { type: "string" },
                  plmEntityType: {
                    type: "string",
                    enum: [
                      "ITEM",
                      "FILE",
                      "FILE_MASTER",
                      "REPORT",
                      "REPORT_INSTANCE",
                      "ITEM_FILE_MAP",
                      "AFS_FOLDER",
                      "CATEGORY",
                      "NUMBER_FORMAT",
                      "ITEM_REVISION",
                      "BOM_LINE",
                      "SUPPLIER",
                      "SUPPLIER_ITEM",
                      "CHANGE",
                      "CHANGE_CUSTOM_ATTRIBUTE",
                      "CHANGE_LIFECYCLE",
                      "CHANGE_DECISION",
                      "REQUEST",
                      "REQUEST_CUSTOM_ATTRIBUTE",
                      "REQUEST_LIFECYCLE",
                      "QUALITY",
                      "QUALITY_STEP",
                      "PROJECT",
                      "PROJECT_SCHEDULE",
                      "QUALITY_CUSTOM_ATTRIBUTE",
                      "PROJECT_CUSTOM_ATTRIBUTE",
                      "DW_EXTRACT",
                      "DW_EXTRACT_RUN",
                      "DW_EXTRACT_RUNFILE_ASSOCIATION",
                      "CHANGE_CUSTOM_CHANGE_VALUE_ID",
                      "REQUEST_CUSTOM_ATTRIBUTE_REQUEST_VALUE_ID",
                      "EXTRACT_VALUE_ID",
                      "ITEM_ADDITIONAL_ATTRIBUTE",
                      "ITEM_BOM",
                      "ITEM_BOM_SUB",
                      "SOURCING_RELATIONSHIP",
                      "SUPPLIER_ITEM_GUID",
                      "SUPPLIER_GUID",
                      "ITEM_CUST_ATTR_SI",
                      "ITEM_CUST_ATTR_PROPERTY_ID",
                      "REQUEST_ITEM_ECR_ITEM_MAP_ID",
                      "QUALITYPROCESS_ASSOCIATION",
                      "URL",
                      "HISTORY_AUDIT",
                      "PROJECT_ITEM_MAP_ID",
                      "PROJECT_CHANGE_MAP_ID",
                      "PROJECT_ECR_MAP_ID",
                      "PROJECT_PROJECT_MAP_ID",
                      "CHANGE_ITEM",
                      "LIFECYCLE_PHASE",
                      "BOMLINE_ADDITIONAL_ATTRIBUTE",
                      "SUPPLIER_VALUE_ID",
                      "QUALITY_STEP_DECISION",
                      "ITEM_COMPLIANCE_REQUIREMENT",
                      "ITEM_REQUIREMENT",
                      "SUPPLIERITEM_COMPLIANCE_REQUIREMENT",
                      "ITEM_BOM_SETTINGS",
                      "ITEM_LIFECYCLE_CHANGE",
                      "QUALITY_CUSTOM_ATTRIBUTE_QUALITY_PROPERTY_MAP_ID",
                      "SUPPLIER_ITEM_RUNFILE_ASSOCIATION",
                      "SUPPLIER_ITEM_SUMMARY_ITEM_GUID",
                      "PROJECT_ITEM_GUID",
                      "QUALITY_AO_ITEM_GUID",
                      "SUPPLIER_ITEM_CUST_ATTR_ITEM_ID",
                      "CHANGE_REQUEST_ECR_CHANGE_MAP_ID",
                      "ATTRIBUTE",
                      "BOMLINE_ATTRIBUTE",
                      "QUALITY_PREFIX",
                      "USER",
                      "ADDITIONAL_ATTRIBUTE",
                      "REQUEST_EVALUATOR_GROUP",
                      "REQUEST_PREFIX",
                      "VERIFY",
                      "RECENT_ACTIVITY",
                      "RECENT_ACTIVITY_USER_ACCESS",
                      "RECENT_ACTIVITY_REPORT_RUN",
                      "RECENT_ACTIVITY_FILE_ACCESS",
                      "RECENT_ACTIVITY_FILE_ACCESS_FILE",
                      "RECENT_ACTIVITY_EXPORT",
                      "SUPPLIER_RUNFILE_ASSOCIATION",
                      "CHANGE_FILE_MAP",
                      "REQUEST_FILE_MAP",
                      "ITEM_LIFECYCLE_TRANSITION",
                      "ITEM_UOM",
                      "ROUTING",
                      "COST_ATTRIBUTE",
                      "AFS_OBJECT",
                      "SUPPLIERITEM_REQUIREMENT",
                      "BULK_SESSION",
                      "REQUEST_ISSUES",
                      "CHANGE_NUMBER_FORMAT_SEQUENCE_PREFIX",
                      "PROD_REQUIREMENT",
                      "SETTINGS_TEMPLATE",
                      "PLM_REFERENCE",
                      "NON_REVISION_CONTROLLED_ADDITIONAL_ATTRIBUTE_VALUE",
                      "NON_REVISION_CONTROLLED_ADDITIONAL_ATTRIBUTE",
                      "CHANGE_IMPLEMENTATION_NOTES",
                      "REVISION",
                      "REQUIREMENT_BASELINE",
                      "PLM_WORKFLOW",
                      "ITEM_NUMBER_FORMAT_FIELD",
                      "ITEM_REFERENCE",
                      "TRAINING",
                      "TRAINING_ITEMS",
                      "TRAINING_USERS",
                      "TRAINING_RECORDS",
                      "EXPORT_DEFINITION",
                      "ITEM_EXPORT_DEFINITION",
                      "EXPORT_RUN",
                      "QUALITYPROCESS_STATUS_CHANGE",
                      "REQUIREMENT",
                      "QUALITY_TEMPLATE",
                      "PROJECT_PHASE",
                      "PROJECT_TASK",
                      "PROJECT_MILESTONE",
                      "PROJECT_REFERENCE",
                      "VERIFY_PREFIX",
                      "TRAINING_PREFIX",
                      "NUMBER_SEQUENCE",
                      "NUMBER_PREFIX",
                      "PROJECT_TEMPLATE",
                      "PROJECT_TEMPLATE_PHASE",
                      "PROJECT_TEMPLATE_TASK",
                      "RELATIONSHIP_TYPE",
                      "MANUFACTURER_ITEM_GUID",
                      "BC_EMAIL_TEMPLATE",
                      "FILE_MARKUP_FILE_ASSOCIATION",
                      "CHANGE_IMPL_FILE_ASSOCIATION",
                      "CHANGE_MARKUP_FILE_ASSOCIATION",
                      "REQUEST_MARKUP_FILE_ASSOCIATION",
                      "CHANGE_NUMBER_FORMAT",
                      "CHANGE_IMPLEMENTATION_STATUS",
                      "TRAINING_FILE_ASSOCIATION",
                      "REQUIREMENT_FILE_ASSOCIATION",
                      "VERIFY_FILE_ASSOCIATION",
                      "PROJECT_FILE_ASSOCIATION",
                      "REQUEST_ITEM",
                      "SI_SCI_RISK_INDICATOR_ID",
                      "ITEM_SCI_RISK_INDICATOR_ID",
                      "INTEGRATION",
                      "INTEGRATION_EVENT",
                      "INTEGRATION_EVENT_ITEM",
                      "ADDRESS",
                      "SUPPLIER_ADDRESS",
                      "SUPPLIER_PHONE_NUMBER",
                      "CHANGE_IMPLEMENTATION_TASKS",
                      "OUTBOUND_EVENT",
                      "EVENT_RESOURCE",
                      "OUTBOUND_EVENT_INTEGRATION",
                      "TRIGGER",
                      "SUPPLIER_APPROVAL_STATUS",
                      "FILE_CORRECTION",
                      "USER_GROUP",
                      "ITEM_BULK_CHANGE",
                      "WORKFLOW_DECISION",
                      "ITEM_TRAINING_ASSOCIATION",
                      "USER_GROUP_MEMBER",
                      "QUOTE_LINE",
                      "PURCHASE_LINE",
                      "CONTACT",
                      "CONTACT_PHONE_NUMBER",
                      "CONTACT_ADDRESS",
                      "INTEGRATED_APP",
                      "IMPORT_DEFINITION",
                      "IMPORT_RUN",
                      "ATTRIBUTE_GROUP",
                      "ITEM_NUMBER_RESERVATION",
                      "REQUIREMENT_TRACE",
                      "FOLDER",
                      "EXTRACT_OWNER_USER",
                      "TICKET",
                      "POLICY",
                      "USER_2_POLICY",
                      "USER_2_USER_GROUP",
                      "DASHBOARD",
                      "SCHEDULED_TRIGGER",
                      "ON_DEMAND_HOMEPAGE_TRIGGER",
                      "GLOBAL",
                    ],
                  },
                  getGuid: { type: "string" },
                },
              },
            },
            attributes: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  guid: { type: "string" },
                  creationDateTime: { type: "string" },
                  creatorId: { type: "integer", format: "int64" },
                  mappingId: { type: "integer", format: "int64" },
                  modifierId: { type: "integer", format: "int64" },
                  workspaceId: { type: "integer", format: "int64" },
                  parentObjectId: { type: "integer", format: "int64" },
                  value: {},
                  name: { type: "string" },
                  apiName: { type: "string" },
                  fieldType: {
                    type: "string",
                    enum: [
                      "SINGLE_LINE_TEXT",
                      "MULTI_LINE_TEXT",
                      "DROP_DOWN",
                      "FIXED_DROP_DOWN",
                      "DATE",
                      "NUMBER",
                      "BOOLEAN",
                      "INTEGER",
                      "OBJECT",
                      "POSITIVE_DOUBLE",
                      "POSITIVE_INTEGER",
                      "RICH_TEXT",
                      "GUID",
                      "DATETIME",
                      "COST",
                      "LIST",
                      "ENUM",
                    ],
                  },
                  plmEntityType: {
                    type: "string",
                    enum: [
                      "ITEM",
                      "FILE",
                      "FILE_MASTER",
                      "REPORT",
                      "REPORT_INSTANCE",
                      "ITEM_FILE_MAP",
                      "AFS_FOLDER",
                      "CATEGORY",
                      "NUMBER_FORMAT",
                      "ITEM_REVISION",
                      "BOM_LINE",
                      "SUPPLIER",
                      "SUPPLIER_ITEM",
                      "CHANGE",
                      "CHANGE_CUSTOM_ATTRIBUTE",
                      "CHANGE_LIFECYCLE",
                      "CHANGE_DECISION",
                      "REQUEST",
                      "REQUEST_CUSTOM_ATTRIBUTE",
                      "REQUEST_LIFECYCLE",
                      "QUALITY",
                      "QUALITY_STEP",
                      "PROJECT",
                      "PROJECT_SCHEDULE",
                      "QUALITY_CUSTOM_ATTRIBUTE",
                      "PROJECT_CUSTOM_ATTRIBUTE",
                      "DW_EXTRACT",
                      "DW_EXTRACT_RUN",
                      "DW_EXTRACT_RUNFILE_ASSOCIATION",
                      "CHANGE_CUSTOM_CHANGE_VALUE_ID",
                      "REQUEST_CUSTOM_ATTRIBUTE_REQUEST_VALUE_ID",
                      "EXTRACT_VALUE_ID",
                      "ITEM_ADDITIONAL_ATTRIBUTE",
                      "ITEM_BOM",
                      "ITEM_BOM_SUB",
                      "SOURCING_RELATIONSHIP",
                      "SUPPLIER_ITEM_GUID",
                      "SUPPLIER_GUID",
                      "ITEM_CUST_ATTR_SI",
                      "ITEM_CUST_ATTR_PROPERTY_ID",
                      "REQUEST_ITEM_ECR_ITEM_MAP_ID",
                      "QUALITYPROCESS_ASSOCIATION",
                      "URL",
                      "HISTORY_AUDIT",
                      "PROJECT_ITEM_MAP_ID",
                      "PROJECT_CHANGE_MAP_ID",
                      "PROJECT_ECR_MAP_ID",
                      "PROJECT_PROJECT_MAP_ID",
                      "CHANGE_ITEM",
                      "LIFECYCLE_PHASE",
                      "BOMLINE_ADDITIONAL_ATTRIBUTE",
                      "SUPPLIER_VALUE_ID",
                      "QUALITY_STEP_DECISION",
                      "ITEM_COMPLIANCE_REQUIREMENT",
                      "ITEM_REQUIREMENT",
                      "SUPPLIERITEM_COMPLIANCE_REQUIREMENT",
                      "ITEM_BOM_SETTINGS",
                      "ITEM_LIFECYCLE_CHANGE",
                      "QUALITY_CUSTOM_ATTRIBUTE_QUALITY_PROPERTY_MAP_ID",
                      "SUPPLIER_ITEM_RUNFILE_ASSOCIATION",
                      "SUPPLIER_ITEM_SUMMARY_ITEM_GUID",
                      "PROJECT_ITEM_GUID",
                      "QUALITY_AO_ITEM_GUID",
                      "SUPPLIER_ITEM_CUST_ATTR_ITEM_ID",
                      "CHANGE_REQUEST_ECR_CHANGE_MAP_ID",
                      "ATTRIBUTE",
                      "BOMLINE_ATTRIBUTE",
                      "QUALITY_PREFIX",
                      "USER",
                      "ADDITIONAL_ATTRIBUTE",
                      "REQUEST_EVALUATOR_GROUP",
                      "REQUEST_PREFIX",
                      "VERIFY",
                      "RECENT_ACTIVITY",
                      "RECENT_ACTIVITY_USER_ACCESS",
                      "RECENT_ACTIVITY_REPORT_RUN",
                      "RECENT_ACTIVITY_FILE_ACCESS",
                      "RECENT_ACTIVITY_FILE_ACCESS_FILE",
                      "RECENT_ACTIVITY_EXPORT",
                      "SUPPLIER_RUNFILE_ASSOCIATION",
                      "CHANGE_FILE_MAP",
                      "REQUEST_FILE_MAP",
                      "ITEM_LIFECYCLE_TRANSITION",
                      "ITEM_UOM",
                      "ROUTING",
                      "COST_ATTRIBUTE",
                      "AFS_OBJECT",
                      "SUPPLIERITEM_REQUIREMENT",
                      "BULK_SESSION",
                      "REQUEST_ISSUES",
                      "CHANGE_NUMBER_FORMAT_SEQUENCE_PREFIX",
                      "PROD_REQUIREMENT",
                      "SETTINGS_TEMPLATE",
                      "PLM_REFERENCE",
                      "NON_REVISION_CONTROLLED_ADDITIONAL_ATTRIBUTE_VALUE",
                      "NON_REVISION_CONTROLLED_ADDITIONAL_ATTRIBUTE",
                      "CHANGE_IMPLEMENTATION_NOTES",
                      "REVISION",
                      "REQUIREMENT_BASELINE",
                      "PLM_WORKFLOW",
                      "ITEM_NUMBER_FORMAT_FIELD",
                      "ITEM_REFERENCE",
                      "TRAINING",
                      "TRAINING_ITEMS",
                      "TRAINING_USERS",
                      "TRAINING_RECORDS",
                      "EXPORT_DEFINITION",
                      "ITEM_EXPORT_DEFINITION",
                      "EXPORT_RUN",
                      "QUALITYPROCESS_STATUS_CHANGE",
                      "REQUIREMENT",
                      "QUALITY_TEMPLATE",
                      "PROJECT_PHASE",
                      "PROJECT_TASK",
                      "PROJECT_MILESTONE",
                      "PROJECT_REFERENCE",
                      "VERIFY_PREFIX",
                      "TRAINING_PREFIX",
                      "NUMBER_SEQUENCE",
                      "NUMBER_PREFIX",
                      "PROJECT_TEMPLATE",
                      "PROJECT_TEMPLATE_PHASE",
                      "PROJECT_TEMPLATE_TASK",
                      "RELATIONSHIP_TYPE",
                      "MANUFACTURER_ITEM_GUID",
                      "BC_EMAIL_TEMPLATE",
                      "FILE_MARKUP_FILE_ASSOCIATION",
                      "CHANGE_IMPL_FILE_ASSOCIATION",
                      "CHANGE_MARKUP_FILE_ASSOCIATION",
                      "REQUEST_MARKUP_FILE_ASSOCIATION",
                      "CHANGE_NUMBER_FORMAT",
                      "CHANGE_IMPLEMENTATION_STATUS",
                      "TRAINING_FILE_ASSOCIATION",
                      "REQUIREMENT_FILE_ASSOCIATION",
                      "VERIFY_FILE_ASSOCIATION",
                      "PROJECT_FILE_ASSOCIATION",
                      "REQUEST_ITEM",
                      "SI_SCI_RISK_INDICATOR_ID",
                      "ITEM_SCI_RISK_INDICATOR_ID",
                      "INTEGRATION",
                      "INTEGRATION_EVENT",
                      "INTEGRATION_EVENT_ITEM",
                      "ADDRESS",
                      "SUPPLIER_ADDRESS",
                      "SUPPLIER_PHONE_NUMBER",
                      "CHANGE_IMPLEMENTATION_TASKS",
                      "OUTBOUND_EVENT",
                      "EVENT_RESOURCE",
                      "OUTBOUND_EVENT_INTEGRATION",
                      "TRIGGER",
                      "SUPPLIER_APPROVAL_STATUS",
                      "FILE_CORRECTION",
                      "USER_GROUP",
                      "ITEM_BULK_CHANGE",
                      "WORKFLOW_DECISION",
                      "ITEM_TRAINING_ASSOCIATION",
                      "USER_GROUP_MEMBER",
                      "QUOTE_LINE",
                      "PURCHASE_LINE",
                      "CONTACT",
                      "CONTACT_PHONE_NUMBER",
                      "CONTACT_ADDRESS",
                      "INTEGRATED_APP",
                      "IMPORT_DEFINITION",
                      "IMPORT_RUN",
                      "ATTRIBUTE_GROUP",
                      "ITEM_NUMBER_RESERVATION",
                      "REQUIREMENT_TRACE",
                      "FOLDER",
                      "EXTRACT_OWNER_USER",
                      "TICKET",
                      "POLICY",
                      "USER_2_POLICY",
                      "USER_2_USER_GROUP",
                      "DASHBOARD",
                      "SCHEDULED_TRIGGER",
                      "ON_DEMAND_HOMEPAGE_TRIGGER",
                      "GLOBAL",
                    ],
                  },
                  attributeGroupId: { type: "integer", format: "int64" },
                  userInput: { type: "boolean" },
                  valueSetToNull: { type: "boolean" },
                  multiSelect: { type: "boolean" },
                  readableValue: { type: "string" },
                  getGuid: { type: "string" },
                },
              },
            },
            decision: { type: "string" },
            reopenedUser: {
              type: "object",
              properties: {
                email: { type: "string" },
                fullName: { type: "string" },
                guid: { type: "string" },
              },
            },
            reopenedDateTime: { type: "string" },
          },
        },
      },
    },
  },
};
export const addRequirementTicketOutputSchema = {
  type: "object" as const,
  properties: {
    id: { type: "integer", format: "int64" },
    guid: { type: "string" },
    creationDateTime: { type: "string" },
    creatorId: { type: "integer", format: "int64" },
    mappingId: { type: "integer", format: "int64" },
    modifierId: { type: "integer", format: "int64" },
    workspaceId: { type: "integer", format: "int64" },
    verifyCompactRep: {
      type: "object",
      properties: {
        guid: { type: "string" },
        creationDateTime: { type: "string" },
        number: { type: "string" },
      },
    },
    plmEntityType: {
      type: "string",
      enum: [
        "ITEM",
        "FILE",
        "FILE_MASTER",
        "REPORT",
        "REPORT_INSTANCE",
        "ITEM_FILE_MAP",
        "AFS_FOLDER",
        "CATEGORY",
        "NUMBER_FORMAT",
        "ITEM_REVISION",
        "BOM_LINE",
        "SUPPLIER",
        "SUPPLIER_ITEM",
        "CHANGE",
        "CHANGE_CUSTOM_ATTRIBUTE",
        "CHANGE_LIFECYCLE",
        "CHANGE_DECISION",
        "REQUEST",
        "REQUEST_CUSTOM_ATTRIBUTE",
        "REQUEST_LIFECYCLE",
        "QUALITY",
        "QUALITY_STEP",
        "PROJECT",
        "PROJECT_SCHEDULE",
        "QUALITY_CUSTOM_ATTRIBUTE",
        "PROJECT_CUSTOM_ATTRIBUTE",
        "DW_EXTRACT",
        "DW_EXTRACT_RUN",
        "DW_EXTRACT_RUNFILE_ASSOCIATION",
        "CHANGE_CUSTOM_CHANGE_VALUE_ID",
        "REQUEST_CUSTOM_ATTRIBUTE_REQUEST_VALUE_ID",
        "EXTRACT_VALUE_ID",
        "ITEM_ADDITIONAL_ATTRIBUTE",
        "ITEM_BOM",
        "ITEM_BOM_SUB",
        "SOURCING_RELATIONSHIP",
        "SUPPLIER_ITEM_GUID",
        "SUPPLIER_GUID",
        "ITEM_CUST_ATTR_SI",
        "ITEM_CUST_ATTR_PROPERTY_ID",
        "REQUEST_ITEM_ECR_ITEM_MAP_ID",
        "QUALITYPROCESS_ASSOCIATION",
        "URL",
        "HISTORY_AUDIT",
        "PROJECT_ITEM_MAP_ID",
        "PROJECT_CHANGE_MAP_ID",
        "PROJECT_ECR_MAP_ID",
        "PROJECT_PROJECT_MAP_ID",
        "CHANGE_ITEM",
        "LIFECYCLE_PHASE",
        "BOMLINE_ADDITIONAL_ATTRIBUTE",
        "SUPPLIER_VALUE_ID",
        "QUALITY_STEP_DECISION",
        "ITEM_COMPLIANCE_REQUIREMENT",
        "ITEM_REQUIREMENT",
        "SUPPLIERITEM_COMPLIANCE_REQUIREMENT",
        "ITEM_BOM_SETTINGS",
        "ITEM_LIFECYCLE_CHANGE",
        "QUALITY_CUSTOM_ATTRIBUTE_QUALITY_PROPERTY_MAP_ID",
        "SUPPLIER_ITEM_RUNFILE_ASSOCIATION",
        "SUPPLIER_ITEM_SUMMARY_ITEM_GUID",
        "PROJECT_ITEM_GUID",
        "QUALITY_AO_ITEM_GUID",
        "SUPPLIER_ITEM_CUST_ATTR_ITEM_ID",
        "CHANGE_REQUEST_ECR_CHANGE_MAP_ID",
        "ATTRIBUTE",
        "BOMLINE_ATTRIBUTE",
        "QUALITY_PREFIX",
        "USER",
        "ADDITIONAL_ATTRIBUTE",
        "REQUEST_EVALUATOR_GROUP",
        "REQUEST_PREFIX",
        "VERIFY",
        "RECENT_ACTIVITY",
        "RECENT_ACTIVITY_USER_ACCESS",
        "RECENT_ACTIVITY_REPORT_RUN",
        "RECENT_ACTIVITY_FILE_ACCESS",
        "RECENT_ACTIVITY_FILE_ACCESS_FILE",
        "RECENT_ACTIVITY_EXPORT",
        "SUPPLIER_RUNFILE_ASSOCIATION",
        "CHANGE_FILE_MAP",
        "REQUEST_FILE_MAP",
        "ITEM_LIFECYCLE_TRANSITION",
        "ITEM_UOM",
        "ROUTING",
        "COST_ATTRIBUTE",
        "AFS_OBJECT",
        "SUPPLIERITEM_REQUIREMENT",
        "BULK_SESSION",
        "REQUEST_ISSUES",
        "CHANGE_NUMBER_FORMAT_SEQUENCE_PREFIX",
        "PROD_REQUIREMENT",
        "SETTINGS_TEMPLATE",
        "PLM_REFERENCE",
        "NON_REVISION_CONTROLLED_ADDITIONAL_ATTRIBUTE_VALUE",
        "NON_REVISION_CONTROLLED_ADDITIONAL_ATTRIBUTE",
        "CHANGE_IMPLEMENTATION_NOTES",
        "REVISION",
        "REQUIREMENT_BASELINE",
        "PLM_WORKFLOW",
        "ITEM_NUMBER_FORMAT_FIELD",
        "ITEM_REFERENCE",
        "TRAINING",
        "TRAINING_ITEMS",
        "TRAINING_USERS",
        "TRAINING_RECORDS",
        "EXPORT_DEFINITION",
        "ITEM_EXPORT_DEFINITION",
        "EXPORT_RUN",
        "QUALITYPROCESS_STATUS_CHANGE",
        "REQUIREMENT",
        "QUALITY_TEMPLATE",
        "PROJECT_PHASE",
        "PROJECT_TASK",
        "PROJECT_MILESTONE",
        "PROJECT_REFERENCE",
        "VERIFY_PREFIX",
        "TRAINING_PREFIX",
        "NUMBER_SEQUENCE",
        "NUMBER_PREFIX",
        "PROJECT_TEMPLATE",
        "PROJECT_TEMPLATE_PHASE",
        "PROJECT_TEMPLATE_TASK",
        "RELATIONSHIP_TYPE",
        "MANUFACTURER_ITEM_GUID",
        "BC_EMAIL_TEMPLATE",
        "FILE_MARKUP_FILE_ASSOCIATION",
        "CHANGE_IMPL_FILE_ASSOCIATION",
        "CHANGE_MARKUP_FILE_ASSOCIATION",
        "REQUEST_MARKUP_FILE_ASSOCIATION",
        "CHANGE_NUMBER_FORMAT",
        "CHANGE_IMPLEMENTATION_STATUS",
        "TRAINING_FILE_ASSOCIATION",
        "REQUIREMENT_FILE_ASSOCIATION",
        "VERIFY_FILE_ASSOCIATION",
        "PROJECT_FILE_ASSOCIATION",
        "REQUEST_ITEM",
        "SI_SCI_RISK_INDICATOR_ID",
        "ITEM_SCI_RISK_INDICATOR_ID",
        "INTEGRATION",
        "INTEGRATION_EVENT",
        "INTEGRATION_EVENT_ITEM",
        "ADDRESS",
        "SUPPLIER_ADDRESS",
        "SUPPLIER_PHONE_NUMBER",
        "CHANGE_IMPLEMENTATION_TASKS",
        "OUTBOUND_EVENT",
        "EVENT_RESOURCE",
        "OUTBOUND_EVENT_INTEGRATION",
        "TRIGGER",
        "SUPPLIER_APPROVAL_STATUS",
        "FILE_CORRECTION",
        "USER_GROUP",
        "ITEM_BULK_CHANGE",
        "WORKFLOW_DECISION",
        "ITEM_TRAINING_ASSOCIATION",
        "USER_GROUP_MEMBER",
        "QUOTE_LINE",
        "PURCHASE_LINE",
        "CONTACT",
        "CONTACT_PHONE_NUMBER",
        "CONTACT_ADDRESS",
        "INTEGRATED_APP",
        "IMPORT_DEFINITION",
        "IMPORT_RUN",
        "ATTRIBUTE_GROUP",
        "ITEM_NUMBER_RESERVATION",
        "REQUIREMENT_TRACE",
        "FOLDER",
        "EXTRACT_OWNER_USER",
        "TICKET",
        "POLICY",
        "USER_2_POLICY",
        "USER_2_USER_GROUP",
        "DASHBOARD",
        "SCHEDULED_TRIGGER",
        "ON_DEMAND_HOMEPAGE_TRIGGER",
        "GLOBAL",
      ],
    },
    getGuid: { type: "string" },
  },
};
export const deleteRequirementOutputSchema = {
  type: "object" as const,
  properties: { success: { type: "boolean" }, message: { type: "string" } },
  required: ["success", "message"],
};
export const deleteRequirementTraceOutputSchema = {
  type: "object" as const,
  properties: { success: { type: "boolean" }, message: { type: "string" } },
  required: ["success", "message"],
};
export const requirementFileAssociationSchema = {
  type: "object" as const,
  properties: {
    guid: { type: "string" },
    file: {
      type: "object",
      properties: {
        author: {
          type: "object",
          properties: { fullName: { type: "string" } },
        },
        category: {
          type: "object",
          properties: { guid: { type: "string" }, name: { type: "string" } },
        },
        checkedOut: { type: "boolean" },
        checkoutDateTime: { type: "string" },
        corrected: { type: "boolean" },
        creationDateTime: { type: "string" },
        description: { type: "string" },
        edition: { type: "string" },
        format: { type: "string" },
        guid: { type: "string" },
        hasMarkup: { type: "boolean" },
        haveContent: { type: "boolean" },
        lastModifiedDateTime: { type: "string" },
        latest: { type: "boolean" },
        location: { type: "string" },
        locked: { type: "boolean" },
        microsoft365: {
          type: "object",
          properties: {
            authorEmail: { type: "string" },
            creationDate: { type: "string" },
            driveId: { type: "string" },
            fileId: { type: "string" },
            fileName: { type: "string" },
            lastEditors: { type: "array", items: { type: "string" } },
            modifiedDate: { type: "string" },
            originalAuthor: { type: "string" },
            siteId: { type: "string" },
            size: { type: "integer", format: "int64" },
            version: { type: "string" },
            webUrl: { type: "string" },
          },
        },
        googleDocs: {
          type: "object",
          properties: {
            authorEmail: { type: "string" },
            creationDate: { type: "string" },
            driveId: { type: "string" },
            fileId: { type: "string" },
            fileName: { type: "string" },
            lastEditors: { type: "array", items: { type: "string" } },
            modifiedDate: { type: "string" },
            originalAuthor: { type: "string" },
            size: { type: "integer", format: "int64" },
            version: { type: "string" },
            webUrl: { type: "string" },
          },
        },
        mimeType: { type: "string" },
        name: { type: "string" },
        number: { type: "string" },
        size: { type: "integer", format: "int64" },
        storageMethodName: { type: "string" },
        title: { type: "string" },
        private: { type: "boolean" },
      },
    },
    latestEditionAssociation: { type: "boolean" },
  },
};
export const listRequirementFilesOutputSchema = {
  type: "object" as const,
  properties: {
    results: { type: "array", items: requirementFileAssociationSchema },
    count: { type: "integer", format: "int32" },
  },
};
export const relationshipTypeSchema = {
  type: "object" as const,
  properties: {
    guid: { type: "string" },
    name: { type: "string" },
    active: { type: "boolean" },
    upstreamLabel: { type: "string" },
    downstreamLabel: { type: "string" },
    description: { type: "string" },
  },
};
export const listRequirementRelationshipTypesOutputSchema = {
  type: "object" as const,
  properties: {
    results: { type: "array", items: relationshipTypeSchema },
    count: { type: "integer", format: "int32" },
  },
};
export const requirementTemplateSchema = {
  type: "object" as const,
  properties: {
    active: { type: "boolean" },
    allowUserDefinedNumber: { type: "boolean" },
    creationDateTime: { type: "string" },
    creator: {
      type: "object",
      properties: {
        email: { type: "string" },
        fullName: { type: "string" },
        guid: { type: "string" },
      },
    },
    defaultAssignee: {
      type: "object",
      properties: {
        email: { type: "string" },
        fullName: { type: "string" },
        guid: { type: "string" },
      },
    },
    defaultNumberSequence: {
      type: "object",
      properties: {
        guid: { type: "string" },
        name: { type: "string" },
        prefixes: {
          type: "array",
          items: {
            type: "object",
            properties: { guid: { type: "string" }, value: { type: "string" } },
          },
        },
      },
    },
    defaultTemplate: { type: "boolean" },
    description: { type: "string" },
    folder: {
      type: "object",
      properties: { guid: { type: "string" }, name: { type: "string" } },
    },
    guid: { type: "string" },
    name: { type: "string" },
    numberSequences: {
      type: "array",
      items: {
        type: "object",
        properties: {
          guid: { type: "string" },
          name: { type: "string" },
          prefixes: {
            type: "array",
            items: {
              type: "object",
              properties: {
                guid: { type: "string" },
                value: { type: "string" },
              },
            },
          },
        },
      },
    },
  },
};
export const listRequirementTemplatesOutputSchema = {
  type: "object" as const,
  properties: {
    results: { type: "array", items: requirementTemplateSchema },
    count: { type: "integer", format: "int32" },
  },
};
export const requirementTraceSchema = {
  type: "object" as const,
  properties: {
    guid: { type: "string" },
    level: { type: "integer", format: "int32" },
    relationshipType: {
      type: "object",
      properties: {
        guid: { type: "string" },
        upstreamLabel: { type: "string" },
        downstreamLabel: { type: "string" },
      },
    },
    suspected: { type: "boolean" },
    objectType: { type: "string" },
    requirement: {
      type: "object",
      properties: {
        assignee: {
          type: "object",
          properties: {
            email: { type: "string" },
            fullName: { type: "string" },
            guid: { type: "string" },
          },
        },
        creationDateTime: { type: "string" },
        creator: {
          type: "object",
          properties: {
            email: { type: "string" },
            fullName: { type: "string" },
            guid: { type: "string" },
          },
        },
        modifier: {
          type: "object",
          properties: {
            email: { type: "string" },
            fullName: { type: "string" },
            guid: { type: "string" },
          },
        },
        modificationDateTime: { type: "string" },
        description: { type: "string" },
        guid: { type: "string" },
        title: { type: "string" },
        number: { type: "string" },
        priority: { type: "string" },
        status: {
          type: "object",
          properties: {
            guid: { type: "string" },
            value: { type: "string" },
            code: { type: "string" },
          },
        },
        template: {
          type: "object",
          properties: { guid: { type: "string" }, name: { type: "string" } },
        },
        additionalAttributes: {
          type: "array",
          items: {
            type: "object",
            properties: {
              apiName: { type: "string" },
              fieldType: {
                type: "string",
                enum: [
                  "SINGLE_LINE_TEXT",
                  "MULTI_LINE_TEXT",
                  "DROP_DOWN",
                  "FIXED_DROP_DOWN",
                  "DATE",
                  "NUMBER",
                  "BOOLEAN",
                  "INTEGER",
                  "OBJECT",
                  "POSITIVE_DOUBLE",
                  "POSITIVE_INTEGER",
                  "RICH_TEXT",
                  "GUID",
                  "DATETIME",
                  "COST",
                  "LIST",
                  "ENUM",
                ],
              },
              guid: { type: "string" },
              multiSelect: { type: "boolean" },
              name: { type: "string" },
              value: {},
            },
          },
        },
      },
    },
    item: {
      type: "object",
      properties: {
        guid: { type: "string" },
        name: { type: "string" },
        number: { type: "string" },
        revisionNumber: { type: "string" },
        revisionStatus: { type: "string" },
        url: {
          type: "object",
          properties: { api: { type: "string" }, app: { type: "string" } },
        },
      },
    },
  },
};
export const listRequirementTracesOutputSchema = {
  type: "object" as const,
  properties: {
    results: { type: "array", items: requirementTraceSchema },
    count: { type: "integer", format: "int32" },
  },
};
export const removeRequirementChildOutputSchema = {
  type: "object" as const,
  properties: { success: { type: "boolean" }, message: { type: "string" } },
  required: ["success", "message"],
};
export const removeRequirementFileAssociationOutputSchema = {
  type: "object" as const,
  properties: { success: { type: "boolean" }, message: { type: "string" } },
  required: ["success", "message"],
};
export const removeRequirementQualityAssociationOutputSchema = {
  type: "object" as const,
  properties: { success: { type: "boolean" }, message: { type: "string" } },
  required: ["success", "message"],
};
export const removeRequirementTicketAssociationOutputSchema = {
  type: "object" as const,
  properties: { success: { type: "boolean" }, message: { type: "string" } },
  required: ["success", "message"],
};
export const requirementSchema = {
  type: "object" as const,
  properties: {
    assignee: {
      type: "object",
      properties: {
        email: { type: "string" },
        fullName: { type: "string" },
        guid: { type: "string" },
      },
    },
    creationDateTime: { type: "string" },
    creator: {
      type: "object",
      properties: {
        email: { type: "string" },
        fullName: { type: "string" },
        guid: { type: "string" },
      },
    },
    modifier: {
      type: "object",
      properties: {
        email: { type: "string" },
        fullName: { type: "string" },
        guid: { type: "string" },
      },
    },
    modificationDateTime: { type: "string" },
    description: { type: "string" },
    guid: { type: "string" },
    title: { type: "string" },
    number: { type: "string" },
    priority: { type: "string" },
    status: {
      type: "object",
      properties: {
        guid: { type: "string" },
        value: { type: "string" },
        code: { type: "string" },
      },
    },
    template: {
      type: "object",
      properties: { guid: { type: "string" }, name: { type: "string" } },
    },
    additionalAttributes: {
      type: "array",
      items: {
        type: "object",
        properties: {
          apiName: { type: "string" },
          fieldType: {
            type: "string",
            enum: [
              "SINGLE_LINE_TEXT",
              "MULTI_LINE_TEXT",
              "DROP_DOWN",
              "FIXED_DROP_DOWN",
              "DATE",
              "NUMBER",
              "BOOLEAN",
              "INTEGER",
              "OBJECT",
              "POSITIVE_DOUBLE",
              "POSITIVE_INTEGER",
              "RICH_TEXT",
              "GUID",
              "DATETIME",
              "COST",
              "LIST",
              "ENUM",
            ],
          },
          guid: { type: "string" },
          multiSelect: { type: "boolean" },
          name: { type: "string" },
          value: {},
        },
      },
    },
  },
};
export const requirementListSchema = {
  type: "object" as const,
  properties: {
    results: { type: "array", items: requirementSchema },
    count: { type: "integer", format: "int32" },
  },
};
