export const attributeDefinitionSchema = {
  type: "object" as const,
  properties: {
    guid: { type: "string" },
    active: { type: "boolean" },
    allowLowerCase: { type: "boolean" },
    allowNegatives: { type: "boolean" },
    allowUpperCase: { type: "boolean" },
    allowsExplicitNullValue: { type: "boolean" },
    creatable: { type: "boolean" },
    custom: { type: "boolean" },
    deleted: { type: "boolean" },
    deprecated: { type: "boolean" },
    editable: { type: "boolean" },
    global: { type: "boolean" },
    apiName: { type: "string" },
    costCalculation: {
      type: "string",
      enum: ["ENTERED", "ROLLUP", "ROLLUP_AND_ENTERED"],
    },
    currency: {
      type: "string",
      enum: [
        "USD",
        "EUR",
        "GBP",
        "YEN",
        "AUD",
        "CAD",
        "CNY",
        "INR",
        "JPY",
        "KRW",
        "NZD",
        "SEK",
        "DKK",
        "NOK",
      ],
    },
    decimalPlaces: { type: "integer", format: "int32" },
    defaultValue: {},
    developerNotes: { type: "string" },
    description: { type: "string" },
    example: { type: "string" },
    excludedValues: { type: "array", items: { type: "string" } },
    fieldType: {
      type: "string",
      enum: [
        "SINGLE_LINE_TEXT",
        "MULTI_LINE_TEXT",
        "DROP_DOWN",
        "FIXED_DROP_DOWN",
        "DATE",
        "NUMBER",
        "BOOLEAN",
        "INTEGER",
        "OBJECT",
        "POSITIVE_DOUBLE",
        "POSITIVE_INTEGER",
        "RICH_TEXT",
        "GUID",
        "DATETIME",
        "COST",
        "LIST",
        "ENUM",
      ],
    },
    inViews: {
      type: "array",
      items: {
        type: "string",
        enum: [
          "EMPTY_VIEW",
          "ITEM_SPECS",
          "ITEM_BOM",
          "ITEM_WHEREUSED",
          "ITEM_SOURCING",
          "ITEM_COSTING",
          "ITEM_FILES",
          "ITEM_COMPLIANCE",
          "ITEM_REVISIONS",
          "ITEM_NOTIFICATIONS",
          "ITEM_SUPPLIER_ACCESS",
          "ITEM_PROJECTS",
          "ITEM_QUALITY",
          "ITEM_CUSTOM",
          "ITEM_CUSTOM_NON_REV",
          "ITEM_TRAINING",
          "ITEM_TRAINING_PLANS",
          "ITEM_TRAINING_RECORDS",
          "ITEM_TRAINING_QUIZ",
          "ITEM_TRAINING_QUIZ_HISTORY",
          "ITEM_VERIFY",
          "ITEM_REFERENCES",
          "REQUEST_SUMMARY",
          "REQUEST_FILES",
          "REQUEST_ITEMS",
          "REQUEST_PARTICIPANTS",
          "REQUEST_EVALUATION",
          "REQUEST_CHANGES",
          "REQUEST_STATUS",
          "REQUEST_RECENT_ACTIVITY",
          "REQUEST_PROJECTS",
          "REQUEST_QUALITY",
          "REQUEST_CUSTOM",
          "CHANGE_SUMMARY",
          "CHANGE_FILES",
          "CHANGE_ITEMS",
          "CHANGE_REQUESTS",
          "CHANGE_APPROVAL_ROUTINGS",
          "CHANGE_APPROVAL_DECISIONS",
          "CHANGE_IMPLEMENTATION",
          "CHANGE_ALERTS",
          "CHANGE_NOTIFICATIONS",
          "CHANGE_STATUS",
          "CHANGE_PROJECTS",
          "CHANGE_QUALITY",
          "CHANGE_SUPPLIER_ACCESS",
          "CHANGE_CUSTOM",
          "CHANGE_VERIFY",
          "SUPPLIER_PROFILE",
          "SUPPLIER_CONTACTS",
          "SUPPLIER_SUPPLIER_ITEMS",
          "SUPPLIER_SOURCING_LINES",
          "SUPPLIER_SOURCED_ITEMS",
          "SUPPLIER_FILES",
          "SUPPLIER_QUALITY",
          "SUPPLIER_CUSTOM",
          "SUPPLIER_ITEMS_QUALITY",
          "SI_SPECS",
          "SI_SOURCING_LINES",
          "SI_QUOTES",
          "SI_PURCHASES",
          "SI_FILES",
          "SI_COMPLIANCE",
          "SI_LOOKUP",
          "SI_CUSTOM",
          "FILE_SUMMARY",
          "FILE_ASSOCIATIONS",
          "FILE_EDITIONS",
          "FILE_MARKUPS",
          "FILE_RECENT_ACTIVITY",
          "FILE_PROJECTS",
          "FILE_QUALITY",
          "PROJECT_SUMMARY",
          "PROJECT_SCHEDULE",
          "PROJECT_REFERENCES",
          "PROJECT_QUALITY",
          "QUALITY_SUMMARY",
          "QUALITY_DETAILS",
          "QUALITY_AFFECTED",
          "QUALITY_PROJECTS",
          "QUALITY_SUPPLIER_ACCESS",
          "QUALITY_HISTORY",
          "TRAINING_SUMMARY",
          "TRAINING_ITEMS",
          "TRAINING_RECORDS",
          "TRAINING_USERS",
          "TRAINING_HISTORY",
          "TRAINING_PROGRESS",
          "REQUIREMENT_SUMMARY",
          "REQUIREMENT_TREE",
          "REQUIREMENT_TRACE",
          "REQUIREMENT_REFERENCES",
          "REQUIREMENT_FILES",
          "REQUIREMENT_HISTORY",
          "REQUIREMENT_BASELINES",
          "EXPORT_SUMMARY",
          "VERIFY_SUMMARY",
          "VERIFY_FILES",
          "VERIFY_REFERENCES",
          "VERIFY_HISTORY",
        ],
      },
      uniqueItems: true,
    },
    maskingValue: {},
    maxLength: { type: "integer", format: "int32" },
    maxSelections: { type: "integer", format: "int32" },
    maxValue: { type: "number", format: "double" },
    multiSelect: { type: "boolean" },
    name: { type: "string" },
    possibleValues: { type: "array", items: {} },
    required: { type: "boolean" },
    revisionControlled: { type: "boolean" },
    searchable: { type: "boolean" },
    visibleWhenBlank: { type: "boolean" },
    revisionType: {
      type: "string",
      enum: [
        "NON_REVISION_CONTROLLED",
        "REVISION_SPECIFIC",
        "REVISION_CONTROLLED",
      ],
    },
    private: { type: "boolean" },
  },
};
export const attributeDefinitionFullRepListSchema = {
  type: "object" as const,
  properties: {
    results: { type: "array", items: attributeDefinitionSchema },
    count: { type: "integer", format: "int32" },
  },
};
export const categoryAttributeDefinitionSchema = {
  type: "object" as const,
  properties: {
    guid: { type: "string" },
    active: { type: "boolean" },
    allowLowerCase: { type: "boolean" },
    allowNegatives: { type: "boolean" },
    allowUpperCase: { type: "boolean" },
    allowsExplicitNullValue: { type: "boolean" },
    creatable: { type: "boolean" },
    custom: { type: "boolean" },
    deleted: { type: "boolean" },
    deprecated: { type: "boolean" },
    editable: { type: "boolean" },
    global: { type: "boolean" },
    apiName: { type: "string" },
    costCalculation: {
      type: "string",
      enum: ["ENTERED", "ROLLUP", "ROLLUP_AND_ENTERED"],
    },
    currency: {
      type: "string",
      enum: [
        "USD",
        "EUR",
        "GBP",
        "YEN",
        "AUD",
        "CAD",
        "CNY",
        "INR",
        "JPY",
        "KRW",
        "NZD",
        "SEK",
        "DKK",
        "NOK",
      ],
    },
    decimalPlaces: { type: "integer", format: "int32" },
    defaultValue: {},
    developerNotes: { type: "string" },
    description: { type: "string" },
    example: { type: "string" },
    excludedValues: { type: "array", items: { type: "string" } },
    fieldType: {
      type: "string",
      enum: [
        "SINGLE_LINE_TEXT",
        "MULTI_LINE_TEXT",
        "DROP_DOWN",
        "FIXED_DROP_DOWN",
        "DATE",
        "NUMBER",
        "BOOLEAN",
        "INTEGER",
        "OBJECT",
        "POSITIVE_DOUBLE",
        "POSITIVE_INTEGER",
        "RICH_TEXT",
        "GUID",
        "DATETIME",
        "COST",
        "LIST",
        "ENUM",
      ],
    },
    inViews: {
      type: "array",
      items: {
        type: "string",
        enum: [
          "EMPTY_VIEW",
          "ITEM_SPECS",
          "ITEM_BOM",
          "ITEM_WHEREUSED",
          "ITEM_SOURCING",
          "ITEM_COSTING",
          "ITEM_FILES",
          "ITEM_COMPLIANCE",
          "ITEM_REVISIONS",
          "ITEM_NOTIFICATIONS",
          "ITEM_SUPPLIER_ACCESS",
          "ITEM_PROJECTS",
          "ITEM_QUALITY",
          "ITEM_CUSTOM",
          "ITEM_CUSTOM_NON_REV",
          "ITEM_TRAINING",
          "ITEM_TRAINING_PLANS",
          "ITEM_TRAINING_RECORDS",
          "ITEM_TRAINING_QUIZ",
          "ITEM_TRAINING_QUIZ_HISTORY",
          "ITEM_VERIFY",
          "ITEM_REFERENCES",
          "REQUEST_SUMMARY",
          "REQUEST_FILES",
          "REQUEST_ITEMS",
          "REQUEST_PARTICIPANTS",
          "REQUEST_EVALUATION",
          "REQUEST_CHANGES",
          "REQUEST_STATUS",
          "REQUEST_RECENT_ACTIVITY",
          "REQUEST_PROJECTS",
          "REQUEST_QUALITY",
          "REQUEST_CUSTOM",
          "CHANGE_SUMMARY",
          "CHANGE_FILES",
          "CHANGE_ITEMS",
          "CHANGE_REQUESTS",
          "CHANGE_APPROVAL_ROUTINGS",
          "CHANGE_APPROVAL_DECISIONS",
          "CHANGE_IMPLEMENTATION",
          "CHANGE_ALERTS",
          "CHANGE_NOTIFICATIONS",
          "CHANGE_STATUS",
          "CHANGE_PROJECTS",
          "CHANGE_QUALITY",
          "CHANGE_SUPPLIER_ACCESS",
          "CHANGE_CUSTOM",
          "CHANGE_VERIFY",
          "SUPPLIER_PROFILE",
          "SUPPLIER_CONTACTS",
          "SUPPLIER_SUPPLIER_ITEMS",
          "SUPPLIER_SOURCING_LINES",
          "SUPPLIER_SOURCED_ITEMS",
          "SUPPLIER_FILES",
          "SUPPLIER_QUALITY",
          "SUPPLIER_CUSTOM",
          "SUPPLIER_ITEMS_QUALITY",
          "SI_SPECS",
          "SI_SOURCING_LINES",
          "SI_QUOTES",
          "SI_PURCHASES",
          "SI_FILES",
          "SI_COMPLIANCE",
          "SI_LOOKUP",
          "SI_CUSTOM",
          "FILE_SUMMARY",
          "FILE_ASSOCIATIONS",
          "FILE_EDITIONS",
          "FILE_MARKUPS",
          "FILE_RECENT_ACTIVITY",
          "FILE_PROJECTS",
          "FILE_QUALITY",
          "PROJECT_SUMMARY",
          "PROJECT_SCHEDULE",
          "PROJECT_REFERENCES",
          "PROJECT_QUALITY",
          "QUALITY_SUMMARY",
          "QUALITY_DETAILS",
          "QUALITY_AFFECTED",
          "QUALITY_PROJECTS",
          "QUALITY_SUPPLIER_ACCESS",
          "QUALITY_HISTORY",
          "TRAINING_SUMMARY",
          "TRAINING_ITEMS",
          "TRAINING_RECORDS",
          "TRAINING_USERS",
          "TRAINING_HISTORY",
          "TRAINING_PROGRESS",
          "REQUIREMENT_SUMMARY",
          "REQUIREMENT_TREE",
          "REQUIREMENT_TRACE",
          "REQUIREMENT_REFERENCES",
          "REQUIREMENT_FILES",
          "REQUIREMENT_HISTORY",
          "REQUIREMENT_BASELINES",
          "EXPORT_SUMMARY",
          "VERIFY_SUMMARY",
          "VERIFY_FILES",
          "VERIFY_REFERENCES",
          "VERIFY_HISTORY",
        ],
      },
      uniqueItems: true,
    },
    maskingValue: {},
    maxLength: { type: "integer", format: "int32" },
    maxSelections: { type: "integer", format: "int32" },
    maxValue: { type: "number", format: "double" },
    multiSelect: { type: "boolean" },
    name: { type: "string" },
    possibleValues: { type: "array", items: {} },
    required: { type: "boolean" },
    revisionControlled: { type: "boolean" },
    searchable: { type: "boolean" },
    visibleWhenBlank: { type: "boolean" },
    origin: {
      type: "object",
      properties: { guid: { type: "string" }, name: { type: "string" } },
    },
    private: { type: "boolean" },
  },
};
export const categoryAttributeDefinitionListSchema = {
  type: "object" as const,
  properties: {
    results: { type: "array", items: categoryAttributeDefinitionSchema },
    count: { type: "integer", format: "int32" },
  },
};
export const qualityAssociationSchema = {
  type: "object" as const,
  properties: {
    guid: { type: "string" },
    notes: { type: "string" },
    qualityProcess: {
      type: "object",
      properties: {
        guid: { type: "string" },
        name: { type: "string" },
        number: { type: "string" },
        step: {
          type: "object",
          properties: { guid: { type: "string" }, name: { type: "string" } },
        },
        type: { type: "string" },
      },
    },
  },
};
export const changeQualityAssociationListSchema = {
  type: "object" as const,
  properties: {
    results: { type: "array", items: qualityAssociationSchema },
    count: { type: "integer", format: "int32" },
  },
};
export const fileAssociationSchema = {
  type: "object" as const,
  properties: {
    guid: { type: "string" },
    file: {
      type: "object",
      properties: {
        author: {
          type: "object",
          properties: { fullName: { type: "string" } },
        },
        category: {
          type: "object",
          properties: { guid: { type: "string" }, name: { type: "string" } },
        },
        checkedOut: { type: "boolean" },
        checkoutDateTime: { type: "string" },
        corrected: { type: "boolean" },
        creationDateTime: { type: "string" },
        description: { type: "string" },
        edition: { type: "string" },
        format: { type: "string" },
        guid: { type: "string" },
        hasMarkup: { type: "boolean" },
        haveContent: { type: "boolean" },
        lastModifiedDateTime: { type: "string" },
        latest: { type: "boolean" },
        location: { type: "string" },
        locked: { type: "boolean" },
        microsoft365: {
          type: "object",
          properties: {
            authorEmail: { type: "string" },
            creationDate: { type: "string" },
            driveId: { type: "string" },
            fileId: { type: "string" },
            fileName: { type: "string" },
            lastEditors: { type: "array", items: { type: "string" } },
            modifiedDate: { type: "string" },
            originalAuthor: { type: "string" },
            siteId: { type: "string" },
            size: { type: "integer", format: "int64" },
            version: { type: "string" },
            webUrl: { type: "string" },
          },
        },
        googleDocs: {
          type: "object",
          properties: {
            authorEmail: { type: "string" },
            creationDate: { type: "string" },
            driveId: { type: "string" },
            fileId: { type: "string" },
            fileName: { type: "string" },
            lastEditors: { type: "array", items: { type: "string" } },
            modifiedDate: { type: "string" },
            originalAuthor: { type: "string" },
            size: { type: "integer", format: "int64" },
            version: { type: "string" },
            webUrl: { type: "string" },
          },
        },
        mimeType: { type: "string" },
        name: { type: "string" },
        number: { type: "string" },
        size: { type: "integer", format: "int64" },
        storageMethodName: { type: "string" },
        title: { type: "string" },
        private: { type: "boolean" },
      },
    },
  },
};
export const fileAssociationListSchema = {
  type: "object" as const,
  properties: {
    results: { type: "array", items: fileAssociationSchema },
    count: { type: "integer", format: "int32" },
  },
};
export const itemToTicketSchema = {
  type: "object" as const,
  properties: {
    guid: { type: "string" },
    ticket: {
      type: "object",
      properties: { guid: { type: "string" }, number: { type: "string" } },
    },
  },
};
export const itemTicketListSchema = {
  type: "object" as const,
  properties: {
    results: { type: "array", items: itemToTicketSchema },
    count: { type: "integer", format: "int32" },
  },
};
export const numberFormatPrefixSchema = {
  type: "object" as const,
  properties: { guid: { type: "string" }, value: { type: "string" } },
};
export const numberSequenceCompactSchema = {
  type: "object" as const,
  properties: {
    guid: { type: "string" },
    lastUsed: { type: "string" },
    name: { type: "string" },
    nextValue: { type: "string" },
    prefixes: {
      type: "array",
      items: {
        type: "object",
        properties: { guid: { type: "string" }, value: { type: "string" } },
      },
    },
    creationDateTime: { type: "string" },
  },
};
export const numberSequencePrefixCompactListSchema = {
  type: "object" as const,
  properties: {
    results: { type: "array", items: numberFormatPrefixSchema },
    count: { type: "integer", format: "int32" },
  },
};
export const querySchema = {
  type: "object" as const,
  properties: {
    results: { type: "array", items: {} },
    count: { type: "integer", format: "int32" },
  },
};
export const referencedQualitySchema = {
  type: "object" as const,
  properties: {
    guid: { type: "string" },
    quality: {
      type: "object",
      properties: {
        guid: { type: "string" },
        number: { type: "string" },
        step: {
          type: "object",
          properties: { guid: { type: "string" }, name: { type: "string" } },
        },
      },
    },
  },
};
export const referencedQualityListSchema = {
  type: "object" as const,
  properties: {
    results: { type: "array", items: referencedQualitySchema },
    count: { type: "integer", format: "int32" },
  },
};
export const requestChangeSchema = {
  type: "object" as const,
  properties: {
    guid: { type: "string" },
    change: {
      type: "object",
      properties: { guid: { type: "string" }, number: { type: "string" } },
    },
  },
};
export const requestChangeListSchema = {
  type: "object" as const,
  properties: {
    results: { type: "array", items: requestChangeSchema },
    count: { type: "integer", format: "int32" },
  },
};
export const userCompactSchema = {
  type: "object" as const,
  properties: {
    email: { type: "string" },
    fullName: { type: "string" },
    guid: { type: "string" },
  },
};
export const userCompactListSchema = {
  type: "object" as const,
  properties: {
    results: { type: "array", items: userCompactSchema },
    count: { type: "integer", format: "int32" },
  },
};
export const verifyTemplateSchema = {
  type: "object" as const,
  properties: {
    active: { type: "boolean" },
    allowUserDefinedNumber: { type: "boolean" },
    creationDateTime: { type: "string" },
    creator: {
      type: "object",
      properties: {
        email: { type: "string" },
        fullName: { type: "string" },
        guid: { type: "string" },
      },
    },
    defaultAssignee: {
      type: "object",
      properties: {
        email: { type: "string" },
        fullName: { type: "string" },
        guid: { type: "string" },
      },
    },
    defaultNumberSequence: {
      type: "object",
      properties: {
        guid: { type: "string" },
        name: { type: "string" },
        prefixes: {
          type: "array",
          items: {
            type: "object",
            properties: { guid: { type: "string" }, value: { type: "string" } },
          },
        },
      },
    },
    defaultTemplate: { type: "boolean" },
    description: { type: "string" },
    guid: { type: "string" },
    name: { type: "string" },
    numberSequences: {
      type: "array",
      items: {
        type: "object",
        properties: {
          guid: { type: "string" },
          name: { type: "string" },
          prefixes: {
            type: "array",
            items: {
              type: "object",
              properties: {
                guid: { type: "string" },
                value: { type: "string" },
              },
            },
          },
        },
      },
    },
  },
};
