export const complianceSchema = {
  type: "object" as const,
  properties: {
    defaultEvidenceType: {
      type: "string",
      enum: ["NONE", "DIRECT_FILES", "AML_AND_FILES"],
    },
    evidenceLocation: {
      type: "object",
      properties: {
        allFileCategories: { type: "boolean" },
        fileCategories: {
          type: "array",
          items: {
            type: "object",
            properties: { guid: { type: "string" }, name: { type: "string" } },
          },
        },
      },
    },
    guid: { type: "string" },
    invalidationRule: { type: "string" },
    name: { type: "string" },
    propagate: { type: "boolean" },
    rationaleHint: { type: "string" },
    statementOfRequirement: { type: "string" },
    type: { type: "string", enum: ["ADMIN_DEFINED", "ARENA_DEFINED"] },
    enabled: { type: "boolean" },
  },
};
export const deleteSourcingRelationshipOutputSchema = {
  type: "object" as const,
  properties: {
    success: { type: "boolean" },
    itemGuid: { type: "string" },
    sourcingRelationshipGuid: { type: "string" },
    message: { type: "string" },
    statusCode: { type: "integer" },
  },
  required: [
    "success",
    "itemGuid",
    "sourcingRelationshipGuid",
    "message",
    "statusCode",
  ],
};
export const deleteSupplierAddressOutputSchema = {
  type: "object" as const,
  properties: {
    success: { type: "boolean" },
    message: { type: "string" },
    supplierGuid: { type: "string" },
    addressGuid: { type: "string" },
  },
  required: ["success", "message", "supplierGuid", "addressGuid"],
};
export const deleteSupplierFileAssociationOutputSchema = {
  type: "object" as const,
  properties: {
    success: { type: "boolean" },
    message: { type: "string" },
    supplierGuid: { type: "string" },
    supplierFileAssociationGuid: { type: "string" },
  },
  required: [
    "success",
    "message",
    "supplierGuid",
    "supplierFileAssociationGuid",
  ],
};
export const deleteSupplierItemOutputSchema = {
  type: "object" as const,
  properties: {
    success: { type: "boolean" },
    message: { type: "string" },
    guid: { type: "string" },
  },
  required: ["success", "message", "guid"],
};
export const deleteSupplierOutputSchema = {
  type: "object" as const,
  properties: {
    success: { type: "boolean" },
    message: { type: "string" },
    supplierGuid: { type: "string" },
  },
  required: ["success", "message", "supplierGuid"],
};
export const deleteSupplierPhoneNumberOutputSchema = {
  type: "object" as const,
  properties: {
    success: { type: "boolean" },
    message: { type: "string" },
    supplierGuid: { type: "string" },
    phoneNumberGuid: { type: "string" },
  },
  required: ["success", "message", "supplierGuid", "phoneNumberGuid"],
};
export const itemSourcingSchema = {
  type: "object" as const,
  properties: {
    activeProduction: { type: "boolean" },
    activePrototype: { type: "boolean" },
    amlRank: { type: "integer", format: "int32" },
    amlSplit: { type: "integer", format: "int32" },
    approved: { type: "boolean" },
    guid: { type: "string" },
    item: {
      type: "object",
      properties: {
        guid: { type: "string" },
        name: { type: "string" },
        number: { type: "string" },
        revisionNumber: { type: "string" },
        revisionStatus: { type: "string" },
        url: {
          type: "object",
          properties: { api: { type: "string" }, app: { type: "string" } },
        },
      },
    },
    makeItem: { type: "boolean" },
    mrfItem: {
      type: "object",
      properties: {
        guid: { type: "string" },
        number: { type: "string" },
        supplier: {
          type: "object",
          properties: { guid: { type: "string" }, name: { type: "string" } },
        },
      },
    },
    notes: { type: "string" },
    vendorItem: {
      type: "object",
      properties: {
        guid: { type: "string" },
        number: { type: "string" },
        supplier: {
          type: "object",
          properties: { guid: { type: "string" }, name: { type: "string" } },
        },
      },
    },
    vendorItemConversionFactor: { type: "integer", format: "int32" },
  },
};
export const itemSourcingListSchema = {
  type: "object" as const,
  properties: {
    results: { type: "array", items: itemSourcingSchema },
    count: { type: "integer", format: "int32" },
  },
};
export const supplierAddressCompactSchema = {
  type: "object" as const,
  properties: {
    primary: { type: "boolean" },
    address: {
      type: "object",
      properties: {
        label: { type: "string" },
        address1: { type: "string" },
        address2: { type: "string" },
        city: { type: "string" },
        state: {
          type: "string",
          enum: [
            "ALASKA",
            "AK",
            "ALABAMA",
            "AL",
            "ARKANSAS",
            "AR",
            "ARIZONA",
            "AZ",
            "CALIFORNIA",
            "CA",
            "COLORADO",
            "CO",
            "CONNECTICUT",
            "CT",
            "DISTRICT OF COLUMBIA",
            "DC",
            "DELAWARE",
            "DE",
            "FLORIDA",
            "FL",
            "GEORGIA",
            "GA",
            "HAWAII",
            "HI",
            "IOWA",
            "IA",
            "IDAHO",
            "ID",
            "ILLINOIS",
            "IL",
            "INDIANA",
            "IN",
            "KANSAS",
            "KS",
            "KENTUCKY",
            "KY",
            "LOUISIANA",
            "LA",
            "MASSACHUSETTS",
            "MA",
            "MARYLAND",
            "MD",
            "MAINE",
            "ME",
            "MICHIGAN",
            "MI",
            "MINNESOTA",
            "MN",
            "MISSOURI",
            "MO",
            "MISSISSIPPI",
            "MS",
            "MONTANA",
            "MT",
            "NORTH CAROLINA",
            "NC",
            "NORTH DAKOTA",
            "ND",
            "NEBRASKA",
            "NE",
            "NEW HAMPSHIRE",
            "NH",
            "NEW JERSEY",
            "NJ",
            "NEW MEXICO",
            "NM",
            "NEVADA",
            "NV",
            "NEW YORK",
            "NY",
            "OHIO",
            "OH",
            "OKLAHOMA",
            "OK",
            "OREGON",
            "OR",
            "PENNSYLVANIA",
            "PA",
            "RHODE ISLAND",
            "RI",
            "SOUTH CAROLINA",
            "SC",
            "SOUTH DAKOTA",
            "SD",
            "TENNESSEE",
            "TN",
            "TEXAS",
            "TX",
            "UTAH",
            "UT",
            "VIRGINIA",
            "VA",
            "VERMONT",
            "VT",
            "WASHINGTON",
            "WA",
            "WISCONSIN",
            "WI",
            "WEST VIRGINIA",
            "WV",
            "WYOMING",
            "WY",
          ],
        },
        province: { type: "string" },
        postalCode: { type: "string" },
        country: {
          type: "string",
          enum: [
            "af",
            "Afghanistan",
            "ax",
            "Aland Islands",
            "al",
            "Albania",
            "dz",
            "Algeria",
            "as",
            "American Samoa",
            "ad",
            "Andorra",
            "ao",
            "Angola",
            "ai",
            "Anguilla",
            "aq",
            "Antarctica",
            "ag",
            "Antigua and Barbuda",
            "ar",
            "Argentina",
            "am",
            "Armenia",
            "aw",
            "Aruba",
            "au",
            "Australia",
            "at",
            "Austria",
            "az",
            "Azerbaijan",
            "bs",
            "Bahamas",
            "bh",
            "Bahrain",
            "bd",
            "Bangladesh",
            "bb",
            "Barbados",
            "by",
            "Belarus",
            "be",
            "Belgium",
            "bz",
            "Belize",
            "bj",
            "Benin",
            "bm",
            "Bermuda",
            "bt",
            "Bhutan",
            "bo",
            "Bolivia",
            "ba",
            "Bosnia and Herzegovina",
            "bw",
            "Botswana",
            "bv",
            "Bouvet Island",
            "br",
            "Brazil",
            "io",
            "British Indian Ocean Territory",
            "bn",
            "Brunei Darussalam",
            "bg",
            "Bulgaria",
            "bf",
            "Burkina Faso",
            "bi",
            "Burundi",
            "kh",
            "Cambodia",
            "cm",
            "Cameroon",
            "ca",
            "Canada",
            "cv",
            "Cape Verde",
            "ky",
            "Cayman Islands",
            "cf",
            "Central African Republic",
            "td",
            "Chad",
            "cl",
            "Chile",
            "cn",
            "China",
            "cx",
            "Christmas Island",
            "cc",
            "Cocos (Keeling) Islands",
            "co",
            "Colombia",
            "km",
            "Comoros",
            "cg",
            "Congo",
            "cd",
            "Congo, the Democratic Republic of the",
            "ck",
            "Cook Islands",
            "cr",
            "Costa Rica",
            "hr",
            "Croatia",
            "cu",
            "Cuba",
            "cy",
            "Cyprus",
            "cz",
            "Czech Republic",
            "dk",
            "Denmark",
            "dj",
            "Djibouti",
            "dm",
            "Dominica",
            "do",
            "Dominican Republic",
            "tp",
            "East Timor",
            "ec",
            "Ecuador",
            "eg",
            "Egypt",
            "sv",
            "El Salvador",
            "gq",
            "Equatorial Guinea",
            "er",
            "Eritrea",
            "ee",
            "Estonia",
            "et",
            "Ethiopia",
            "fk",
            "Falkland Islands (Malvinas",
            "fo",
            "Faroe Islands",
            "fj",
            "Fiji",
            "fi",
            "Finland",
            "fr",
            "France",
            "fx",
            "France, Metropolitan",
            "gf",
            "French Guiana",
            "pf",
            "French Polynesia",
            "tf",
            "French Southern Territories",
            "ga",
            "Gabon",
            "gm",
            "Gambia",
            "ge",
            "Georgia",
            "de",
            "Germany",
            "gh",
            "Ghana",
            "gi",
            "Gibraltar",
            "gb",
            "Great Britain (UK)",
            "gr",
            "Greece",
            "gl",
            "Greenland",
            "gd",
            "Grenada",
            "gp",
            "Guadeloupe",
            "gu",
            "Guam",
            "gt",
            "Guatemala",
            "gg",
            "Guernsey",
            "gn",
            "Guinea",
            "gw",
            "Guinea-Bissau",
            "gy",
            "Guyana",
            "ht",
            "Haiti",
            "hm",
            "Heard and McDonald Islands",
            "hn",
            "Honduras",
            "hk",
            "Hong Kong",
            "hu",
            "Hungary",
            "is",
            "Iceland",
            "in",
            "India",
            "id",
            "Indonesia",
            "ir",
            "Iran",
            "iq",
            "Iraq",
            "ie",
            "Ireland",
            "im",
            "Isle of Man",
            "il",
            "Israel",
            "it",
            "Italy",
            "ci",
            "Ivory Coast",
            "jm",
            "Jamaica",
            "jp",
            "Japan",
            "je",
            "Jersey",
            "jo",
            "Jordan",
            "kz",
            "Kazakhstan",
            "ke",
            "Kenya",
            "ki",
            "Kiribati",
            "XK",
            "Kosovo",
            "kw",
            "Kuwait",
            "kg",
            "Kyrgyzstan",
            "la",
            "Laos",
            "lv",
            "Latvia",
            "lb",
            "Lebanon",
            "ls",
            "Lesotho",
            "lr",
            "Liberia",
            "ly",
            "Libya",
            "li",
            "Liechtenstein",
            "lt",
            "Lithuania",
            "lu",
            "Luxembourg",
            "mo",
            "Macau",
            "mg",
            "Madagascar",
            "mw",
            "Malawi",
            "my",
            "Malaysia",
            "mv",
            "Maldives",
            "ml",
            "Mali",
            "mt",
            "Malta",
            "mh",
            "Marshall Islands",
            "mq",
            "Martinique",
            "mr",
            "Mauritania",
            "mu",
            "Mauritius",
            "yt",
            "Mayotte",
            "mx",
            "Mexico",
            "fm",
            "Micronesia",
            "md",
            "Moldova",
            "mc",
            "Monaco",
            "mn",
            "Mongolia",
            "me",
            "Montenegro",
            "ms",
            "Montserrat",
            "ma",
            "Morocco",
            "mz",
            "Mozambique",
            "mm",
            "Myanmar",
            "na",
            "Namibia",
            "nr",
            "Nauru",
            "np",
            "Nepal",
            "nl",
            "Netherlands",
            "an",
            "Netherlands Antilles",
            "nt",
            "Neutral Zone",
            "nc",
            "New Caledonia",
            "nz",
            "New Zealand",
            "ni",
            "Nicaragua",
            "ne",
            "Niger",
            "ng",
            "Nigeria",
            "nu",
            "Niue",
            "nf",
            "Norfolk Island",
            "kp",
            "North Korea",
            "mk",
            "North Macedonia",
            "mp",
            "Northern Mariana Islands",
            "no",
            "Norway",
            "om",
            "Oman",
            "pk",
            "Pakistan",
            "pw",
            "Palau",
            "ps",
            "Palestine",
            "pa",
            "Panama",
            "pg",
            "Papua New Guinea",
            "py",
            "Paraguay",
            "pe",
            "Peru",
            "ph",
            "Philippines",
            "pn",
            "Pitcairn",
            "pl",
            "Poland",
            "pt",
            "Portugal",
            "pr",
            "Puerto Rico",
            "qa",
            "Qatar",
            "re",
            "Reunion",
            "ro",
            "Romania",
            "su",
            "Russia",
            "ru",
            "Russian Federation",
            "rw",
            "Rwanda",
            "gs",
            "S. Georgia and S. Sandwich Isls.",
            "bl",
            "Saint Barthélemy",
            "kn",
            "Saint Kitts and Nevis",
            "lc",
            "Saint Lucia",
            "mf",
            "Saint Martin (French part)",
            "vc",
            "Saint Vincent and the Grenadines",
            "ws",
            "Samoa",
            "sm",
            "San Marino",
            "st",
            "Sao Tome and Principe",
            "sa",
            "Saudi Arabia",
            "sn",
            "Senegal",
            "rs",
            "Serbia",
            "sc",
            "Seychelles",
            "sl",
            "Sierra Leone",
            "sg",
            "Singapore",
            "sk",
            "Slovakia",
            "si",
            "Slovenia",
            "sb",
            "Solomon Islands",
            "so",
            "Somalia",
            "za",
            "South Africa",
            "kr",
            "South Korea",
            "es",
            "Spain",
            "lk",
            "Sri Lanka",
            "sh",
            "St. Helena",
            "pm",
            "St. Pierre and Miquelon",
            "sd",
            "Sudan",
            "sr",
            "Suriname",
            "sj",
            "Svalbard and Jan Mayen Islands",
            "sz",
            "Swaziland",
            "se",
            "Sweden",
            "ch",
            "Switzerland",
            "sy",
            "Syria",
            "tw",
            "Taiwan",
            "tj",
            "Tajikistan",
            "tz",
            "Tanzania",
            "th",
            "Thailand",
            "tl",
            "Timor-Leste",
            "tg",
            "Togo",
            "tk",
            "Tokelau",
            "to",
            "Tonga",
            "tt",
            "Trinidad and Tobago",
            "tn",
            "Tunisia",
            "tr",
            "Turkey",
            "tm",
            "Turkmenistan",
            "tc",
            "Turks and Caicos Islands",
            "tv",
            "Tuvalu",
            "um",
            "US Minor Outlying Islands",
            "ug",
            "Uganda",
            "ua",
            "Ukraine",
            "ae",
            "United Arab Emirates",
            "uk",
            "United Kingdom",
            "us",
            "United States",
            "uy",
            "Uruguay",
            "uz",
            "Uzbekistan",
            "vu",
            "Vanuatu",
            "va",
            "Vatican City State (Holy See)",
            "ve",
            "Venezuela",
            "vn",
            "Vietnam",
            "vg",
            "Virgin Islands (British)",
            "vi",
            "Virgin Islands (U.S.)",
            "wf",
            "Wallis and Futuna Islands",
            "eh",
            "Western Sahara",
            "ye",
            "Yemen",
            "zr",
            "Zaire",
            "zm",
            "Zambia",
            "zw",
            "Zimbabwe",
          ],
        },
        guid: { type: "string" },
      },
    },
  },
};
export const listSupplierAddressesOutputSchema = {
  type: "object" as const,
  properties: {
    results: { type: "array", items: supplierAddressCompactSchema },
    count: { type: "integer", format: "int32" },
  },
};
export const supplierApprovalStatusFullSchema = {
  type: "object" as const,
  properties: {
    name: { type: "string" },
    type: { type: "string" },
    description: { type: "string" },
    used: { type: "boolean" },
    active: { type: "boolean" },
    custom: { type: "boolean" },
    color: { type: "string" },
    guid: { type: "string" },
  },
};
export const listSupplierApprovalStatusesOutputSchema = {
  type: "object" as const,
  properties: {
    results: { type: "array", items: supplierApprovalStatusFullSchema },
    count: { type: "integer", format: "int32" },
  },
};
export const supplierItemComplianceSchema = {
  type: "object" as const,
  properties: {
    evidenceType: { type: "string" },
    guid: { type: "string" },
    lastModifiedBy: {
      type: "object",
      properties: {
        email: { type: "string" },
        fullName: { type: "string" },
        guid: { type: "string" },
      },
    },
    lastModifiedDateTime: { type: "string" },
    mark: { type: "string" },
    rationale: { type: "string" },
    requirement: {
      type: "object",
      properties: { guid: { type: "string" }, name: { type: "string" } },
    },
    status: { type: "string" },
    type: { type: "string" },
  },
};
export const listSupplierItemComplianceOutputSchema = {
  type: "object" as const,
  properties: {
    results: { type: "array", items: supplierItemComplianceSchema },
    count: { type: "integer", format: "int32" },
  },
};
export const supplierItemFileSchema = {
  type: "object" as const,
  properties: {
    file: {
      type: "object",
      properties: {
        author: {
          type: "object",
          properties: { fullName: { type: "string" } },
        },
        category: {
          type: "object",
          properties: { guid: { type: "string" }, name: { type: "string" } },
        },
        checkedOut: { type: "boolean" },
        checkoutDateTime: { type: "string" },
        corrected: { type: "boolean" },
        creationDateTime: { type: "string" },
        description: { type: "string" },
        edition: { type: "string" },
        format: { type: "string" },
        guid: { type: "string" },
        hasMarkup: { type: "boolean" },
        haveContent: { type: "boolean" },
        lastModifiedDateTime: { type: "string" },
        latest: { type: "boolean" },
        location: { type: "string" },
        locked: { type: "boolean" },
        microsoft365: {
          type: "object",
          properties: {
            authorEmail: { type: "string" },
            creationDate: { type: "string" },
            driveId: { type: "string" },
            fileId: { type: "string" },
            fileName: { type: "string" },
            lastEditors: { type: "array", items: { type: "string" } },
            modifiedDate: { type: "string" },
            originalAuthor: { type: "string" },
            siteId: { type: "string" },
            size: { type: "integer", format: "int64" },
            version: { type: "string" },
            webUrl: { type: "string" },
          },
        },
        googleDocs: {
          type: "object",
          properties: {
            authorEmail: { type: "string" },
            creationDate: { type: "string" },
            driveId: { type: "string" },
            fileId: { type: "string" },
            fileName: { type: "string" },
            lastEditors: { type: "array", items: { type: "string" } },
            modifiedDate: { type: "string" },
            originalAuthor: { type: "string" },
            size: { type: "integer", format: "int64" },
            version: { type: "string" },
            webUrl: { type: "string" },
          },
        },
        mimeType: { type: "string" },
        name: { type: "string" },
        number: { type: "string" },
        size: { type: "integer", format: "int64" },
        storageMethodName: { type: "string" },
        title: { type: "string" },
        private: { type: "boolean" },
      },
    },
    guid: { type: "string" },
    primary: { type: "boolean" },
  },
};
export const listSupplierItemFilesOutputSchema = {
  type: "object" as const,
  properties: {
    results: { type: "array", items: supplierItemFileSchema },
    count: { type: "integer", format: "int32" },
  },
};
export const listSupplierItemRequirementsOutputSchema = {
  type: "object" as const,
  properties: {
    results: { type: "array", items: complianceSchema },
    count: { type: "integer", format: "int32" },
  },
};
export const supplierItemFullSchema = {
  type: "object" as const,
  properties: {
    creationDateTime: { type: "string" },
    number: { type: "string" },
    creator: {
      type: "object",
      properties: {
        email: { type: "string" },
        fullName: { type: "string" },
        guid: { type: "string" },
      },
    },
    description: { type: "string" },
    guid: { type: "string" },
    name: { type: "string" },
    uom: { type: "string" },
    offTheShelf: { type: "boolean" },
    type: { type: "string" },
    procurementType: { type: "string", enum: ["OTS", "MTS"] },
    additionalAttributes: {
      type: "array",
      items: {
        type: "object",
        properties: {
          apiName: { type: "string" },
          fieldType: {
            type: "string",
            enum: [
              "SINGLE_LINE_TEXT",
              "MULTI_LINE_TEXT",
              "DROP_DOWN",
              "FIXED_DROP_DOWN",
              "DATE",
              "NUMBER",
              "BOOLEAN",
              "INTEGER",
              "OBJECT",
              "POSITIVE_DOUBLE",
              "POSITIVE_INTEGER",
              "RICH_TEXT",
              "GUID",
              "DATETIME",
              "COST",
              "LIST",
              "ENUM",
            ],
          },
          guid: { type: "string" },
          multiSelect: { type: "boolean" },
          name: { type: "string" },
          value: {},
        },
      },
    },
    supplier: {
      type: "object",
      properties: { guid: { type: "string" }, name: { type: "string" } },
    },
  },
};
export const listSupplierItemsOutputSchema = {
  type: "object" as const,
  properties: {
    results: { type: "array", items: supplierItemFullSchema },
    count: { type: "integer", format: "int32" },
  },
};
export const supplierPhoneNumberSchema = {
  type: "object" as const,
  properties: {
    label: { type: "string" },
    number: { type: "string" },
    extension: { type: "string" },
    comment: { type: "string" },
    guid: { type: "string" },
  },
};
export const listSupplierPhoneNumbersOutputSchema = {
  type: "object" as const,
  properties: {
    results: { type: "array", items: supplierPhoneNumberSchema },
    count: { type: "integer", format: "int32" },
  },
};
export const supplierFullSchema = {
  type: "object" as const,
  properties: {
    accountNumber: { type: "string" },
    additionalAttributes: {
      type: "array",
      items: {
        type: "object",
        properties: {
          apiName: { type: "string" },
          fieldType: {
            type: "string",
            enum: [
              "SINGLE_LINE_TEXT",
              "MULTI_LINE_TEXT",
              "DROP_DOWN",
              "FIXED_DROP_DOWN",
              "DATE",
              "NUMBER",
              "BOOLEAN",
              "INTEGER",
              "OBJECT",
              "POSITIVE_DOUBLE",
              "POSITIVE_INTEGER",
              "RICH_TEXT",
              "GUID",
              "DATETIME",
              "COST",
              "LIST",
              "ENUM",
            ],
          },
          guid: { type: "string" },
          multiSelect: { type: "boolean" },
          name: { type: "string" },
          value: {},
        },
      },
    },
    addresses: {
      type: "array",
      items: {
        type: "object",
        properties: {
          primary: { type: "boolean" },
          address: {
            type: "object",
            properties: {
              label: { type: "string" },
              address1: { type: "string" },
              address2: { type: "string" },
              city: { type: "string" },
              state: {
                type: "string",
                enum: [
                  "ALASKA",
                  "AK",
                  "ALABAMA",
                  "AL",
                  "ARKANSAS",
                  "AR",
                  "ARIZONA",
                  "AZ",
                  "CALIFORNIA",
                  "CA",
                  "COLORADO",
                  "CO",
                  "CONNECTICUT",
                  "CT",
                  "DISTRICT OF COLUMBIA",
                  "DC",
                  "DELAWARE",
                  "DE",
                  "FLORIDA",
                  "FL",
                  "GEORGIA",
                  "GA",
                  "HAWAII",
                  "HI",
                  "IOWA",
                  "IA",
                  "IDAHO",
                  "ID",
                  "ILLINOIS",
                  "IL",
                  "INDIANA",
                  "IN",
                  "KANSAS",
                  "KS",
                  "KENTUCKY",
                  "KY",
                  "LOUISIANA",
                  "LA",
                  "MASSACHUSETTS",
                  "MA",
                  "MARYLAND",
                  "MD",
                  "MAINE",
                  "ME",
                  "MICHIGAN",
                  "MI",
                  "MINNESOTA",
                  "MN",
                  "MISSOURI",
                  "MO",
                  "MISSISSIPPI",
                  "MS",
                  "MONTANA",
                  "MT",
                  "NORTH CAROLINA",
                  "NC",
                  "NORTH DAKOTA",
                  "ND",
                  "NEBRASKA",
                  "NE",
                  "NEW HAMPSHIRE",
                  "NH",
                  "NEW JERSEY",
                  "NJ",
                  "NEW MEXICO",
                  "NM",
                  "NEVADA",
                  "NV",
                  "NEW YORK",
                  "NY",
                  "OHIO",
                  "OH",
                  "OKLAHOMA",
                  "OK",
                  "OREGON",
                  "OR",
                  "PENNSYLVANIA",
                  "PA",
                  "RHODE ISLAND",
                  "RI",
                  "SOUTH CAROLINA",
                  "SC",
                  "SOUTH DAKOTA",
                  "SD",
                  "TENNESSEE",
                  "TN",
                  "TEXAS",
                  "TX",
                  "UTAH",
                  "UT",
                  "VIRGINIA",
                  "VA",
                  "VERMONT",
                  "VT",
                  "WASHINGTON",
                  "WA",
                  "WISCONSIN",
                  "WI",
                  "WEST VIRGINIA",
                  "WV",
                  "WYOMING",
                  "WY",
                ],
              },
              province: { type: "string" },
              postalCode: { type: "string" },
              country: {
                type: "string",
                enum: [
                  "af",
                  "Afghanistan",
                  "ax",
                  "Aland Islands",
                  "al",
                  "Albania",
                  "dz",
                  "Algeria",
                  "as",
                  "American Samoa",
                  "ad",
                  "Andorra",
                  "ao",
                  "Angola",
                  "ai",
                  "Anguilla",
                  "aq",
                  "Antarctica",
                  "ag",
                  "Antigua and Barbuda",
                  "ar",
                  "Argentina",
                  "am",
                  "Armenia",
                  "aw",
                  "Aruba",
                  "au",
                  "Australia",
                  "at",
                  "Austria",
                  "az",
                  "Azerbaijan",
                  "bs",
                  "Bahamas",
                  "bh",
                  "Bahrain",
                  "bd",
                  "Bangladesh",
                  "bb",
                  "Barbados",
                  "by",
                  "Belarus",
                  "be",
                  "Belgium",
                  "bz",
                  "Belize",
                  "bj",
                  "Benin",
                  "bm",
                  "Bermuda",
                  "bt",
                  "Bhutan",
                  "bo",
                  "Bolivia",
                  "ba",
                  "Bosnia and Herzegovina",
                  "bw",
                  "Botswana",
                  "bv",
                  "Bouvet Island",
                  "br",
                  "Brazil",
                  "io",
                  "British Indian Ocean Territory",
                  "bn",
                  "Brunei Darussalam",
                  "bg",
                  "Bulgaria",
                  "bf",
                  "Burkina Faso",
                  "bi",
                  "Burundi",
                  "kh",
                  "Cambodia",
                  "cm",
                  "Cameroon",
                  "ca",
                  "Canada",
                  "cv",
                  "Cape Verde",
                  "ky",
                  "Cayman Islands",
                  "cf",
                  "Central African Republic",
                  "td",
                  "Chad",
                  "cl",
                  "Chile",
                  "cn",
                  "China",
                  "cx",
                  "Christmas Island",
                  "cc",
                  "Cocos (Keeling) Islands",
                  "co",
                  "Colombia",
                  "km",
                  "Comoros",
                  "cg",
                  "Congo",
                  "cd",
                  "Congo, the Democratic Republic of the",
                  "ck",
                  "Cook Islands",
                  "cr",
                  "Costa Rica",
                  "hr",
                  "Croatia",
                  "cu",
                  "Cuba",
                  "cy",
                  "Cyprus",
                  "cz",
                  "Czech Republic",
                  "dk",
                  "Denmark",
                  "dj",
                  "Djibouti",
                  "dm",
                  "Dominica",
                  "do",
                  "Dominican Republic",
                  "tp",
                  "East Timor",
                  "ec",
                  "Ecuador",
                  "eg",
                  "Egypt",
                  "sv",
                  "El Salvador",
                  "gq",
                  "Equatorial Guinea",
                  "er",
                  "Eritrea",
                  "ee",
                  "Estonia",
                  "et",
                  "Ethiopia",
                  "fk",
                  "Falkland Islands (Malvinas",
                  "fo",
                  "Faroe Islands",
                  "fj",
                  "Fiji",
                  "fi",
                  "Finland",
                  "fr",
                  "France",
                  "fx",
                  "France, Metropolitan",
                  "gf",
                  "French Guiana",
                  "pf",
                  "French Polynesia",
                  "tf",
                  "French Southern Territories",
                  "ga",
                  "Gabon",
                  "gm",
                  "Gambia",
                  "ge",
                  "Georgia",
                  "de",
                  "Germany",
                  "gh",
                  "Ghana",
                  "gi",
                  "Gibraltar",
                  "gb",
                  "Great Britain (UK)",
                  "gr",
                  "Greece",
                  "gl",
                  "Greenland",
                  "gd",
                  "Grenada",
                  "gp",
                  "Guadeloupe",
                  "gu",
                  "Guam",
                  "gt",
                  "Guatemala",
                  "gg",
                  "Guernsey",
                  "gn",
                  "Guinea",
                  "gw",
                  "Guinea-Bissau",
                  "gy",
                  "Guyana",
                  "ht",
                  "Haiti",
                  "hm",
                  "Heard and McDonald Islands",
                  "hn",
                  "Honduras",
                  "hk",
                  "Hong Kong",
                  "hu",
                  "Hungary",
                  "is",
                  "Iceland",
                  "in",
                  "India",
                  "id",
                  "Indonesia",
                  "ir",
                  "Iran",
                  "iq",
                  "Iraq",
                  "ie",
                  "Ireland",
                  "im",
                  "Isle of Man",
                  "il",
                  "Israel",
                  "it",
                  "Italy",
                  "ci",
                  "Ivory Coast",
                  "jm",
                  "Jamaica",
                  "jp",
                  "Japan",
                  "je",
                  "Jersey",
                  "jo",
                  "Jordan",
                  "kz",
                  "Kazakhstan",
                  "ke",
                  "Kenya",
                  "ki",
                  "Kiribati",
                  "XK",
                  "Kosovo",
                  "kw",
                  "Kuwait",
                  "kg",
                  "Kyrgyzstan",
                  "la",
                  "Laos",
                  "lv",
                  "Latvia",
                  "lb",
                  "Lebanon",
                  "ls",
                  "Lesotho",
                  "lr",
                  "Liberia",
                  "ly",
                  "Libya",
                  "li",
                  "Liechtenstein",
                  "lt",
                  "Lithuania",
                  "lu",
                  "Luxembourg",
                  "mo",
                  "Macau",
                  "mg",
                  "Madagascar",
                  "mw",
                  "Malawi",
                  "my",
                  "Malaysia",
                  "mv",
                  "Maldives",
                  "ml",
                  "Mali",
                  "mt",
                  "Malta",
                  "mh",
                  "Marshall Islands",
                  "mq",
                  "Martinique",
                  "mr",
                  "Mauritania",
                  "mu",
                  "Mauritius",
                  "yt",
                  "Mayotte",
                  "mx",
                  "Mexico",
                  "fm",
                  "Micronesia",
                  "md",
                  "Moldova",
                  "mc",
                  "Monaco",
                  "mn",
                  "Mongolia",
                  "me",
                  "Montenegro",
                  "ms",
                  "Montserrat",
                  "ma",
                  "Morocco",
                  "mz",
                  "Mozambique",
                  "mm",
                  "Myanmar",
                  "na",
                  "Namibia",
                  "nr",
                  "Nauru",
                  "np",
                  "Nepal",
                  "nl",
                  "Netherlands",
                  "an",
                  "Netherlands Antilles",
                  "nt",
                  "Neutral Zone",
                  "nc",
                  "New Caledonia",
                  "nz",
                  "New Zealand",
                  "ni",
                  "Nicaragua",
                  "ne",
                  "Niger",
                  "ng",
                  "Nigeria",
                  "nu",
                  "Niue",
                  "nf",
                  "Norfolk Island",
                  "kp",
                  "North Korea",
                  "mk",
                  "North Macedonia",
                  "mp",
                  "Northern Mariana Islands",
                  "no",
                  "Norway",
                  "om",
                  "Oman",
                  "pk",
                  "Pakistan",
                  "pw",
                  "Palau",
                  "ps",
                  "Palestine",
                  "pa",
                  "Panama",
                  "pg",
                  "Papua New Guinea",
                  "py",
                  "Paraguay",
                  "pe",
                  "Peru",
                  "ph",
                  "Philippines",
                  "pn",
                  "Pitcairn",
                  "pl",
                  "Poland",
                  "pt",
                  "Portugal",
                  "pr",
                  "Puerto Rico",
                  "qa",
                  "Qatar",
                  "re",
                  "Reunion",
                  "ro",
                  "Romania",
                  "su",
                  "Russia",
                  "ru",
                  "Russian Federation",
                  "rw",
                  "Rwanda",
                  "gs",
                  "S. Georgia and S. Sandwich Isls.",
                  "bl",
                  "Saint Barthélemy",
                  "kn",
                  "Saint Kitts and Nevis",
                  "lc",
                  "Saint Lucia",
                  "mf",
                  "Saint Martin (French part)",
                  "vc",
                  "Saint Vincent and the Grenadines",
                  "ws",
                  "Samoa",
                  "sm",
                  "San Marino",
                  "st",
                  "Sao Tome and Principe",
                  "sa",
                  "Saudi Arabia",
                  "sn",
                  "Senegal",
                  "rs",
                  "Serbia",
                  "sc",
                  "Seychelles",
                  "sl",
                  "Sierra Leone",
                  "sg",
                  "Singapore",
                  "sk",
                  "Slovakia",
                  "si",
                  "Slovenia",
                  "sb",
                  "Solomon Islands",
                  "so",
                  "Somalia",
                  "za",
                  "South Africa",
                  "kr",
                  "South Korea",
                  "es",
                  "Spain",
                  "lk",
                  "Sri Lanka",
                  "sh",
                  "St. Helena",
                  "pm",
                  "St. Pierre and Miquelon",
                  "sd",
                  "Sudan",
                  "sr",
                  "Suriname",
                  "sj",
                  "Svalbard and Jan Mayen Islands",
                  "sz",
                  "Swaziland",
                  "se",
                  "Sweden",
                  "ch",
                  "Switzerland",
                  "sy",
                  "Syria",
                  "tw",
                  "Taiwan",
                  "tj",
                  "Tajikistan",
                  "tz",
                  "Tanzania",
                  "th",
                  "Thailand",
                  "tl",
                  "Timor-Leste",
                  "tg",
                  "Togo",
                  "tk",
                  "Tokelau",
                  "to",
                  "Tonga",
                  "tt",
                  "Trinidad and Tobago",
                  "tn",
                  "Tunisia",
                  "tr",
                  "Turkey",
                  "tm",
                  "Turkmenistan",
                  "tc",
                  "Turks and Caicos Islands",
                  "tv",
                  "Tuvalu",
                  "um",
                  "US Minor Outlying Islands",
                  "ug",
                  "Uganda",
                  "ua",
                  "Ukraine",
                  "ae",
                  "United Arab Emirates",
                  "uk",
                  "United Kingdom",
                  "us",
                  "United States",
                  "uy",
                  "Uruguay",
                  "uz",
                  "Uzbekistan",
                  "vu",
                  "Vanuatu",
                  "va",
                  "Vatican City State (Holy See)",
                  "ve",
                  "Venezuela",
                  "vn",
                  "Vietnam",
                  "vg",
                  "Virgin Islands (British)",
                  "vi",
                  "Virgin Islands (U.S.)",
                  "wf",
                  "Wallis and Futuna Islands",
                  "eh",
                  "Western Sahara",
                  "ye",
                  "Yemen",
                  "zr",
                  "Zaire",
                  "zm",
                  "Zambia",
                  "zw",
                  "Zimbabwe",
                ],
              },
              guid: { type: "string" },
            },
          },
        },
      },
    },
    approvalStatus: { type: "string" },
    approvalStatusSetting: {
      type: "object",
      properties: {
        name: { type: "string" },
        type: { type: "string" },
        guid: { type: "string" },
      },
    },
    creationDateTime: { type: "string" },
    creator: {
      type: "object",
      properties: {
        email: { type: "string" },
        fullName: { type: "string" },
        guid: { type: "string" },
      },
    },
    description: { type: "string" },
    guid: { type: "string" },
    name: { type: "string" },
    phoneNumbers: {
      type: "array",
      items: {
        type: "object",
        properties: {
          label: { type: "string" },
          number: { type: "string" },
          extension: { type: "string" },
          comment: { type: "string" },
          guid: { type: "string" },
        },
      },
    },
    supplierId: { type: "string" },
    website: { type: "string" },
  },
};
export const listSuppliersOutputSchema = {
  type: "object" as const,
  properties: {
    results: { type: "array", items: supplierFullSchema },
    count: { type: "integer", format: "int32" },
  },
};
export const updateSupplierFileAssociationOutputSchema = {
  type: "object" as const,
  properties: {
    guid: { type: "string" },
    file: {
      type: "object",
      properties: {
        guid: { type: "string" },
        name: { type: "string" },
        number: { type: "string" },
        title: { type: "string" },
        description: { type: "string" },
        edition: { type: "string" },
        format: { type: "string" },
        mimeType: { type: "string" },
        size: { type: "integer" },
        storageMethodName: { type: "string" },
        category: {
          type: "object",
          properties: { guid: { type: "string" }, name: { type: "string" } },
        },
        author: {
          type: "object",
          properties: { fullName: { type: "string" } },
        },
        creationDateTime: { type: "string" },
        lastModifiedDateTime: { type: "string" },
        latest: { type: "boolean" },
        private: { type: "boolean" },
      },
    },
  },
};
